return [[
{
    "Lang": "en",
    "Name": "English",


    "Entities.gmod_subway_81-717_lvz.Buttons.HelperPanel.VUD2Toggle": "VUD2: Door control toggle (close doors)",
    "Entities.gmod_subway_81-717_lvz.Buttons.HelperPanel.VDLSet": "VDL: Left doors open",
    "Entities.gmod_subway_81-717_lvz.Buttons.Battery_2.1:RC1Toggle": "RC-1: ARS circuits disconnect",
    "Entities.gmod_subway_81-717_lvz.Buttons.Battery_2.1:VBToggle": "VB: Battery on/off",
    "Entities.gmod_subway_81-717_lvz.Buttons.Battery_2.1:BPSToggle": "RC-BPS: Anti-rolling",
    "Entities.gmod_subway_81-717_lvz.Buttons.Battery_2.1:BUDToggle": "BUD: Doors control unit",
    "Entities.gmod_subway_81-717_lvz.Buttons.Battery_2.1:VRDToggle": "VRD: Allow movement(when 0 on ALS)",
    "Entities.gmod_subway_81-717_lvz.Buttons.VRD1.VRDToggle": "VRD: Allow movement(when 0 on ALS)",
    "Entities.gmod_subway_81-717_lvz.Buttons.Wiper.WiperToggle": "Wiper",
    "Entities.gmod_subway_81-717_lvz.Buttons.RearPneumatic.RearBrakeLineIsolationToggle": "Brake line isolation valve",
    "Entities.gmod_subway_81-717_lvz.Buttons.RearPneumatic.RearTrainLineIsolationToggle": "Train line isolation valve",
    "Entities.gmod_subway_81-717_lvz.Buttons.Main.R_UNchToggle": "UNCh: Low frequency amplifier",
    "Entities.gmod_subway_81-717_lvz.Buttons.Main.R_ZSToggle": "ES: Emergency communication control",
    "Entities.gmod_subway_81-717_lvz.Buttons.Main.R_GToggle": "Loudspeaker: Sound in cabin enable",
    "Entities.gmod_subway_81-717_lvz.Buttons.Main.R_UPOToggle": "UPO: Announcer",
    "Entities.gmod_subway_81-717_lvz.Buttons.Main.2:KVTSet": "KB: Attention button",
    "Entities.gmod_subway_81-717_lvz.Buttons.Main.VZ1Set": "VZ1: Pneumatic valve #1",
    "Entities.gmod_subway_81-717_lvz.Buttons.Main.VUD1Toggle": "VUD: Door control toggle (close doors)",
    "Entities.gmod_subway_81-717_lvz.Buttons.Main.KDLSet": "KDL: Open left doors",
    "Entities.gmod_subway_81-717_lvz.Buttons.Main.KDLKToggle": "KDL button cover",
    "Entities.gmod_subway_81-717_lvz.Buttons.Main.KDLRSet": "KDL: Open left doors",
    "Entities.gmod_subway_81-717_lvz.Buttons.Main.KDLRKToggle": "KDL button cover",
    "Entities.gmod_subway_81-717_lvz.Buttons.Main.DoorSelectToggle": "Select doors side",
    "Entities.gmod_subway_81-717_lvz.Buttons.Main.KRZDSet": "KRZD: Emergency door closing",
    "Entities.gmod_subway_81-717_lvz.Buttons.Main.VozvratRPSet": "Reset overload relay",
    "Entities.gmod_subway_81-717_lvz.Buttons.Main.GreenRPLight": "RP: Green overload relay light (overload relay open on current train)",
    "Entities.gmod_subway_81-717_lvz.Buttons.Main.AVULight": "AVU: Automatic control disabler active",
    "Entities.gmod_subway_81-717_lvz.Buttons.Main.LKVPLight": "LKVP: High-voltage converter control",
    "Entities.gmod_subway_81-717_lvz.Buttons.Main.SPLight": "LSP: Fire emergency (rheostat overheat)",
    "Entities.gmod_subway_81-717_lvz.Buttons.Main.ConverterProtectionSet": "Converter protection",
    "Entities.gmod_subway_81-717_lvz.Buttons.Main.KSNSet": "KSN: Forced activation of the RP on the faulty wagon (Malfunction signaling)",
    "Entities.gmod_subway_81-717_lvz.Buttons.Main.DIPoffSet": "Ring",
    "Entities.gmod_subway_81-717_lvz.Buttons.Main.ARSToggle": "ARS: Automatic speed regulation",
    "Entities.gmod_subway_81-717_lvz.Buttons.Main.ALSToggle": "ALS: Automatic locomotive signalling",
    "Entities.gmod_subway_81-717_lvz.Buttons.Main.TormATToggle": "(placeholder) Emergency brake toggle",
    "Entities.gmod_subway_81-717_lvz.Buttons.Main.OtklAVUToggle": "OtklAVU: Turn off automatic control disable relay (failure of AVU)",
    "Entities.gmod_subway_81-717_lvz.Buttons.Main.L_1Toggle": "Interior lighting",
    "Entities.gmod_subway_81-717_lvz.Buttons.Main.L_2Toggle": "Cabin lighting",
    "Entities.gmod_subway_81-717_lvz.Buttons.Main.L_3Toggle": "Gauges lighting",
    "Entities.gmod_subway_81-717_lvz.Buttons.PassengerDoor.PassengerDoor": "Passenger door",
    "Entities.gmod_subway_81-717_lvz.Buttons.IGLAButtons.IGLA1Set": "IGLA: First button",
    "Entities.gmod_subway_81-717_lvz.Buttons.IGLAButtons.IGLA2Set": "IGLA: Second button",
    "Entities.gmod_subway_81-717_lvz.Buttons.IGLAButtons.IGLA23": "IGLA: Second and third buttons",
    "Entities.gmod_subway_81-717_lvz.Buttons.IGLAButtons.IGLA3Set": "IGLA: Third button",
    "Entities.gmod_subway_81-717_lvz.Buttons.IGLAButtons.IGLA4Set": "IGLA: Fourth button",
    "Entities.gmod_subway_81-717_lvz.Buttons.IGLAButtons.!IGLAFire": "IGLA: Fire",
    "Entities.gmod_subway_81-717_lvz.Buttons.IGLAButtons.!IGLAErr": "IGLA: Malfunction",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A61Toggle": "A61 Train wire 6 control",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A55Toggle": "A55 Train wire 10AS control",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A54Toggle": "A54 Train wire 10AK control",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A56Toggle": "A56 Turn on battery power to control circuits",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A27Toggle": "A27 Turn on DIP and lighting",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A21Toggle": "A21 Door control",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A10Toggle": "A10 Motor-compressor control",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A53Toggle": "A53 KVC power supply",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A43Toggle": "A43 ARS 12V power supply",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A45Toggle": "A45 ARS train wire 10AU",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A42Toggle": "A42 ARS 75V power supply",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A41Toggle": "A41 ARS braking",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:VUToggle": "VU  Train control",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A64Toggle": "A64 Cabin lighting",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A63Toggle": "A63 IGLA/BIS",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A50Toggle": "A50 Turn on DIP and lighting",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A51Toggle": "A51 Turn off DIP and lighting",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A23Toggle": "A23 Emergency motor-compressor turn on",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A14Toggle": "A14 Train wire 18",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A75Toggle": "A75 Cabin heating",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A1Toggle": "A1  X-1",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A2Toggle": "A2  X-2",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A3Toggle": "A3  X-3",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A17Toggle": "A17 Reset overload relay",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A62Toggle": "A62 Radio communications",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A29Toggle": "A29 Radio broadcasting",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A5Toggle": "A5 Interim wagon",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A6Toggle": "A6  T-1",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A8Toggle": "A8  Pneumatic valves #1, #2",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A20Toggle": "A20 Drive/brake circuit control, train wire 20",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A25Toggle": "A25 Manual electric braking",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A22Toggle": "A22 Turn on KK",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A30Toggle": "A30 Rheostat controller motor power",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A39Toggle": "A39 Emergency control",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A44Toggle": "A44 Emergency train control",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A80Toggle": "A80 Power circuit mode switch motor power",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A65Toggle": "A65 Interior lighting",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:L_5Toggle": "А49 Emergency lighting",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A24Toggle": "A24 Battery charging",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A32Toggle": "A32 Open right doors",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A31Toggle": "A31 Open left doors",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A16Toggle": "A16 Close doors",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A13Toggle": "A13 Door alarm",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A12Toggle": "A12 Emergency door close",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A7Toggle": "A7  Red lamp",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A9Toggle": "A9  Red lamp",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A46Toggle": "A46 White lamp",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A47Toggle": "A47 White lamp",
    "Entities.gmod_subway_81-717_lvz.Buttons.Schedule.!RouteNum": "М №\nRoute number",
    "Entities.gmod_subway_81-717_lvz.Buttons.Schedule.!PathNum": "П №\nPath number",
    "Entities.gmod_subway_81-717_lvz.Buttons.Schedule.!SchTime": "ВРЕМЯ ХОДА\nTotal schedule time",
    "Entities.gmod_subway_81-717_lvz.Buttons.Schedule.!SchInterval": "ИНТ\nTrain interval",
    "Entities.gmod_subway_81-717_lvz.Buttons.Schedule.!SchHour": "ЧАС\nHour",
    "Entities.gmod_subway_81-717_lvz.Buttons.Schedule.!SchMin": "МИН\nMinute",
    "Entities.gmod_subway_81-717_lvz.Buttons.Schedule.!SchSec": "СЕК\nSecond",
    "Entities.gmod_subway_81-717_lvz.Buttons.Schedule.!SchArrival": "Arrival times",
    "Entities.gmod_subway_81-717_lvz.Buttons.Schedule.!SchStations": "Station name",
    "Entities.gmod_subway_81-717_lvz.Buttons.Stopkran.EmergencyBrakeValveToggle": "Emergency brake",
    "Entities.gmod_subway_81-717_lvz.Buttons.PneumaticPanels.!CylinderPressure": "Brake cylinder pressure",
    "Entities.gmod_subway_81-717_lvz.Buttons.PneumaticPanels.!LinePressure": "Pressure in pneumatic lines (red: brake line, black: train line)",
    "Entities.gmod_subway_81-717_lvz.Buttons.Battery.BPSToggle": "RC-BPS: Anti-rolling",
    "Entities.gmod_subway_81-717_lvz.Buttons.Battery.RC1Toggle": "RC-1: ARS circuits disconnect",
    "Entities.gmod_subway_81-717_lvz.Buttons.Battery.BUDToggle": "BUD: Doors control unit",
    "Entities.gmod_subway_81-717_lvz.Buttons.Battery.VBToggle": "VB: Battery on/off",
    "Entities.gmod_subway_81-717_lvz.Buttons.FrontPneumatic.FrontBrakeLineIsolationToggle": "Brake line isolation valve",
    "Entities.gmod_subway_81-717_lvz.Buttons.FrontPneumatic.FrontTrainLineIsolationToggle": "Train line isolation valve",
    "Entities.gmod_subway_81-717_lvz.Buttons.SPBARS.!Speedometer1": "Speed indicator",
    "Entities.gmod_subway_81-717_lvz.Buttons.SPBARS.!Speedometer2": "Speed indicator",
    "Entities.gmod_subway_81-717_lvz.Buttons.SPBARS.!ARSOch": "NCh: No ARS frequency",
    "Entities.gmod_subway_81-717_lvz.Buttons.SPBARS.!ARS0": "0: ARS stop signal",
    "Entities.gmod_subway_81-717_lvz.Buttons.SPBARS.!ARS40": "Speed limit 40 kph",
    "Entities.gmod_subway_81-717_lvz.Buttons.SPBARS.!ARS60": "Speed limit 60 kph",
    "Entities.gmod_subway_81-717_lvz.Buttons.SPBARS.!ARS70": "Speed limit 70 kph",
    "Entities.gmod_subway_81-717_lvz.Buttons.SPBARS.!ARS80": "Speed limit 80 kph",
    "Entities.gmod_subway_81-717_lvz.Buttons.SPBARS.!LampLSD1": "LSD: Door state light (doors are closed)",
    "Entities.gmod_subway_81-717_lvz.Buttons.SPBARS.!LampLSD2": "LSD: Door state light (doors are closed)",
    "Entities.gmod_subway_81-717_lvz.Buttons.SPBARS.!LampLVD": "1: Engines engaged",
    "Entities.gmod_subway_81-717_lvz.Buttons.SPBARS.!LampLHRK": "2: Rheostat controller motion lamp",
    "Entities.gmod_subway_81-717_lvz.Buttons.SPBARS.!LampLST": "6: Brakes engaged",
    "Entities.gmod_subway_81-717_lvz.Buttons.SPBARS.!LampLRD": "LRD: Move permission(when 0 on ALS)",
    "Entities.gmod_subway_81-717_lvz.Buttons.SPBARS.!LampRP": "RP: Red overload relay light (power circuits failed to assemble)",
    "Entities.gmod_subway_81-717_lvz.Buttons.SPBARS.!LampLSN": "LSN: Failure indicator light (power circuits failed to assemble)",
    "Entities.gmod_subway_81-717_lvz.Buttons.SPBARS.!LampLKVD": "LKVD: ARS engine shutdown indicator",
    "Entities.gmod_subway_81-717_lvz.Buttons.SPBARS.!LampLKT": "LKT: ARS braking indicator",
    "Entities.gmod_subway_81-717_lvz.Buttons.SPBARS.!LampDV": "DV: Rotational sensor",
    "Entities.gmod_subway_81-717_lvz.Buttons.SPBARS.!SpeedFact1": "Speed",
    "Entities.gmod_subway_81-717_lvz.Buttons.SPBARS.!SpeedFact2": "Speed",
    "Entities.gmod_subway_81-717_lvz.Buttons.SPBARS.!ARSL20": "NCh: No ARS frequency",
    "Entities.gmod_subway_81-717_lvz.Buttons.SPBARS.!ARSL40": "Speed limit 40 kph",
    "Entities.gmod_subway_81-717_lvz.Buttons.SPBARS.!ARSL60": "Speed limit 60 kph",
    "Entities.gmod_subway_81-717_lvz.Buttons.SPBARS.!ARSL70": "Speed limit 70 kph",
    "Entities.gmod_subway_81-717_lvz.Buttons.SPBARS.!ARSL80": "Speed limit 80 kph",
    "Entities.gmod_subway_81-717_lvz.Buttons.ParkingBrake2.1:ParkingBrakeToggle": "Parking brake",
    "Entities.gmod_subway_81-717_lvz.Buttons.RearDoor.RearDoor": "Front door",
    "Entities.gmod_subway_81-717_lvz.Buttons.GV.GVToggle": "HV switch",
    "Entities.gmod_subway_81-717_lvz.Buttons.Meters.!TotalVoltmeter": "HV voltmeter (kV)",
    "Entities.gmod_subway_81-717_lvz.Buttons.Meters.!TotalAmpermeter": "Total ampermeter (A)",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A61Toggle": "Train wire 6 control",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A55Toggle": "Train wire 10AS control",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A54Toggle": "Train wire 10AK control",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A56Toggle": "Turn on battery power to control circuits",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A27Toggle": "A27 Turn on DIP and lighting",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A21Toggle": "A21 Door control",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A10Toggle": "A10 Motor-compressor control",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A53Toggle": "A53 KVC power supply",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A43Toggle": "A43 ARS 12V power supply",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A45Toggle": "A45 ARS train wire 10AU",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A42Toggle": "A42 ARS 75V power supply",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A41Toggle": "A41 ARS braking",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.VUToggle": "VU  Train control",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A64Toggle": "A64 Cabin lighting",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A63Toggle": "A63 IGLA/BIS",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A50Toggle": "A50 Turn on DIP and lighting",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A51Toggle": "A51 Turn off DIP and lighting",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A23Toggle": "A23 Emergency motor-compressor turn on",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A14Toggle": "A14 Train wire 18",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A75Toggle": "A75 Cabin heating",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A1Toggle": "A1  X-1",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A2Toggle": "A2  X-2",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A3Toggle": "A3  X-3",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A17Toggle": "A17 Reset overload relay",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A62Toggle": "A62 Radio communications",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A29Toggle": "A29 Radio broadcasting",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A5Toggle": "A5 Interim wagon",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A6Toggle": "A6  T-1",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A8Toggle": "A8  Pneumatic valves #1, #2",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A20Toggle": "A20 Drive/brake circuit control, train wire 20",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A25Toggle": "A25 Manual electric braking",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A22Toggle": "A22 Turn on KK",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A30Toggle": "A30 Rheostat controller motor power",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A39Toggle": "A39 Emergency control",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A44Toggle": "A44 Emergency train control",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A80Toggle": "A80 Power circuit mode switch motor power",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A65Toggle": "A65 Interior lighting",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.L_5Toggle": "А49 Emergency lighting",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A24Toggle": "A24 Battery charging",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A32Toggle": "A32 Open right doors",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A31Toggle": "A31 Open left doors",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A16Toggle": "A16 Close doors",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A13Toggle": "A13 Door alarm",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A12Toggle": "A12 Emergency door close",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A7Toggle": "A7  Red lamp",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A9Toggle": "A9  Red lamp",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A46Toggle": "A46 White lamp",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A47Toggle": "A47 White lamp",
    "Entities.gmod_subway_81-717_lvz.Buttons.Front.L_4Toggle": "Headlights toggle",
    "Entities.gmod_subway_81-717_lvz.Buttons.Front.VUSToggle": "VUS: Headlights bright/dim",
    "Entities.gmod_subway_81-717_lvz.Buttons.Front.VADToggle": "VAD: Emergency door close override (failure of KD relay)",
    "Entities.gmod_subway_81-717_lvz.Buttons.Front.VAHToggle": "VAH: Emergency driving mode (failure of RPB relay)",
    "Entities.gmod_subway_81-717_lvz.Buttons.Front.KRPSet": "KRP: Emergency start button",
    "Entities.gmod_subway_81-717_lvz.Buttons.Front.RezMKSet": "Emergency motor-compressor startup",
    "Entities.gmod_subway_81-717_lvz.Buttons.Front.KDPSet": "KDP: Right doors open",
    "Entities.gmod_subway_81-717_lvz.Buttons.Front.KDPKToggle": "KDP button cover",
    "Entities.gmod_subway_81-717_lvz.Buttons.Front.PN": "Pneumatic brake control",
    "Entities.gmod_subway_81-717_lvz.Buttons.BPSNFront.!Voltage": "Battery voltage",
    "Entities.gmod_subway_81-717_lvz.Buttons.BPSNFront.VMKToggle": "Turn motor-compressor on",
    "Entities.gmod_subway_81-717_lvz.Buttons.BPSNFront.BPSNonToggle": "BPSN: Train power supply",
    "Entities.gmod_subway_81-717_lvz.Buttons.BPSNFront.ARS13Set": "ARS 13V: ARS stabilized voltage check",
    "Entities.gmod_subway_81-717_lvz.Buttons.ParkingBrake.ParkingBrakeToggle": "Parking brake",
    "Entities.gmod_subway_81-717_lvz.Buttons.ParkingBrake.DriverValveTLDisconnectToggle": "Brake line disconnect valve",
    "Entities.gmod_subway_81-717_lvz.Buttons.CabinDoor.CabinDoor": "Cabin door",
    "Entities.gmod_subway_81-717_lvz.Buttons.PUAVN.!K16": "NCh: No ARS frequency",
    "Entities.gmod_subway_81-717_lvz.Buttons.PUAVN.!OS": "0: ARS stop signal",
    "Entities.gmod_subway_81-717_lvz.Buttons.PUAVN.!AVT": "Speed limit 40 kph",
    "Entities.gmod_subway_81-717_lvz.Buttons.PUAVN.!ARS": "Speed limit 60 kph",
    "Entities.gmod_subway_81-717_lvz.Buttons.PUAVN.!KI1": "Speed limit 70 kph",
    "Entities.gmod_subway_81-717_lvz.Buttons.PUAVN.!KI2": "Speed limit 80 kph",
    "Entities.gmod_subway_81-717_lvz.Buttons.PUAVN.!ARSOch": "NCh: No ARS frequency",
    "Entities.gmod_subway_81-717_lvz.Buttons.PUAVN.!ARS0": "0: ARS stop signal",
    "Entities.gmod_subway_81-717_lvz.Buttons.PUAVN.!ARS40": "Speed limit 40 kph",
    "Entities.gmod_subway_81-717_lvz.Buttons.PUAVN.!ARS60": "Speed limit 60 kph",
    "Entities.gmod_subway_81-717_lvz.Buttons.PUAVN.!ARS70": "Speed limit 70 kph",
    "Entities.gmod_subway_81-717_lvz.Buttons.PUAVN.!ARS80": "Speed limit 80 kph",
    "Entities.gmod_subway_81-717_lvz.Buttons.PUAVN.KHSet": "",
    "Entities.gmod_subway_81-717_lvz.Buttons.PUAVN.KSZDSet": "",
    "Entities.gmod_subway_81-717_lvz.Buttons.PUAVN.VAVToggle": "",
    "Entities.gmod_subway_81-717_lvz.Buttons.PUAVN.VZPToggle": "",
    "Entities.gmod_subway_81-717_lvz.Buttons.PassengerDoor1.PassengerDoor": "Passenger door",
    "Entities.gmod_subway_81-717_lvz.Buttons.Reverser.KVReverserDown": "Reverser back",
    "Entities.gmod_subway_81-717_lvz.Buttons.Reverser.KVReverserUp": "Reverser forward",
    "Entities.gmod_subway_81-717_lvz.Buttons.EPKDisconnect.EPKToggle": "EPV disconnect valve",
    "Entities.gmod_subway_81-717_lvz.Buttons.Help.ShowHelp": "Show help on driving the train",
    "Entities.gmod_subway_81-717_lvz.Buttons.UAVAPanel.UAVAToggle": "UAVA: Universal Automatic Autostop Disabler (disable autostop)",
    "Entities.gmod_subway_81-717_lvz.Buttons.UAVAPanel.UAVACToggle   ": "UAVA: Universal Automatic Autostop Disabler(reset contacts)",
    "Entities.gmod_subway_81-717_lvz.Buttons.DriverValveDisconnect.DriverValveDisconnectToggle": "Brake lever disconnect valve",
    "Entities.gmod_subway_81-717_lvz.Buttons.DriverValveDisconnect.DriverValveBLDisconnectToggle": "Train line disconnect valve",
    "Entities.gmod_subway_81-717_lvz.Buttons.AirDistributor.AirDistributorDisconnectToggle": "Disable air distributor",




    "Entities.gmod_subway_81-714_lvz.Buttons.GV.GVToggle": "HV switch",
    "Entities.gmod_subway_81-714_lvz.Buttons.RearPneumatic.RearBrakeLineIsolationToggle": "Brake line isolation valve",
    "Entities.gmod_subway_81-714_lvz.Buttons.RearPneumatic.RearTrainLineIsolationToggle": "Train line isolation valve",
    "Entities.gmod_subway_81-714_lvz.Buttons.RearDoor.RearDoor": "Rear door",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Left.DriverValveBLDisconnectToggle": "Brake line disconnect valve",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Left.DriverValveTLDisconnectToggle": "Train line disconnect valve",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Left.A65Toggle": "A65 Interior lighting",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Left.A56Toggle": "A56 Turn on battery power to control circuits",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Left.A63Toggle": "A63 IGLA/BIS",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Left.A10Toggle": "A10 Motor-compressor control",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Left.A30Toggle": "A30 Rheostat controller motor power",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Left.A80Toggle": "A80 Power circuit mode switch motor power",
    "Entities.gmod_subway_81-714_lvz.Buttons.FrontPneumatic.FrontBrakeLineIsolationToggle": "Brake line isolation valve",
    "Entities.gmod_subway_81-714_lvz.Buttons.FrontPneumatic.FrontTrainLineIsolationToggle": "Train line isolation valve",
    "Entities.gmod_subway_81-714_lvz.Buttons.FrontPneumatic.ParkingBrakeToggle": "Parking brake",
    "Entities.gmod_subway_81-714_lvz.Buttons.AirDistributor.AirDistributorDisconnectToggle": "Disable air distributor",
    "Entities.gmod_subway_81-714_lvz.Buttons.FrontDoor.FrontDoor": "Front door",
    "Entities.gmod_subway_81-714_lvz.Buttons.Battery.VBToggle": "VB: Battery on/off",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Right.A54Toggle": "A54 Train wire 10AK control",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Right.A27Toggle": "A27 Turn on DIP and lighting",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Right.A24Toggle": "A24 Battery charging",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Right.A53Toggle": "A53 KVC power supply",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Right.A13Toggle": "A13 Door alarm",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Right.A32Toggle": "A32 Open right doors",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Right.A31Toggle": "A31 Open left doors",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Right.A16Toggle": "A16 Close doors",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Right.A12Toggle": "A12 Emergency door close",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Right.A50Toggle": "A50 Turn on DIP and lighting",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Right.A51Toggle": "A51 Turn off DIP and lighting",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Right.A1Toggle": "A1  X-1",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Right.KRPSet": "START: Emergency start button",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Right.VozvratRPSet": "Reset overload relay",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Right.RezMKSet": "Emergency motor-compressor startup",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Right.VMKToggle": "Turn motor-compressor on",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Right.BPSNonToggle": "BPSN: Train power supply",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Right.A2Toggle": "A2  X-2",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Right.A3Toggle": "A3  X-3",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Right.A17Toggle": "A17 Reset overload relay",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Right.A5Toggle": "A5  ",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Right.A6Toggle": "A6  T-1",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Right.A8Toggle": "A8  Pneumatic valves #1, #2",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Right.A20Toggle": "A20 Drive/brake circuit control, train wire 20",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Right.A25Toggle": "A25 Manual electric braking",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Right.A22Toggle": "A22 Turn on KK",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Right.A23Toggle": "A23 Emergency motor-compressor turn on",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Right.A39Toggle": "A39 Emergency control",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Right.A14Toggle": "A14 Train wire 18"
}
]]
