return [[
{
    "Lang": "en",
    "Name": "English",

    "Entities.gmod_subway_ezh.Buttons.HelperPanel.VDLSet": "VDL: Left doors open",
    "Entities.gmod_subway_ezh.Buttons.HelperPanel.VUD2Toggle": "VUD2: Door control toggle (close doors)",
    "Entities.gmod_subway_ezh.Buttons.Meters.!TotalVoltmeter": "HV voltmeter (kV)",
    "Entities.gmod_subway_ezh.Buttons.Meters.!TotalAmpermeter": "Total ampermeter (A)",
    "Entities.gmod_subway_ezh.Buttons.AV2.R_RadioToggle": "+50V: Announcer, RRI block ",
    "Entities.gmod_subway_ezh.Buttons.AV2.RSTToggle": "RST: Radiostation",
    "Entities.gmod_subway_ezh.Buttons.AV2.UOSToggle": "UOS: Speed limitation tumbler",
    "Entities.gmod_subway_ezh.Buttons.AB1.AB1Set": "Switch ARS unit to AB mode(drivers button)",
    "Entities.gmod_subway_ezh.Buttons.KAH.KAHToggle": "TAH: Emergency Drive Mode",
    "Entities.gmod_subway_ezh.Buttons.RearPneumatic.RearTrainLineIsolationToggle": "Train line isolation valve",
    "Entities.gmod_subway_ezh.Buttons.RearPneumatic.RearBrakeLineIsolationToggle": "Brake line isolation valve",
    "Entities.gmod_subway_ezh.Buttons.AVU.AVULight": "Lamp: AVU is turned on (Automatic control disabler)",
    "Entities.gmod_subway_ezh.Buttons.AVU.OtklAVUToggle": "Turn off automatic control disable relay (failure of AVU)",
    "Entities.gmod_subway_ezh.Buttons.Main.DIPonSet": "Turn interior lights on",
    "Entities.gmod_subway_ezh.Buttons.Main.DIPoffSet": "Turn interior lights off (Ring)",
    "Entities.gmod_subway_ezh.Buttons.Main.KDPSet": "KDP: Right doors open",
    "Entities.gmod_subway_ezh.Buttons.Main.KDLSet": "KDL: Left doors open",
    "Entities.gmod_subway_ezh.Buttons.Main.DoorSelectToggle": "Select doors side",
    "Entities.gmod_subway_ezh.Buttons.Main.KVTSet": "KVT: Brake reception button (ARS Cancel)",
    "Entities.gmod_subway_ezh.Buttons.Main.VUSToggle": "Switcher: Near Headlights(down)/Far Headlights (up)",
    "Entities.gmod_subway_ezh.Buttons.Main.ALSToggle": "Switcher: ALS",
    "Entities.gmod_subway_ezh.Buttons.Main.ALSFreqToggle": "Switch: Decoder (Down - ARS 2/6, up - ARS 1/5)",
    "Entities.gmod_subway_ezh.Buttons.Main.ARSToggle": "Switcher: Automatic speed regulation",
    "Entities.gmod_subway_ezh.Buttons.Main.KU1Toggle": "Turn motor-compressor on",
    "Entities.gmod_subway_ezh.Buttons.Main.KSNSet": "SN: Failure indication button",
    "Entities.gmod_subway_ezh.Buttons.Main.VozvratRPSet": "KU9: Reset overload relay",
    "Entities.gmod_subway_ezh.Buttons.Main.R_Program1Set": "Announcer: Program 1",
    "Entities.gmod_subway_ezh.Buttons.Main.VUD1Toggle": "VUD: Door control toggle (close doors)",
    "Entities.gmod_subway_ezh.Buttons.Main.KRZDSet": "KRZD: Emergency door closing",
    "Entities.gmod_subway_ezh.Buttons.AV1.VU3Toggle": "VU3: Cabin lighting",
    "Entities.gmod_subway_ezh.Buttons.AV1.VU2Toggle": "VU2: Emergency lighting (45V)",
    "Entities.gmod_subway_ezh.Buttons.AV1.VU1Toggle": "VU1: Cabin heater (3kWt)",
    "Entities.gmod_subway_ezh.Buttons.Back1.!RignARS": "ARS tonal device",
    "Entities.gmod_subway_ezh.Buttons.Back1.!USPM": "UESPM (Emergency intercom)",
    "Entities.gmod_subway_ezh.Buttons.Back1.!AK": "Pressure controller",
    "Entities.gmod_subway_ezh.Buttons.Back1.!LVP": "Shield with low-voltage fuses",
    "Entities.gmod_subway_ezh.Buttons.RC1.RC1Toggle": "RCR: ARS Circuit Breaker",
    "Entities.gmod_subway_ezh.Buttons.Lamp.L_3Toggle": "Lamp: Gauges lighting",
    "Entities.gmod_subway_ezh.Buttons.DriverValveTLDisconnect.DriverValveTLDisconnectToggle": "Train line disconnect valve",
    "Entities.gmod_subway_ezh.Buttons.VU.VUToggle": "VU: Train control",
    "Entities.gmod_subway_ezh.Buttons.VU.RezMKSet": "KU15: Motor Compressor emergency toggle",
    "Entities.gmod_subway_ezh.Buttons.VU.KRPSet": "Emergency start",
    "Entities.gmod_subway_ezh.Buttons.FrontDoor.FrontDoor": "Front door",
    "Entities.gmod_subway_ezh.Buttons.AB2.AB2Set": "Switch ARS unit to AB mode(helpers button)",
    "Entities.gmod_subway_ezh.Buttons.PneumaticManometer.!LinesPressure": "Pressure in pneumatic lines (red: brake line, black: train line)",
    "Entities.gmod_subway_ezh.Buttons.Stopkran.EmergencyBrakeValveToggle": "Emergency brake",
    "Entities.gmod_subway_ezh.Buttons.UAVAPanel.UAVAToggle": "UAVA: Universal Automatic Autostop Disabler (disable autostop)",
    "Entities.gmod_subway_ezh.Buttons.UAVAPanel.UAVACToggle   ": "UAVA: Universal Automatic Autostop Disabler(reset contacts)",
    "Entities.gmod_subway_ezh.Buttons.PneumaticPanels.!BrakeCylinder": "Brake manometer: Brake cylinder pressure",
    "Entities.gmod_subway_ezh.Buttons.Battery.VBToggle": "AB: Battery on/off",
    "Entities.gmod_subway_ezh.Buttons.FrontPneumatic.FrontBrakeLineIsolationToggle": "Brake line isolation valve",
    "Entities.gmod_subway_ezh.Buttons.FrontPneumatic.FrontTrainLineIsolationToggle": "Train line isolation valve",
    "Entities.gmod_subway_ezh.Buttons.ASNP.R_ASNPMenuSet": "Announcer: Menu",
    "Entities.gmod_subway_ezh.Buttons.ASNP.R_ASNPUpSet": "Announcer: Up",
    "Entities.gmod_subway_ezh.Buttons.ASNP.R_ASNPDownSet": "Announcer: Down",
    "Entities.gmod_subway_ezh.Buttons.ASNP.R_ASNPOnToggle": "Announcer: Turn on",
    "Entities.gmod_subway_ezh.Buttons.Tsepi.!BatteryVoltage": "Battery voltage",
    "Entities.gmod_subway_ezh.Buttons.PassengerDoor1.PassengerDoor": "Passenger door",
    "Entities.gmod_subway_ezh.Buttons.PassengerDoor.PassengerDoor": "Passenger door",
    "Entities.gmod_subway_ezh.Buttons.GV.GVToggle": "GV: HV switch",
    "Entities.gmod_subway_ezh.Buttons.LampsALS.!L80": "Speed limit 80 kph",
    "Entities.gmod_subway_ezh.Buttons.LampsALS.!L70": "Speed limit 70 kph",
    "Entities.gmod_subway_ezh.Buttons.LampsALS.!L60": "Speed limit 60 kph",
    "Entities.gmod_subway_ezh.Buttons.LampsALS.!L40": "Speed limit 40 kph",
    "Entities.gmod_subway_ezh.Buttons.LampsALS.!L0": "0: Speed limit 0 kph",
    "Entities.gmod_subway_ezh.Buttons.LampsALS.!LNF": "OCh: No ARS frequency",
    "Entities.gmod_subway_ezh.Buttons.DriverValveBLDisconnect.DriverValveBLDisconnectToggle": "Brake line disconnect valve",
    "Entities.gmod_subway_ezh.Buttons.CabinDoor.CabinDoor": "Cabin door",
    "Entities.gmod_subway_ezh.Buttons.IGLAButtons.IGLA1USet": "IGLA: First button up",
    "Entities.gmod_subway_ezh.Buttons.IGLAButtons.IGLA1Set": "IGLA: First button",
    "Entities.gmod_subway_ezh.Buttons.IGLAButtons.IGLA1DSet": "IGLA: First button down",
    "Entities.gmod_subway_ezh.Buttons.IGLAButtons.IGLA2USet": "IGLA: Second button up",
    "Entities.gmod_subway_ezh.Buttons.IGLAButtons.IGLA2Set": "IGLA: Second button",
    "Entities.gmod_subway_ezh.Buttons.IGLAButtons.IGLA2DSet": "IGLA: Second button down",
    "Entities.gmod_subway_ezh.Buttons.IGLAButtons.!IGLASR": "IGLA: SR",
    "Entities.gmod_subway_ezh.Buttons.IGLAButtons.!IGLARX": "IGLA: SR",
    "Entities.gmod_subway_ezh.Buttons.IGLAButtons.!IGLAErr": "IGLA: Malfunction",
    "Entities.gmod_subway_ezh.Buttons.IGLAButtons.!IGLAOSP": "IGLA: OSP(Fire extinguisher)",
    "Entities.gmod_subway_ezh.Buttons.IGLAButtons.!IGLAPI": "IGLA: PI(Fire indication)",
    "Entities.gmod_subway_ezh.Buttons.IGLAButtons.!IGLAOff": "IGLA: Off",
    "Entities.gmod_subway_ezh.Buttons.Lamps.!RedRP": "RP: Red overload relay light (power circuits failed to assemble)",
    "Entities.gmod_subway_ezh.Buttons.Lamps.!LPU": "Sequence (Verifying the inclusion of machines in the run and braking mode when there is no high voltage)",
    "Entities.gmod_subway_ezh.Buttons.Lamps.!VD": "VD: Engines engaged (indicates the presence of voltage on the 1 train wire)",
    "Entities.gmod_subway_ezh.Buttons.Lamps.!KT": "KT: Brake control (efficient brakes)",
    "Entities.gmod_subway_ezh.Buttons.Lamps.!AB": "AB: Work in auto-lock mode (ARS is disabled)",
    "Entities.gmod_subway_ezh.Buttons.Lamps.!Doors": "Doors: door state light (doors are open)",
    "Entities.gmod_subway_ezh.Buttons.Lamps.!LN": "LN: Direction signal",
    "Entities.gmod_subway_ezh.Buttons.Lamps.!Sbor": "Lamp SBOR: Failure indicator light (power circuits failed to assemble)",
    "Entities.gmod_subway_ezh.Buttons.EPKDisconnect.EPKToggle": "EPK disconnect valve",
    "Entities.gmod_subway_ezh.Buttons.AVMain.AV8BToggle": "AV-8B: Circuit breaker (High voltage auxiliary circuits)",
    "Entities.gmod_subway_ezh.Buttons.KRR.KRRToggle": "KRR: Button of enabling reversers",
    "Entities.gmod_subway_ezh.Buttons.ParkingBrake.ParkingBrakeLeft": "Parking brake",
    "Entities.gmod_subway_ezh.Buttons.ParkingBrake.ParkingBrakeRight": "Parking brake",
    "Entities.gmod_subway_ezh.Buttons.AirDistributor.AirDistributorDisconnectToggle": "Disable air distributor",



    "Entities.gmod_subway_ezh1.Buttons.Stopkran.EmergencyBrakeValveToggle": "Emergency brake",
    "Entities.gmod_subway_ezh1.Buttons.DriverValveBLTLDisconnect.DriverValveBLDisconnectToggle": "Brake line disconnect valve",
    "Entities.gmod_subway_ezh1.Buttons.DriverValveBLTLDisconnect.DriverValveTLDisconnectToggle": "Train line disconnect valve",
    "Entities.gmod_subway_ezh1.Buttons.PneumaticPanels.!CylinderPressure": "Brake manometer: Brake cylinder pressure",
    "Entities.gmod_subway_ezh1.Buttons.Battery.VBToggle": "AB: Battery on/off",
    "Entities.gmod_subway_ezh1.Buttons.Meters.!TotalVoltmerer": "HV voltmeter (kV)",
    "Entities.gmod_subway_ezh1.Buttons.Meters.!TotalAmpermeter": "Total ampermeter (A)",
    "Entities.gmod_subway_ezh1.Buttons.FrontPneumatic.FrontBrakeLineIsolationToggle": "Brake line isolation valve",
    "Entities.gmod_subway_ezh1.Buttons.FrontPneumatic.FrontTrainLineIsolationToggle": "Train line isolation valve",
    "Entities.gmod_subway_ezh1.Buttons.RearDoor.RearDoor": "Passenger door",
    "Entities.gmod_subway_ezh1.Buttons.Tsepi.!BatteryVoltage": "Battery voltage",
    "Entities.gmod_subway_ezh1.Buttons.RearPneumatic.RearTrainLineIsolationToggle": "Train line isolation valve",
    "Entities.gmod_subway_ezh1.Buttons.RearPneumatic.RearBrakeLineIsolationToggle": "Brake line isolation valve",
    "Entities.gmod_subway_ezh1.Buttons.PassengerDoor.PassengerDoor": "Passenger door",
    "Entities.gmod_subway_ezh1.Buttons.Back2.!HVFuses": "HV fuses block",
    "Entities.gmod_subway_ezh1.Buttons.Back2.!Relays": "The box with the devices for battery recharging and door pressure diffuser",
    "Entities.gmod_subway_ezh1.Buttons.Back2.!Heater": "The heater",
    "Entities.gmod_subway_ezh1.Buttons.Main.RedRP": "RP: Red overload relay light (power circuits failed to assemble)",
    "Entities.gmod_subway_ezh1.Buttons.Main.GreenRP": "RP: Green overload relay light (overload relay open on current train)",
    "Entities.gmod_subway_ezh1.Buttons.Main.SD": "Blue door state light (doors are closed)",
    "Entities.gmod_subway_ezh1.Buttons.Main.DIPonSet": "KU4: Turn interior lights on",
    "Entities.gmod_subway_ezh1.Buttons.Main.DIPoffSet": "KU5: Turn interior lights off",
    "Entities.gmod_subway_ezh1.Buttons.Main.VozvratRPSet": "Switcher: Reset overload relay",
    "Entities.gmod_subway_ezh1.Buttons.Main.KSNSet": "Turn motor-compressor on",
    "Entities.gmod_subway_ezh1.Buttons.Main.KDPSet": "KDP: Open right doors",
    "Entities.gmod_subway_ezh1.Buttons.Main.KRZDSet": "KRZD: Emergency door closing",
    "Entities.gmod_subway_ezh1.Buttons.Main.KDLSet": "KU12: Open left doors",
    "Entities.gmod_subway_ezh1.Buttons.Main.KU1Toggle": "Switcher: Turn motor-compressor on",
    "Entities.gmod_subway_ezh1.Buttons.Main.VUD1Toggle": "Switcher: Doors control toggle (close doors)",
    "Entities.gmod_subway_ezh1.Buttons.AV1.VU3Toggle": "VU3: Cabin lighting",
    "Entities.gmod_subway_ezh1.Buttons.AV1.VU2Toggle": "VU2: Emergency lighting (45V)",
    "Entities.gmod_subway_ezh1.Buttons.AV1.VU1Toggle": "VU1: Cabin heater (3kWt)",
    "Entities.gmod_subway_ezh1.Buttons.AVMain.AV8BToggle": "AV-8B: Circuit breaker (High voltage auxiliary circuits)",
    "Entities.gmod_subway_ezh1.Buttons.CabinDoor.CabinDoor1": "Cabin door",
    "Entities.gmod_subway_ezh1.Buttons.Front.FrontDoor": "Front door",
    "Entities.gmod_subway_ezh1.Buttons.PassengerDoor1.PassengerDoor": "Passenger door",
    "Entities.gmod_subway_ezh1.Buttons.AirDistributor.AirDistributorDisconnectToggle": "Disable air distributor",
    "Entities.gmod_subway_ezh1.Buttons.GV.GVToggle": "GV: HV switch",
    "Entities.gmod_subway_ezh1.Buttons.VU.VUToggle": "VU: Enable train-control",
    "Entities.gmod_subway_ezh1.Buttons.HelperPanel.VUD2Toggle": "VUD2: Door control toggle (close doors)",
    "Entities.gmod_subway_ezh1.Buttons.HelperPanel.VDLSet": "VDL: Open left doors",
    "Entities.gmod_subway_ezh1.Buttons.ParkingBrake.ParkingBrakeLeft": "Parking brake",
    "Entities.gmod_subway_ezh1.Buttons.ParkingBrake.ParkingBrakeRight": "Parking brake",
    "Entities.gmod_subway_ezh1.Buttons.PneumaticManometer.!LinesPressure": "Pressure in pneumatic lines (red: brake line, black: train line)"
}
]]
