return [[
{
    "Lang": "en",
    "Name": "English",


    "Entities.gmod_subway_em508.Buttons.Back.BackDoor": "Rear door",
    "Entities.gmod_subway_em508.Buttons.HelperPanel.R_Program1Set": "Program 1",
    "Entities.gmod_subway_em508.Buttons.HelperPanel.R_Program2Set": "Program 2",
    "Entities.gmod_subway_em508.Buttons.HelperPanel.VDLSet": "VDL: Left doors open",
    "Entities.gmod_subway_em508.Buttons.HelperPanel.VUD2Toggle": "VUD2: Door control toggle (close doors)",
    "Entities.gmod_subway_em508.Buttons.AV2.RSTToggle": "RST: Radiostation",
    "Entities.gmod_subway_em508.Buttons.RearPneumatic.RearTrainLineIsolationToggle": "Train line isolation valve",
    "Entities.gmod_subway_em508.Buttons.RearPneumatic.RearBrakeLineIsolationToggle": "Brake line isolation valve",
    "Entities.gmod_subway_em508.Buttons.AVU.AVULight": "Lamp: Automatic control disabler is active",
    "Entities.gmod_subway_em508.Buttons.AVU.OtklAVUToggle": "OtklAVU: Turn off automatic control disable relay (failure of AVU)",
    "Entities.gmod_subway_em508.Buttons.Back2.!HVFuses": "HV fuses block",
    "Entities.gmod_subway_em508.Buttons.Back2.!Relays": "The box with the devices for battery recharging and door pressure diffuser",
    "Entities.gmod_subway_em508.Buttons.Back2.!Heater": "The heater",
    "Entities.gmod_subway_em508.Buttons.Main.DoorSelectToggle": "Switcher:Select doors side",
    "Entities.gmod_subway_em508.Buttons.Main.DIPonSet": "Swithcer:Turn interior lights on",
    "Entities.gmod_subway_em508.Buttons.Main.DIPoffSet": "Swithcer:Turn interior lights off",
    "Entities.gmod_subway_em508.Buttons.Main.VozvratRPSet": "VRP:Reset overload relay",
    "Entities.gmod_subway_em508.Buttons.Main.KSNSet": "KSN: Forced activation of the RP on the faulty wagon (Malfunction signaling)",
    "Entities.gmod_subway_em508.Buttons.Main.KRZDSet": "KRZD: Emergency door closing",
    "Entities.gmod_subway_em508.Buttons.Main.KSDSet": "KSD: Door state controle(Door check)",
    "Entities.gmod_subway_em508.Buttons.Main.KDPSet": "KDP: Right doors open",
    "Entities.gmod_subway_em508.Buttons.Main.KDLSet": "KDL: Left doors open",
    "Entities.gmod_subway_em508.Buttons.Main.RezMKSet": "RMC: Emergency motor-compressor enabling",
    "Entities.gmod_subway_em508.Buttons.Main.KU1Toggle": "MK: Turn motor-compressor on",
    "Entities.gmod_subway_em508.Buttons.Main.VUD1Toggle": "VUD: Door control toggle (close doors)",
    "Entities.gmod_subway_em508.Buttons.AV1.VU3Toggle": "VU3: Cabin lighting",
    "Entities.gmod_subway_em508.Buttons.AV1.VU2Toggle": "VU2: Emergency lighting",
    "Entities.gmod_subway_em508.Buttons.AV1.VU1Toggle": "VU1: Cabin heater",
    "Entities.gmod_subway_em508.Buttons.Back1.!ULSPM": "UESPM (Emergency intercom)",
    "Entities.gmod_subway_em508.Buttons.Back1.!TonalARS": "Ring",
    "Entities.gmod_subway_em508.Buttons.Back1.!PressureRelay": "Pressure controller",
    "Entities.gmod_subway_em508.Buttons.Back1.!Reproductor": "Speaker",
    "Entities.gmod_subway_em508.Buttons.Back1.!LVFuses": "Shield with low-voltage fuses",
    "Entities.gmod_subway_em508.Buttons.Back1.R_UNchToggle": "Announcer control",
    "Entities.gmod_subway_em508.Buttons.Lamp.L_3Toggle": "Lamp: Gauges lighting",
    "Entities.gmod_subway_em508.Buttons.DriverValveTLDisconnect.DriverValveTLDisconnectToggle": "Train line disconnect valve",
    "Entities.gmod_subway_em508.Buttons.VU.VUToggle": "VU: Train control",
    "Entities.gmod_subway_em508.Buttons.PneumaticManometer.!LinesPressure": "Pressure in pneumatic lines (red: brake line, black: train line)",
    "Entities.gmod_subway_em508.Buttons.Stopkran.EmergencyBrakeValveToggle": "Emergency brake",
    "Entities.gmod_subway_em508.Buttons.LAMPS.SN": "Lamp: Overload relay light (overload relay open on current train)",
    "Entities.gmod_subway_em508.Buttons.LAMPS.RedRP": "Lamp: Red overload relay light (power circuits failed to assemble)",
    "Entities.gmod_subway_em508.Buttons.LAMPS.SD": "Lamp: SD door state light (doors are open)",
    "Entities.gmod_subway_em508.Buttons.LAMPS.GreenRP": "Lamp: Green overload relay light",
    "Entities.gmod_subway_em508.Buttons.LAMPS.UKS": "Speed control device UKS-20M",
    "Entities.gmod_subway_em508.Buttons.LAMPS.Red": "Lamp: The heater is on",
    "Entities.gmod_subway_em508.Buttons.LAMPS.AGS": "Lamp: AGS (Automatic Creast Greaser)",
    "Entities.gmod_subway_em508.Buttons.UAVAPanel.UAVAToggle": "UAVA: Universal Automatic Autostop Disabler (disable autostop)",
    "Entities.gmod_subway_em508.Buttons.UAVAPanel.UAVACToggle   ": "UAVA: Universal Automatic Autostop Disabler(reset contacts)",
    "Entities.gmod_subway_em508.Buttons.PneumaticPanels.!CylinderPressure": "Brake cylinder pressure",
    "Entities.gmod_subway_em508.Buttons.Battery.VBToggle": "VB: Battery on/off",
    "Entities.gmod_subway_em508.Buttons.Battery.R_RadioToggle": "Announcer power (+50V)",
    "Entities.gmod_subway_em508.Buttons.FrontPneumatic.FrontBrakeLineIsolationToggle": "Brake line isolation valve",
    "Entities.gmod_subway_em508.Buttons.FrontPneumatic.FrontTrainLineIsolationToggle": "Train line isolation valve",
    "Entities.gmod_subway_em508.Buttons.ASNP.R_ASNPMenuSet": "Announcer: Menu",
    "Entities.gmod_subway_em508.Buttons.ASNP.R_ASNPUpSet": "Announcer: Up",
    "Entities.gmod_subway_em508.Buttons.ASNP.R_ASNPDownSet": "Announcer: Down",
    "Entities.gmod_subway_em508.Buttons.ASNP.R_ASNPOnToggle": "Announcer: Turn on",
    "Entities.gmod_subway_em508.Buttons.VU1.KRPSet": "RRP: Emergency start",
    "Entities.gmod_subway_em508.Buttons.GV.GVToggle": "GV: HV switch",
    "Entities.gmod_subway_em508.Buttons.IGLAButtons.IGLA1USet": "IGLA: First button up",
    "Entities.gmod_subway_em508.Buttons.IGLAButtons.IGLA1Set": "IGLA: First button",
    "Entities.gmod_subway_em508.Buttons.IGLAButtons.IGLA1DSet": "IGLA: First button down",
    "Entities.gmod_subway_em508.Buttons.IGLAButtons.IGLA2USet": "IGLA: Second button up",
    "Entities.gmod_subway_em508.Buttons.IGLAButtons.IGLA2Set": "IGLA: Second button",
    "Entities.gmod_subway_em508.Buttons.IGLAButtons.IGLA2DSet": "IGLA: Second button down",
    "Entities.gmod_subway_em508.Buttons.IGLAButtons.!IGLASR": "IGLA: SR",
    "Entities.gmod_subway_em508.Buttons.IGLAButtons.!IGLARX": "IGLA: RX",
    "Entities.gmod_subway_em508.Buttons.IGLAButtons.!IGLAErr": "IGLA: Malfunction",
    "Entities.gmod_subway_em508.Buttons.IGLAButtons.!IGLAOSP": "IGLA: OSP(Fire extinguisher)",
    "Entities.gmod_subway_em508.Buttons.IGLAButtons.!IGLAPI": "IGLA: PI(Fire indication)",
    "Entities.gmod_subway_em508.Buttons.IGLAButtons.!IGLAOff": "IGLA: Off",
    "Entities.gmod_subway_em508.Buttons.PassengerDoor.PassengerDoor": "Passenger door",
    "Entities.gmod_subway_em508.Buttons.InfoTableSelect.PrevSign": "Previous sign",
    "Entities.gmod_subway_em508.Buttons.InfoTableSelect.NextSign": "Next sign",
    "Entities.gmod_subway_em508.Buttons.InfoTableSelect.Num2P": "Route: Increase 2nd number",
    "Entities.gmod_subway_em508.Buttons.InfoTableSelect.Num2M": "Route: Decrease 2nd number",
    "Entities.gmod_subway_em508.Buttons.InfoTableSelect.Num1P": "Route: Increase 1st number",
    "Entities.gmod_subway_em508.Buttons.InfoTableSelect.Num1M": "Route: Decrease 1st number",
    "Entities.gmod_subway_em508.Buttons.Front.FrontDoor": "Front door",
    "Entities.gmod_subway_em508.Buttons.KRR.KRRSet": "KRR: Button of enabling reversers",
    "Entities.gmod_subway_em508.Buttons.AGS.VUSToggle": "Switcher: Near Headlights(down)/Far Headlights (up)",
    "Entities.gmod_subway_em508.Buttons.CabinDoor.CabinDoor": "Cabin door",
    "Entities.gmod_subway_em508.Buttons.PassengerDoor1.PassengerDoor": "Passenger door",
    "Entities.gmod_subway_em508.Buttons.ParkingBrake.ParkingBrakeLeft": "Parking brake",
    "Entities.gmod_subway_em508.Buttons.ParkingBrake.ParkingBrakeRight": "Parking brake",
    "Entities.gmod_subway_em508.Buttons.AVMain.AV8BToggle": "AV-8B: Circuit breaker (High voltage auxiliary circuits)",
    "Entities.gmod_subway_em508.Buttons.Back3.!RTM": "Remote radio with dispatcher",
    "Entities.gmod_subway_em508.Buttons.Back3.!ULSPMSpeaker": "Emergency intercom speaker block",
    "Entities.gmod_subway_em508.Buttons.Back3.!Amplifier": "Amplifier unit of train station",
    "Entities.gmod_subway_em508.Buttons.DriverValveBLDisconnect.DriverValveBLDisconnectToggle": "Brake line disconnect valve",
    "Entities.gmod_subway_em508.Buttons.AirDistributor.AirDistributorDisconnectToggle": "Disable air distributor",



    "Entities.gmod_subway_em508_int.Buttons.Stopkran.EmergencyBrakeValveToggle": "Emergency brake",
    "Entities.gmod_subway_em508_int.Buttons.Back.BackDoor": "Rear door",
    "Entities.gmod_subway_em508_int.Buttons.HelperPanel.R_Program1Set": "Program 1",
    "Entities.gmod_subway_em508_int.Buttons.HelperPanel.R_Program2Set": "Program 2",
    "Entities.gmod_subway_em508_int.Buttons.HelperPanel.VDLSet": "VDL: Left doors open",
    "Entities.gmod_subway_em508_int.Buttons.HelperPanel.VUD2Toggle": "VUD2: Door control toggle (close doors)",
    "Entities.gmod_subway_em508_int.Buttons.DriverValveBLDisconnect.DriverValveBLDisconnectToggle": "Brake line disconnect valve",
    "Entities.gmod_subway_em508_int.Buttons.Battery.VBToggle": "AB: Battery on/off",
    "Entities.gmod_subway_em508_int.Buttons.Battery.R_RadioToggle": "Announcer power (+50V)",
    "Entities.gmod_subway_em508_int.Buttons.FrontPneumatic.FrontBrakeLineIsolationToggle": "Brake line isolation valve",
    "Entities.gmod_subway_em508_int.Buttons.FrontPneumatic.FrontTrainLineIsolationToggle": "Train line isolation valve",
    "Entities.gmod_subway_em508_int.Buttons.AirDistributor.AirDistributorDisconnectToggle": "Disable air distributor",
    "Entities.gmod_subway_em508_int.Buttons.PassengerDoor.PassengerDoor": "Passenger door",
    "Entities.gmod_subway_em508_int.Buttons.VU1.KRPSet": "RRP: Emergency start",
    "Entities.gmod_subway_em508_int.Buttons.UAVAPanel.UAVAToggle": "UAVA: Universal Automatic Autostop Disabler (disable autostop)",
    "Entities.gmod_subway_em508_int.Buttons.UAVAPanel.UAVACToggle   ": "UAVA: Universal Automatic Autostop Disabler(reset contacts)",
    "Entities.gmod_subway_em508_int.Buttons.Front.FrontDoor": "Front door",
    "Entities.gmod_subway_em508_int.Buttons.Tsepi.!BatteryVoltage": "Battery voltage",
    "Entities.gmod_subway_em508_int.Buttons.RearPneumatic.RearTrainLineIsolationToggle": "Train line isolation valve",
    "Entities.gmod_subway_em508_int.Buttons.RearPneumatic.RearBrakeLineIsolationToggle": "Brake line isolation valve",
    "Entities.gmod_subway_em508_int.Buttons.InfoTableSelect.PrevSign": "Previous sign",
    "Entities.gmod_subway_em508_int.Buttons.InfoTableSelect.NextSign": "Next sign",
    "Entities.gmod_subway_em508_int.Buttons.InfoTableSelect.Num2P": "Route: Increase 2nd number",
    "Entities.gmod_subway_em508_int.Buttons.InfoTableSelect.Num2M": "Route: Decrease 2nd number",
    "Entities.gmod_subway_em508_int.Buttons.InfoTableSelect.Num1P": "Route: Increase 1st number",
    "Entities.gmod_subway_em508_int.Buttons.InfoTableSelect.Num1M": "Route: Decrease 1st number",
    "Entities.gmod_subway_em508_int.Buttons.Back2.!HVFuses": "HV fuses block",
    "Entities.gmod_subway_em508_int.Buttons.Back2.!Relays": "The box with the devices for battery recharging and door pressure diffuser",
    "Entities.gmod_subway_em508_int.Buttons.Back2.!Heater": "The heater",
    "Entities.gmod_subway_em508_int.Buttons.Main.GreenRP": "Lamp: Green overload relay light",
    "Entities.gmod_subway_em508_int.Buttons.Main.RedRP": "Lamp: Red overload relay light (power circuits failed to assemble)",
    "Entities.gmod_subway_em508_int.Buttons.Main.SD": "Lamp: SD door state light (doors are open)",
    "Entities.gmod_subway_em508_int.Buttons.Main.DIPonSet": "Switcher: Turn interior lights on",
    "Entities.gmod_subway_em508_int.Buttons.Main.DIPoffSet": "Switcher: Turn interior lights off",
    "Entities.gmod_subway_em508_int.Buttons.Main.VozvratRPSet": "VRP: Reset overload relay",
    "Entities.gmod_subway_em508_int.Buttons.Main.KSNSet": "KSN: Forced activation of the RP on the faulty wagon (Malfunction signaling)",
    "Entities.gmod_subway_em508_int.Buttons.Main.KRZDSet": "KRZD: Emergency door closing",
    "Entities.gmod_subway_em508_int.Buttons.Main.KDPSet": "KDP: Right doors open",
    "Entities.gmod_subway_em508_int.Buttons.Main.KDLSet": "KDL: Left doors open",
    "Entities.gmod_subway_em508_int.Buttons.Main.KU1Toggle": "MK: Turn motor-compressor on",
    "Entities.gmod_subway_em508_int.Buttons.Main.VUD1Toggle": "VUD: Door control toggle (close doors)",
    "Entities.gmod_subway_em508_int.Buttons.AV1.VU3Toggle": "VU3: Cabin lighting",
    "Entities.gmod_subway_em508_int.Buttons.AV1.VU2Toggle": "VU2: Emergency lighting",
    "Entities.gmod_subway_em508_int.Buttons.AV1.VU1Toggle": "VU1: Cabin heater",
    "Entities.gmod_subway_em508_int.Buttons.AVMain.AV8BToggle": "AV-8B: Circuit breaker (High voltage auxiliary circuits)",
    "Entities.gmod_subway_em508_int.Buttons.CabinDoor.CabinDoor": "Cabin door",
    "Entities.gmod_subway_em508_int.Buttons.Lamp.L_3Toggle": "Lamp: Gauges lighting",
    "Entities.gmod_subway_em508_int.Buttons.PassengerDoor1.PassengerDoor": "Passenger door",
    "Entities.gmod_subway_em508_int.Buttons.DriverValveTLDisconnect.DriverValveTLDisconnectToggle": "Train line disconnect valve",
    "Entities.gmod_subway_em508_int.Buttons.GV.GVToggle": "GV: HV switch",
    "Entities.gmod_subway_em508_int.Buttons.VU.VUToggle": "VU: Train control",
    "Entities.gmod_subway_em508_int.Buttons.PneumaticPanels.!CylinderPressure": "Brake cylinder pressure",
    "Entities.gmod_subway_em508_int.Buttons.ParkingBrake.ParkingBrakeLeft": "Parking brake",
    "Entities.gmod_subway_em508_int.Buttons.ParkingBrake.ParkingBrakeRight": "Parking brake",
    "Entities.gmod_subway_em508_int.Buttons.PneumaticManometer.!LinesPressure": "Pressure in pneumatic lines (red: brake line, black: train line)"
}
]]
