return [[
{
	"Lang": "en",
	"Name": "English",
	"Panel.Admin": "Admin",
	"Panel.Client": "Client",
	"Panel.DrawDebugInfo": "Draw debugging info",
	"Panel.DisableCamAccel": "Disable cam acceleration",
	"Panel.DisableHoverText": "Disable hover text",
	"Panel.DrawCams": "Render cameras",
	"Panel.FOV": "Field of view",

	"Train.Common.Camera0": "Driver seat",

	"Train.Buttons.Sealed": "Sealed",

	"Entities.gmod_subway_base.Name": "Subway base",
	"Entities.gmod_subway_81-703.Name": "E",
	"Entities.gmod_subway_81-703_2.Name": "E (intermediate)",
	"Entities.gmod_subway_81-717_mvm.Name": "81-717(MVM)",
	"Entities.gmod_subway_81-717_lvz.Name": "81-717(LVZ)",
	"Entities.gmod_subway_81-714_mvm.Name": "81-714(MVM)",
	"Entities.gmod_subway_81-714_lvz.Name": "81-714(LVZ)",
	"Entities.gmod_subway_81-7036.Name": "81-7036 (doesn't work)",
	"Entities.gmod_subway_81-7037.Name": "81-7037 (doesn't work)",
	"Entities.gmod_subway_81-720.Name": "81-720 (head)",
	"Entities.gmod_subway_81-721.Name": "81-721 (intermediate)",
	"Entities.gmod_subway_81-722.Name": "81-722 (head)",
	"Entities.gmod_subway_81-723.Name": "81-723 (intermediate motor)",
	"Entities.gmod_subway_81-724.Name": "81-724 (intermediate trailer)",
	"Entities.gmod_subway_e.Name": "E",
	"Entities.gmod_subway_em.Name": "Em",
	"Entities.gmod_subway_ema.Name": "Ema",
	"Entities.gmod_subway_ezh.Name": "Ezh",
	"Entities.gmod_subway_ezh1.Name": "Ezh1",
	"Entities.gmod_subway_em508.Name": "Em-508",
	"Entities.gmod_subway_em508_int.Name": "Em-508 (intermediate)",
	"Entities.gmod_subway_ezh3.Name": "Ezh3",
	"Entities.gmod_subway_ezh3ru1.Name": "Ezh3 RU1",
	"Entities.gmod_subway_ema508t.Name": "Em-508t",
	"Entities.gmod_subway_tatra_t3.Name": "Tatra T3",
	"Entities.gmod_subway_ai.Name": "AI train",

	"Entities.gmod_train_bogey.Name": "Train bogey",
	"Entities.gmod_train_couple.Name": "Couple",

	"Entities.gmod_track_pui.Name": "PUI clock",
	"Entities.gmod_track_mus_elektronika7.Name": "Electronika clock",
	"Entities.gmod_mus_clock_analog.Name": "Analog clock",
	"Entities.gmod_track_clock_time.Name": "Big interval clock(time)",
	"Entities.gmod_track_clock_small.Name": "Small interval clock",
	"Entities.gmod_track_clock_interval.Name": "Big interval clock(interval)",
	"Entities.gmod_track_switch.Name": "Track switch",
	"Entities.gmod_track_powermeter.Name": "Power meter",
	"Entities.gmod_track_controller.Name": "Track controller",
	"Entities.gmod_track_udochka.Name": "Electric connector",
	"Entities.gmod_train_spawner.Name": "Train spawner",

	"Train.703.VU": "Train-control",
	"Train.703.Breakers1" : "Batteries",
	"Train.703.Breakers2" : "Circuit breakers",
	"Train.703.RCARS" : "RC-ARS",
	"Train.703.Left" : "Helper panel",
	"Train.703.Parking" : "UAVA and parking brake",
	"Train.703.ASNP" : "ASNP",
	"Train.703.IGLA" : "IGLA",
	"Train.717.Breakers1": "Middle side circuit breakers",
	"Train.717.VB1": "Panel with RC",
	"Train.717.Breakers2": "Right side circuit breakers",
	"Train.717.VB2": "Bottom panel with RC",
	"Train.717.UAVA": "UAVA",
	"Train.717.Pneumo": "Pneumatic valves",
	"Train.717.Helpers": "Helper panel",
	"Train.717.Block4": "4th block",
	"Train.717.IGLA": "IGLA",
	"Train.717.ASNP" : "ASNP",
	"Train.720.CameraCond": "Conditioners panel",
	"Train.720.CameraPPZ": "Train protection panel",
	"Train.720.CameraPV": "Auxiliary buttons panel",
	"Train.720.CameraASNP": "ASNP",
	"Train.720.CameraVityaz": "SAU Vityaz",
	"Train.720.CameraKRMH": "KRMSH valve",
	"Train.720.CameraPVZ": "Wagon protection panel",
	"Train.722.Breakers": "Train protection circuit breakers",
	"Train.722.PU2_1": "Buttons panel",
	"Train.722.PU2_2": "Disablers panel",
	"Train.722.Vityaz": "SAU Vityaz-SP screen",
	"Train.722.SARMAT": "BM CIK SARMAT screen",
	"Train.722.CabLights": "Cabin ligting panel",
	"Train.722.Route": "Setting route number",
	"Train.722.Disconnects": "Isolation valves",
	"Train.722.KRMH": "KRMSH & RVTB disabler"
}
]]
