return [[
{
  "Lang": "en",
  "Name": "English",


  "Entities.gmod_subway_ezh3.Buttons.Stopkran.EmergencyBrakeValveToggle": "Emergency brake",
  "Entities.gmod_subway_ezh3.Buttons.Back.BackDoor": "Back door",
  "Entities.gmod_subway_ezh3.Buttons.DriverValveBLTLDisconnect.DriverValveBLDisconnectToggle": "Brake line disconnect valve",
  "Entities.gmod_subway_ezh3.Buttons.DriverValveBLTLDisconnect.DriverValveTLDisconnectToggle": "Train line disconnect valve",
  "Entities.gmod_subway_ezh3.Buttons.Battery.VBToggle": "VB: Battery on/off (low voltage)",
  "Entities.gmod_subway_ezh3.Buttons.FrontPneumatic.FrontBrakeLineIsolationToggle": "Brake line isolation valve",
  "Entities.gmod_subway_ezh3.Buttons.FrontPneumatic.FrontTrainLineIsolationToggle": "Train line isolation valve",
  "Entities.gmod_subway_ezh3.Buttons.ASNP.R_ASNPMenuSet": "Announcer: Menu",
  "Entities.gmod_subway_ezh3.Buttons.ASNP.R_ASNPUpSet": "Announcer: Up",
  "Entities.gmod_subway_ezh3.Buttons.ASNP.R_ASNPDownSet": "Announcer: Down",
  "Entities.gmod_subway_ezh3.Buttons.ASNP.R_ASNPOnToggle": "Announcer: Turn on",
  "Entities.gmod_subway_ezh3.Buttons.PassengerDoor1.PassengerDoor": "Passenger door",
  "Entities.gmod_subway_ezh3.Buttons.PassengerDoor.PassengerDoor": "Passenger door",
  "Entities.gmod_subway_ezh3.Buttons.CabinDoor.CabinDoor": "Cabin door",
  "Entities.gmod_subway_ezh3.Buttons.Front.FrontDoor": "Front door",
  "Entities.gmod_subway_ezh3.Buttons.GV.GVToggle": "HV switch",
  "Entities.gmod_subway_ezh3.Buttons.RearPneumatic.RearTrainLineIsolationToggle": "Train line disconnect valve",
  "Entities.gmod_subway_ezh3.Buttons.RearPneumatic.RearBrakeLineIsolationToggle": "Brake line disconnect valve",
  "Entities.gmod_subway_ezh3.Buttons.Panel.!OCH": "NCh: No ARS frequency",
  "Entities.gmod_subway_ezh3.Buttons.Panel.!0": "0: ARS stop signal",
  "Entities.gmod_subway_ezh3.Buttons.Panel.!40": "Speed limit 40 kph",
  "Entities.gmod_subway_ezh3.Buttons.Panel.!60": "Speed limit 60 kph",
  "Entities.gmod_subway_ezh3.Buttons.Panel.!70": "Speed limit 70 kph",
  "Entities.gmod_subway_ezh3.Buttons.Panel.!80": "Speed limit 80 kph",
  "Entities.gmod_subway_ezh3.Buttons.Panel.!Speedometer": "Speedometer (km/h)",
  "Entities.gmod_subway_ezh3.Buttons.Panel.!TotalAmpermeter": "Total engines ampermeter (A)",
  "Entities.gmod_subway_ezh3.Buttons.Panel.!TotalVoltmeter": "Total voltmeter (kV)",
  "Entities.gmod_subway_ezh3.Buttons.Panel.!BatteryVoltage": "Battery voltage of train control(V)",
  "Entities.gmod_subway_ezh3.Buttons.Panel.!BrakeCylinder": "Brake cylinder pressure",
  "Entities.gmod_subway_ezh3.Buttons.Panel.!LinesPressure": "Pressure in pneumatic lines (red: brake line, black: train line)",
  "Entities.gmod_subway_ezh3.Buttons.Main.KU1Toggle": "Turn motor-compressor on",
  "Entities.gmod_subway_ezh3.Buttons.Main.SAMM1Set": "SAMM: Turning off drive",
  "Entities.gmod_subway_ezh3.Buttons.Main.SAMM2Set": "SAMM: Start",
  "Entities.gmod_subway_ezh3.Buttons.Main.SAMM3Set": "SAMM: Reset",
  "Entities.gmod_subway_ezh3.Buttons.Main.SAMMSignal1": "Lamp: Drive-Brake",
  "Entities.gmod_subway_ezh3.Buttons.Main.SAMMSignal2": "Lamp: Working state SAMM",
  "Entities.gmod_subway_ezh3.Buttons.Main.SAMMSignal3": "Lamp: Enabled SAMM execution unit",
  "Entities.gmod_subway_ezh3.Buttons.Main.SAMMOnToggle": "SAMM: Turn autodrive on",
  "Entities.gmod_subway_ezh3.Buttons.Main.SAMMBlokToggle": "SAMM: Execution unit",
  "Entities.gmod_subway_ezh3.Buttons.Main.SAMMCommand3Set": "SAMM: X-2",
  "Entities.gmod_subway_ezh3.Buttons.Main.SAMMCommand2Set": "SAMM: Catch Up",
  "Entities.gmod_subway_ezh3.Buttons.Main.SAMMCommand1Set": "SAMM: Permission",
  "Entities.gmod_subway_ezh3.Buttons.Main.KSNSet": "KSN: Failure indication button",
  "Entities.gmod_subway_ezh3.Buttons.Main.R_Program1Set": "Program 1",
  "Entities.gmod_subway_ezh3.Buttons.Main.R_Program2Set": "Program 2",
  "Entities.gmod_subway_ezh3.Buttons.Main.VUSToggle": "Switch: Near Headlights(down)/Far Headlights (up)",
  "Entities.gmod_subway_ezh3.Buttons.Main.L_3Toggle": "Switch: Gauges lighting",
  "Entities.gmod_subway_ezh3.Buttons.Main.VAHToggle": "Switch: Emergency Run",
  "Entities.gmod_subway_ezh3.Buttons.Main.DIPonSet": "Osv. Vkl.: Turn on lighting",
  "Entities.gmod_subway_ezh3.Buttons.Main.DIPoffSet": "Osv. Vykl.: Turn off lighting",
  "Entities.gmod_subway_ezh3.Buttons.Main.KSDSet": "KSD: Doors signalization check",
  "Entities.gmod_subway_ezh3.Buttons.Main.KVTSet": "KVT: Brake perception button",
  "Entities.gmod_subway_ezh3.Buttons.Main.KBSet": "KB: Attention button",
  "Entities.gmod_subway_ezh3.Buttons.Main.KBLamp": "Lamp: RK spinning",
  "Entities.gmod_subway_ezh3.Buttons.Main.ARSToggle": "ARS: Automatic speed regulation",
  "Entities.gmod_subway_ezh3.Buttons.Main.R_UNchToggle": "UNCh: Low frequency amplifier",
  "Entities.gmod_subway_ezh3.Buttons.Main.VUD1Toggle": "VUD: Door control toggle (close doors)",
  "Entities.gmod_subway_ezh3.Buttons.Main.R_RadioToggle": "Radioinformator: Announcer (built-in)",
  "Entities.gmod_subway_ezh3.Buttons.Main.ALSToggle": "ALS: Automatic locomotive signalling",
  "Entities.gmod_subway_ezh3.Buttons.Main.VozvratRPSet": "KVRP: Reset overload relay",
  "Entities.gmod_subway_ezh3.Buttons.Main.RingSet": "Ring",
  "Entities.gmod_subway_ezh3.Buttons.Main.L_2Toggle": "Switch: Cabin lighting",
  "Entities.gmod_subway_ezh3.Buttons.Main.KRZDSet": "KRZD: Emergency door closing",
  "Entities.gmod_subway_ezh3.Buttons.Main.KDPSet": "KDP: Open right doors",
  "Entities.gmod_subway_ezh3.Buttons.Main.KDLSet": "KDL: Open left doors",
  "Entities.gmod_subway_ezh3.Buttons.Main.KAHSet": "KAH: Emergency drive button",
  "Entities.gmod_subway_ezh3.Buttons.Main.RezMKSet": "Emergency motor-compressor startup",
  "Entities.gmod_subway_ezh3.Buttons.Main.KRPSet": "KRP: Emergency start button",
  "Entities.gmod_subway_ezh3.Buttons.Main.RSTToggle": "VPR: Radiostation enable",
  "Entities.gmod_subway_ezh3.Buttons.Main.R_GToggle": "Loudspeaker: Sound in cabin enable",
  "Entities.gmod_subway_ezh3.Buttons.Main.Custom2Set": "Unused switch",
  "Entities.gmod_subway_ezh3.Buttons.Main.Custom3Set": "Unused switch",
  "Entities.gmod_subway_ezh3.Buttons.Main.ASNPPlay": "Announcer work indicator",
  "Entities.gmod_subway_ezh3.Buttons.AV1.VU3Toggle": "VU3: Cabin light",
  "Entities.gmod_subway_ezh3.Buttons.AV1.VU2Toggle": "VU2: Emergency lighting (45V)",
  "Entities.gmod_subway_ezh3.Buttons.AV1.VU1Toggle": "VU1: Cabin heater (3kWt)",
  "Entities.gmod_subway_ezh3.Buttons.AVMain.AV8BToggle": "AV-8B: Automatic switch (High voltage)",
  "Entities.gmod_subway_ezh3.Buttons.RC1.RC1Toggle": "RC-ARS: ARS Circuit Breaker",
  "Entities.gmod_subway_ezh3.Buttons.UAVAPanel.UAVAToggle": "UAVA: Universal Automatic Autostop Disabler (disable autostop)",
  "Entities.gmod_subway_ezh3.Buttons.UAVAPanel.UAVACToggle   ": "UAVA: Universal Automatic Autostop Disabler(reset contacts)",
  "Entities.gmod_subway_ezh3.Buttons.VUHelper.VUToggle": "VU: Enable train-control",
  "Entities.gmod_subway_ezh3.Buttons.HelperPanel.VDLSet": "KDL: Open left doors",
  "Entities.gmod_subway_ezh3.Buttons.HelperPanel.VUD2Toggle": "VUD2: Door control toggle (close doors)",
  "Entities.gmod_subway_ezh3.Buttons.EPKDisconnect.EPKToggle": "EPK disconnect valve",
  "Entities.gmod_subway_ezh3.Buttons.VU.VUToggle": "VU: Enable train-control",
  "Entities.gmod_subway_ezh3.Buttons.ParkingBrake.ParkingBrakeLeft": "Parking brake wheel",
  "Entities.gmod_subway_ezh3.Buttons.ParkingBrake.ParkingBrakeRight": "Parking brake wheel",
  "Entities.gmod_subway_ezh3.Buttons.AirDistributor.AirDistributorDisconnectToggle": "Disable air distributor",

  "Entities.gmod_subway_em508t.Buttons.Stopkran.EmergencyBrakeValveToggle": "Emergency brake",
  "Entities.gmod_subway_em508t.Buttons.Battery.VBToggle": "VB: Battery on/off (low voltage)",
  "Entities.gmod_subway_em508t.Buttons.FrontPneumatic.FrontBrakeLineIsolationToggle": "Brake line disconnect valve",
  "Entities.gmod_subway_em508t.Buttons.FrontPneumatic.FrontTrainLineIsolationToggle": "Train line disconnect valve",
  "Entities.gmod_subway_em508t.Buttons.GV.GVToggle": "HV switch",
  "Entities.gmod_subway_em508t.Buttons.RearPneumatic.RearTrainLineIsolationToggle": "Train line disconnect valve",
  "Entities.gmod_subway_em508t.Buttons.RearPneumatic.RearBrakeLineIsolationToggle": "Brake line disconnect valve",
  "Entities.gmod_subway_em508t.Buttons.RearDoor.RearDoor": "Passenger door",
  "Entities.gmod_subway_em508t.Buttons.Back2.!HVFuse": "HV fuses block",
  "Entities.gmod_subway_em508t.Buttons.Back2.!Relays": "The box with the devices for battery recharging and door pressure diffuser",
  "Entities.gmod_subway_em508t.Buttons.Back2.!Heater": "The heater",
  "Entities.gmod_subway_em508t.Buttons.Front.FrontDoor": "Front door",
  "Entities.gmod_subway_em508t.Buttons.AV1.VU3Toggle": "VU3: Cabin light",
  "Entities.gmod_subway_em508t.Buttons.AV1.VU2Toggle": "VU2: Emergency lighting (45V)",
  "Entities.gmod_subway_em508t.Buttons.AV1.VU1Toggle": "VU1: Cabin heater (3kWt)",
  "Entities.gmod_subway_em508t.Buttons.ParkingBrake.ParkingBrakeLeft": "Parking brake wheel",
  "Entities.gmod_subway_em508t.Buttons.ParkingBrake.ParkingBrakeRight": "Parking brake wheel",
  "Entities.gmod_subway_em508t.Buttons.CabinDoor.CabinDoor1": "Cabin door",
  "Entities.gmod_subway_em508t.Buttons.PassengerDoor.PassengerDoor": "Passenger door",
  "Entities.gmod_subway_em508t.Buttons.PassengerDoor1.PassengerDoor": "Passenger door",
  "Entities.gmod_subway_em508t.Buttons.Main.!RedRP": "RP: Red overload relay light (power circuits failed to assemble)",
  "Entities.gmod_subway_em508t.Buttons.Main.!GreenRP": "RP: Green overload relay light (prevents overcurrent of engines)",
  "Entities.gmod_subway_em508t.Buttons.Main.!SD": "Blue door state light (doors are closed)",
  "Entities.gmod_subway_em508t.Buttons.Main.KDLSet": "Switch: Open left doors",
  "Entities.gmod_subway_em508t.Buttons.Main.KSDSet": "Switch: Signalization (Doors control check)",
  "Entities.gmod_subway_em508t.Buttons.Main.VozvratRPSet": "Switch: Reset overload relay",
  "Entities.gmod_subway_em508t.Buttons.Main.KSNSet": "Switch: Failure indication switch",
  "Entities.gmod_subway_em508t.Buttons.Main.VUD1Toggle": "Switch: Doors control toggle (close doors)",
  "Entities.gmod_subway_em508t.Buttons.Main.KU1Toggle": "Switch: Compressor turn on",
  "Entities.gmod_subway_em508t.Buttons.Main.DIPonSet": "KU4: Turn interior lights on",
  "Entities.gmod_subway_em508t.Buttons.Main.DIPoffSet": "KU5: Turn interior lights off",
  "Entities.gmod_subway_em508t.Buttons.Main.RezMKSet": "Switch: Emergency motor-compressor startup",
  "Entities.gmod_subway_em508t.Buttons.Main.KDPSet": "KDP: Open right doors",
  "Entities.gmod_subway_em508t.Buttons.Main.KRZDSet": "KU10: Emergency door closing",
  "Entities.gmod_subway_em508t.Buttons.AVMain.AV8BToggle": "AV-8B: Automatic switch (High voltage)",
  "Entities.gmod_subway_em508t.Buttons.VU.VUToggle": "VU: Enable train-control",
  "Entities.gmod_subway_em508t.Buttons.VU.!Voltage": "Control circuits voltage",
  "Entities.gmod_subway_em508t.Buttons.HelperPanel.VUD2Toggle": "VUD2: Door control toggle (close doors)",
  "Entities.gmod_subway_em508t.Buttons.HelperPanel.VDLSet": "VDL: Open left doors",
  "Entities.gmod_subway_em508t.Buttons.DriverValveBLTLDisconnect.DriverValveBLDisconnectToggle": "Brake line disconnect valve",
  "Entities.gmod_subway_em508t.Buttons.DriverValveBLTLDisconnect.DriverValveTLDisconnectToggle": "Train line disconnect valve",
  "Entities.gmod_subway_em508t.Buttons.AirDistributor.AirDistributorDisconnectToggle": "Disable air distributor",


  "Entities.gmod_subway_ezh3.Buttons.Main.Custom1Toggle": "Unused switch",
  "Entities.gmod_subway_ezh3.Buttons.IGLAButtons.IGLA1USet": "IGLA: First button up",
  "Entities.gmod_subway_ezh3.Buttons.IGLAButtons.IGLA1Set": "IGLA: First button",
  "Entities.gmod_subway_ezh3.Buttons.IGLAButtons.IGLA1DSet": "IGLA: First button down",
  "Entities.gmod_subway_ezh3.Buttons.IGLAButtons.IGLA2USet": "IGLA: Second button up",
  "Entities.gmod_subway_ezh3.Buttons.IGLAButtons.IGLA2Set": "IGLA: Second button",
  "Entities.gmod_subway_ezh3.Buttons.IGLAButtons.IGLA2DSet": "IGLA: Second button down",
  "Entities.gmod_subway_ezh3.Buttons.IGLAButtons.!IGLASR": "IGLA: SR",
  "Entities.gmod_subway_ezh3.Buttons.IGLAButtons.!IGLARX": "IGLA: RX",
  "Entities.gmod_subway_ezh3.Buttons.IGLAButtons.!IGLAErr": "IGLA: Malfunction",
  "Entities.gmod_subway_ezh3.Buttons.IGLAButtons.!IGLAOSP": "IGLA: OSP(Fire extinguisher)",
  "Entities.gmod_subway_ezh3.Buttons.IGLAButtons.!IGLAPI": "IGLA: PI(Fire indication)",
  "Entities.gmod_subway_ezh3.Buttons.IGLAButtons.!IGLAOff": "IGLA: Off",

  "Entities.gmod_subway_ezh3.Buttons.Back2.!HVHuse": "HV fuses block",
  "Entities.gmod_subway_ezh3.Buttons.Back2.!AKBCharge": "The box with the devices for battery recharging and door pressure diffuser",
  "Entities.gmod_subway_ezh3.Buttons.Back2.!Heater": "The heater"
}
]]
