return [[
{
  "Lang": "en",
  "Name": "English",

  "Entities.gmod_subway_81-720.Buttons.VityazButtons.VityazF1Set": "Vityaz: F1",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.VityazF2Set": "Vityaz: Next screen",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.VityazF3Set": "Vityaz: Previous screen",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.VityazF4Set": "Vityaz: Main",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.Vityaz1Set": "Vityaz: 1",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.Vityaz4Set": "Vityaz: 4",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.Vityaz7Set": "Vityaz: 7",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.Vityaz2Set": "Vityaz: 2",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.Vityaz5Set": "Vityaz: 5",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.Vityaz8Set": "Vityaz: 8",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.Vityaz0Set": "Vityaz: 0",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.Vityaz3Set": "Vityaz: 3",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.Vityaz6Set": "Vityaz: 6",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.Vityaz9Set": "Vityaz: 9",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.VityazF5Set": "Vityaz: Erase",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.VityazF6Set": "Vityaz: Up\\Speed",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.VityazF7Set": "Vityaz: Down\\Currents",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.VityazF8Set": "Vityaz: Input\\Wagon equipment",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.VityazF9Set": "Vityaz: Select\\Wagon equipment controlling",
  "Entities.gmod_subway_81-720.Buttons.RV.EmerX1Set": "Emergency X-1",
  "Entities.gmod_subway_81-720.Buttons.RV.EmerX2Set": "Emergency X-2",
  "Entities.gmod_subway_81-720.Buttons.RV.EmerCloseDoorsSet": "Emergency door close",
  "Entities.gmod_subway_81-720.Buttons.RV.EmergencyDoorsToggle": "Emergency doors",
  "Entities.gmod_subway_81-720.Buttons.BackVent.VentCondMode-": "Fan operation mode: +",
  "Entities.gmod_subway_81-720.Buttons.BackVent.VentCondMode+": "Fan operation mode: -",
  "Entities.gmod_subway_81-720.Buttons.BackVent.VentHeatMode+": "+",
  "Entities.gmod_subway_81-720.Buttons.BackVent.VentHeatMode-": "-",
  "Entities.gmod_subway_81-720.Buttons.BackVent.VentStrengthMode-": "Fan strength: +",
  "Entities.gmod_subway_81-720.Buttons.BackVent.VentStrengthMode+": "Fan strength: -",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV1Toggle": "SF1: Control circuits power",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV2Toggle": "SF2: BUV Power (wagon controlling unit)",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV3Toggle": "SF3: BUTP Power (engines controlling unit)",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV4Toggle": "SF4: BUTP Controlling",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV5Toggle": "SF5: BUTP Emergency control",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV6Toggle": "SF6: BUTP Power",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV7Toggle": "SF7: BBE (onboard power supply unit)",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV8Toggle": "SF8: BV controlling",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV9Toggle": "SF9: BV power (overload relay)",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV10Toggle": "SF10: PPO",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV11Toggle": "SF11: Motor-compressor",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV12Toggle": "SF12: Doors closing",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV13Toggle": "SF13: Doors open left",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV14Toggle": "SF14: Doors open right",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV15Toggle": "SF15: Front doors",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV16Toggle": "SF16: Announcer",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV17Toggle": "SF17: Emergency intercom",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV18Toggle": "SF18: (placeholder)",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV19Toggle": "SF19: Passenger lighting power",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV20Toggle": "SF20: Emergency passenger lighting",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV21Toggle": "SF21: Speed sensor",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV22Toggle": "SF22: Parking brake",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV23Toggle": "SF23: 1st fan group controlling",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV24Toggle": "SF24: 2nd fan group controlling",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV25Toggle": "SF25: 1st fan group power",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV26Toggle": "SF26: 2nd fan group power",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV27Toggle": "SF27: Exciter power",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV28Toggle": "SF28: ZKK power",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV29Toggle": "SF29: Current collectors",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV30Toggle": "SF30: Line schemes & ticker",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV31Toggle": "SF31: (placeholder)",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV32Toggle": "SF32: (placeholder)",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV33Toggle": "SF33: (placeholder)",
  "Entities.gmod_subway_81-720.Buttons.ASNP.R_ASNPMenuSet": "ASNP: Menu",
  "Entities.gmod_subway_81-720.Buttons.ASNP.R_ASNPUpSet": "ASNP: Up",
  "Entities.gmod_subway_81-720.Buttons.ASNP.R_ASNPDownSet": "ASNP: Down",
  "Entities.gmod_subway_81-720.Buttons.ASNP.R_ASNPOnToggle": "ASNP: Turn on",
  "Entities.gmod_subway_81-720.Buttons.PneumoHelper1.!BrakeCylinder": "Brake cylinder",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF1Toggle": "SF1: Main power",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF2Toggle": "SF2: Main control",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF3Toggle": "SF3: Emergency control",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF4Toggle": "SF4: BARS (ARS unit)",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF5Toggle": "SF5: BUP (train controlling unit)",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF6Toggle": "SF6: BKCU (control circuits commutation unit)",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF7Toggle": "SF7: BARS (ARS unit)",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF8Toggle": "SF8: Announcer",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF9Toggle": "SF9: Radiostation",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF10Toggle": "SF10: Wagon orientation",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF11Toggle": "SF11: Movement direction",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF12Toggle": "SF12: 1st headlights group",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF13Toggle": "SF13: 2nd headlights group",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF14Toggle": "SF14: Red lights",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF15Toggle": "SF15: Cabin lighting",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF16Toggle": "SF16: Heater",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF17Toggle": "SF17: Cabin air conditioner",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF18Toggle": "SF18: Flange lubrication",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF19Toggle": "SF19: Main KRM power (brake lever)",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF20Toggle": "SF20: Emergency KRM power (brake lever)",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF21Toggle": "SF21: Doors opening",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF22Toggle": "SF22: Doors closing",
  "Entities.gmod_subway_81-720.Buttons.BTO.K29Toggle": "KRMSH (brake lever disconnect valve)",
  "Entities.gmod_subway_81-720.Buttons.PassengerDoor2.PassengerDoor": "Passenger door",
  "Entities.gmod_subway_81-720.Buttons.VoltHelper2.!HV": "Total voltmeter (kV)",
  "Entities.gmod_subway_81-720.Buttons.VoltHelper2.!I1_3": "1st engine group current (A)",
  "Entities.gmod_subway_81-720.Buttons.VoltHelper2.!I2_4": "2nd engine group current (A)",
  "Entities.gmod_subway_81-720.Buttons.GV.GVToggle": "HV switch",
  "Entities.gmod_subway_81-720.Buttons.RearPneumatic.RearBrakeLineIsolationToggle": "Brake line isolation valve",
  "Entities.gmod_subway_81-720.Buttons.RearPneumatic.RearTrainLineIsolationToggle": "Train line isolation valve",
  "Entities.gmod_subway_81-720.Buttons.RearDoor1.RearDoor": "Rear door",
  "Entities.gmod_subway_81-720.Buttons.RearDoor.RearDoor": "Rear door",
  "Entities.gmod_subway_81-720.Buttons.BackDown.Pant1Toggle": "Disable 1st current collectors group",
  "Entities.gmod_subway_81-720.Buttons.BackDown.Pant2Toggle": "Disable 2nd current collectors group",
  "Entities.gmod_subway_81-720.Buttons.BackDown.Vent1Toggle": "1st ventilation group",
  "Entities.gmod_subway_81-720.Buttons.BackDown.Vent2Toggle": "2nd ventilation group",
  "Entities.gmod_subway_81-720.Buttons.BackDown.VentToggle": "",
  "Entities.gmod_subway_81-720.Buttons.BackDown.PassLightToggle": "Passenger lighting",
  "Entities.gmod_subway_81-720.Buttons.BackDown.CabLightToggle": "Cabin lighting",
  "Entities.gmod_subway_81-720.Buttons.BackDown.Headlights1Toggle": "1st headlights group",
  "Entities.gmod_subway_81-720.Buttons.BackDown.Headlights2Toggle": "2nd headlights group",
  "Entities.gmod_subway_81-720.Buttons.BackDown.ParkingBrakeToggle": "Parking brake",
  "Entities.gmod_subway_81-720.Buttons.BackDown.TorecDoorsToggle": "Front doors",
  "Entities.gmod_subway_81-720.Buttons.BackDown.BBERToggle": "Turning on emergency BBE",
  "Entities.gmod_subway_81-720.Buttons.BackDown.BBEToggle": "BBE (onboard power supply unit)",
  "Entities.gmod_subway_81-720.Buttons.BackDown.CompressorToggle": "Motor-compressor",
  "Entities.gmod_subway_81-720.Buttons.BackDown.CabLightStrengthToggle": "Cabin lighting power",
  "Entities.gmod_subway_81-720.Buttons.BackDown.AppLights1Toggle": "Wagon equipment lighting",
  "Entities.gmod_subway_81-720.Buttons.BackDown.AppLights2Toggle": "",
  "Entities.gmod_subway_81-720.Buttons.BackDown.BARSBlock-": "Broken BARS (ARS unit) blocking: -",
  "Entities.gmod_subway_81-720.Buttons.BackDown.BARSBlock+": "Broken BARS (ARS unit) blocking: +",
  "Entities.gmod_subway_81-720.Buttons.BackDown.BatteryToggle": "Battery on/off",
  "Entities.gmod_subway_81-720.Buttons.BackDown.ALSFreqToggle": "ALS decoder",
  "Entities.gmod_subway_81-720.Buttons.VoltHelper1.!Battery": "Control circuits voltage",
  "Entities.gmod_subway_81-720.Buttons.PassengerDoor.PassengerDoor": "Passenger door",
  "Entities.gmod_subway_81-720.Buttons.CabinDoorR.CabinDoorRight": "Cabin door",
  "Entities.gmod_subway_81-720.Buttons.CabinDoorL.CabinDoorLeft": "Cabin door",
  "Entities.gmod_subway_81-720.Buttons.FrontPneumatic.FrontBrakeLineIsolationToggle": "Brake line isolation valve",
  "Entities.gmod_subway_81-720.Buttons.FrontPneumatic.FrontTrainLineIsolationToggle": "Train line isolation valve",
  "Entities.gmod_subway_81-720.Buttons.PUL.DoorSelectLToggle": "Select left doors",
  "Entities.gmod_subway_81-720.Buttons.PUL.DoorSelectRToggle": "Select right doors",
  "Entities.gmod_subway_81-720.Buttons.PUL.DoorBlockToggle": "Doors locking: Emergency door close override",
  "Entities.gmod_subway_81-720.Buttons.PUL.!DoorLeftLamp": "Left doors button work",
  "Entities.gmod_subway_81-720.Buttons.PUL.DoorLeftSet": "Left doors",
  "Entities.gmod_subway_81-720.Buttons.PUU.!DoorsClosed": "Doors are closed",
  "Entities.gmod_subway_81-720.Buttons.PUU.StandToggle": "Stay",
  "Entities.gmod_subway_81-720.Buttons.PUU.TickerToggle": "Ticker",
  "Entities.gmod_subway_81-720.Buttons.PUU.KAHToggle": "KAH",
  "Entities.gmod_subway_81-720.Buttons.PUU.ALSToggle": "ALS",
  "Entities.gmod_subway_81-720.Buttons.PUU.FDepotToggle": "Depature from depot",
  "Entities.gmod_subway_81-720.Buttons.PUU.!HVoltage": "No high voltage",
  "Entities.gmod_subway_81-720.Buttons.PUU.PassSchemeToggle": "Line schemes",
  "Entities.gmod_subway_81-720.Buttons.PUU.EmergencyCompressorSet": "Emergency compressor",
  "Entities.gmod_subway_81-720.Buttons.PUU.EnableBVSet": "Turn on protection (overload relay)",
  "Entities.gmod_subway_81-720.Buttons.PUU.DisableBVSet": "Disable BV (overload relay)",
  "Entities.gmod_subway_81-720.Buttons.PUU.RingSet": "Ring",
  "Entities.gmod_subway_81-720.Buttons.PUU.R_Program2Set": "Program 2",
  "Entities.gmod_subway_81-720.Buttons.PUU.R_AnnouncerToggle": "Announcer",
  "Entities.gmod_subway_81-720.Buttons.PUU.R_LineToggle": "Line",
  "Entities.gmod_subway_81-720.Buttons.PUU.R_EmerSet": "Emergency intercom",
  "Entities.gmod_subway_81-720.Buttons.PUU.R_Program1Set": "Program 1",
  "Entities.gmod_subway_81-720.Buttons.PUU.EnableBVEmerSet": "Emergency BV recovery",
  "Entities.gmod_subway_81-720.Buttons.PUU.EmergencyControlsToggle": "Emergency control",
  "Entities.gmod_subway_81-720.Buttons.PUU.WiperToggle": "Wiper",
  "Entities.gmod_subway_81-720.Buttons.PUU.!VDop": "Allowed speed",
  "Entities.gmod_subway_81-720.Buttons.PUU.!VFact": "Actual speed",
  "Entities.gmod_subway_81-720.Buttons.PUU.!VPred": "Preventive speed",
  "Entities.gmod_subway_81-720.Buttons.PUU.!VDop2": "Allowed speed",
  "Entities.gmod_subway_81-720.Buttons.PUU.!Acc": "Acceleration",
  "Entities.gmod_subway_81-720.Buttons.PUU.!Forw": "Moving forward",
  "Entities.gmod_subway_81-720.Buttons.PUU.!Back": "Moving backward",
  "Entities.gmod_subway_81-720.Buttons.PUR.EmerBrakeAddSet": "(auxiliary) Brake",
  "Entities.gmod_subway_81-720.Buttons.PUR.EmerBrakeReleaseSet": "(auxiliary) Release",
  "Entities.gmod_subway_81-720.Buttons.PUR.EmerBrakeToggle": "Auxiliary brake",
  "Entities.gmod_subway_81-720.Buttons.PUR.EmergencyBrakeToggle": "Emergency brake",
  "Entities.gmod_subway_81-720.Buttons.PUR.DoorCloseToggle": "Close doors",
  "Entities.gmod_subway_81-720.Buttons.PUR.AttentionMessageSet": "Message perception",
  "Entities.gmod_subway_81-720.Buttons.PUR.AttentionSet": "Attention",
  "Entities.gmod_subway_81-720.Buttons.PUR.AttentionBrakeSet": "Braking perception",
  "Entities.gmod_subway_81-720.Buttons.PUR.HornBSet": "Horn",
  "Entities.gmod_subway_81-720.Buttons.PUR.DoorRightSet": "Right doors",
  "Entities.gmod_subway_81-720.Buttons.PUR.!DoorRightLamp": "Right doors button work",
  "Entities.gmod_subway_81-720.Buttons.PneumoHelper2.!BrakeTrainLine": "Red - brake line, black - train line",

  "Entities.gmod_subway_81-721.Buttons.GV.GVToggle": "HV switch",
  "Entities.gmod_subway_81-721.Buttons.RearPneumatic.RearBrakeLineIsolationToggle": "Brake line isolation valve",
  "Entities.gmod_subway_81-721.Buttons.RearPneumatic.RearTrainLineIsolationToggle": "Train line isolation valve",
  "Entities.gmod_subway_81-721.Buttons.FrontDoor.FrontDoor": "Front door",
  "Entities.gmod_subway_81-721.Buttons.RearDoor.RearDoor": "Rear door",
  "Entities.gmod_subway_81-721.Buttons.Battery.BatteryToggle": "Battery on/off",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV1Toggle": "SF1: Control circuits power",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV2Toggle": "SF2: BUV Power (wagon controlling unit)",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV3Toggle": "SF3: BUTP Power (engines controlling unit)",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV4Toggle": "SF4: BUTP Controlling",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV5Toggle": "SF5: BUTP Emergency control",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV6Toggle": "SF6: BUTP Power",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV7Toggle": "SF7: BBE (onboard power supply unit)",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV8Toggle": "SF8: BV controlling",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV9Toggle": "SF9: BV power (overload relay)",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV10Toggle": "SF10: PPO",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV11Toggle": "SF11: Motor-compressor",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV12Toggle": "SF12: Doors closing",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV13Toggle": "SF13: Doors open left",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV14Toggle": "SF14: Doors open right",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV15Toggle": "SF15: Front doors",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV16Toggle": "SF16: Announcer",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV17Toggle": "SF17: Emergency intercom",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV18Toggle": "SF18: (placeholder)",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV19Toggle": "SF19: Passenger lighting power",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV20Toggle": "SF20: Emergency passenger lighting",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV21Toggle": "SF21: Speed sensor",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV22Toggle": "SF22: Parking brake",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV23Toggle": "SF23: 1st fan group controlling",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV24Toggle": "SF24: 2nd fan group controlling",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV25Toggle": "SF25: 1st fan group power",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV26Toggle": "SF26: 2nd fan group power",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV27Toggle": "SF27: Exciter power",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV28Toggle": "SF28: ZKK power",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV29Toggle": "SF29: Current collectors",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV30Toggle": "SF30: Line schemes & ticker",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV31Toggle": "SF31: (placeholder)",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV32Toggle": "SF32: (placeholder)",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV33Toggle": "SF33: (placeholder)",
  "Entities.gmod_subway_81-721.Buttons.FrontPneumatic.FrontBrakeLineIsolationToggle": "Brake line isolation valve",
  "Entities.gmod_subway_81-721.Buttons.FrontPneumatic.FrontTrainLineIsolationToggle": "Train line isolation valve",

  "Entities.gmod_subway_81-720.Buttons.IGLAButtons.IGLA1USet": "IGLA: First button UP",
  "Entities.gmod_subway_81-720.Buttons.IGLAButtons.IGLA1Set": "IGLA: First button",
  "Entities.gmod_subway_81-720.Buttons.IGLAButtons.IGLA1DSet": "IGLA: First button DOWN",
  "Entities.gmod_subway_81-720.Buttons.IGLAButtons.IGLA2USet": "IGLA: Second button UP",
  "Entities.gmod_subway_81-720.Buttons.IGLAButtons.IGLA2Set": "IGLA: Second button",
  "Entities.gmod_subway_81-720.Buttons.IGLAButtons.IGLA2DSet": "IGLA: Second button DOWN",
  "Entities.gmod_subway_81-720.Buttons.IGLAButtons.!IGLASR": "IGLA: SR",
  "Entities.gmod_subway_81-720.Buttons.IGLAButtons.!IGLARX": "IGLA: RX",
  "Entities.gmod_subway_81-720.Buttons.IGLAButtons.!IGLAErr": "IGLA: Malfunction",
  "Entities.gmod_subway_81-720.Buttons.IGLAButtons.!IGLAOSP": "IGLA: OSP(Fire extinguisher)",
  "Entities.gmod_subway_81-720.Buttons.IGLAButtons.!IGLAPI": "IGLA: PI(Fire indication)",
  "Entities.gmod_subway_81-720.Buttons.IGLAButtons.!IGLAOff": "IGLA: Off",
  "Entities.gmod_subway_81-720.Buttons.PUU.KAHkToggle": "KAH button cover",
  "Entities.gmod_subway_81-720.Buttons.PUU.ALSkToggle": "ALS button cover",
  "Entities.gmod_subway_81-720.Buttons.PUR.AccelRateSet": "Acceleration rate(Slope mode)",

  "Entities.gmod_subway_81-720.Buttons.BTO.UAVAToggle": "UAVA: Universal Automatic Autostop Disabler (disable autostop)"
}
]]
