return [[
{
    "Lang": "en",
    "Name": "English",


    "Entities.gmod_subway_81-703.Buttons.HelperPanel.R_Program1Set": "Program 1",
    "Entities.gmod_subway_81-703.Buttons.HelperPanel.R_Program2Set": "Program 2",
    "Entities.gmod_subway_81-703.Buttons.HelperPanel.VDLSet": "VDL: Open left doors",
    "Entities.gmod_subway_81-703.Buttons.HelperPanel.VUD2Toggle": "VUD2: Door control toggle (close doors)",
    "Entities.gmod_subway_81-703.Buttons.Meters.!TotalVoltmeter": "HV voltmeter (kV)",
    "Entities.gmod_subway_81-703.Buttons.Meters.!TotalAmpermeter": "Total ampermeter (A)",
    "Entities.gmod_subway_81-703.Buttons.AV2.RSTToggle": "RST: Radiostation",
    "Entities.gmod_subway_81-703.Buttons.RearPneumatic.RearTrainLineIsolationToggle": "Train line isolation valve",
    "Entities.gmod_subway_81-703.Buttons.RearPneumatic.RearBrakeLineIsolationToggle": "Brake line isolation valve",
    "Entities.gmod_subway_81-703.Buttons.Back2.!HVFuses": "HV fuses block",
    "Entities.gmod_subway_81-703.Buttons.Back2.!DVR": "The box with the door pressure diffuser",
    "Entities.gmod_subway_81-703.Buttons.Main.RK": "Lamp: Rheostat controller is spinning",
    "Entities.gmod_subway_81-703.Buttons.Main.GreenRP": "Lamp: Green overload relay light (overload relay open on current train)",
    "Entities.gmod_subway_81-703.Buttons.Main.RedRP": "Lamp: Red overload relay light (power circuits failed to assemble)",
    "Entities.gmod_subway_81-703.Buttons.Main.Blue": "Lamp: Door state light (doors are closed)",
    "Entities.gmod_subway_81-703.Buttons.Main.DIPonSet": "Swithcer: Turn interior lights on",
    "Entities.gmod_subway_81-703.Buttons.Main.DIPoffSet": "Swithcer: Turn interior lights off (ring)",
    "Entities.gmod_subway_81-703.Buttons.Main.VozvratRPSet": "KU: Reset overload relay",
    "Entities.gmod_subway_81-703.Buttons.Main.KSNSet": "KSN: Forced activation of the RP on the faulty wagon (Malfunction signaling)",
    "Entities.gmod_subway_81-703.Buttons.Main.KRZDSet": "KRZD: Emergency door closing",
    "Entities.gmod_subway_81-703.Buttons.Main.KSDSet": "KSD: Door state control(Door check)",
    "Entities.gmod_subway_81-703.Buttons.Main.KDPSet": "KDP: Open right doors",
    "Entities.gmod_subway_81-703.Buttons.Main.KDLSet": "KDL: Open left doors",
    "Entities.gmod_subway_81-703.Buttons.Main.KU1Toggle": "MK: Turn motor-compressor on",
    "Entities.gmod_subway_81-703.Buttons.Main.VUD1Toggle": "VUD: Door control toggle (close doors)",
    "Entities.gmod_subway_81-703.Buttons.Main.KRPSet": "KRP: Emergency start",
    "Entities.gmod_subway_81-703.Buttons.AV1.VU3Toggle": "VU3: Cabin lighting",
    "Entities.gmod_subway_81-703.Buttons.AV1.VU2Toggle": "VU2: Emergency lighting (45V)",
    "Entities.gmod_subway_81-703.Buttons.AV1.VU1Toggle": "VU1: Cabin heater (3kWt)",
    "Entities.gmod_subway_81-703.Buttons.AVMain.AV8BToggle": "Circuit braker (High voltage auxiliary circuits)",
    "Entities.gmod_subway_81-703.Buttons.Lamp.L_3Toggle": "Lamp: Gauges lighting",
    "Entities.gmod_subway_81-703.Buttons.DriverValveTLDisconnect.DriverValveTLDisconnectToggle": "Train line disconnect valve",
    "Entities.gmod_subway_81-703.Buttons.VU.VUToggle": "VU: Enable train-control",
    "Entities.gmod_subway_81-703.Buttons.FrontDoor.FrontDoor": "Front door",
    "Entities.gmod_subway_81-703.Buttons.PneumaticManometer.!LinesPressure": "Pressure in pneumatic lines (red: brake line, black: train line)",
    "Entities.gmod_subway_81-703.Buttons.Stopkran.EmergencyBrakeValveToggle": "Emergency brake",
    "Entities.gmod_subway_81-703.Buttons.UAVAPanel.UAVAToggle": "UAVA: Universal Automatic Autostop Disabler (disable autostop)",
    "Entities.gmod_subway_81-703.Buttons.UAVAPanel.UAVACToggle   ": "UAVA: Universal Automatic Autostop Disabler(reset contacts)",
    "Entities.gmod_subway_81-703.Buttons.PneumaticPanels.!CylinderPressure": "Brake manometer: Brake cylinder pressure",
    "Entities.gmod_subway_81-703.Buttons.Battery.VBToggle": "VB: Battery on/off (Low voltage circuits)",
    "Entities.gmod_subway_81-703.Buttons.Battery.R_RadioToggle": "Announcer (+50V)",
    "Entities.gmod_subway_81-703.Buttons.FrontPneumatic.FrontBrakeLineIsolationToggle": "Brake line isolation valve",
    "Entities.gmod_subway_81-703.Buttons.FrontPneumatic.FrontTrainLineIsolationToggle": "Train line isolation valve",
    "Entities.gmod_subway_81-703.Buttons.ASNP.R_ASNPMenuSet": "Announcer: Menu",
    "Entities.gmod_subway_81-703.Buttons.ASNP.R_ASNPUpSet": "Announcer: Up",
    "Entities.gmod_subway_81-703.Buttons.ASNP.R_ASNPDownSet": "Announcer: Down",
    "Entities.gmod_subway_81-703.Buttons.ASNP.R_ASNPOnToggle": "Announcer: Turn on",
    "Entities.gmod_subway_81-703.Buttons.GV.GVToggle": "GV: HV switch",
    "Entities.gmod_subway_81-703.Buttons.PassengerDoor.PassengerDoor": "Passenger door",
    "Entities.gmod_subway_81-703.Buttons.KRR.KRRToggle": "KRR: Button of enabling reversers",
    "Entities.gmod_subway_81-703.Buttons.VU4.VUSToggle": "Switcher: Near Headlights/Far Headlights",
    "Entities.gmod_subway_81-703.Buttons.CabinDoor.CabinDoor1": "Cabin door",
    "Entities.gmod_subway_81-703.Buttons.Tsepi.!BatteryVoltage": "Control circuits voltage",
    "Entities.gmod_subway_81-703.Buttons.IGLAButtons.IGLA1USet": "IGLA: First button up",
    "Entities.gmod_subway_81-703.Buttons.IGLAButtons.IGLA1Set": "IGLA: First button",
    "Entities.gmod_subway_81-703.Buttons.IGLAButtons.IGLA1DSet": "IGLA: First button down",
    "Entities.gmod_subway_81-703.Buttons.IGLAButtons.IGLA2USet": "IGLA: Second button up",
    "Entities.gmod_subway_81-703.Buttons.IGLAButtons.IGLA2Set": "IGLA: Second button",
    "Entities.gmod_subway_81-703.Buttons.IGLAButtons.IGLA2DSet": "IGLA: Second button down",
    "Entities.gmod_subway_81-703.Buttons.IGLAButtons.!IGLASR": "IGLA: SR",
    "Entities.gmod_subway_81-703.Buttons.IGLAButtons.!IGLARX": "IGLA: RX",
    "Entities.gmod_subway_81-703.Buttons.IGLAButtons.!IGLAErr": "IGLA: Malfunction",
    "Entities.gmod_subway_81-703.Buttons.IGLAButtons.!IGLAOSP": "IGLA: OSP(Fire extinguisher)",
    "Entities.gmod_subway_81-703.Buttons.IGLAButtons.!IGLAPI": "IGLA: PI(Fire indication)",
    "Entities.gmod_subway_81-703.Buttons.IGLAButtons.!IGLAOff": "IGLA: Off",
    "Entities.gmod_subway_81-703.Buttons.Back1.R_UNchToggle": "UNCh: Low frequency amplifier (passenger announcer sound)",
    "Entities.gmod_subway_81-703.Buttons.Back1.IGLAToggle": "ASOTP: IGLA",
    "Entities.gmod_subway_81-703.Buttons.Back1.RezMKSet": "Emergency motor-compressor startup",
    "Entities.gmod_subway_81-703.Buttons.ParkingBrake.ParkingBrakeLeft": "Parking brake wheel",
    "Entities.gmod_subway_81-703.Buttons.ParkingBrake.ParkingBrakeRight": "Parking brake wheel",
    "Entities.gmod_subway_81-703.Buttons.DriverValveBLDisconnect.DriverValveBLDisconnectToggle": "Brake line disconnect valve",
    "Entities.gmod_subway_81-703.Buttons.Speedometer.!Speedometer": "Speedometer",
    "Entities.gmod_subway_81-703.Buttons.AirDistributor.AirDistributorDisconnectToggle": "Disable air distributor",



    "Entities.gmod_subway_81-703_2.Buttons.Stopkran.EmergencyBrakeValveToggle": "Emergency brake",
    "Entities.gmod_subway_81-703_2.Buttons.HelperPanel.R_Program1Set": "Program 1",
    "Entities.gmod_subway_81-703_2.Buttons.HelperPanel.R_Program2Set": "Program 2",
    "Entities.gmod_subway_81-703_2.Buttons.HelperPanel.VDLSet": "VDL: Open left doors",
    "Entities.gmod_subway_81-703_2.Buttons.HelperPanel.VUD2LToggle": "VUD2 lock",
    "Entities.gmod_subway_81-703_2.Buttons.HelperPanel.VUD2Toggle": "VUD2: Door control toggle (close doors)",
    "Entities.gmod_subway_81-703_2.Buttons.PneumaticPanels.!CylinderPressure": "Brake manometer: Brake cylinder pressure",
    "Entities.gmod_subway_81-703_2.Buttons.Battery.VBToggle": "VB: Battery on/off (Low voltage circuits)",
    "Entities.gmod_subway_81-703_2.Buttons.Battery.R_RadioToggle": "Announcer (+50V)",
    "Entities.gmod_subway_81-703_2.Buttons.Meters.!TotalVoltmeter": "HV voltmeter (kV)",
    "Entities.gmod_subway_81-703_2.Buttons.Meters.!TotalAmpermeter": "Total ampermeter (A)",
    "Entities.gmod_subway_81-703_2.Buttons.AV2.RSTToggle": "RST: Radiostation",
    "Entities.gmod_subway_81-703_2.Buttons.PassengerDoor.PassengerDoor": "Passenger door",
    "Entities.gmod_subway_81-703_2.Buttons.VU4.VUSToggle": "Switcher: Near Headlights/Far Headlights",
    "Entities.gmod_subway_81-703_2.Buttons.AV1.VU3Toggle": "VU3: Cabin lighting",
    "Entities.gmod_subway_81-703_2.Buttons.AV1.VU2Toggle": "VU2: Emergency lighting (45V)",
    "Entities.gmod_subway_81-703_2.Buttons.AV1.VU1Toggle": "VU1: Cabin heater (3kWt)",
    "Entities.gmod_subway_81-703_2.Buttons.UAVAPanel.UAVAToggle": "UAVA: Universal Automatic Autostop Disabler (disable autostop)",
    "Entities.gmod_subway_81-703_2.Buttons.UAVAPanel.UAVACToggle   ": "UAVA: Universal Automatic Autostop Disabler(reset contacts)",
    "Entities.gmod_subway_81-703_2.Buttons.AirDistributor.AirDistributorDisconnectToggle": "Disable air distributor",
    "Entities.gmod_subway_81-703_2.Buttons.GV.GVToggle": "GV: HV switch",
    "Entities.gmod_subway_81-703_2.Buttons.FrontPneumatic.FrontBrakeLineIsolationToggle": "Brake line isolation valve",
    "Entities.gmod_subway_81-703_2.Buttons.FrontPneumatic.FrontTrainLineIsolationToggle": "Train line isolation valve",
    "Entities.gmod_subway_81-703_2.Buttons.Tsepi.!BatteryVoltage": "Battery voltage",
    "Entities.gmod_subway_81-703_2.Buttons.RearPneumatic.RearTrainLineIsolationToggle": "Train line isolation valve",
    "Entities.gmod_subway_81-703_2.Buttons.RearPneumatic.RearBrakeLineIsolationToggle": "Brake line isolation valve",
    "Entities.gmod_subway_81-703_2.Buttons.ParkingBrake.ParkingBrakeLeft": "Parking brake wheel",
    "Entities.gmod_subway_81-703_2.Buttons.ParkingBrake.ParkingBrakeRight": "Parking brake wheel",
    "Entities.gmod_subway_81-703_2.Buttons.Back2.!HVFuses": "HV fuses block",
    "Entities.gmod_subway_81-703_2.Buttons.Back2.!DVR": "The box with the door pressure diffuser",
    "Entities.gmod_subway_81-703_2.Buttons.Main.RK": "Lamp: Rheostat controller is spinning",
    "Entities.gmod_subway_81-703_2.Buttons.Main.GreenRP": "Lamp: Green overload relay light (overload relay open on current train)",
    "Entities.gmod_subway_81-703_2.Buttons.Main.RedRP": "Lamp: Red overload relay light (power circuits failed to assemble)",
    "Entities.gmod_subway_81-703_2.Buttons.Main.Blue": "Lamp: Door state light (doors are closed)",
    "Entities.gmod_subway_81-703_2.Buttons.Main.DIPonSet": "Swithcer: Turn interior lights on",
    "Entities.gmod_subway_81-703_2.Buttons.Main.DIPoffSet": "Swithcer: Turn interior lights off",
    "Entities.gmod_subway_81-703_2.Buttons.Main.VozvratRPSet": "VRP: Reset overload relay",
    "Entities.gmod_subway_81-703_2.Buttons.Main.KSNSet": "KSN: Forced activation of the RP on the faulty wagon (Malfunction signaling)",
    "Entities.gmod_subway_81-703_2.Buttons.Main.KRZDSet": "KRZD: Emergency door closing",
    "Entities.gmod_subway_81-703_2.Buttons.Main.KSDSet": "KSD: Door state control(Door check)",
    "Entities.gmod_subway_81-703_2.Buttons.Main.KDPSet": "KDP: Open right doors",
    "Entities.gmod_subway_81-703_2.Buttons.Main.KDLSet": "KDL: Open left",
    "Entities.gmod_subway_81-703_2.Buttons.Main.KU1Toggle": "MK: Turn motor-compressor on",
    "Entities.gmod_subway_81-703_2.Buttons.Main.VUD1Toggle": "VUD: Door control toggle (close doors)",
    "Entities.gmod_subway_81-703_2.Buttons.Main.KRPSet": "KRP: Emergency start",
    "Entities.gmod_subway_81-703_2.Buttons.KRR.KRRToggle": "KRR: Button of enabling reversers",
    "Entities.gmod_subway_81-703_2.Buttons.Back1.R_ZSToggle": "ZS: Switch loudspeaker amplification, the sound in the train",
    "Entities.gmod_subway_81-703_2.Buttons.Back1.IGLAToggle": "ASOTP: IGLA",
    "Entities.gmod_subway_81-703_2.Buttons.Back1.RezMKSet": "Emergency motor-compressor startup",
    "Entities.gmod_subway_81-703_2.Buttons.CabinDoor.CabinDoor1": "Cabin door",
    "Entities.gmod_subway_81-703_2.Buttons.Lamp.L_3Toggle": "Lamp: Gauges lighting",
    "Entities.gmod_subway_81-703_2.Buttons.DriverValveBLDisconnect.DriverValveBLDisconnectToggle": "Brake line disconnect valve",
    "Entities.gmod_subway_81-703_2.Buttons.DriverValveTLDisconnect.DriverValveTLDisconnectToggle": "Train line disconnect valve",
    "Entities.gmod_subway_81-703_2.Buttons.AVMain.AV8BToggle": "AV-8B: Circuit breaker (High voltage auxiliary circuits)",
    "Entities.gmod_subway_81-703_2.Buttons.VU.VUToggle": "VU: Enable train-control",
    "Entities.gmod_subway_81-703_2.Buttons.FrontDoor.FrontDoor": "Front door",
    "Entities.gmod_subway_81-703_2.Buttons.Speedometer.!Speedometer": "Speedometer",
"Entities.gmod_subway_81-703_2.Buttons.PneumaticManometer.!LinesPressure": "Pressure in pneumatic lines (red: brake line, black: train line)"
}
]]
