return [[
{
	"Lang": "en",
	"Name": "English",

	"Spawner.Title": "Train spawner",
	"Spawner.Trains1": "Trains",
	"Spawner.Trains2": "Max for you",
	"Spawner.WagNum": "Wagons",
	"Spawner.AutoCouple": "Automatically couple wagons",

	"Entities.gmod_subway_81-717_mvm.Spawner.Texture.Name": "Skin",
	"Entities.gmod_subway_81-717_mvm.Spawner.PassTexture.Name": "Interior texture",
	"Entities.gmod_subway_81-717_mvm.Spawner.CabTexture.Name": "Cabin texture",
	"Entities.gmod_subway_81-717_mvm.Spawner.Announcer.Name": "Announcer",
	"Entities.gmod_subway_81-717_mvm.Spawner.Lighter.Name": "Lighter",
	"Entities.gmod_subway_81-717_mvm.Spawner.ARSType.Name": "ARS panel type",
	"Entities.gmod_subway_81-717_mvm.Spawner.ARSType.1": "Standard(square lamps)",
	"Entities.gmod_subway_81-717_mvm.Spawner.ARSType.2": "Standard(round lamps)",
	"Entities.gmod_subway_81-717_mvm.Spawner.ARSType.3": "Kiev/SPB",
	"Entities.gmod_subway_81-717_mvm.Spawner.ARSType.4": "Old ARS",
	"Entities.gmod_subway_81-717_mvm.Spawner.Cran.Name": "Brake lever type",
	"Entities.gmod_subway_81-717_mvm.Spawner.Cran.1": "334",
	"Entities.gmod_subway_81-717_mvm.Spawner.Cran.2": "013",
	"Entities.gmod_subway_81-717_mvm.Spawner.MaskType.Name": "Mask type",
	"Entities.gmod_subway_81-717_mvm.Spawner.MaskType.1": "2-2",
	"Entities.gmod_subway_81-717_mvm.Spawner.MaskType.2": "2-2-2",
	"Entities.gmod_subway_81-717_mvm.Spawner.MaskType.3": "1-4-1 bumper 1",
	"Entities.gmod_subway_81-717_mvm.Spawner.MaskType.4": "1-4-1 bumper 2",
	"Entities.gmod_subway_81-717_mvm.Spawner.MaskType.5": "1-1",
	"Entities.gmod_subway_81-717_mvm.Spawner.MaskType.6": "Retro",
	"Entities.gmod_subway_81-717_mvm.Spawner.LED.Name": "LED",
	"Entities.gmod_subway_81-717_mvm.Spawner.BPSNType.Name": "BPSN type",
	"Entities.gmod_subway_81-717_mvm.Spawner.BPSNType.1": "Old sound high tone",
	"Entities.gmod_subway_81-717_mvm.Spawner.BPSNType.2": "Old sound medium tone",
	"Entities.gmod_subway_81-717_mvm.Spawner.BPSNType.3": "Standard(from SPB)",
	"Entities.gmod_subway_81-717_mvm.Spawner.BPSNType.4": "Standard(TKL)",
	"Entities.gmod_subway_81-717_mvm.Spawner.BPSNType.5": "Standard",
	"Entities.gmod_subway_81-717_mvm.Spawner.BPSNType.6": "Kiev",
	"Entities.gmod_subway_81-717_mvm.Spawner.BPSNType.7": "Old",
	"Entities.gmod_subway_81-717_mvm.Spawner.BPSNType.8": "Standard 2",
	"Entities.gmod_subway_81-717_mvm.Spawner.BPSNType.9": "Standard 3",
	"Entities.gmod_subway_81-717_mvm.Spawner.BPSNType.10": "No sound(BPN-115)",
	"Entities.gmod_subway_81-717_mvm.Spawner.NewKV.Name": "New contoller model",
	"Entities.gmod_subway_81-717_mvm.Spawner.HornType.Name": "SPB horn",
	"Entities.gmod_subway_81-717_mvm.Spawner.RingType.Name": "Ring sound",
	"Entities.gmod_subway_81-717_mvm.Spawner.RingType.1": "Old",
	"Entities.gmod_subway_81-717_mvm.Spawner.RingType.2": "Standard with low tone",
	"Entities.gmod_subway_81-717_mvm.Spawner.RingType.3": "Standard with high tone",
	"Entities.gmod_subway_81-717_mvm.Spawner.RingType.4": "Standard intermittent with low tone",
	"Entities.gmod_subway_81-717_mvm.Spawner.RingType.5": "Standard intermittent with high tone",
	"Entities.gmod_subway_81-717_mvm.Spawner.NM.Name": "Train line pressure",
	"Entities.gmod_subway_81-717_mvm.Spawner.Battery.Name": "Battery",
	"Entities.gmod_subway_81-717_mvm.Spawner.Switches.Name": "Circuit breakers on",
	"Entities.gmod_subway_81-717_mvm.Spawner.SwitchesR.Name": "Random circuit breakers",
	"Entities.gmod_subway_81-717_mvm.Spawner.DoorsL.Name": "Open left doors",
	"Entities.gmod_subway_81-717_mvm.Spawner.DoorsR.Name": "Open right doors",
	"Entities.gmod_subway_81-717_mvm.Spawner.GV.Name": "HV switch",
	"Entities.gmod_subway_81-717_mvm.Spawner.PB.Name": "Parking brake",
	"Entities.gmod_subway_81-717_mvm.Spawner.BortLampType.Name": "Board lamps type",
	"Entities.gmod_subway_81-717_mvm.Spawner.BortLampType.1": "Horizontal",
	"Entities.gmod_subway_81-717_mvm.Spawner.BortLampType.2": "Vertical",
	"Entities.gmod_subway_81-717_mvm.Spawner.MVM.Name": "MVM sign",
	"Entities.gmod_subway_81-717_mvm.Spawner.HandRail.Name": "Handrails type",
	"Entities.gmod_subway_81-717_mvm.Spawner.HandRail.1": "Old",
	"Entities.gmod_subway_81-717_mvm.Spawner.HandRail.2": "New",
	"Entities.gmod_subway_81-717_mvm.Spawner.SeatType.Name": "Seats type",
	"Entities.gmod_subway_81-717_mvm.Spawner.SeatType.1": "Old",
	"Entities.gmod_subway_81-717_mvm.Spawner.SeatType.2": "New",
	"Entities.gmod_subway_81-717_mvm.Spawner.LampType.Name": "Lamps type",
	"Entities.gmod_subway_81-717_mvm.Spawner.LampType.1": "Type 1",
	"Entities.gmod_subway_81-717_mvm.Spawner.LampType.2": "Type 2",
	"Entities.gmod_subway_81-717_mvm.Spawner.LampType.3": "Type 3",
	"Entities.gmod_subway_81-717_mvm.Spawner.Breakers.Name": "Right side circuit breakers",
	"Entities.gmod_subway_81-717_mvm.Spawner.Adverts.Name": "Adverts type",
	"Entities.gmod_subway_81-717_mvm.Spawner.Adverts.1": "Type 1",
	"Entities.gmod_subway_81-717_mvm.Spawner.Adverts.2": "Type 2",
	"Entities.gmod_subway_81-717_mvm.Spawner.Adverts.3": "Type 3",
	"Entities.gmod_subway_81-717_mvm.Spawner.Adverts.4": "No adverts",

	"Entities.gmod_subway_81-720.Spawner.Texture.Name": "Skin",
	"Entities.gmod_subway_81-720.Spawner.PassTexture.Name": "Interior texture",
	"Entities.gmod_subway_81-720.Spawner.CabTexture.Name": "Cabin texture",
	"Entities.gmod_subway_81-720.Spawner.Announcer.Name": "Announcer",
	"Entities.gmod_subway_81-720.Spawner.Scheme.Name": "Line scheme",
	"Entities.gmod_subway_81-720.Spawner.PassSchemesInvert.Name": "Invert scheme",
	"Entities.gmod_subway_81-720.Spawner.NM.Name": "Train line pressure",
	"Entities.gmod_subway_81-720.Spawner.Battery.Name": "Battery",
	"Entities.gmod_subway_81-720.Spawner.BRU.Name": "HV switch",
	"Entities.gmod_subway_81-720.Spawner.PVZR.Name": "Random train protection panel circuit breakers",
	"Entities.gmod_subway_81-720.Spawner.PPZ.Name": "Enable all train circuit breakers",
	"Entities.gmod_subway_81-720.Spawner.PPZDepot.Name": "Disable circuit breakers like in depot",
	"Entities.gmod_subway_81-720.Spawner.PPZR.Name": "Random wagon protection panel circuit breakers",
	"Entities.gmod_subway_81-720.Spawner.DoorsL.Name": "Open left doors",
	"Entities.gmod_subway_81-720.Spawner.DoorsR.Name": "Open right doors",

	"Entities.gmod_subway_81-722.Spawner.Texture.Name": "Skin",
	"Entities.gmod_subway_81-722.Spawner.PassTexture.Name": "Interior texture",
	"Entities.gmod_subway_81-722.Spawner.CabTexture.Name": "Cabin texture",
	"Entities.gmod_subway_81-722.Spawner.Announcer.Name": "Announcer",
	"Entities.gmod_subway_81-722.Spawner.Scheme.Name": "Line scheme",
	"Entities.gmod_subway_81-722.Spawner.SarmatInvert.Name": "Invert scheme",
	"Entities.gmod_subway_81-722.Spawner.NM.Name": "Train line pressure",
	"Entities.gmod_subway_81-722.Spawner.Battery.Name": "Battery",
	"Entities.gmod_subway_81-722.Spawner.Switches.Name": "Enable all train circuit breakers",
	"Entities.gmod_subway_81-722.Spawner.SwitchesR.Name": "Random circuit breakers",
	"Entities.gmod_subway_81-722.Spawner.DoorsL.Name": "Open left doors",
	"Entities.gmod_subway_81-722.Spawner.DoorsR.Name": "Open right doors",

	"Entities.gmod_subway_ezh.Spawner.Texture.Name": "Skin",
	"Entities.gmod_subway_ezh.Spawner.PassTexture.Name": "Interior texture",
	"Entities.gmod_subway_ezh.Spawner.CabTexture.Name": "Cabin texture",
	"Entities.gmod_subway_ezh.Spawner.Announcer.Name": "Announcer",
	"Entities.gmod_subway_ezh.Spawner.HornType.Name": "SPB horn",
	"Entities.gmod_subway_ezh.Spawner.NM.Name": "Train line pressure",
	"Entities.gmod_subway_ezh.Spawner.Battery.Name": "Turn on battery",
	"Entities.gmod_subway_ezh.Spawner.AV8B.Name": "Enable AV8B",
	"Entities.gmod_subway_ezh.Spawner.DoorsL.Name": "Open left doors",
	"Entities.gmod_subway_ezh.Spawner.DoorsR.Name": "Open right doors",
	"Entities.gmod_subway_ezh.Spawner.GV.Name": "Enable HV switch",

	"Entities.gmod_subway_em508.Spawner.Texture.Name": "Skin",
	"Entities.gmod_subway_em508.Spawner.PassTexture.Name": "Interior texture",
	"Entities.gmod_subway_em508.Spawner.CabTexture.Name": "Cabin texture",
	"Entities.gmod_subway_em508.Spawner.Announcer.Name": "Announcer",
	"Entities.gmod_subway_em508.Spawner.HornType.Name": "SPB horn",
	"Entities.gmod_subway_em508.Spawner.NM.Name": "Train line pressure",
	"Entities.gmod_subway_em508.Spawner.Battery.Name": "Turn on battery",
	"Entities.gmod_subway_em508.Spawner.AV8B.Name": "Enable AV8B",
	"Entities.gmod_subway_em508.Spawner.DoorsL.Name": "Open left doors",
	"Entities.gmod_subway_em508.Spawner.DoorsR.Name": "Open right doors",
	"Entities.gmod_subway_em508.Spawner.GV.Name": "Enable HV switch",

	"Entities.gmod_subway_ezh3.Spawner.Texture.Name": "Skin",
	"Entities.gmod_subway_ezh3.Spawner.PassTexture.Name": "Interior texture",
	"Entities.gmod_subway_ezh3.Spawner.CabTexture.Name": "Cabin texture",
	"Entities.gmod_subway_ezh3.Spawner.Announcer.Name": "Announcer",
	"Entities.gmod_subway_ezh3.Spawner.HornType.Name": "SPB horn",
	"Entities.gmod_subway_ezh3.Spawner.NM.Name": "Train line pressure",
	"Entities.gmod_subway_ezh3.Spawner.Battery.Name": "Turn on battery",
	"Entities.gmod_subway_ezh3.Spawner.AV8B.Name": "Enable AV8B",
	"Entities.gmod_subway_ezh3.Spawner.DoorsL.Name": "Open left doors",
	"Entities.gmod_subway_ezh3.Spawner.DoorsR.Name": "Open right doors",
	"Entities.gmod_subway_ezh3.Spawner.GV.Name": "Enable HV switch",

	"Entities.gmod_subway_81-717_lvz.Spawner.Texture.Name": "Skin",
	"Entities.gmod_subway_81-717_lvz.Spawner.PassTexture.Name": "Interior texture",
	"Entities.gmod_subway_81-717_lvz.Spawner.CabTexture.Name": "Cabin texture",
	"Entities.gmod_subway_81-717_lvz.Spawner.Announcer.Name": "Announcer",
	"Entities.gmod_subway_81-717_lvz.Spawner.Lighter.Name": "Lighter",
	"Entities.gmod_subway_81-717_lvz.Spawner.Cran.Name": "Brake lever type",
	"Entities.gmod_subway_81-717_lvz.Spawner.Cran.1": "334",
	"Entities.gmod_subway_81-717_lvz.Spawner.Cran.2": "013",
	"Entities.gmod_subway_81-717_lvz.Spawner.MaskType.Name": "Mask type",
	"Entities.gmod_subway_81-717_lvz.Spawner.MaskType.1": "1-4-1",
	"Entities.gmod_subway_81-717_lvz.Spawner.MaskType.2": "2-2(down)-2",
	"Entities.gmod_subway_81-717_lvz.Spawner.MaskType.3": "2-2",
	"Entities.gmod_subway_81-717_lvz.Spawner.MaskType.4": "2-2-2",
	"Entities.gmod_subway_81-717_lvz.Spawner.MaskType.5": "1-3-1",
	"Entities.gmod_subway_81-717_lvz.Spawner.LED.Name": "LED",
	"Entities.gmod_subway_81-717_lvz.Spawner.BPSNType.Name": "BPSN type",
	"Entities.gmod_subway_81-717_lvz.Spawner.BPSNType.1": "Old sound high tone",
	"Entities.gmod_subway_81-717_lvz.Spawner.BPSNType.2": "Old sound medium tone",
	"Entities.gmod_subway_81-717_lvz.Spawner.BPSNType.3": "Standard(from SPB)",
	"Entities.gmod_subway_81-717_lvz.Spawner.BPSNType.4": "Standard(TKL)",
	"Entities.gmod_subway_81-717_lvz.Spawner.BPSNType.5": "Standard",
	"Entities.gmod_subway_81-717_lvz.Spawner.BPSNType.6": "Kiev",
	"Entities.gmod_subway_81-717_lvz.Spawner.BPSNType.7": "Old",
	"Entities.gmod_subway_81-717_lvz.Spawner.BPSNType.8": "Standard 2",
	"Entities.gmod_subway_81-717_lvz.Spawner.BPSNType.9": "Standard 3",
	"Entities.gmod_subway_81-717_lvz.Spawner.BPSNType.10": "No sound(BPN-115)",
    "Entities.gmod_subway_81-717_lvz.Spawner.NewKV.Name": "New contoller model",
    "Entities.gmod_subway_81-717_lvz.Spawner.HornType.Name": "SPB horn",
    "Entities.gmod_subway_81-717_lvz.Spawner.RingType.Name": "Ring sound",
    "Entities.gmod_subway_81-717_lvz.Spawner.RingType.1": "Old",
    "Entities.gmod_subway_81-717_lvz.Spawner.RingType.2": "Standard with low tone",
    "Entities.gmod_subway_81-717_lvz.Spawner.RingType.3": "Standard with high tone",
    "Entities.gmod_subway_81-717_lvz.Spawner.RingType.4": "Standard intermittent with low tone",
    "Entities.gmod_subway_81-717_lvz.Spawner.RingType.5": "Standard intermittent with high tone",
    "Entities.gmod_subway_81-717_lvz.Spawner.NM.Name": "Train line pressure",
    "Entities.gmod_subway_81-717_lvz.Spawner.Battery.Name": "Turn on battery",
    "Entities.gmod_subway_81-717_lvz.Spawner.Switches.Name": "Circuit breakers on",
    "Entities.gmod_subway_81-717_lvz.Spawner.SwitchesR.Name": "Random circuit breakers",
    "Entities.gmod_subway_81-717_lvz.Spawner.DoorsL.Name": "Open left doors",
    "Entities.gmod_subway_81-717_lvz.Spawner.DoorsR.Name": "Open right doors",
    "Entities.gmod_subway_81-717_lvz.Spawner.GV.Name": "Enable HV switch",
    "Entities.gmod_subway_81-717_lvz.Spawner.PB.Name": "Enable parking brake",
    "Entities.gmod_subway_81-717_lvz.Spawner.BortLampType.Name": "Board lamps type",
    "Entities.gmod_subway_81-717_lvz.Spawner.BortLampType.1": "Horizontal",
    "Entities.gmod_subway_81-717_lvz.Spawner.BortLampType.2": "Vertical",
    "Entities.gmod_subway_81-717_lvz.Spawner.HandRail.Name": "Handrails type",
    "Entities.gmod_subway_81-717_lvz.Spawner.HandRail.1": "Old",
    "Entities.gmod_subway_81-717_lvz.Spawner.HandRail.2": "New",
    "Entities.gmod_subway_81-717_lvz.Spawner.SeatType.Name": "Seats type",
    "Entities.gmod_subway_81-717_lvz.Spawner.SeatType.1": "Old",
    "Entities.gmod_subway_81-717_lvz.Spawner.SeatType.2": "New",
    "Entities.gmod_subway_81-717_lvz.Spawner.LampType.Name": "Lamps type",
    "Entities.gmod_subway_81-717_lvz.Spawner.LampType.1": "Type 1",
    "Entities.gmod_subway_81-717_lvz.Spawner.LampType.2": "Type 2",
    "Entities.gmod_subway_81-717_lvz.Spawner.LampType.3": "Type 3",
    "Entities.gmod_subway_81-717_lvz.Spawner.Breakers.Name": "Right side circuit breakers",
    "Entities.gmod_subway_81-717_lvz.Spawner.Adverts.Name": "Adverts type",
    "Entities.gmod_subway_81-717_lvz.Spawner.Adverts.1": "Type 1",
    "Entities.gmod_subway_81-717_lvz.Spawner.Adverts.2": "Type 2",
    "Entities.gmod_subway_81-717_lvz.Spawner.Adverts.3": "Type 3",
    "Entities.gmod_subway_81-717_lvz.Spawner.Adverts.4": "No adverts",

	"Entities.gmod_subway_81-703.Spawner.Texture.Name": "Skin",
	"Entities.gmod_subway_81-703.Spawner.PassTexture.Name": "Interior texture",
	"Entities.gmod_subway_81-703.Spawner.CabTexture.Name": "Cabin texture",
	"Entities.gmod_subway_81-703.Spawner.Announcer.Name": "Announcer",
	"Entities.gmod_subway_81-703.Spawner.HornType.Name": "SPB horn",
	"Entities.gmod_subway_81-703.Spawner.NM.Name": "Train line pressure",
	"Entities.gmod_subway_81-703.Spawner.Battery.Name": "Turn on battery",
	"Entities.gmod_subway_81-703.Spawner.AV8B.Name": "Enable AV8B",
	"Entities.gmod_subway_81-703.Spawner.DoorsL.Name": "Open left doors",
	"Entities.gmod_subway_81-703.Spawner.DoorsR.Name": "Open right doors",
	"Entities.gmod_subway_81-703.Spawner.GV.Name": "Enable HV switch",

	"Spawner.Close": "Close",
	"Spawner.Spawn": "Done"
}
]]
