return [[
{
  "Lang": "ru",
  "Name": "Russian",

  "Entities.gmod_subway_81-720.Buttons.VityazButtons.VityazF1Set": "Витязь: F1",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.VityazF2Set": "Витязь: Следующая страница",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.VityazF3Set": "Витязь: Предыдущая страница",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.VityazF4Set": "Витязь: Штатный режим",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.Vityaz1Set": "Витязь: 1",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.Vityaz4Set": "Витязь: 4",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.Vityaz7Set": "Витязь: 7",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.Vityaz2Set": "Витязь: 2",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.Vityaz5Set": "Витязь: 5",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.Vityaz8Set": "Витязь: 8",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.Vityaz0Set": "Витязь: 0",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.Vityaz3Set": "Витязь: 3",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.Vityaz6Set": "Витязь: 6",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.Vityaz9Set": "Витязь: 9",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.VityazF5Set": "Витязь: ЗВ",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.VityazF6Set": "Витязь: Вверх\\Скорость",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.VityazF7Set": "Витязь: Вниз\\Токи",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.VityazF8Set": "Витязь: Ввод\\Вагонное оборудование",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.VityazF9Set": "Витязь: Выбор\\Управление вагонным оборудованием",
  "Entities.gmod_subway_81-720.Buttons.RV.EmerX1Set": "Ход 1 резервный",
  "Entities.gmod_subway_81-720.Buttons.RV.EmerX2Set": "Ход 2 резервный",
  "Entities.gmod_subway_81-720.Buttons.RV.EmerCloseDoorsSet": "Закрытие дверей резервное",
  "Entities.gmod_subway_81-720.Buttons.RV.EmergencyDoorsToggle": "Двери резервные",
  "Entities.gmod_subway_81-720.Buttons.BackVent.VentCondMode-": "Режим работы вентилятора: +",
  "Entities.gmod_subway_81-720.Buttons.BackVent.VentCondMode+": "Режим работы вентилятора: -",
  "Entities.gmod_subway_81-720.Buttons.BackVent.VentHeatMode+": "+",
  "Entities.gmod_subway_81-720.Buttons.BackVent.VentHeatMode-": "-",
  "Entities.gmod_subway_81-720.Buttons.BackVent.VentStrengthMode-": "Сила вентилятора: +",
  "Entities.gmod_subway_81-720.Buttons.BackVent.VentStrengthMode+": "Сила вентилятора: -",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV1Toggle": "SF1: Питание цепей управления вагона",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV2Toggle": "SF2: Питание БУВ",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV3Toggle": "SF3: Питание БУТП",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV4Toggle": "SF4: БУТП Управление",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV5Toggle": "SF5: БУТП Управление резервное",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV6Toggle": "SF6: БУТП Питание",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV7Toggle": "SF7: ББЭ",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV8Toggle": "SF8: БВ управление",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV9Toggle": "SF9: БВ питание",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV10Toggle": "SF10: ППО",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV11Toggle": "SF11: Мотор-компрессор",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV12Toggle": "SF12: Двери закрытие",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV13Toggle": "SF13: Двери открытие левых",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV14Toggle": "SF14: Двери открытие правых",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV15Toggle": "SF15: Двери торцевые",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV16Toggle": "SF16: Оповещение",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV17Toggle": "SF17: Экстренная связь",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV18Toggle": "SF18: Резерв",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV19Toggle": "SF19: Освещение салона питание",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV20Toggle": "SF20: Освещение салона аварийное",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV21Toggle": "SF21: Датчик скорости",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV22Toggle": "SF22: Тормоз стояночный",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV23Toggle": "SF23: Вентиляция управление 1-я группа",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV24Toggle": "SF24: Вентиляция управление 2-я группа",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV25Toggle": "SF25: Вентиляция питание 1-я группа",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV26Toggle": "SF26: Вентиляция питание 2-я группа",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV27Toggle": "SF27: Питание возбудителя FIXME",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV28Toggle": "SF28: Питание ЗКК FIXME",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV29Toggle": "SF29: Токоприёмники",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV30Toggle": "SF30: Табло",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV31Toggle": "SF31: Резерв",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV32Toggle": "SF32: Резерв",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV33Toggle": "SF33: Резерв",
  "Entities.gmod_subway_81-720.Buttons.ASNP.R_ASNPMenuSet": "АСНП: Меню",
  "Entities.gmod_subway_81-720.Buttons.ASNP.R_ASNPUpSet": "АСНП: Вверх",
  "Entities.gmod_subway_81-720.Buttons.ASNP.R_ASNPDownSet": "АСНП: Вниз",
  "Entities.gmod_subway_81-720.Buttons.ASNP.R_ASNPOnToggle": "АСНП: Включение",
  "Entities.gmod_subway_81-720.Buttons.PneumoHelper1.!BrakeCylinder": "Тормозной цилиндр",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF1Toggle": "SF1: Питание общее",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF2Toggle": "SF2: Управление основное",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF3Toggle": "SF3: Управление резервное",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF4Toggle": "SF4: БАРС",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF5Toggle": "SF5: БУП",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF6Toggle": "SF6: БКЦУ",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF7Toggle": "SF7: ППО",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF8Toggle": "SF8: Оповещение",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF9Toggle": "SF9: Радиосвязь",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF10Toggle": "SF10: Ориентация вагона",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF11Toggle": "SF11: Направление движения",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF12Toggle": "SF12: Фары 1-й группы",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF13Toggle": "SF13: Фары 2-й группы",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF14Toggle": "SF14: Огни габаритные",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF15Toggle": "SF15: Освещение кабины",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF16Toggle": "SF16: Отопление",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF17Toggle": "SF17: Кондиционер кабины",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF18Toggle": "SF18: Гребнесмазыватель",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF19Toggle": "SF19: Питание КРМ основное",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF20Toggle": "SF20: Питание КРМ резервное",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF21Toggle": "SF21: Двери открытие",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF22Toggle": "SF22: Двери закрытие",
  "Entities.gmod_subway_81-720.Buttons.BTO.K29Toggle": "КРМШ",
  "Entities.gmod_subway_81-720.Buttons.PassengerDoor2.PassengerDoor": "Дверь в кабину машиниста из салона\nPass door",
  "Entities.gmod_subway_81-720.Buttons.VoltHelper2.!HV": "Киловольтметр высокого напряжения(контактный рельс)",
  "Entities.gmod_subway_81-720.Buttons.VoltHelper2.!I1_3": "Ток 1-й группы тяговых двигателей",
  "Entities.gmod_subway_81-720.Buttons.VoltHelper2.!I2_4": "Ток 2-й группы тяговых двигателей",
  "Entities.gmod_subway_81-720.Buttons.GV.GVToggle": "Разъединитель БРУ (ГВ)",
  "Entities.gmod_subway_81-720.Buttons.RearPneumatic.RearBrakeLineIsolationToggle": "Концевой кран тормозной магистрали",
  "Entities.gmod_subway_81-720.Buttons.RearPneumatic.RearTrainLineIsolationToggle": "Концевой кран напорной магистрали",
  "Entities.gmod_subway_81-720.Buttons.RearDoor1.RearDoor": "Передняя дверь\nFront door",
  "Entities.gmod_subway_81-720.Buttons.RearDoor.RearDoor": "Передняя дверь\nFront door",
  "Entities.gmod_subway_81-720.Buttons.BackDown.Pant1Toggle": "Отжатие токоприёмников 1-й группы",
  "Entities.gmod_subway_81-720.Buttons.BackDown.Pant2Toggle": "Отжатие токоприёмников 2-й группы",
  "Entities.gmod_subway_81-720.Buttons.BackDown.Vent1Toggle": "Вентиляция 1-я группа",
  "Entities.gmod_subway_81-720.Buttons.BackDown.Vent2Toggle": "Вентиляция 2-я группа",
  "Entities.gmod_subway_81-720.Buttons.BackDown.VentToggle": "",
  "Entities.gmod_subway_81-720.Buttons.BackDown.PassLightToggle": "Освещение салона",
  "Entities.gmod_subway_81-720.Buttons.BackDown.CabLightToggle": "Освещение кабины",
  "Entities.gmod_subway_81-720.Buttons.BackDown.Headlights1Toggle": "Фары 1-я группа",
  "Entities.gmod_subway_81-720.Buttons.BackDown.Headlights2Toggle": "Фары 2-я группа",
  "Entities.gmod_subway_81-720.Buttons.BackDown.ParkingBrakeToggle": "Стояночный тормоз",
  "Entities.gmod_subway_81-720.Buttons.BackDown.TorecDoorsToggle": "Двери торцевые",
  "Entities.gmod_subway_81-720.Buttons.BackDown.BBERToggle": "ББЭ Резервнео включение",
  "Entities.gmod_subway_81-720.Buttons.BackDown.BBEToggle": "ББЭ",
  "Entities.gmod_subway_81-720.Buttons.BackDown.CompressorToggle": "Компрессор",
  "Entities.gmod_subway_81-720.Buttons.BackDown.CabLightStrengthToggle": "Сила освещения кабины",
  "Entities.gmod_subway_81-720.Buttons.BackDown.AppLights1Toggle": "Освещение аппаратного отсека",
  "Entities.gmod_subway_81-720.Buttons.BackDown.AppLights2Toggle": "",
  "Entities.gmod_subway_81-720.Buttons.BackDown.BARSBlock-": "Блокировка неисправных БАРСов: -",
  "Entities.gmod_subway_81-720.Buttons.BackDown.BARSBlock+": "Блокировка неисправных БАРСов: +",
  "Entities.gmod_subway_81-720.Buttons.BackDown.BatteryToggle": "Выключатель батареи",
  "Entities.gmod_subway_81-720.Buttons.BackDown.ALSFreqToggle": "Дешифратор АЛС",
  "Entities.gmod_subway_81-720.Buttons.VoltHelper1.!Battery": "Вольтметр бортовой сети(батарея)",
  "Entities.gmod_subway_81-720.Buttons.PassengerDoor.PassengerDoor": "Дверь в кабину машиниста из салона\nPass door",
  "Entities.gmod_subway_81-720.Buttons.CabinDoorR.CabinDoorRight": "Дверь в кабину машиниста\nCabin door",
  "Entities.gmod_subway_81-720.Buttons.CabinDoorL.CabinDoorLeft": "Дверь в кабину машиниста\nCabin door",
  "Entities.gmod_subway_81-720.Buttons.FrontPneumatic.FrontBrakeLineIsolationToggle": "Концевой кран тормозной магистрали",
  "Entities.gmod_subway_81-720.Buttons.FrontPneumatic.FrontTrainLineIsolationToggle": "Концевой кран напорной магистрали",
  "Entities.gmod_subway_81-720.Buttons.PUL.DoorSelectLToggle": "Выбор левых дверей",
  "Entities.gmod_subway_81-720.Buttons.PUL.DoorSelectRToggle": "Выбор правых дверей",
  "Entities.gmod_subway_81-720.Buttons.PUL.DoorBlockToggle": "Блокировка дверей",
  "Entities.gmod_subway_81-720.Buttons.PUL.!DoorLeftLamp": "Работа кнопки левых дверей",
  "Entities.gmod_subway_81-720.Buttons.PUL.DoorLeftSet": "Левые двери",
  "Entities.gmod_subway_81-720.Buttons.PUU.!DoorsClosed": "Двери закрыты",
  "Entities.gmod_subway_81-720.Buttons.PUU.StandToggle": "Стоянка",
  "Entities.gmod_subway_81-720.Buttons.PUU.TickerToggle": "Бегущая строка",
  "Entities.gmod_subway_81-720.Buttons.PUU.KAHToggle": "КАХ",
  "Entities.gmod_subway_81-720.Buttons.PUU.ALSToggle": "АЛС",
  "Entities.gmod_subway_81-720.Buttons.PUU.FDepotToggle": "Выезд из депо",
  "Entities.gmod_subway_81-720.Buttons.PUU.!HVoltage": "Сеть контактная",
  "Entities.gmod_subway_81-720.Buttons.PUU.PassSchemeToggle": "Табло наддверное",
  "Entities.gmod_subway_81-720.Buttons.PUU.EmergencyCompressorSet": "Компрессор резервный",
  "Entities.gmod_subway_81-720.Buttons.PUU.EnableBVSet": "Включение защиты",
  "Entities.gmod_subway_81-720.Buttons.PUU.DisableBVSet": "Отключение БВ",
  "Entities.gmod_subway_81-720.Buttons.PUU.RingSet": "Передача управления(звонок)",
  "Entities.gmod_subway_81-720.Buttons.PUU.R_Program2Set": "Программа 2",
  "Entities.gmod_subway_81-720.Buttons.PUU.R_AnnouncerToggle": "Информатор",
  "Entities.gmod_subway_81-720.Buttons.PUU.R_LineToggle": "Линия",
  "Entities.gmod_subway_81-720.Buttons.PUU.R_EmerSet": "Связь экстренная",
  "Entities.gmod_subway_81-720.Buttons.PUU.R_Program1Set": "Пуск записи",
  "Entities.gmod_subway_81-720.Buttons.PUU.EnableBVEmerSet": "Возврат БВ резервный",
  "Entities.gmod_subway_81-720.Buttons.PUU.EmergencyControlsToggle": "Управление резервное",
  "Entities.gmod_subway_81-720.Buttons.PUU.WiperToggle": "Стекло-очиститель",
  "Entities.gmod_subway_81-720.Buttons.PUU.!VDop": "Допустимая скорость",
  "Entities.gmod_subway_81-720.Buttons.PUU.!VFact": "Фактическая скорость",
  "Entities.gmod_subway_81-720.Buttons.PUU.!VPred": "Предупредительная скорость",
  "Entities.gmod_subway_81-720.Buttons.PUU.!VDop2": "Допустимая скорость",
  "Entities.gmod_subway_81-720.Buttons.PUU.!Acc": "Ускорение",
  "Entities.gmod_subway_81-720.Buttons.PUU.!Forw": "Движение вперёд",
  "Entities.gmod_subway_81-720.Buttons.PUU.!Back": "Движение назад",
  "Entities.gmod_subway_81-720.Buttons.PUR.EmerBrakeAddSet": "(резервный) Тормоз",
  "Entities.gmod_subway_81-720.Buttons.PUR.EmerBrakeReleaseSet": "(резервный) Отпуск",
  "Entities.gmod_subway_81-720.Buttons.PUR.EmerBrakeToggle": "Тормоз резервный",
  "Entities.gmod_subway_81-720.Buttons.PUR.EmergencyBrakeToggle": "Тормоз экстренный",
  "Entities.gmod_subway_81-720.Buttons.PUR.DoorCloseToggle": "Закрытие дверей",
  "Entities.gmod_subway_81-720.Buttons.PUR.AttentionMessageSet": "Восприятие сообщения",
  "Entities.gmod_subway_81-720.Buttons.PUR.AttentionSet": "Бдительность",
  "Entities.gmod_subway_81-720.Buttons.PUR.AttentionBrakeSet": "Восприятие торможения",
  "Entities.gmod_subway_81-720.Buttons.PUR.HornBSet": "Сигнал",
  "Entities.gmod_subway_81-720.Buttons.PUR.DoorRightSet": "Прав двери",
  "Entities.gmod_subway_81-720.Buttons.PUR.!DoorRightLamp": "Работа кнопки правых дверей",
  "Entities.gmod_subway_81-720.Buttons.PneumoHelper2.!BrakeTrainLine": "Красная - тормозная, чёрная - напорная магистраль",

  "Entities.gmod_subway_81-721.Buttons.GV.GVToggle": "Разъединитель БРУ (ГВ)",
  "Entities.gmod_subway_81-721.Buttons.RearPneumatic.RearBrakeLineIsolationToggle": "Концевой кран тормозной магистрали",
  "Entities.gmod_subway_81-721.Buttons.RearPneumatic.RearTrainLineIsolationToggle": "Концевой кран напорной магистрали",
  "Entities.gmod_subway_81-721.Buttons.FrontDoor.FrontDoor": "Передняя дверь\nFront door",
  "Entities.gmod_subway_81-721.Buttons.RearDoor.RearDoor": "Задняя дверь\nRear door",
  "Entities.gmod_subway_81-721.Buttons.Battery.BatteryToggle": "Батарея",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV1Toggle": "SF1: Питание цепей управления вагона",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV2Toggle": "SF2: Питание БУВ",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV3Toggle": "SF3: Питание БУТП",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV4Toggle": "SF4: БУТП Управление",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV5Toggle": "SF5: БУТП Управление резервное",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV6Toggle": "SF6: БУТП Питание",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV7Toggle": "SF7: ББЭ",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV8Toggle": "SF8: БВ управление",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV9Toggle": "SF9: БВ питание",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV10Toggle": "SF10: ППО",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV11Toggle": "SF11: Мотор-компрессор",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV12Toggle": "SF12: Двери закрытие",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV13Toggle": "SF13: Двери открытие левых",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV14Toggle": "SF14: Двери открытие правых",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV15Toggle": "SF15: Двери торцевые",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV16Toggle": "SF16: Оповещение",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV17Toggle": "SF17: Экстренная связь",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV18Toggle": "SF18: Резерв",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV19Toggle": "SF19: Освещение салона питание",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV20Toggle": "SF20: Освещение салона аварийное",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV21Toggle": "SF21: Датчик скорости",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV22Toggle": "SF22: Тормоз стояночный",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV23Toggle": "SF23: Вентиляция управление 1-я группа",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV24Toggle": "SF24: Вентиляция управление 2-я группа",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV25Toggle": "SF25: Вентиляция питание 1-я группа",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV26Toggle": "SF26: Вентиляция питание 2-я группа",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV27Toggle": "SF27: Питание возбудителя FIXME",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV28Toggle": "SF28: Питание ЗКК FIXME",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV29Toggle": "SF29: Токоприёмники",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV30Toggle": "SF30: Табло",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV31Toggle": "SF31: Резерв",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV32Toggle": "SF32: Резерв",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV33Toggle": "SF33: Резерв",
  "Entities.gmod_subway_81-721.Buttons.FrontPneumatic.FrontBrakeLineIsolationToggle": "Концевой кран тормозной магистрали",
  "Entities.gmod_subway_81-721.Buttons.FrontPneumatic.FrontTrainLineIsolationToggle": "Концевой кран напорной магистрали",

  "Entities.gmod_subway_81-720.Buttons.IGLAButtons.IGLA1USet": "ИГЛА: Первая кнопка вверх",
  "Entities.gmod_subway_81-720.Buttons.IGLAButtons.IGLA1Set": "ИГЛА: Первая кнопка",
  "Entities.gmod_subway_81-720.Buttons.IGLAButtons.IGLA1DSet": "ИГЛА: Первая кнопка вниз",
  "Entities.gmod_subway_81-720.Buttons.IGLAButtons.IGLA2USet": "ИГЛА: Вторая кнопка вверх",
  "Entities.gmod_subway_81-720.Buttons.IGLAButtons.IGLA2Set": "ИГЛА: Вторая кнопка",
  "Entities.gmod_subway_81-720.Buttons.IGLAButtons.IGLA2DSet": "ИГЛА: Вторая кнопка вниз",
  "Entities.gmod_subway_81-720.Buttons.IGLAButtons.!IGLASR": "ИГЛА: SR",
  "Entities.gmod_subway_81-720.Buttons.IGLAButtons.!IGLARX": "ИГЛА: RX",
  "Entities.gmod_subway_81-720.Buttons.IGLAButtons.!IGLAErr": "ИГЛА: Отказ",
  "Entities.gmod_subway_81-720.Buttons.IGLAButtons.!IGLAOSP": "ИГЛА: ОСП(Сработка огнетушителей)",
  "Entities.gmod_subway_81-720.Buttons.IGLAButtons.!IGLAPI": "ИГЛА: ПИ(Пожар)",
  "Entities.gmod_subway_81-720.Buttons.IGLAButtons.!IGLAOff": "ИГЛА: Откл",
  "Entities.gmod_subway_81-720.Buttons.PUU.KAHkToggle": "Крышка кнопки КАХ",
  "Entities.gmod_subway_81-720.Buttons.PUU.ALSkToggle": "Крышка кнопки АЛС",
  "Entities.gmod_subway_81-720.Buttons.PUR.AccelRateSet": "Темп разгона(Режим подъём)",

  "Entities.gmod_subway_81-720.Buttons.BTO.UAVAToggle": "УАВА: Универсальный Автоматический Выключатель Автостопа"
}
]]
