return [[
{
    "Lang": "ru",
    "Name": "Russian",


    "Entities.gmod_subway_em508.Buttons.Back.BackDoor": "Задняя дверь",
    "Entities.gmod_subway_em508.Buttons.HelperPanel.R_Program1Set": "Программа 1",
    "Entities.gmod_subway_em508.Buttons.HelperPanel.R_Program2Set": "Программа 2",
    "Entities.gmod_subway_em508.Buttons.HelperPanel.VDLSet": "ВДЛ: Выключатель левых дверей",
    "Entities.gmod_subway_em508.Buttons.HelperPanel.VUD2Toggle": "ВУД2: Выключатель управления дверьми",
    "Entities.gmod_subway_em508.Buttons.AV2.RSTToggle": "РСТ: Радиостанция",
    "Entities.gmod_subway_em508.Buttons.RearPneumatic.RearTrainLineIsolationToggle": "Концевой кран напорной магистрали",
    "Entities.gmod_subway_em508.Buttons.RearPneumatic.RearBrakeLineIsolationToggle": "Концевой кран тормозной магистрали",
    "Entities.gmod_subway_em508.Buttons.AVU.AVULight": "Лампа:Включен АВУ (Автоматический выключатель управления)",
    "Entities.gmod_subway_em508.Buttons.AVU.OtklAVUToggle": "Отключение автоматического выключения управления (неисправность АВУ)",
    "Entities.gmod_subway_em508.Buttons.Back2.!HVFuses": "Блок предохранителей",
    "Entities.gmod_subway_em508.Buttons.Back2.!Relays": "Ящик с аппаратами для подзаряда аккумуляторной батареи и дверной воздухораспределитель",
    "Entities.gmod_subway_em508.Buttons.Back2.!Heater": "Печка",
    "Entities.gmod_subway_em508.Buttons.Main.DoorSelectToggle": "Переключатель: Выбор стороны открытия дверей",
    "Entities.gmod_subway_em508.Buttons.Main.DIPonSet": "Вкл. Осв.: Включение освещения",
    "Entities.gmod_subway_em508.Buttons.Main.DIPoffSet": "Выкл. Осв.: Отключение освещения",
    "Entities.gmod_subway_em508.Buttons.Main.VozvratRPSet": "ВРП: Возврат РП",
    "Entities.gmod_subway_em508.Buttons.Main.KSNSet": "КСН:Принудительное срабатывание РП на неисправном вагоне (Сигнализация неисправности)",
    "Entities.gmod_subway_em508.Buttons.Main.KRZDSet": "КРЗД: Кнопка резервного закрытия дверей",
    "Entities.gmod_subway_em508.Buttons.Main.KSDSet": "КСД: Контроль сигнализации дверей(проверка СД)",
    "Entities.gmod_subway_em508.Buttons.Main.KDPSet": "КДП:Правые двери",
    "Entities.gmod_subway_em508.Buttons.Main.KDLSet": "КДЛ: Кнопка левых дверей",
    "Entities.gmod_subway_em508.Buttons.Main.RezMKSet": "РМК: Резервное включение мотор-компрессора",
    "Entities.gmod_subway_em508.Buttons.Main.KU1Toggle": "МК: Включение мотор-компрессора",
    "Entities.gmod_subway_em508.Buttons.Main.VUD1Toggle": "ВУД: Закрытие дверей",
    "Entities.gmod_subway_em508.Buttons.AV1.VU3Toggle": "ВУ3: Освещение кабины\n",
    "Entities.gmod_subway_em508.Buttons.AV1.VU2Toggle": "ВУ2: Аварийное освещение\n",
    "Entities.gmod_subway_em508.Buttons.AV1.VU1Toggle": "ВУ1: Печь отопления кабины\n",
    "Entities.gmod_subway_em508.Buttons.Back1.!ULSPM": "УЭСПМ (Устройство связи пассажир-машинист)",
    "Entities.gmod_subway_em508.Buttons.Back1.!TonalARS": "Тональное устройство - Звонок",
    "Entities.gmod_subway_em508.Buttons.Back1.!PressureRelay": "Регулятор давления",
    "Entities.gmod_subway_em508.Buttons.Back1.!Reproductor": "Громкоговоритель",
    "Entities.gmod_subway_em508.Buttons.Back1.!LVFuses": "Щиток с низковольтными предохранителями",
    "Entities.gmod_subway_em508.Buttons.Back1.R_UNchToggle": "Питание статива РРИ",
    "Entities.gmod_subway_em508.Buttons.Lamp.L_3Toggle": "Лампа: Подсветка приборов",
    "Entities.gmod_subway_em508.Buttons.DriverValveTLDisconnect.DriverValveTLDisconnectToggle": "Кран двойной тяги напорной магистрали",
    "Entities.gmod_subway_em508.Buttons.VU.VUToggle": "ВУ: Выключатель Управления",
    "Entities.gmod_subway_em508.Buttons.PneumaticManometer.!LinesPressure": "Давление в магистралях (красная: тормозной, чёрная: напорной)",
    "Entities.gmod_subway_em508.Buttons.Stopkran.EmergencyBrakeValveToggle": "Стопкран",
    "Entities.gmod_subway_em508.Buttons.LAMPS.SN": "Индикатор: Cигнализация неисправности",
    "Entities.gmod_subway_em508.Buttons.LAMPS.RedRP": "Индикатор: Красная лампа реле перегрузки",
    "Entities.gmod_subway_em508.Buttons.LAMPS.SD": "Индикатор: Сигнализация дверей",
    "Entities.gmod_subway_em508.Buttons.LAMPS.GreenRP": "Индикатор: Зеленая лампа реле перегрузки",
    "Entities.gmod_subway_em508.Buttons.LAMPS.UKS": "Индикатор: Устройство контроля скорости УКС-20М",
    "Entities.gmod_subway_em508.Buttons.LAMPS.Red": "Индикатор: Обогрев кабины",
    "Entities.gmod_subway_em508.Buttons.LAMPS.AGS": "Лампа: Работа АГС (Автоматический гребне смазыватель)",
    "Entities.gmod_subway_em508.Buttons.UAVAPanel.UAVAToggle": "УАВА: Универсальный Автоматический Выключатель Автостопа (отключение автостопа)",
    "Entities.gmod_subway_em508.Buttons.UAVAPanel.UAVACToggle   ": "УАВА: Универсальный Автоматический Выключатель Автостопа (восстановление контактов)",
    "Entities.gmod_subway_em508.Buttons.PneumaticPanels.!CylinderPressure": "Тормозной манометр: Давление в тормозных цилиндрах (ТЦ)",
    "Entities.gmod_subway_em508.Buttons.Battery.VBToggle": "АБ: Выключатель аккумуляторной батареи (Вспомогательные цепи низкого напряжения)",
    "Entities.gmod_subway_em508.Buttons.Battery.R_RadioToggle": "Питание радиоинформатора +50В",
    "Entities.gmod_subway_em508.Buttons.FrontPneumatic.FrontBrakeLineIsolationToggle": "Концевой кран тормозной магистрали",
    "Entities.gmod_subway_em508.Buttons.FrontPneumatic.FrontTrainLineIsolationToggle": "Концевой кран напорной магистрали",
    "Entities.gmod_subway_em508.Buttons.ASNP.R_ASNPMenuSet": "Информатор: Меню",
    "Entities.gmod_subway_em508.Buttons.ASNP.R_ASNPUpSet": "Информатор: Вверх",
    "Entities.gmod_subway_em508.Buttons.ASNP.R_ASNPDownSet": "Информатор: Вниз",
    "Entities.gmod_subway_em508.Buttons.ASNP.R_ASNPOnToggle": "Информатор: Включение",
    "Entities.gmod_subway_em508.Buttons.VU1.KRPSet": "РРП: Резервный пуск ",
    "Entities.gmod_subway_em508.Buttons.GV.GVToggle": "Главный выключатель",
    "Entities.gmod_subway_em508.Buttons.IGLAButtons.IGLA1USet": "ИГЛА: Первая кнопка вверх",
    "Entities.gmod_subway_em508.Buttons.IGLAButtons.IGLA1Set": "ИГЛА: Первая кнопка",
    "Entities.gmod_subway_em508.Buttons.IGLAButtons.IGLA1DSet": "ИГЛА: Первая кнопка вниз",
    "Entities.gmod_subway_em508.Buttons.IGLAButtons.IGLA2USet": "ИГЛА: Вторая кнопка вверх",
    "Entities.gmod_subway_em508.Buttons.IGLAButtons.IGLA2Set": "ИГЛА: Вторая кнопка",
    "Entities.gmod_subway_em508.Buttons.IGLAButtons.IGLA2DSet": "ИГЛА: Вторая кнопка вниз",
    "Entities.gmod_subway_em508.Buttons.IGLAButtons.!IGLASR": "ИГЛА: SR",
    "Entities.gmod_subway_em508.Buttons.IGLAButtons.!IGLARX": "ИГЛА: RX",
    "Entities.gmod_subway_em508.Buttons.IGLAButtons.!IGLAErr": "ИГЛА: Отказ",
    "Entities.gmod_subway_em508.Buttons.IGLAButtons.!IGLAOSP": "ИГЛА: ОСП",
    "Entities.gmod_subway_em508.Buttons.IGLAButtons.!IGLAPI": "ИГЛА: ПИ",
    "Entities.gmod_subway_em508.Buttons.IGLAButtons.!IGLAOff": "ИГЛА: Откл",
    "Entities.gmod_subway_em508.Buttons.PassengerDoor.PassengerDoor": "Дверь в кабину машиниста из салона",
    "Entities.gmod_subway_em508.Buttons.InfoTableSelect.PrevSign": "Предыдущая надпись",
    "Entities.gmod_subway_em508.Buttons.InfoTableSelect.NextSign": "Следующая надпись",
    "Entities.gmod_subway_em508.Buttons.InfoTableSelect.Num2P": "Маршрут: Увеличить число 2",
    "Entities.gmod_subway_em508.Buttons.InfoTableSelect.Num2M": "Маршрут: Уменьшить число 2",
    "Entities.gmod_subway_em508.Buttons.InfoTableSelect.Num1P": "Маршрут: Увеличить число 1",
    "Entities.gmod_subway_em508.Buttons.InfoTableSelect.Num1M": "Маршрут: Уменьшить число 1",
    "Entities.gmod_subway_em508.Buttons.Front.FrontDoor": "Передняя дверь",
    "Entities.gmod_subway_em508.Buttons.KRR.KRRSet": "KРР: Кнопка разворота реверсоров",
    "Entities.gmod_subway_em508.Buttons.AGS.VUSToggle": "Переключатель: Ближний свет/Дальний свет",
    "Entities.gmod_subway_em508.Buttons.CabinDoor.CabinDoor": "Дверь в кабину машиниста",
    "Entities.gmod_subway_em508.Buttons.PassengerDoor1.PassengerDoor": "Дверь в кабину машиниста из салона",
    "Entities.gmod_subway_em508.Buttons.ParkingBrake.ParkingBrakeLeft": "Поворот колеса ручного тормоза",
    "Entities.gmod_subway_em508.Buttons.ParkingBrake.ParkingBrakeRight": "Поворот колеса ручного тормоза",
    "Entities.gmod_subway_em508.Buttons.AVMain.AV8BToggle": "АВ-8Б: Автоматическй выключатель (Вспомогательные цепи высокого напряжения)\n",
    "Entities.gmod_subway_em508.Buttons.Back3.!RTM": "Пульт диспетчерской радиосвязи",
    "Entities.gmod_subway_em508.Buttons.Back3.!ULSPMSpeaker": "Блок громкоговорителя связи пассажир-машинист",
    "Entities.gmod_subway_em508.Buttons.Back3.!Amplifier": "Блок усилителя поездной радиостанции",
    "Entities.gmod_subway_em508.Buttons.DriverValveBLDisconnect.DriverValveBLDisconnectToggle": "Кран двойной тяги тормозной магистрали",
    "Entities.gmod_subway_em508.Buttons.AirDistributor.AirDistributorDisconnectToggle": "Выключение воздухораспределителя",



    "Entities.gmod_subway_em508_int.Buttons.Stopkran.EmergencyBrakeValveToggle": "Стопкран",
    "Entities.gmod_subway_em508_int.Buttons.Back.BackDoor": "Задняя дверь",
    "Entities.gmod_subway_em508_int.Buttons.HelperPanel.R_Program1Set": "Программа 1",
    "Entities.gmod_subway_em508_int.Buttons.HelperPanel.R_Program2Set": "Программа 2",
    "Entities.gmod_subway_em508_int.Buttons.HelperPanel.VDLSet": "ВДЛ: Выключатель левых дверей",
    "Entities.gmod_subway_em508_int.Buttons.HelperPanel.VUD2Toggle": "ВУД2: Выключатель управления дверьми",
    "Entities.gmod_subway_em508_int.Buttons.DriverValveBLDisconnect.DriverValveBLDisconnectToggle": "Кран двойной тяги тормозной магистрали",
    "Entities.gmod_subway_em508_int.Buttons.Battery.VBToggle": "АБ: Выключатель аккумуляторной батареи (Вспомогательные цепи низкого напряжения)",
    "Entities.gmod_subway_em508_int.Buttons.Battery.R_RadioToggle": "Питание радиоинформатора +50В",
    "Entities.gmod_subway_em508_int.Buttons.FrontPneumatic.FrontBrakeLineIsolationToggle": "Концевой кран тормозной магистрали",
    "Entities.gmod_subway_em508_int.Buttons.FrontPneumatic.FrontTrainLineIsolationToggle": "Концевой кран напорной магистрали",
    "Entities.gmod_subway_em508_int.Buttons.AirDistributor.AirDistributorDisconnectToggle": "Выключение воздухораспределителя",
    "Entities.gmod_subway_em508_int.Buttons.PassengerDoor.PassengerDoor": "Дверь в кабину машиниста из салона",
    "Entities.gmod_subway_em508_int.Buttons.VU1.KRPSet": "РРП: Резервный пуск ",
    "Entities.gmod_subway_em508_int.Buttons.UAVAPanel.UAVAToggle": "УАВА: Универсальный Автоматический Выключатель Автостопа (отключение автостопа)",
    "Entities.gmod_subway_em508_int.Buttons.UAVAPanel.UAVACToggle   ": "УАВА: Универсальный Автоматический Выключатель Автостопа (восстановление контактов)",
    "Entities.gmod_subway_em508_int.Buttons.Front.FrontDoor": "Передняя дверь",
    "Entities.gmod_subway_em508_int.Buttons.Tsepi.!BatteryVoltage": "Напряжение цепей управления",
    "Entities.gmod_subway_em508_int.Buttons.RearPneumatic.RearTrainLineIsolationToggle": "Концевой кран напорной магистрали",
    "Entities.gmod_subway_em508_int.Buttons.RearPneumatic.RearBrakeLineIsolationToggle": "Концевой кран тормозной магистрали",
    "Entities.gmod_subway_em508_int.Buttons.InfoTableSelect.PrevSign": "Предыдущая надпись",
    "Entities.gmod_subway_em508_int.Buttons.InfoTableSelect.NextSign": "Следующая надпись",
    "Entities.gmod_subway_em508_int.Buttons.InfoTableSelect.Num2P": "Маршрут: Увеличить число 2",
    "Entities.gmod_subway_em508_int.Buttons.InfoTableSelect.Num2M": "Маршрут: Уменьшить число 2",
    "Entities.gmod_subway_em508_int.Buttons.InfoTableSelect.Num1P": "Маршрут: Увеличить число 1",
    "Entities.gmod_subway_em508_int.Buttons.InfoTableSelect.Num1M": "Маршрут: Уменьшить число 1",
    "Entities.gmod_subway_em508_int.Buttons.Back2.!HVFuses": "Блок предохранителей",
    "Entities.gmod_subway_em508_int.Buttons.Back2.!Relays": "Ящик с аппаратами для подзаряда аккумуляторной батареи и дверной воздухораспределитель",
    "Entities.gmod_subway_em508_int.Buttons.Back2.!Heater": "Печка",
    "Entities.gmod_subway_em508_int.Buttons.Main.GreenRP": "Лампа: Зеленая лампа реле перегрузки",
    "Entities.gmod_subway_em508_int.Buttons.Main.RedRP": "Лампа: Красная лампа реле перегрузки",
    "Entities.gmod_subway_em508_int.Buttons.Main.SD": "Лампа: Сигнализация дверей",
    "Entities.gmod_subway_em508_int.Buttons.Main.DIPonSet": "Вкл. Осв.: Включение освещения",
    "Entities.gmod_subway_em508_int.Buttons.Main.DIPoffSet": "Выкл. Осв.: Отключение освещения",
    "Entities.gmod_subway_em508_int.Buttons.Main.VozvratRPSet": "ВРП: Возврат РП",
    "Entities.gmod_subway_em508_int.Buttons.Main.KSNSet": "КСН:Принудительное срабатывание РП на неисправном вагоне (Сигнализация неисправности)",
    "Entities.gmod_subway_em508_int.Buttons.Main.KRZDSet": "КРЗД: Кнопка резервного закрытия дверей",
    "Entities.gmod_subway_em508_int.Buttons.Main.KDPSet": "КДП:Правые двери",
    "Entities.gmod_subway_em508_int.Buttons.Main.KDLSet": "КДЛ: Кнопка левых дверей",
    "Entities.gmod_subway_em508_int.Buttons.Main.KU1Toggle": "МК: Включение мотор-компрессора",
    "Entities.gmod_subway_em508_int.Buttons.Main.VUD1Toggle": "ВУД: Закрытие дверей",
    "Entities.gmod_subway_em508_int.Buttons.AV1.VU3Toggle": "ВУ3: Освещение кабины",
    "Entities.gmod_subway_em508_int.Buttons.AV1.VU2Toggle": "ВУ2: Аварийное освещение",
    "Entities.gmod_subway_em508_int.Buttons.AV1.VU1Toggle": "ВУ1: Печь отопления кабины",
    "Entities.gmod_subway_em508_int.Buttons.AVMain.AV8BToggle": "АВ-8Б: Автоматическй выключатель (Вспомогательные цепи высокого напряжения)\n",
    "Entities.gmod_subway_em508_int.Buttons.CabinDoor.CabinDoor": "Дверь в кабину машиниста",
    "Entities.gmod_subway_em508_int.Buttons.Lamp.L_3Toggle": "Лампа: Подсветка приборов",
    "Entities.gmod_subway_em508_int.Buttons.PassengerDoor1.PassengerDoor": "Дверь в кабину машиниста из салона",
    "Entities.gmod_subway_em508_int.Buttons.DriverValveTLDisconnect.DriverValveTLDisconnectToggle": "Кран двойной тяги напорной магистрали",
    "Entities.gmod_subway_em508_int.Buttons.GV.GVToggle": "Главный выключатель",
    "Entities.gmod_subway_em508_int.Buttons.VU.VUToggle": "ВУ: Выключатель Управления",
    "Entities.gmod_subway_em508_int.Buttons.PneumaticPanels.!CylinderPressure": "Тормозной манометр: Давление в тормозных цилиндрах (ТЦ)",
    "Entities.gmod_subway_em508_int.Buttons.ParkingBrake.ParkingBrakeLeft": "Поворот колеса ручного тормоза",
    "Entities.gmod_subway_em508_int.Buttons.ParkingBrake.ParkingBrakeRight": "Поворот колеса ручного тормоза",
    "Entities.gmod_subway_em508_int.Buttons.PneumaticManometer.!LinesPressure": "Давление в магистралях (красная: тормозной, чёрная: напорной)"
}
]]
