return [[
{
	"Lang": "ru",
	"Name": "Russian",
	"Panel.Admin": "Админ",
	"Panel.Client": "Клиент",
	"Panel.DrawDebugInfo": "Отображать отладочную информацию",
	"Panel.DisableCamAccel": "Откл. симуляцию качания головы",
	"Panel.DisableHoverText": "Откл. всплывающий текст",
	"Panel.DrawCams": "Отрисовывать камеры",
	"Panel.FOV": "Поле зрения",

	"Train.Common.Camera0": "Место машиниста",

	"Train.Buttons.Sealed": "Запломбировано",

	"Entities.gmod_subway_base.Name": "База метропоездов",
	"Entities.gmod_subway_81-703.Name": "E",
	"Entities.gmod_subway_81-703_2.Name": "E (промежуточный)",
	"Entities.gmod_subway_81-717_mvm.Name": "81-717(МВМ головной)",
	"Entities.gmod_subway_81-717_lvz.Name": "81-717(ЛВЗ головной)",
	"Entities.gmod_subway_81-714_mvm.Name": "81-714(МВМ промежуточный)",
	"Entities.gmod_subway_81-714_lvz.Name": "81-714(ЛВЗ промежуточный)",
	"Entities.gmod_subway_81-7036.Name": "81-7036 (не работоспособен)",
	"Entities.gmod_subway_81-7037.Name": "81-7037 (не работоспособен)",
	"Entities.gmod_subway_81-720.Name": "81-720 (головной)",
	"Entities.gmod_subway_81-721.Name": "81-721 (промежуточный)",
	"Entities.gmod_subway_81-722.Name": "81-722 (головной)",
	"Entities.gmod_subway_81-723.Name": "81-723 (промежуточный моторный)",
	"Entities.gmod_subway_81-724.Name": "81-724 (промежуточный немоторный)",
	"Entities.gmod_subway_e.Name": "Е (стар)",
	"Entities.gmod_subway_em.Name": "Ем",
	"Entities.gmod_subway_ema.Name": "Ема",
	"Entities.gmod_subway_ezh.Name": "Еж",
	"Entities.gmod_subway_ezh1.Name": "Еж1",
	"Entities.gmod_subway_em508.Name": "Ем-508",
	"Entities.gmod_subway_em508_int.Name": "Ем-508 *промежуточный)",
	"Entities.gmod_subway_ezh3.Name": "Еж3",
	"Entities.gmod_subway_ezh3ru1.Name": "Еж3 РУ1",
	"Entities.gmod_subway_ema508t.Name": "Ем-508Т",
	"Entities.gmod_subway_tatra_t3.Name": "Татра Т3",
	"Entities.gmod_subway_ai.Name": "Поезд с ИИ",

	"Entities.gmod_train_bogey.Name": "Тележка вагона",
	"Entities.gmod_train_couple.Name": "Сцепка",

	"Entities.gmod_track_pui.Name": "ПУИ",
	"Entities.gmod_track_mus_elektronika7.Name": "Часы \"Электроника\"",
	"Entities.gmod_mus_clock_analog.Name": "Стрелочные часы",
	"Entities.gmod_track_clock_time.Name": "Большие интервальные часы(время)",
	"Entities.gmod_track_clock_small.Name": "Маленькие интервальные часы",
	"Entities.gmod_track_clock_interval.Name": "Большие интервальные часы(интервал)",
	"Entities.gmod_track_switch.Name": "Путевая стрелка",
	"Entities.gmod_track_powermeter.Name": "Измеритель напряжения",
	"Entities.gmod_track_controller.Name": "Диспечерский пульт(не работает)",
	"Entities.gmod_track_udochka.Name": "Удочка",
	"Entities.gmod_train_spawner.Name": "Спавнер поездов",

	"Train.703.VU": "Выключатель управления",
	"Train.703.Breakers1" : "Батареи",
	"Train.703.Breakers2" : "Автоматы",
	"Train.703.RCARS" : "РЦ-АРС",
	"Train.703.Left" : "Панель помощника",
	"Train.703.Parking" : "УАВА и ручной тормоз",
	"Train.703.ASNP" : "АСНП",
	"Train.703.IGLA" : "ИГЛА",
	"Train.717.Breakers1": "Центральные автоматы",
	"Train.717.VB1": "Панель с РЦ",
	"Train.717.Breakers2": "Правые автоматы",
	"Train.717.VB2": "Нижняя панель с РЦ",
	"Train.717.UAVA": "УАВА",
	"Train.717.Pneumo": "Пневматические краны",
	"Train.717.Helpers": "Пульт помощника",
	"Train.717.Block4": "4 блок",
	"Train.717.IGLA": "ИГЛА",
	"Train.717.ASNP" : "АСНП",
	"Train.720.CameraCond": "Панель кондиционеров",
	"Train.720.CameraPPZ": "Панель поездной защиты",
	"Train.720.CameraPV": "Панель вспомогательных кнопок",
	"Train.720.CameraASNP": "АСНП",
	"Train.720.CameraVityaz": "САУ Витязь",
	"Train.720.CameraKRMH": "Кран КРМШ",
	"Train.720.CameraPVZ": "Панель вагонной защиты",
	"Train.722.Breakers": "Автоматы поездной защиты",
	"Train.722.PU2_1": "Панель кнопок",
	"Train.722.PU2_2": "Панель выключателей",
	"Train.722.Vityaz": "Экран САУ Витязь",
	"Train.722.SARMAT": "Экран БМ ЦИК САРМАТ",
	"Train.722.CabLights": "Панель освещения кабины",
	"Train.722.Route": "Установка номера маршрута",
	"Train.722.Disconnects": "Концевые краны",
	"Train.722.KRMH": "Выключатель КРМШ и РВТБ"
}
]]
