return [[
{
    "Lang": "ru",
    "Name": "Russian",

    "Entities.gmod_subway_ezh.Buttons.HelperPanel.VDLSet": "ВДЛ: Выключатель левых дверей",
    "Entities.gmod_subway_ezh.Buttons.HelperPanel.VUD2Toggle": "ВУД2: Выключатель управления дверьми",
    "Entities.gmod_subway_ezh.Buttons.Meters.!TotalVoltmeter": "Вольтметр высокого напряжения (кВ)",
    "Entities.gmod_subway_ezh.Buttons.Meters.!TotalAmpermeter": "Амперметр (А)",
    "Entities.gmod_subway_ezh.Buttons.AV2.R_RadioToggle": "+50В: Блок управления РРИ и ПНМ (Включение радиоинформатора)",
    "Entities.gmod_subway_ezh.Buttons.AV2.RSTToggle": "РСТ: Радиостанция",
    "Entities.gmod_subway_ezh.Buttons.AV2.UOSToggle": "УОС: Тумблер ограничителя скорости ",
    "Entities.gmod_subway_ezh.Buttons.AB1.AB1Set": "Переход системы АРС в режим АБ(кнопка машиниста)",
    "Entities.gmod_subway_ezh.Buttons.KAH.KAHToggle": "ТАХ: Тумблер аварийного хода ",
    "Entities.gmod_subway_ezh.Buttons.RearPneumatic.RearTrainLineIsolationToggle": "Концевой кран напорной магистрали",
    "Entities.gmod_subway_ezh.Buttons.RearPneumatic.RearBrakeLineIsolationToggle": "Концевой кран тормозной магистрали",
    "Entities.gmod_subway_ezh.Buttons.AVU.AVULight": "Лампа:Включен АВУ (Автоматический выключатель управления)",
    "Entities.gmod_subway_ezh.Buttons.AVU.OtklAVUToggle": "Отключение автоматического выключения управления (неисправность АВУ)",
    "Entities.gmod_subway_ezh.Buttons.Main.DIPonSet": "Осв. Вкл.: Включение освещения",
    "Entities.gmod_subway_ezh.Buttons.Main.DIPoffSet": "Осв. Выкл.: Выключение освещения (Звонок)",
    "Entities.gmod_subway_ezh.Buttons.Main.KDPSet": "КДП:Правые двери",
    "Entities.gmod_subway_ezh.Buttons.Main.KDLSet": "КДЛ: Левые дверей",
    "Entities.gmod_subway_ezh.Buttons.Main.DoorSelectToggle": "Крышка выбора стороны открытия дверей",
    "Entities.gmod_subway_ezh.Buttons.Main.KVTSet": "КВТ: Кнопка восприятия торможения (Отмена АРС)",
    "Entities.gmod_subway_ezh.Buttons.Main.VUSToggle": "Переключатель: Ближний свет/Дальний свет",
    "Entities.gmod_subway_ezh.Buttons.Main.ALSToggle": "Переключатель: АЛС",
    "Entities.gmod_subway_ezh.Buttons.Main.ALSFreqToggle": "Переключатель: Дешифратор (АРС 2/6 вниз, АРС 1/5 вверх)",
    "Entities.gmod_subway_ezh.Buttons.Main.ARSToggle": "Переключатель: АРС",
    "Entities.gmod_subway_ezh.Buttons.Main.KU1Toggle": "МК:Включение мотор-компрессора",
    "Entities.gmod_subway_ezh.Buttons.Main.KSNSet": "СН:Принудительное срабатывание РП на неисправном вагоне (сигнализация неисправности)",
    "Entities.gmod_subway_ezh.Buttons.Main.VozvratRPSet": "КУ9:Возврат РП",
    "Entities.gmod_subway_ezh.Buttons.Main.R_Program1Set": "Радиоинформатор: Программа 1",
    "Entities.gmod_subway_ezh.Buttons.Main.VUD1Toggle": "ВУД: Закрытие дверей",
    "Entities.gmod_subway_ezh.Buttons.Main.KRZDSet": "КРЗД: Кнопка резервного закрытия дверей",
    "Entities.gmod_subway_ezh.Buttons.AV1.VU3Toggle": "ВУ3: Освещение кабины",
    "Entities.gmod_subway_ezh.Buttons.AV1.VU2Toggle": "ВУ2: Аварийное освещение (45В)",
    "Entities.gmod_subway_ezh.Buttons.AV1.VU1Toggle": "ВУ1: Печь отопления кабины (3кВт)",
    "Entities.gmod_subway_ezh.Buttons.Back1.!RignARS": "Тональное устройство АРС",
    "Entities.gmod_subway_ezh.Buttons.Back1.!USPM": "УЛСПМ (Уствойство связи пассажир-машинист)",
    "Entities.gmod_subway_ezh.Buttons.Back1.!AK": "Регулятор давления",
    "Entities.gmod_subway_ezh.Buttons.Back1.!LVP": "Щиток с низковольтными предохранителями",
    "Entities.gmod_subway_ezh.Buttons.RC1.RC1Toggle": "РЦР: Кулачковый разъединитель цепей АРС",
    "Entities.gmod_subway_ezh.Buttons.Lamp.L_3Toggle": "Лампа: Подсветка приборов",
    "Entities.gmod_subway_ezh.Buttons.DriverValveTLDisconnect.DriverValveTLDisconnectToggle": "Кран двойной тяги напорной магистрали",
    "Entities.gmod_subway_ezh.Buttons.VU.VUToggle": "ВУ: Выключатель Управления",
    "Entities.gmod_subway_ezh.Buttons.VU.RezMKSet": "КУ15:Резервное включение мотор-компрессора",
    "Entities.gmod_subway_ezh.Buttons.VU.KRPSet": "Резервный пуск ",
    "Entities.gmod_subway_ezh.Buttons.FrontDoor.FrontDoor": "Передняя дверь",
    "Entities.gmod_subway_ezh.Buttons.AB2.AB2Set": "Переход системы АРС в режим АБ(кнопка помощника машиниста)",
    "Entities.gmod_subway_ezh.Buttons.PneumaticManometer.!LinesPressure": "Давление в магистралях (красная: тормозной, чёрная: напорной)",
    "Entities.gmod_subway_ezh.Buttons.Stopkran.EmergencyBrakeValveToggle": "Стопкран",
    "Entities.gmod_subway_ezh.Buttons.UAVAPanel.UAVAToggle": "УАВА: Универсальный Автоматический Выключатель Автостопа (отключение автостопа)",
    "Entities.gmod_subway_ezh.Buttons.UAVAPanel.UAVACToggle   ": "УАВА: Универсальный Автоматический Выключатель Автостопа (восстановление контактов)",
    "Entities.gmod_subway_ezh.Buttons.PneumaticPanels.!BrakeCylinder": "Тормозной манометр: Давление в тормозных цилиндрах (ТЦ)",
    "Entities.gmod_subway_ezh.Buttons.Battery.VBToggle": "АБ: Выключатель аккумуляторной батареи (Вспомогательные цепи низкого напряжения)",
    "Entities.gmod_subway_ezh.Buttons.FrontPneumatic.FrontBrakeLineIsolationToggle": "Концевой кран тормозной магистрали",
    "Entities.gmod_subway_ezh.Buttons.FrontPneumatic.FrontTrainLineIsolationToggle": "Концевой кран напорной магистрали",
    "Entities.gmod_subway_ezh.Buttons.ASNP.R_ASNPMenuSet": "Информатор: Меню",
    "Entities.gmod_subway_ezh.Buttons.ASNP.R_ASNPUpSet": "Информатор: Вверх",
    "Entities.gmod_subway_ezh.Buttons.ASNP.R_ASNPDownSet": "Информатор: Вниз",
    "Entities.gmod_subway_ezh.Buttons.ASNP.R_ASNPOnToggle": "Информатор: Включение",
    "Entities.gmod_subway_ezh.Buttons.Tsepi.!BatteryVoltage": "Напряжение батареи",
    "Entities.gmod_subway_ezh.Buttons.PassengerDoor1.PassengerDoor": "Дверь в кабину машиниста из салона",
    "Entities.gmod_subway_ezh.Buttons.PassengerDoor.PassengerDoor": "Дверь в кабину машиниста из салона",
    "Entities.gmod_subway_ezh.Buttons.GV.GVToggle": "Главный выключатель",
    "Entities.gmod_subway_ezh.Buttons.LampsALS.!L80": "80: Ограничение скорости 80 км/ч",
    "Entities.gmod_subway_ezh.Buttons.LampsALS.!L70": "70: Ограничение скорости 70 км/ч",
    "Entities.gmod_subway_ezh.Buttons.LampsALS.!L60": "60: Ограничение скорости 60 км/ч",
    "Entities.gmod_subway_ezh.Buttons.LampsALS.!L40": "40: Ограничение скорости 40 км/ч",
    "Entities.gmod_subway_ezh.Buttons.LampsALS.!L0": "0: Ограничение скорости 0 км/ч",
    "Entities.gmod_subway_ezh.Buttons.LampsALS.!LNF": "ОЧ: Отсутствие частоты АРС",
    "Entities.gmod_subway_ezh.Buttons.DriverValveBLDisconnect.DriverValveBLDisconnectToggle": "Кран двойной тяги тормозной магистрали",
    "Entities.gmod_subway_ezh.Buttons.CabinDoor.CabinDoor": "Дверь в кабину машиниста",
    "Entities.gmod_subway_ezh.Buttons.IGLAButtons.IGLA1USet": "ИГЛА: Первая кнопка вверх",
    "Entities.gmod_subway_ezh.Buttons.IGLAButtons.IGLA1Set": "ИГЛА: Первая кнопка",
    "Entities.gmod_subway_ezh.Buttons.IGLAButtons.IGLA1DSet": "ИГЛА: Первая кнопка вниз",
    "Entities.gmod_subway_ezh.Buttons.IGLAButtons.IGLA2USet": "ИГЛА: Вторая кнопка вверх",
    "Entities.gmod_subway_ezh.Buttons.IGLAButtons.IGLA2Set": "ИГЛА: Вторая кнопка",
    "Entities.gmod_subway_ezh.Buttons.IGLAButtons.IGLA2DSet": "ИГЛА: Вторая кнопка вниз",
    "Entities.gmod_subway_ezh.Buttons.IGLAButtons.!IGLASR": "ИГЛА: SR",
    "Entities.gmod_subway_ezh.Buttons.IGLAButtons.!IGLARX": "ИГЛА: RX",
    "Entities.gmod_subway_ezh.Buttons.IGLAButtons.!IGLAErr": "ИГЛА: Отказ",
    "Entities.gmod_subway_ezh.Buttons.IGLAButtons.!IGLAOSP": "ИГЛА: ОСП",
    "Entities.gmod_subway_ezh.Buttons.IGLAButtons.!IGLAPI": "ИГЛА: ПИ",
    "Entities.gmod_subway_ezh.Buttons.IGLAButtons.!IGLAOff": "ИГЛА: Откл",
    "Entities.gmod_subway_ezh.Buttons.Lamps.!RedRP": "РП: Красная лампа реле перегрузки",
    "Entities.gmod_subway_ezh.Buttons.Lamps.!LPU": "Секвенция (Контроль правильности включения аппаратов в режимах тяги и торможения при отсутствии высокого напряжения)",
    "Entities.gmod_subway_ezh.Buttons.Lamps.!VD": "ВД: Светодиод контроля выключения двигателей (ЛКВД)",
    "Entities.gmod_subway_ezh.Buttons.Lamps.!KT": "КТ: Контроль тормоза(торможение эффективно)",
    "Entities.gmod_subway_ezh.Buttons.Lamps.!AB": "Зеленая AБ: Следование по участку с автоблокировкой (некодируемый участок).",
    "Entities.gmod_subway_ezh.Buttons.Lamps.!Doors": "Двери: Сигнализация дверей поезда",
    "Entities.gmod_subway_ezh.Buttons.Lamps.!LN": "ЛН: Светодиод установленного направления движения для данного участка",
    "Entities.gmod_subway_ezh.Buttons.Lamps.!Sbor": "Лампа СБОР: Ошибка сбора электрической схемы (Сигнализация неисправности)",
    "Entities.gmod_subway_ezh.Buttons.EPKDisconnect.EPKToggle": "Кран ЭПК",
    "Entities.gmod_subway_ezh.Buttons.AVMain.AV8BToggle": "АВ-8Б: Автоматическй выключатель (Вспомогательные цепи высокого напряжения)",
    "Entities.gmod_subway_ezh.Buttons.KRR.KRRToggle": "KРР: Кнопка разворота реверсоров",
    "Entities.gmod_subway_ezh.Buttons.ParkingBrake.ParkingBrakeLeft": "Поворот колеса ручного тормоза",
    "Entities.gmod_subway_ezh.Buttons.ParkingBrake.ParkingBrakeRight": "Поворот колеса ручного тормоза",
    "Entities.gmod_subway_ezh.Buttons.AirDistributor.AirDistributorDisconnectToggle": "Выключение воздухораспределителя",



    "Entities.gmod_subway_ezh1.Buttons.Stopkran.EmergencyBrakeValveToggle": "Стопкран",
    "Entities.gmod_subway_ezh1.Buttons.DriverValveBLTLDisconnect.DriverValveBLDisconnectToggle": "Кран двойной тяги тормозной магистрали",
    "Entities.gmod_subway_ezh1.Buttons.DriverValveBLTLDisconnect.DriverValveTLDisconnectToggle": "Кран двойной тяги напорной магистрали",
    "Entities.gmod_subway_ezh1.Buttons.PneumaticPanels.!CylinderPressure": "Тормозной манометр: Давление в тормозных цилиндрах (ТЦ)",
    "Entities.gmod_subway_ezh1.Buttons.Battery.VBToggle": "АБ: Выключатель аккумуляторной батареи (Вспомогательные цепи низкого напряжения)",
    "Entities.gmod_subway_ezh1.Buttons.Meters.!TotalVoltmerer": "Вольтметр высокого напряжения (кВ)",
    "Entities.gmod_subway_ezh1.Buttons.Meters.!TotalAmpermeter": "Амперметр (А)",
    "Entities.gmod_subway_ezh1.Buttons.FrontPneumatic.FrontBrakeLineIsolationToggle": "Концевой кран тормозной магистрали",
    "Entities.gmod_subway_ezh1.Buttons.FrontPneumatic.FrontTrainLineIsolationToggle": "Концевой кран напорной магистрали",
    "Entities.gmod_subway_ezh1.Buttons.RearDoor.RearDoor": "Дверь из салона",
    "Entities.gmod_subway_ezh1.Buttons.Tsepi.!BatteryVoltage": "Напряжение цепей управления",
    "Entities.gmod_subway_ezh1.Buttons.RearPneumatic.RearTrainLineIsolationToggle": "Концевой кран тормозной магистрали",
    "Entities.gmod_subway_ezh1.Buttons.RearPneumatic.RearBrakeLineIsolationToggle": "Концевой кран напорной магистрали",
    "Entities.gmod_subway_ezh1.Buttons.PassengerDoor.PassengerDoor": "Дверь из салона",
    "Entities.gmod_subway_ezh1.Buttons.Back2.!HVFuses": "Блок предохранителей",
    "Entities.gmod_subway_ezh1.Buttons.Back2.!Relays": "Ящик с аппаратами для подзаряда аккумуляторной батареи и дверной воздухораспределитель",
    "Entities.gmod_subway_ezh1.Buttons.Back2.!Heater": "Печка",
    "Entities.gmod_subway_ezh1.Buttons.Main.RedRP": "Красная РП: Красная лампа реле перегрузки",
    "Entities.gmod_subway_ezh1.Buttons.Main.GreenRP": "Зеленая РП: Зелёная лампа реле перегрузки (Сигнализация перегрузки)",
    "Entities.gmod_subway_ezh1.Buttons.Main.SD": "Синяя лампа СД: Сигнализация дверей поезда",
    "Entities.gmod_subway_ezh1.Buttons.Main.DIPonSet": "КУ4:Включение освещения",
    "Entities.gmod_subway_ezh1.Buttons.Main.DIPoffSet": "КУ5:Отключение освещения",
    "Entities.gmod_subway_ezh1.Buttons.Main.VozvratRPSet": "Переключатель: Возврат Реле Перегрузки",
    "Entities.gmod_subway_ezh1.Buttons.Main.KSNSet": "Переключатель: Сигнализация неисправности (Срабатывание РП на неисправном вагоне)",
    "Entities.gmod_subway_ezh1.Buttons.Main.KDPSet": "КДП:Правые двери",
    "Entities.gmod_subway_ezh1.Buttons.Main.KRZDSet": "КРЗД: Кнопка резервного закрытия дверей",
    "Entities.gmod_subway_ezh1.Buttons.Main.KDLSet": "КУ12: Открытие левых дверей",
    "Entities.gmod_subway_ezh1.Buttons.Main.KU1Toggle": "Переключатель:Включение мотор-компрессора",
    "Entities.gmod_subway_ezh1.Buttons.Main.VUD1Toggle": "Переключатель: Закрытие дверей",
    "Entities.gmod_subway_ezh1.Buttons.AV1.VU3Toggle": "ВУ3: Освещение кабины",
    "Entities.gmod_subway_ezh1.Buttons.AV1.VU2Toggle": "ВУ2: Аварийное освещение (45В)",
    "Entities.gmod_subway_ezh1.Buttons.AV1.VU1Toggle": "ВУ1: Печь отопления кабины (3кВт)",
    "Entities.gmod_subway_ezh1.Buttons.AVMain.AV8BToggle": "АВ-8Б: Автоматическй выключатель (Вспомогательные цепи высокого напряжения)",
    "Entities.gmod_subway_ezh1.Buttons.CabinDoor.CabinDoor1": "Дверь в кабину машиниста",
    "Entities.gmod_subway_ezh1.Buttons.Front.FrontDoor": "Передняя дверь",
    "Entities.gmod_subway_ezh1.Buttons.PassengerDoor1.PassengerDoor": "Дверь из салона",
    "Entities.gmod_subway_ezh1.Buttons.AirDistributor.AirDistributorDisconnectToggle": "Выключение воздухораспределителя",
    "Entities.gmod_subway_ezh1.Buttons.GV.GVToggle": "Главный выключатель",
    "Entities.gmod_subway_ezh1.Buttons.VU.VUToggle": "ВУ: Выключатель управления",
    "Entities.gmod_subway_ezh1.Buttons.HelperPanel.VUD2Toggle": "ВУД2: Выключатель управления дверьми",
    "Entities.gmod_subway_ezh1.Buttons.HelperPanel.VDLSet": "ВДЛ: Выключатель левых дверей",
    "Entities.gmod_subway_ezh1.Buttons.ParkingBrake.ParkingBrakeLeft": "Поворот колеса ручного тормоза",
    "Entities.gmod_subway_ezh1.Buttons.ParkingBrake.ParkingBrakeRight": "Поворот колеса ручного тормоза",
    "Entities.gmod_subway_ezh1.Buttons.PneumaticManometer.!LinesPressure": "Давление в магистралях (красная: тормозной, чёрная: напорной)"
}
]]
