return [[
{
  "Lang": "ru",
  "Name": "Russian",


  "Entities.gmod_subway_ezh3.Buttons.Stopkran.EmergencyBrakeValveToggle": "Стопкран",
  "Entities.gmod_subway_ezh3.Buttons.Back.BackDoor": "Задняя дверь",
  "Entities.gmod_subway_ezh3.Buttons.DriverValveBLTLDisconnect.DriverValveBLDisconnectToggle": "Кран двойной тяги тормозной магистрали",
  "Entities.gmod_subway_ezh3.Buttons.DriverValveBLTLDisconnect.DriverValveTLDisconnectToggle": "Кран двойной тяги напорной магистрали",
  "Entities.gmod_subway_ezh3.Buttons.Battery.VBToggle": "АБ: Выключатель аккумуляторной батареи (Вспомогательные цепи низкого напряжения)",
  "Entities.gmod_subway_ezh3.Buttons.FrontPneumatic.FrontBrakeLineIsolationToggle": "Концевой кран тормозной магистрали",
  "Entities.gmod_subway_ezh3.Buttons.FrontPneumatic.FrontTrainLineIsolationToggle": "Концевой кран напорной магистрали",
  "Entities.gmod_subway_ezh3.Buttons.ASNP.R_ASNPMenuSet": "Информатор: Меню",
  "Entities.gmod_subway_ezh3.Buttons.ASNP.R_ASNPUpSet": "Информатор: Вверх",
  "Entities.gmod_subway_ezh3.Buttons.ASNP.R_ASNPDownSet": "Информатор: Вниз",
  "Entities.gmod_subway_ezh3.Buttons.ASNP.R_ASNPOnToggle": "Информатор: Включение",
  "Entities.gmod_subway_ezh3.Buttons.PassengerDoor1.PassengerDoor": "Дверь в кабину машиниста из салона",
  "Entities.gmod_subway_ezh3.Buttons.PassengerDoor.PassengerDoor": "Дверь в кабину машиниста из салона",
  "Entities.gmod_subway_ezh3.Buttons.CabinDoor.CabinDoor": "Дверь в кабину машиниста",
  "Entities.gmod_subway_ezh3.Buttons.Front.FrontDoor": "Передняя дверь",
  "Entities.gmod_subway_ezh3.Buttons.GV.GVToggle": "Главный выключатель",
  "Entities.gmod_subway_ezh3.Buttons.RearPneumatic.RearTrainLineIsolationToggle": "Концевой кран напорной магистрали",
  "Entities.gmod_subway_ezh3.Buttons.RearPneumatic.RearBrakeLineIsolationToggle": "Концевой кран тормозной магистрали",
  "Entities.gmod_subway_ezh3.Buttons.Panel.!OCH": "ОЧ: Лампа отсутствия частоты (0км\\ч)",
  "Entities.gmod_subway_ezh3.Buttons.Panel.!0": "0: Лампа ограничения в 0км\\ч",
  "Entities.gmod_subway_ezh3.Buttons.Panel.!40": "40: Лампа ограничения в 40км\\ч",
  "Entities.gmod_subway_ezh3.Buttons.Panel.!60": "60: Лампа ограничения в 60км\\ч",
  "Entities.gmod_subway_ezh3.Buttons.Panel.!70": "70: Лампа ограничения в 70км\\ч",
  "Entities.gmod_subway_ezh3.Buttons.Panel.!80": "80: Лампа ограничения в 80км\\ч",
  "Entities.gmod_subway_ezh3.Buttons.Panel.!Speedometer": "Индикатор скорости (км/ч)",
  "Entities.gmod_subway_ezh3.Buttons.Panel.!TotalAmpermeter": "Силовой амперметр тяговых электродвигателей (А)",
  "Entities.gmod_subway_ezh3.Buttons.Panel.!TotalVoltmeter": "Напряжение силовой сети (кВ)",
  "Entities.gmod_subway_ezh3.Buttons.Panel.!BatteryVoltage": "Напряжение аккумуляторной батареи управления (В)",
  "Entities.gmod_subway_ezh3.Buttons.Panel.!BrakeCylinder": "Давление в тормозных цилиндрах (ТЦ)",
  "Entities.gmod_subway_ezh3.Buttons.Panel.!LinesPressure": "Давление в магистралях (красная: тормозной, чёрная: напорной)",
  "Entities.gmod_subway_ezh3.Buttons.Main.KU1Toggle": "ВМК: Включение мотор-компрессора",
  "Entities.gmod_subway_ezh3.Buttons.Main.SAMM1Set": "САММ:Выключение тяги",
  "Entities.gmod_subway_ezh3.Buttons.Main.SAMM2Set": "САММ:Пуск",
  "Entities.gmod_subway_ezh3.Buttons.Main.SAMM3Set": "САММ:Сброс",
  "Entities.gmod_subway_ezh3.Buttons.Main.SAMMSignal1": "Лампа:Ход-Тормоз",
  "Entities.gmod_subway_ezh3.Buttons.Main.SAMMSignal2": "Лампа: Рабочее состояние САММ",
  "Entities.gmod_subway_ezh3.Buttons.Main.SAMMSignal3": "Лампа:Включен исполнительный блок САММ",
  "Entities.gmod_subway_ezh3.Buttons.Main.SAMMOnToggle": "САММ:Включение системы автоведения",
  "Entities.gmod_subway_ezh3.Buttons.Main.SAMMBlokToggle": "САММ:Исполнительный блок",
  "Entities.gmod_subway_ezh3.Buttons.Main.SAMMCommand3Set": "САММ:Ход2",
  "Entities.gmod_subway_ezh3.Buttons.Main.SAMMCommand2Set": "САММ:Нагон",
  "Entities.gmod_subway_ezh3.Buttons.Main.SAMMCommand1Set": "САММ:Разрешение",
  "Entities.gmod_subway_ezh3.Buttons.Main.KSNSet": "КСН: Кнопка сигнализации неисправности",
  "Entities.gmod_subway_ezh3.Buttons.Main.R_Program1Set": "Программа 1",
  "Entities.gmod_subway_ezh3.Buttons.Main.R_Program2Set": "Программа 2",
  "Entities.gmod_subway_ezh3.Buttons.Main.VUSToggle": "Переключатель: Ближний свет/Дальний свет",
  "Entities.gmod_subway_ezh3.Buttons.Main.L_3Toggle": "Переключатель: Подсветка приборов",
  "Entities.gmod_subway_ezh3.Buttons.Main.VAHToggle": "Переключатель: Аварийный Ход",
  "Entities.gmod_subway_ezh3.Buttons.Main.DIPonSet": "Осв. Вкл.: Включение освещения",
  "Entities.gmod_subway_ezh3.Buttons.Main.DIPoffSet": "Осв. Выкл.: Выключение освещения",
  "Entities.gmod_subway_ezh3.Buttons.Main.KSDSet": "КСД: Сигнализация дверей",
  "Entities.gmod_subway_ezh3.Buttons.Main.KVTSet": "КВТ: Кнопка Восприятия Торможения",
  "Entities.gmod_subway_ezh3.Buttons.Main.KBSet": "КБ: Кнопка Бдительности",
  "Entities.gmod_subway_ezh3.Buttons.Main.KBLamp": "Лампа: Вращение РК",
  "Entities.gmod_subway_ezh3.Buttons.Main.ARSToggle": "АРС: Включение системы автоматического регулирования скорости",
  "Entities.gmod_subway_ezh3.Buttons.Main.R_UNchToggle": "УНЧ: Усилитель низких частот",
  "Entities.gmod_subway_ezh3.Buttons.Main.VUD1Toggle": "ВУД: Выключатель управления дверьми",
  "Entities.gmod_subway_ezh3.Buttons.Main.R_RadioToggle": "Радиоинформатор (встроеный)",
  "Entities.gmod_subway_ezh3.Buttons.Main.ALSToggle": "АЛС: Включение системы автоматической локомотивной сигнализации",
  "Entities.gmod_subway_ezh3.Buttons.Main.VozvratRPSet": "КВРП: Возврат реле перегрузки",
  "Entities.gmod_subway_ezh3.Buttons.Main.RingSet": "Звонок",
  "Entities.gmod_subway_ezh3.Buttons.Main.L_2Toggle": "Переключатель: Освещение кабины",
  "Entities.gmod_subway_ezh3.Buttons.Main.KRZDSet": "КРЗД: Кнопка резервного закрытия дверей",
  "Entities.gmod_subway_ezh3.Buttons.Main.KDPSet": "КДП: Кнопка правых дверей",
  "Entities.gmod_subway_ezh3.Buttons.Main.KDLSet": "КДЛ: Кнопка левых дверей",
  "Entities.gmod_subway_ezh3.Buttons.Main.KAHSet": "KAH",
  "Entities.gmod_subway_ezh3.Buttons.Main.RezMKSet": "Резервное включение мотор-компрессора",
  "Entities.gmod_subway_ezh3.Buttons.Main.KRPSet": "КРП: Кнопка резервного пуска",
  "Entities.gmod_subway_ezh3.Buttons.Main.RSTToggle": "ВПР: Включение поездной радиосвязи",
  "Entities.gmod_subway_ezh3.Buttons.Main.R_GToggle": "Громкоговоритель",
  "Entities.gmod_subway_ezh3.Buttons.Main.Custom2Set": "Незаведенный тумблер",
  "Entities.gmod_subway_ezh3.Buttons.Main.Custom3Set": "Незаведенный тумблер",
  "Entities.gmod_subway_ezh3.Buttons.Main.ASNPPlay": "Индикатор работы программы информатора",
  "Entities.gmod_subway_ezh3.Buttons.AV1.VU3Toggle": "ВУ3: Освещение кабины\n",
  "Entities.gmod_subway_ezh3.Buttons.AV1.VU2Toggle": "ВУ2: Аварийное освещение (45В)\n",
  "Entities.gmod_subway_ezh3.Buttons.AV1.VU1Toggle": "ВУ1: Печь отопления кабины (3кВт)\n",
  "Entities.gmod_subway_ezh3.Buttons.AVMain.AV8BToggle": "АВ-8Б: Автоматическй выключатель (Вспомогательные цепи высокого напряжения)\n",
  "Entities.gmod_subway_ezh3.Buttons.RC1.RC1Toggle": "РЦ-АРС: Разъединитель цепей АРС",
  "Entities.gmod_subway_ezh3.Buttons.UAVAPanel.UAVAToggle": "УАВА: Универсальный Автоматический Выключатель Автостопа (отключение автостопа)",
  "Entities.gmod_subway_ezh3.Buttons.UAVAPanel.UAVACToggle   ": "УАВА: Универсальный Автоматический Выключатель Автостопа (восстановление контактов)",
  "Entities.gmod_subway_ezh3.Buttons.VUHelper.VUToggle": "ВУ: Выключатель управления",
  "Entities.gmod_subway_ezh3.Buttons.HelperPanel.VDLSet": "ВДЛ: Выключатель левых дверей",
  "Entities.gmod_subway_ezh3.Buttons.HelperPanel.VUD2Toggle": "ВУД2: Выключатель управления дверьми",
  "Entities.gmod_subway_ezh3.Buttons.EPKDisconnect.EPKToggle": "Кран ЭПК",
  "Entities.gmod_subway_ezh3.Buttons.VU.VUToggle": "ВУ: Выключатель управления",
  "Entities.gmod_subway_ezh3.Buttons.ParkingBrake.ParkingBrakeLeft": "Поворот колеса ручного тормоза",
  "Entities.gmod_subway_ezh3.Buttons.ParkingBrake.ParkingBrakeRight": "Поворот колеса ручного тормоза",
  "Entities.gmod_subway_ezh3.Buttons.AirDistributor.AirDistributorDisconnectToggle": "Выключение воздухораспределителя",

  "Entities.gmod_subway_em508t.Buttons.Stopkran.EmergencyBrakeValveToggle": "Стопкран",
  "Entities.gmod_subway_em508t.Buttons.Battery.VBToggle": "АБ: Выключатель аккумуляторной батареи (Вспомогательные цепи низкого напряжения)",
  "Entities.gmod_subway_em508t.Buttons.FrontPneumatic.FrontBrakeLineIsolationToggle": "Концевой кран тормозной магистрали",
  "Entities.gmod_subway_em508t.Buttons.FrontPneumatic.FrontTrainLineIsolationToggle": "Концевой кран напорной магистрали",
  "Entities.gmod_subway_em508t.Buttons.GV.GVToggle": "Главный выключатель",
  "Entities.gmod_subway_em508t.Buttons.RearPneumatic.RearTrainLineIsolationToggle": "Концевой кран тормозной магистрали",
  "Entities.gmod_subway_em508t.Buttons.RearPneumatic.RearBrakeLineIsolationToggle": "Концевой кран напорной магистрали",
  "Entities.gmod_subway_em508t.Buttons.RearDoor.RearDoor": "Дверь из салона",
  "Entities.gmod_subway_em508t.Buttons.Back2.!HVFuse": "Блок высоковольтных предохранителей",
  "Entities.gmod_subway_em508t.Buttons.Back2.!Relays": "Ящик с аппаратами для подзаряда аккумуляторной батареи и дверной воздухораспределитель",
  "Entities.gmod_subway_em508t.Buttons.Back2.!Heater": "Печка",
  "Entities.gmod_subway_em508t.Buttons.Front.FrontDoor": "Передняя дверь",
  "Entities.gmod_subway_em508t.Buttons.AV1.VU3Toggle": "ВУ3: Освещение кабины\n",
  "Entities.gmod_subway_em508t.Buttons.AV1.VU2Toggle": "ВУ2: Аварийное освещение (45В)\n",
  "Entities.gmod_subway_em508t.Buttons.AV1.VU1Toggle": "ВУ1: Печь отопления кабины (3кВт)\n",
  "Entities.gmod_subway_em508t.Buttons.ParkingBrake.ParkingBrakeLeft": "Поворот колеса ручного тормоза",
  "Entities.gmod_subway_em508t.Buttons.ParkingBrake.ParkingBrakeRight": "Поворот колеса ручного тормоза",
  "Entities.gmod_subway_em508t.Buttons.CabinDoor.CabinDoor1": "Дверь в кабину машиниста",
  "Entities.gmod_subway_em508t.Buttons.PassengerDoor.PassengerDoor": "Дверь из салона",
  "Entities.gmod_subway_em508t.Buttons.PassengerDoor1.PassengerDoor": "Дверь из салона",
  "Entities.gmod_subway_em508t.Buttons.Main.!RedRP": "Красная РП: Красная лампа реле перегрузки",
  "Entities.gmod_subway_em508t.Buttons.Main.!GreenRP": "Зеленая РП: Зелёная лампа реле перегрузки (Сигнализация перегрузки)",
  "Entities.gmod_subway_em508t.Buttons.Main.!SD": "Синяя лампа СД: Сигнализация дверей поезда",
  "Entities.gmod_subway_em508t.Buttons.Main.KDLSet": "Переключатель: Открытие левых дверей",
  "Entities.gmod_subway_em508t.Buttons.Main.KSDSet": "Переключатель: Сигнализация (Сигнализация дверей)",
  "Entities.gmod_subway_em508t.Buttons.Main.VozvratRPSet": "Переключатель: Возврат Реле Перегрузки",
  "Entities.gmod_subway_em508t.Buttons.Main.KSNSet": "Переключатель: Сигнализация неисправности (Срабатывание РП на неисправном вагоне)",
  "Entities.gmod_subway_em508t.Buttons.Main.VUD1Toggle": "Переключатель: Закрытие дверей",
  "Entities.gmod_subway_em508t.Buttons.Main.KU1Toggle": "Переключатель: Включение Мотор-компрессора",
  "Entities.gmod_subway_em508t.Buttons.Main.DIPonSet": "КУ4:Включение освещения",
  "Entities.gmod_subway_em508t.Buttons.Main.DIPoffSet": "КУ5:Отключение освещения",
  "Entities.gmod_subway_em508t.Buttons.Main.RezMKSet": "КУ5:Отключение освещения",
  "Entities.gmod_subway_em508t.Buttons.Main.KDPSet": "КДП:Правые двери",
  "Entities.gmod_subway_em508t.Buttons.Main.KRZDSet": "КУ10: Кнопка резервного закрытия дверей",
  "Entities.gmod_subway_em508t.Buttons.AVMain.AV8BToggle": "АВ-8Б: Автоматическй выключатель (Вспомогательные цепи высокого напряжения)\n",
  "Entities.gmod_subway_em508t.Buttons.VU.VUToggle": "ВУ: Выключатель управления",
  "Entities.gmod_subway_em508t.Buttons.VU.!Voltage": "Напряжение цепей управления",
  "Entities.gmod_subway_em508t.Buttons.HelperPanel.VUD2Toggle": "ВУД2: Выключатель управления дверьми",
  "Entities.gmod_subway_em508t.Buttons.HelperPanel.VDLSet": "ВДЛ: Выключатель левых дверей",
  "Entities.gmod_subway_em508t.Buttons.DriverValveBLTLDisconnect.DriverValveBLDisconnectToggle": "Кран двойной тяги тормозной магистрали",
  "Entities.gmod_subway_em508t.Buttons.DriverValveBLTLDisconnect.DriverValveTLDisconnectToggle": "Кран двойной тяги напорной магистрали",
  "Entities.gmod_subway_em508t.Buttons.AirDistributor.AirDistributorDisconnectToggle": "Выключение воздухораспределителя",


  "Entities.gmod_subway_ezh3.Buttons.Main.Custom1Toggle": "Незаведенный тумблер",
  "Entities.gmod_subway_ezh3.Buttons.IGLAButtons.IGLA1USet": "ИГЛА: Первая кнопка вверх",
  "Entities.gmod_subway_ezh3.Buttons.IGLAButtons.IGLA1Set": "ИГЛА: Первая кнопка",
  "Entities.gmod_subway_ezh3.Buttons.IGLAButtons.IGLA1DSet": "ИГЛА: Первая кнопка вниз",
  "Entities.gmod_subway_ezh3.Buttons.IGLAButtons.IGLA2USet": "ИГЛА: Вторая кнопка вверх",
  "Entities.gmod_subway_ezh3.Buttons.IGLAButtons.IGLA2Set": "ИГЛА: Вторая кнопка",
  "Entities.gmod_subway_ezh3.Buttons.IGLAButtons.IGLA2DSet": "ИГЛА: Вторая кнопка вниз",
  "Entities.gmod_subway_ezh3.Buttons.IGLAButtons.!IGLASR": "ИГЛА: SR",
  "Entities.gmod_subway_ezh3.Buttons.IGLAButtons.!IGLARX": "ИГЛА: RX",
  "Entities.gmod_subway_ezh3.Buttons.IGLAButtons.!IGLAErr": "ИГЛА: Отказ",
  "Entities.gmod_subway_ezh3.Buttons.IGLAButtons.!IGLAOSP": "ИГЛА: ОСП(Сработка огнетушителей)",
  "Entities.gmod_subway_ezh3.Buttons.IGLAButtons.!IGLAPI": "ИГЛА: ПИ(Пожар)",
  "Entities.gmod_subway_ezh3.Buttons.IGLAButtons.!IGLAOff": "ИГЛА: Откл",

  "Entities.gmod_subway_ezh3.Buttons.Back2.!HVHuse": "Блок высоковольтных предохранителей",
  "Entities.gmod_subway_ezh3.Buttons.Back2.!AKBCharge": "Ящик с аппаратами для подзаряда аккумуляторной батареи и дверной воздухораспределитель",
  "Entities.gmod_subway_ezh3.Buttons.Back2.!Heater": "Печка"
}
]]
