return [[
{
  "Lang": "ru",
  "Name": "Russian",


  "Entities.gmod_subway_81-722.Buttons.StopKran.UAVAToggle": "Выключатель автостопа",
  "Entities.gmod_subway_81-722.Buttons.StopKran.EmergencyBrakeValveToggle": "Стопкран",
  "Entities.gmod_subway_81-722.Buttons.PU2.ARSToggle": "АРС: Автоматическое регулирвоание скорости",
  "Entities.gmod_subway_81-722.Buttons.PU2.ALSToggle": "АЛС:Автоматическая локомотивная сигнализация",
  "Entities.gmod_subway_81-722.Buttons.PU2.GlassWasherSet": "Омыватель стекла",
  "Entities.gmod_subway_81-722.Buttons.PU2.GlassCleaner+": "Стеклоочиститель(вверх)",
  "Entities.gmod_subway_81-722.Buttons.PU2.GlassCleaner-": "Стеклоочиститель(вниз)",
  "Entities.gmod_subway_81-722.Buttons.PU2.EmergencyBrakeTPlusKToggle": "Крышка кнопки Аварийный тормоз \"Т+\"",
  "Entities.gmod_subway_81-722.Buttons.PU2.EmergencyBrakeTPlusSet": "Аварийный тормоз \"Т+\"",
  "Entities.gmod_subway_81-722.Buttons.PU2.EmergencyBrakeToggle": "Экстренное торможение",
  "Entities.gmod_subway_81-722.Buttons.PU2.VigilanceSet": "Бдительность",
  "Entities.gmod_subway_81-722.Buttons.PU2.Headlights+": "Фары(вверх)",
  "Entities.gmod_subway_81-722.Buttons.PU2.Headlights-": "Фары(вниз)",
  "Entities.gmod_subway_81-722.Buttons.PU2.DoorSelectToggle": "Выбор стороны дверей",
  "Entities.gmod_subway_81-722.Buttons.PU2.DoorClose+": "Закрытие дверей(вверх)",
  "Entities.gmod_subway_81-722.Buttons.PU2.DoorClose-": "Закрытие дверей(вниз)",
  "Entities.gmod_subway_81-722.Buttons.PU2.DoorRightSet": "Открытие правых дверей",
  "Entities.gmod_subway_81-722.Buttons.SarmatButtons.SarmatUpSet": "САРМАТ: Вверх",
  "Entities.gmod_subway_81-722.Buttons.SarmatButtons.SarmatDownSet": "САРМАТ: Вниз",
  "Entities.gmod_subway_81-722.Buttons.SarmatButtons.SarmatEnterSet": "САРМАТ: Enter",
  "Entities.gmod_subway_81-722.Buttons.SarmatButtons.SarmatEscSet": "САРМАТ: Esc",
  "Entities.gmod_subway_81-722.Buttons.SarmatButtons.SarmatF1Set": "САРМАТ: F1",
  "Entities.gmod_subway_81-722.Buttons.SarmatButtons.SarmatF2Set": "САРМАТ: F2",
  "Entities.gmod_subway_81-722.Buttons.SarmatButtons.SarmatF3Set": "САРМАТ: F3",
  "Entities.gmod_subway_81-722.Buttons.SarmatButtons.SarmatF4Set": "САРМАТ: F4",
  "Entities.gmod_subway_81-722.Buttons.HelperLamps.!LRD": "ЛРД: Лампа разрешающая движение(разрешение движения под 0)",
  "Entities.gmod_subway_81-722.Buttons.HelperLamps.!LPT": "ЛПТ: Лампа включение пневмотормоза",
  "Entities.gmod_subway_81-722.Buttons.HelperLamps.!RS": "Р/С: Лампа аварийного питания радиостанции",
  "Entities.gmod_subway_81-722.Buttons.HelperLamps.!AVS": "АВС Лампа низкого давления ТМ",
  "Entities.gmod_subway_81-722.Buttons.HelperLamps.!LSD": "ЛСД: Лампа сигнализации закрытия дверей",
  "Entities.gmod_subway_81-722.Buttons.HelperLamps.!RU": "РУ: Лампа выключения Реле Управления",
  "Entities.gmod_subway_81-722.Buttons.HelperLamps.!04": "НЧ: Лампа отсутствия частоты (0км\\ч)",
  "Entities.gmod_subway_81-722.Buttons.HelperLamps.!00": "0: Лампа ограничения в 0км\\ч",
  "Entities.gmod_subway_81-722.Buttons.HelperLamps.!40": "40: Лампа ограничения в 40км\\ч",
  "Entities.gmod_subway_81-722.Buttons.HelperLamps.!60": "60 Лампа ограничения в 60км\\ч",
  "Entities.gmod_subway_81-722.Buttons.HelperLamps.!70": "70: Лампа ограничения в 70км\\ч",
  "Entities.gmod_subway_81-722.Buttons.HelperLamps.!80": "80: Лампа ограничения в 80км\\ч",
  "Entities.gmod_subway_81-722.Buttons.CabinDoorL.CabinDoorLeft": "Дверь в кабину машиниста",
  "Entities.gmod_subway_81-722.Buttons.BMP.SarmatPathSet": "САРМАТ: Путь",
  "Entities.gmod_subway_81-722.Buttons.BMP.SarmatLineSet": "САРМАТ: Линия",
  "Entities.gmod_subway_81-722.Buttons.BMP.SarmatZeroSet": "САРМАТ: >0<",
  "Entities.gmod_subway_81-722.Buttons.BMP.SarmatStartSet": "САРМАТ: Пуск",
  "Entities.gmod_subway_81-722.Buttons.BTO.K29Toggle": "КРМШ",
  "Entities.gmod_subway_81-722.Buttons.BTO.K9Toggle": "РВТБ",
  "Entities.gmod_subway_81-722.Buttons.RearPneumatic.RearBrakeLineIsolationToggle": "Концевой кран тормозной магистрали",
  "Entities.gmod_subway_81-722.Buttons.RearPneumatic.RearTrainLineIsolationToggle": "Концевой кран напорной магистрали",
  "Entities.gmod_subway_81-722.Buttons.RouteNumberSet.RouteNumber1Set": "Первая цифра",
  "Entities.gmod_subway_81-722.Buttons.RouteNumberSet.RouteNumber2Set": "Вторая цифра",
  "Entities.gmod_subway_81-722.Buttons.RouteNumberSet.RouteNumber3Set": "Третья цифра",
  "Entities.gmod_subway_81-722.Buttons.RearDoor.RearDoor": "Задняя дверь",
  "Entities.gmod_subway_81-722.Buttons.Lighting.CabinLightToggle": "Освещение кабины",
  "Entities.gmod_subway_81-722.Buttons.Lighting.CabinLight-": "Освещение кабины(влево)",
  "Entities.gmod_subway_81-722.Buttons.Lighting.CabinLight+": "Освещение кабины(вправо)",
  "Entities.gmod_subway_81-722.Buttons.Lighting.PanelLightToggle": "Освещение пульта",
  "Entities.gmod_subway_81-722.Buttons.PassengerDoor.PassengerDoor": "Дверь в кабину машиниста из салона",
  "Entities.gmod_subway_81-722.Buttons.PU1.MirrorHeatingSet": "Отопление зеркал",
  "Entities.gmod_subway_81-722.Buttons.PU1.DoorLeft2Set": "Двери левые",
  "Entities.gmod_subway_81-722.Buttons.PU1.DoorBackSet": "Открытие правых дверей хвостового вагона",
  "Entities.gmod_subway_81-722.Buttons.PU1.EmergencyDriveSet": "Аварийный ход",
  "Entities.gmod_subway_81-722.Buttons.PU1.MicrophoneSet": "Микрофон",
  "Entities.gmod_subway_81-722.Buttons.PU1.DoorLeft1Set": "Двери левые",
  "Entities.gmod_subway_81-722.Buttons.PPZ.SF1Toggle": "SF1:Бортовая сеть (управление)",
  "Entities.gmod_subway_81-722.Buttons.PPZ.SF2Toggle": "SF2:Активная кабина",
  "Entities.gmod_subway_81-722.Buttons.PPZ.SF3Toggle": "SF3:Управление основное",
  "Entities.gmod_subway_81-722.Buttons.PPZ.SF4Toggle": "SF4:Управление резервное",
  "Entities.gmod_subway_81-722.Buttons.PPZ.SF5Toggle": "SF5:Управление РВТБ",
  "Entities.gmod_subway_81-722.Buttons.PPZ.SF6Toggle": "SF6:Питание крана машиниста",
  "Entities.gmod_subway_81-722.Buttons.PPZ.SF7Toggle": "SF7:Двери(управление)",
  "Entities.gmod_subway_81-722.Buttons.PPZ.SF8Toggle": "SF8:БАРС 1",
  "Entities.gmod_subway_81-722.Buttons.PPZ.SF9Toggle": "SF9:БАРС 2",
  "Entities.gmod_subway_81-722.Buttons.PPZ.SF00Toggle": "SF00:",
  "Entities.gmod_subway_81-722.Buttons.PPZ.SF01Toggle": "SF01:",
  "Entities.gmod_subway_81-722.Buttons.PPZ.SF10Toggle": "SF10:БРПИ-М1",
  "Entities.gmod_subway_81-722.Buttons.PPZ.SF11Toggle": "SF11:БРПИ-М2",
  "Entities.gmod_subway_81-722.Buttons.PPZ.SF12Toggle": "SF12:Пожарная система",
  "Entities.gmod_subway_81-722.Buttons.PPZ.SF13Toggle": "SF13:Токоприёмник, короткозамыкатель",
  "Entities.gmod_subway_81-722.Buttons.PPZ.SF02Toggle": "SF02:",
  "Entities.gmod_subway_81-722.Buttons.PPZ.SF14Toggle": "SF14:Радиосвязь 1",
  "Entities.gmod_subway_81-722.Buttons.PPZ.SF15Toggle": "SF15:Радиосвязь 2",
  "Entities.gmod_subway_81-722.Buttons.PPZ.SF16Toggle": "SF16:ЦИС 1",
  "Entities.gmod_subway_81-722.Buttons.PPZ.SF17Toggle": "SF17:ЦИС 2",
  "Entities.gmod_subway_81-722.Buttons.PPZ.SF18Toggle": "SF18:ЦИС 3",
  "Entities.gmod_subway_81-722.Buttons.PPZ.SF19Toggle": "SF19:БУКП, УПИ",
  "Entities.gmod_subway_81-722.Buttons.PPZ.SF20Toggle": "SF20:Монитор",
  "Entities.gmod_subway_81-722.Buttons.PPZ.SF21Toggle": "SF21:Ориентация",
  "Entities.gmod_subway_81-722.Buttons.PPZ.SF22Toggle": "SF22:Габаритные огни АБ",
  "Entities.gmod_subway_81-722.Buttons.PPZ.SF23Toggle": "SF23:Фары, габаритные огни",
  "Entities.gmod_subway_81-722.Buttons.PPZ.SF24Toggle": "SF24:СОСД",
  "Entities.gmod_subway_81-722.Buttons.PPZ.SF25Toggle": "SF25:Освещение кабины",
  "Entities.gmod_subway_81-722.Buttons.PPZ.SF26Toggle": "SF26:Кондиционер кабины",
  "Entities.gmod_subway_81-722.Buttons.PPZ.SF27Toggle": "SF27:Стеклоочиститель, омыватель, гудок",
  "Entities.gmod_subway_81-722.Buttons.PPZ.SF03Toggle": "SF03:",
  "Entities.gmod_subway_81-722.Buttons.PPZ.SF04Toggle": "SF04:",
  "Entities.gmod_subway_81-722.Buttons.PassengerDoor1.PassengerDoor": "Дверь в кабину машиниста из салона",
  "Entities.gmod_subway_81-722.Buttons.CabinDoorR.CabinDoorRight": "Дверь в кабину машиниста",
  "Entities.gmod_subway_81-722.Buttons.PPZB.PSNToggleSet": "Зарядка АКБ",
  "Entities.gmod_subway_81-722.Buttons.PPZB.BattOnSet": "Включение источника питания бортовой сети",
  "Entities.gmod_subway_81-722.Buttons.PPZB.BattOffSet": "Отключение источника питания бортовой сети",
  "Entities.gmod_subway_81-722.Buttons.PPZB.TorecDoorUnlockSet": "Разблокировка торцевых дверей",
  "Entities.gmod_subway_81-722.Buttons.PPZB.SCEnable": "Короткозамыкатель",
  "Entities.gmod_subway_81-722.Buttons.PPZB.SOSD": "СОСД",
  "Entities.gmod_subway_81-722.Buttons.Isolations.FrontBrakeLineIsolationToggle": "Концевой кран тормозной магистрали",
  "Entities.gmod_subway_81-722.Buttons.Isolations.FrontTrainLineIsolationToggle": "Концевой кран напорной магистрали",
  "Entities.gmod_subway_81-722.Buttons.BI3.KRO+": "Направление движения(вверх)",
  "Entities.gmod_subway_81-722.Buttons.BI3.KRO-": "Направление движения(вниз)",
  "Entities.gmod_subway_81-722.Buttons.BI3.RingSet": "Звонок",
  "Entities.gmod_subway_81-722.Buttons.BI3.Compressor-": "Компрессоры(-)",
  "Entities.gmod_subway_81-722.Buttons.BI3.Compressor+": "Компрессоры(+)",
  "Entities.gmod_subway_81-722.Buttons.BI3.!BrakeCylinder": "Тормозной цилиндр",
  "Entities.gmod_subway_81-722.Buttons.BI3.!BrakeTrainLine": "Красная - тормозная, чёрная - напорная магистраль",
  "Entities.gmod_subway_81-722.Buttons.PVZ.SF31Toggle": "SF31:Поездной питающий провод",
  "Entities.gmod_subway_81-722.Buttons.PVZ.1:SF31Toggle": "SF31:Поездной питающий провод",
  "Entities.gmod_subway_81-722.Buttons.PVZ.SF32Toggle": "SF32:Бортовая сеть управление",
  "Entities.gmod_subway_81-722.Buttons.PVZ.SF33Toggle": "SF33:Питание цепей управления",
  "Entities.gmod_subway_81-722.Buttons.PVZ.SF34Toggle": "SF34:ЦИС левый",
  "Entities.gmod_subway_81-722.Buttons.PVZ.SF35Toggle": "SF35:ЦИС правый",
  "Entities.gmod_subway_81-722.Buttons.PVZ.SF36Toggle": "SF36:Бортовая сигнализация",
  "Entities.gmod_subway_81-722.Buttons.PVZ.SF37Toggle": "SF37:Отжатие токоприёмников",
  "Entities.gmod_subway_81-722.Buttons.PVZ.SF38Toggle": "SF38:Резерв",
  "Entities.gmod_subway_81-722.Buttons.PVZ.SF41Toggle": "SF41:Двери открытие левые",
  "Entities.gmod_subway_81-722.Buttons.PVZ.SF42Toggle": "SF42:Двери открытие правые",
  "Entities.gmod_subway_81-722.Buttons.PVZ.SF43Toggle": "SF43:Двери закрытие",
  "Entities.gmod_subway_81-722.Buttons.PVZ.SF44Toggle": "SF44:Двери торцевые",
  "Entities.gmod_subway_81-722.Buttons.PVZ.SF45Toggle": "SF45:Освещение салона питание",
  "Entities.gmod_subway_81-722.Buttons.PVZ.SF46Toggle": "SF46:Освещение салона аварийное",
  "Entities.gmod_subway_81-722.Buttons.PVZ.SF47Toggle": "SF47:Вентиляция 1 группа",
  "Entities.gmod_subway_81-722.Buttons.PVZ.SF48Toggle": "SF48:Вентиляция 2 группа",
  "Entities.gmod_subway_81-722.Buttons.PVZ.SF49Toggle": "SF49:Счётчик",
  "Entities.gmod_subway_81-722.Buttons.PVZ.SF51Toggle": "SF51:БУВ",
  "Entities.gmod_subway_81-722.Buttons.PVZ.SF52Toggle": "SF52:БОДВ",
  "Entities.gmod_subway_81-722.Buttons.PVZ.SF53Toggle": "SF53:ПСН",
  "Entities.gmod_subway_81-722.Buttons.PVZ.SF54Toggle": "SF54:Осушитель",
  "Entities.gmod_subway_81-722.Buttons.PVZ.SF55Toggle": "SF55:БУФТ",
  "Entities.gmod_subway_81-722.Buttons.PVZ.SF56Toggle": "SF56:Инвертор инвертор",
  "Entities.gmod_subway_81-722.Buttons.PVZ.SF57Toggle": "SF57:Инвертор обогрев",
  "Entities.gmod_subway_81-722.Buttons.PVZ.SF58Toggle": "SF58:ЦУВ основное",
  "Entities.gmod_subway_81-722.Buttons.PVZ.SF59Toggle": "SF59:ЦУВ резервное",
  "Entities.gmod_subway_81-722.Buttons.PVM.PassLightToggle": "Освещение салона",
  "Entities.gmod_subway_81-722.Buttons.PVM.PassVent-": "Вентиляция салона(-)",
  "Entities.gmod_subway_81-722.Buttons.PVM.PassVent+": "Вентиляция салона(+)",
  "Entities.gmod_subway_81-722.Buttons.PVM.VKFToggle": "ВКФ",
  "Entities.gmod_subway_81-722.Buttons.PVM.ParkingBrakeToggle": "Стояночный тормоз",
  "Entities.gmod_subway_81-722.Buttons.PVM.VRDToggle": "ВРД",
  "Entities.gmod_subway_81-722.Buttons.PVM.SOSDEnableToggle": "СОСД",
  "Entities.gmod_subway_81-722.Buttons.PVM.VRU-": "ВРУ(-)",
  "Entities.gmod_subway_81-722.Buttons.PVM.VRU+": "ВРУ(+)",
  "Entities.gmod_subway_81-722.Buttons.PVM.VADToggle": "Движение без контроля дверей",
  "Entities.gmod_subway_81-722.Buttons.PVM.VAHToggle": "Движение без педали бдительности",
  "Entities.gmod_subway_81-722.Buttons.PVM.EmergencyRadioPowerToggle": "Аварийное питание радиостанции",
  "Entities.gmod_subway_81-722.Buttons.PVM.BARSMode-": "Режимы БАРС(влево)",
  "Entities.gmod_subway_81-722.Buttons.PVM.BARSMode+": "Режимы БАРС(вправо)",
  "Entities.gmod_subway_81-722.Buttons.PVM.PantSC-": "Токоприёмники и короткозамыкатель(-)",
  "Entities.gmod_subway_81-722.Buttons.PVM.PantSC+": "Токоприёмники и короткозамыкатель(+)",
  "Entities.gmod_subway_81-722.Buttons.PVM.RCARSToggle": "РЦ АРС",

  "Entities.gmod_subway_81-723.Buttons.RearPneumatic.RearBrakeLineIsolationToggle": "Концевой кран тормозной магистрали",
  "Entities.gmod_subway_81-723.Buttons.RearPneumatic.RearTrainLineIsolationToggle": "Концевой кран напорной магистрали",
  "Entities.gmod_subway_81-723.Buttons.RearDoor.RearDoor": "Задняя дверь",
  "Entities.gmod_subway_81-723.Buttons.FrontDoor.FrontDoor": "Передняя дверь",
  "Entities.gmod_subway_81-723.Buttons.FrontPneumatic.FrontBrakeLineIsolationToggle": "Концевой кран тормозной магистрали",
  "Entities.gmod_subway_81-723.Buttons.FrontPneumatic.FrontTrainLineIsolationToggle": "Концевой кран напорной магистрали",
  "Entities.gmod_subway_81-723.Buttons.PVZ.SF31Toggle": "SF31:Поездной питающий провод",
  "Entities.gmod_subway_81-723.Buttons.PVZ.1:SF31Toggle": "SF31:Поездной питающий провод",
  "Entities.gmod_subway_81-723.Buttons.PVZ.SF32Toggle": "SF32:Бортовая сеть управление",
  "Entities.gmod_subway_81-723.Buttons.PVZ.SF33Toggle": "SF33:Питание цепей управленяи",
  "Entities.gmod_subway_81-723.Buttons.PVZ.SF34Toggle": "SF34:ЦИС левый",
  "Entities.gmod_subway_81-723.Buttons.PVZ.SF35Toggle": "SF35:ЦИС правый",
  "Entities.gmod_subway_81-723.Buttons.PVZ.SF36Toggle": "SF36:Бортовая сигнализация",
  "Entities.gmod_subway_81-723.Buttons.PVZ.SF37Toggle": "SF37:Отжатие токоприёмников",
  "Entities.gmod_subway_81-723.Buttons.PVZ.SF38Toggle": "SF38:Резерв",
  "Entities.gmod_subway_81-723.Buttons.PVZ.SF41Toggle": "SF41:Двери открытие левые",
  "Entities.gmod_subway_81-723.Buttons.PVZ.SF42Toggle": "SF42:Двери открытие правые",
  "Entities.gmod_subway_81-723.Buttons.PVZ.SF43Toggle": "SF43:Двери закрытие",
  "Entities.gmod_subway_81-723.Buttons.PVZ.SF44Toggle": "SF44:Двери торцевые",
  "Entities.gmod_subway_81-723.Buttons.PVZ.SF45Toggle": "SF45:Освещение салона питание",
  "Entities.gmod_subway_81-723.Buttons.PVZ.SF46Toggle": "SF46:Освещение салона аварийное",
  "Entities.gmod_subway_81-723.Buttons.PVZ.SF47Toggle": "SF47:Вентиляция 1 группа",
  "Entities.gmod_subway_81-723.Buttons.PVZ.SF48Toggle": "SF48:Вентиляция 2 группа",
  "Entities.gmod_subway_81-723.Buttons.PVZ.SF49Toggle": "SF49:Счётчик",
  "Entities.gmod_subway_81-723.Buttons.PVZ.SF51Toggle": "SF51:БУВ",
  "Entities.gmod_subway_81-723.Buttons.PVZ.SF52Toggle": "SF52:БОДВ",
  "Entities.gmod_subway_81-723.Buttons.PVZ.SF53Toggle": "SF53:ПСН",
  "Entities.gmod_subway_81-723.Buttons.PVZ.SF54Toggle": "SF54:Осушитель",
  "Entities.gmod_subway_81-723.Buttons.PVZ.SF55Toggle": "SF55:БУФТ",
  "Entities.gmod_subway_81-723.Buttons.PVZ.SF56Toggle": "SF56:Инвертор инвертор",
  "Entities.gmod_subway_81-723.Buttons.PVZ.SF57Toggle": "SF57:Инвертор обогрев",
  "Entities.gmod_subway_81-723.Buttons.PVZ.SF58Toggle": "SF58:ЦУВ основное",
  "Entities.gmod_subway_81-723.Buttons.PVZ.SF59Toggle": "SF59:ЦУВ резервное",

  "Entities.gmod_subway_81-724.Buttons.RearPneumatic.RearBrakeLineIsolationToggle": "Концевой кран тормозной магистрали",
  "Entities.gmod_subway_81-724.Buttons.RearPneumatic.RearTrainLineIsolationToggle": "Концевой кран напорной магистрали",
  "Entities.gmod_subway_81-724.Buttons.RearDoor.RearDoor": "Задняя дверь",
  "Entities.gmod_subway_81-724.Buttons.FrontDoor.FrontDoor": "Передняя дверь",
  "Entities.gmod_subway_81-724.Buttons.FrontPneumatic.FrontBrakeLineIsolationToggle": "Концевой кран тормозной магистрали",
  "Entities.gmod_subway_81-724.Buttons.FrontPneumatic.FrontTrainLineIsolationToggle": "Концевой кран напорной магистрали",
  "Entities.gmod_subway_81-724.Buttons.PVZ.SF34Toggle": "SF34:ЦИС левый",
  "Entities.gmod_subway_81-724.Buttons.PVZ.SF35Toggle": "SF35:ЦИС правый",
  "Entities.gmod_subway_81-724.Buttons.PVZ.SF36Toggle": "SF36:Бортовая сигнализация",
  "Entities.gmod_subway_81-724.Buttons.PVZ.SF41Toggle": "SF41:Двери открытие левые",
  "Entities.gmod_subway_81-724.Buttons.PVZ.SF42Toggle": "SF42:Двери открытие правые",
  "Entities.gmod_subway_81-724.Buttons.PVZ.SF43Toggle": "SF43:Двери закрытие",
  "Entities.gmod_subway_81-724.Buttons.PVZ.SF44Toggle": "SF44:Двери торцевые",
  "Entities.gmod_subway_81-724.Buttons.PVZ.SF45Toggle": "SF45:Освещение салона питание",
  "Entities.gmod_subway_81-724.Buttons.PVZ.SF46Toggle": "SF46:Освещение салона аварийное",
  "Entities.gmod_subway_81-724.Buttons.PVZ.SF47Toggle": "SF47:Вентиляция 1 группа",
  "Entities.gmod_subway_81-724.Buttons.PVZ.SF48Toggle": "SF48:Вентиляция 2 группа",
  "Entities.gmod_subway_81-724.Buttons.PVZ.SF51Toggle": "SF51:БУВ",
  "Entities.gmod_subway_81-724.Buttons.PVZ.SF52Toggle": "SF52:БОДВ",
  "Entities.gmod_subway_81-724.Buttons.PVZ.SF53Toggle": "SF53:Резерв",
  "Entities.gmod_subway_81-724.Buttons.PVZ.SF54Toggle": "SF54:Резерв",
  "Entities.gmod_subway_81-724.Buttons.PVZ.SF55Toggle": "SF55:БУФТ"
}
]]
