return [[
{
    "Lang": "ru",
    "Name": "Russian",


    "Entities.gmod_subway_81-717_lvz.Buttons.HelperPanel.VUD2Toggle": "ВУД2: Выключатель управления дверьми",
    "Entities.gmod_subway_81-717_lvz.Buttons.HelperPanel.VDLSet": "ВДЛ: Выключатель левых дверей",
    "Entities.gmod_subway_81-717_lvz.Buttons.Battery_2.1:RC1Toggle": "РЦ-1: Разъединитель цепей АРС",
    "Entities.gmod_subway_81-717_lvz.Buttons.Battery_2.1:VBToggle": "ВБ: Выключатель батареи",
    "Entities.gmod_subway_81-717_lvz.Buttons.Battery_2.1:BPSToggle": "РЦ-БПС: Блок противоскатывания",
    "Entities.gmod_subway_81-717_lvz.Buttons.Battery_2.1:BUDToggle": "БУД: Блок управления дверьми",
    "Entities.gmod_subway_81-717_lvz.Buttons.Battery_2.1:VRDToggle": "ВРД: Выключатель разрешающий движение (под 0)",
    "Entities.gmod_subway_81-717_lvz.Buttons.VRD1.VRDToggle": "ВРД: Выключатель разрешающий движение (под 0)",
    "Entities.gmod_subway_81-717_lvz.Buttons.Wiper.WiperToggle": "Дворник",
    "Entities.gmod_subway_81-717_lvz.Buttons.RearPneumatic.RearBrakeLineIsolationToggle": "Концевой кран тормозной магистрали",
    "Entities.gmod_subway_81-717_lvz.Buttons.RearPneumatic.RearTrainLineIsolationToggle": "Концевой кран напорной магистрали",
    "Entities.gmod_subway_81-717_lvz.Buttons.Main.R_UNchToggle": "УНЧ: Усилитель низких частот",
    "Entities.gmod_subway_81-717_lvz.Buttons.Main.R_ZSToggle": "ЭС: Контроль экстренной связи",
    "Entities.gmod_subway_81-717_lvz.Buttons.Main.R_GToggle": "Громкоговоритель",
    "Entities.gmod_subway_81-717_lvz.Buttons.Main.R_UPOToggle": "УПО: Информатор",
    "Entities.gmod_subway_81-717_lvz.Buttons.Main.2:KVTSet": "КБ: Кнопка Бдительности",
    "Entities.gmod_subway_81-717_lvz.Buttons.Main.VZ1Set": "ВЗ1: Вентиль замещения №1",
    "Entities.gmod_subway_81-717_lvz.Buttons.Main.VUD1Toggle": "ВУД: Выключатель управления дверьми",
    "Entities.gmod_subway_81-717_lvz.Buttons.Main.KDLSet": "КДЛ: Кнопка левых дверей",
    "Entities.gmod_subway_81-717_lvz.Buttons.Main.KDLKToggle": "Крышка кнопки КДЛ",
    "Entities.gmod_subway_81-717_lvz.Buttons.Main.KDLRSet": "ВДЛ: Выключатель левых дверей",
    "Entities.gmod_subway_81-717_lvz.Buttons.Main.KDLRKToggle": "Крышка кнопки ВДЛ",
    "Entities.gmod_subway_81-717_lvz.Buttons.Main.DoorSelectToggle": "Выбор стороны открытия дверей",
    "Entities.gmod_subway_81-717_lvz.Buttons.Main.KRZDSet": "КРЗД: Кнопка резервного закрытия дверей",
    "Entities.gmod_subway_81-717_lvz.Buttons.Main.VozvratRPSet": "Возврат реле перегрузки",
    "Entities.gmod_subway_81-717_lvz.Buttons.Main.GreenRPLight": "РП: Зелёная лампа реле перегрузки",
    "Entities.gmod_subway_81-717_lvz.Buttons.Main.AVULight": "АВУ: Автоматический выключатель управления",
    "Entities.gmod_subway_81-717_lvz.Buttons.Main.LKVPLight": "ЛКВП: Контроль высоковольного преобразователя",
    "Entities.gmod_subway_81-717_lvz.Buttons.Main.SPLight": "ЛСП: Лампа сигнализации пожара",
    "Entities.gmod_subway_81-717_lvz.Buttons.Main.ConverterProtectionSet": "Converter protection",
    "Entities.gmod_subway_81-717_lvz.Buttons.Main.KSNSet": "КСН: Кнопка сигнализации неисправности",
    "Entities.gmod_subway_81-717_lvz.Buttons.Main.DIPoffSet": "Звонок",
    "Entities.gmod_subway_81-717_lvz.Buttons.Main.ARSToggle": "АРС: Включение системы автоматического регулирования скорости",
    "Entities.gmod_subway_81-717_lvz.Buttons.Main.ALSToggle": "АЛС: Включение системы автоматической локомотивной сигнализации",
    "Entities.gmod_subway_81-717_lvz.Buttons.Main.TormATToggle": "(placeholder)",
    "Entities.gmod_subway_81-717_lvz.Buttons.Main.OtklAVUToggle": "ОтклАВУ: Отключение автоматического выключения управления (неисправность АВУ)",
    "Entities.gmod_subway_81-717_lvz.Buttons.Main.L_1Toggle": "Освещение салона",
    "Entities.gmod_subway_81-717_lvz.Buttons.Main.L_2Toggle": "Освещение кабины",
    "Entities.gmod_subway_81-717_lvz.Buttons.Main.L_3Toggle": "Освещение пульта",
    "Entities.gmod_subway_81-717_lvz.Buttons.PassengerDoor.PassengerDoor": "Дверь в кабину машиниста из салона",
    "Entities.gmod_subway_81-717_lvz.Buttons.IGLAButtons.IGLA1Set": "ИГЛА: Первая кнопка",
    "Entities.gmod_subway_81-717_lvz.Buttons.IGLAButtons.IGLA2Set": "ИГЛА: Вторая кнопка",
    "Entities.gmod_subway_81-717_lvz.Buttons.IGLAButtons.IGLA23": "ИГЛА: Вторая и третья кнопка",
    "Entities.gmod_subway_81-717_lvz.Buttons.IGLAButtons.IGLA3Set": "ИГЛА: Третья кнопка",
    "Entities.gmod_subway_81-717_lvz.Buttons.IGLAButtons.IGLA4Set": "ИГЛА: Четвёртая кнопка",
    "Entities.gmod_subway_81-717_lvz.Buttons.IGLAButtons.!IGLAFire": "ИГЛА: Пожар",
    "Entities.gmod_subway_81-717_lvz.Buttons.IGLAButtons.!IGLAErr": "ИГЛА: Неисправность",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A61Toggle": "A61 Управление 6ым поездным проводом",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A55Toggle": "A55 Управление проводом 10АС",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A54Toggle": "A54 Управление проводом 10АК",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A56Toggle": "A56 Включение аккумуляторной батареи",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A27Toggle": "A27 Включение ДИП и освещения",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A21Toggle": "A21 Управление дверей",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A10Toggle": "A10 Управление мотор-компрессором",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A53Toggle": "A53 Питание КВЦ",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A43Toggle": "A43 Питание АРС 12В",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A45Toggle": "A45 АРС провод 10АУ",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A42Toggle": "A42 Питание АРС 75В",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A41Toggle": "A41 Торможение АРС",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:VUToggle": "ВУ  Управление поезда",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A64Toggle": "A64 Включение освещения кабины",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A63Toggle": "A63 ИГЛА/БИС",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A50Toggle": "A50 ДИП и освещение включение",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A51Toggle": "A51 ДИП и освещение отключение",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A23Toggle": "A23 Резервное включение мотор-компрессора",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A14Toggle": "A14 18 провод",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A75Toggle": "A75 Отопление кабины",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A1Toggle": "A1  Ход 1",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A2Toggle": "A2  Ход 2",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A3Toggle": "A3  Ход 3",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A17Toggle": "A17 Возврат РП",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A62Toggle": "A62 Радиосвязь",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A29Toggle": "A29 Радио опевещение",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A5Toggle": "A5 ",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A6Toggle": "A6  Тормоз 1",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A8Toggle": "A8  Вентиль #1, #2",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A20Toggle": "A20 Ход 1, 20 провод",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A25Toggle": "A25 Торможение ручное",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A22Toggle": "A22 Включение КК",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A30Toggle": "A30 Серводвигатель реостатного контроллера",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A39Toggle": "A39 Резервное управление",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A44Toggle": "A44 Резервное управление поезда",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A80Toggle": "A80 Серводвигатель переключателя положений",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A65Toggle": "A65 Освещение салона",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:L_5Toggle": "А49 Аварийное освещение",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A24Toggle": "A24 Заряд аккумуляторной батареи",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A32Toggle": "A32 Открытие правых дверей",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A31Toggle": "A31 Открытие левых дверей",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A16Toggle": "A16 Закрытие дверей",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A13Toggle": "A13 Сигнализация дверей",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A12Toggle": "A12 Резервное закрытие дверей",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A7Toggle": "A7  Красный фонарь",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A9Toggle": "A9  Красный фонарь",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A46Toggle": "A46 Фары белые",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A47Toggle": "A47 Фары белые",
    "Entities.gmod_subway_81-717_lvz.Buttons.Schedule.!RouteNum": "М №\nRoute number",
    "Entities.gmod_subway_81-717_lvz.Buttons.Schedule.!PathNum": "П №\nPath number",
    "Entities.gmod_subway_81-717_lvz.Buttons.Schedule.!SchTime": "ВРЕМЯ ХОДА\nTotal schedule time",
    "Entities.gmod_subway_81-717_lvz.Buttons.Schedule.!SchInterval": "ИНТ\nTrain interval",
    "Entities.gmod_subway_81-717_lvz.Buttons.Schedule.!SchHour": "ЧАС\nHour",
    "Entities.gmod_subway_81-717_lvz.Buttons.Schedule.!SchMin": "МИН\nMinute",
    "Entities.gmod_subway_81-717_lvz.Buttons.Schedule.!SchSec": "СЕК\nSecond",
    "Entities.gmod_subway_81-717_lvz.Buttons.Schedule.!SchArrival": "Arrival times",
    "Entities.gmod_subway_81-717_lvz.Buttons.Schedule.!SchStations": "Station name",
    "Entities.gmod_subway_81-717_lvz.Buttons.Stopkran.EmergencyBrakeValveToggle": "Стопкран",
    "Entities.gmod_subway_81-717_lvz.Buttons.PneumaticPanels.!CylinderPressure": "Давление в тормозных цилиндрах (ТЦ)",
    "Entities.gmod_subway_81-717_lvz.Buttons.PneumaticPanels.!LinePressure": "Давление в магистралях (красная: тормозной, чёрная: напорной)",
    "Entities.gmod_subway_81-717_lvz.Buttons.Battery.BPSToggle": "РЦ-БПС: Блок противоскатывания",
    "Entities.gmod_subway_81-717_lvz.Buttons.Battery.RC1Toggle": "РЦ-1: Разъединитель цепей АРС",
    "Entities.gmod_subway_81-717_lvz.Buttons.Battery.BUDToggle": "БУД: Блок управления дверьми",
    "Entities.gmod_subway_81-717_lvz.Buttons.Battery.VBToggle": "ВБ: Выключатель батареи",
    "Entities.gmod_subway_81-717_lvz.Buttons.FrontPneumatic.FrontBrakeLineIsolationToggle": "Концевой кран тормозной магистрали",
    "Entities.gmod_subway_81-717_lvz.Buttons.FrontPneumatic.FrontTrainLineIsolationToggle": "Концевой кран напорной магистрали",
    "Entities.gmod_subway_81-717_lvz.Buttons.SPBARS.!Speedometer1": "Индикатор скорости",
    "Entities.gmod_subway_81-717_lvz.Buttons.SPBARS.!Speedometer2": "Индикатор скорости",
    "Entities.gmod_subway_81-717_lvz.Buttons.SPBARS.!ARSOch": "НЧ: Отсутствие частоты АРС",
    "Entities.gmod_subway_81-717_lvz.Buttons.SPBARS.!ARS0": "0: Сигнал АРС остановки",
    "Entities.gmod_subway_81-717_lvz.Buttons.SPBARS.!ARS40": "40: Ограничение скорости 40 км/ч",
    "Entities.gmod_subway_81-717_lvz.Buttons.SPBARS.!ARS60": "60: Ограничение скорости 60 км/ч",
    "Entities.gmod_subway_81-717_lvz.Buttons.SPBARS.!ARS70": "70: Ограничение скорости 70 км/ч",
    "Entities.gmod_subway_81-717_lvz.Buttons.SPBARS.!ARS80": "80: Ограничение скорости 80 км/ч",
    "Entities.gmod_subway_81-717_lvz.Buttons.SPBARS.!LampLSD1": "ЛСД: Сигнализация дверей",
    "Entities.gmod_subway_81-717_lvz.Buttons.SPBARS.!LampLSD2": "ЛСД: Сигнализация дверей",
    "Entities.gmod_subway_81-717_lvz.Buttons.SPBARS.!LampLVD": "1: Лампа включения двигателей",
    "Entities.gmod_subway_81-717_lvz.Buttons.SPBARS.!LampLHRK": "2: Лампа хода реостатного контроллера",
    "Entities.gmod_subway_81-717_lvz.Buttons.SPBARS.!LampLST": "6: Лампа сигнализации торможения",
    "Entities.gmod_subway_81-717_lvz.Buttons.SPBARS.!LampLRD": "ЛРД",
    "Entities.gmod_subway_81-717_lvz.Buttons.SPBARS.!LampRP": "РП: Красная лампа реле перегрузки",
    "Entities.gmod_subway_81-717_lvz.Buttons.SPBARS.!LampLSN": "ЛСН: Лампа сигнализации неисправности",
    "Entities.gmod_subway_81-717_lvz.Buttons.SPBARS.!LampLKVD": "ЛКВД: Контроль выключения двигателей",
    "Entities.gmod_subway_81-717_lvz.Buttons.SPBARS.!LampLKT": "ЛКТ: Контроль тормоза",
    "Entities.gmod_subway_81-717_lvz.Buttons.SPBARS.!LampDV": "ДВ: Датчик вращения",
    "Entities.gmod_subway_81-717_lvz.Buttons.SPBARS.!SpeedFact1": "Скорость",
    "Entities.gmod_subway_81-717_lvz.Buttons.SPBARS.!SpeedFact2": "Скорость",
    "Entities.gmod_subway_81-717_lvz.Buttons.SPBARS.!ARSL20": "НЧ: Отсутствие частоты АРС",
    "Entities.gmod_subway_81-717_lvz.Buttons.SPBARS.!ARSL40": "40: Ограничение скорости 40 км/ч",
    "Entities.gmod_subway_81-717_lvz.Buttons.SPBARS.!ARSL60": "60: Ограничение скорости 60 км/ч",
    "Entities.gmod_subway_81-717_lvz.Buttons.SPBARS.!ARSL70": "70: Ограничение скорости 70 км/ч",
    "Entities.gmod_subway_81-717_lvz.Buttons.SPBARS.!ARSL80": "80: Ограничение скорости 80 км/ч",
    "Entities.gmod_subway_81-717_lvz.Buttons.ParkingBrake2.1:ParkingBrakeToggle": "Стояночный тормоз",
    "Entities.gmod_subway_81-717_lvz.Buttons.RearDoor.RearDoor": "Передняя дверь",
    "Entities.gmod_subway_81-717_lvz.Buttons.GV.GVToggle": "Главный выключатель",
    "Entities.gmod_subway_81-717_lvz.Buttons.Meters.!TotalVoltmeter": "Вольтметр высокого напряжения (кВ)",
    "Entities.gmod_subway_81-717_lvz.Buttons.Meters.!TotalAmpermeter": "Амперметр (А)",
   "Entities.gmod_subway_81-717_lvz.Buttons.AV.A61Toggle": "A61 Управление 6ым поездным проводом",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A55Toggle": "A55 Управление проводом 10АС",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A54Toggle": "A54 Управление проводом 10АК",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A56Toggle": "A56 Включение аккумуляторной батареи",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A27Toggle": "A27 Включение ДИП и освещения",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A21Toggle": "A21 Управление дверей",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A10Toggle": "A10 Управление мотор-компрессором",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A53Toggle": "A53 Питание КВЦ",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A43Toggle": "A43 Питание АРС 12В",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A45Toggle": "A45 АРС провод 10АУ",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A42Toggle": "A42 Питание АРС 75В",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A41Toggle": "A41 Торможение АРС",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.VUToggle": "ВУ  Управление поезда",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A64Toggle": "A64 Включение освещения кабины",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A63Toggle": "A63 ИГЛА/БИС",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A50Toggle": "A50 ДИП и освещение включение",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A51Toggle": "A51 ДИП и освещение отключение",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A23Toggle": "A23 Резервное включение мотор-компрессора",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A14Toggle": "A14 18 провод",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A75Toggle": "A75 Отопление кабины",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A1Toggle": "A1  Ход 1",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A2Toggle": "A2  Ход 2",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A3Toggle": "A3  Ход 3",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A17Toggle": "A17 Возврат РП",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A62Toggle": "A62 Радиосвязь",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A29Toggle": "A29 Радио опевещение",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A5Toggle": "A5 ",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A6Toggle": "A6  Тормоз 1",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A8Toggle": "A8  Вентиль #1, #2",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A20Toggle": "A20 Ход 1, 20 провод",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A25Toggle": "A25 Торможение ручное",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A22Toggle": "A22 Включение КК",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A30Toggle": "A30 Серводвигатель реостатного контроллера",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A39Toggle": "A39 Резервное управление",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A44Toggle": "A44 Резервное управление поезда",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A80Toggle": "A80 Серводвигатель переключателя положений",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A65Toggle": "A65 Освещение салона",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.L_5Toggle": "А49 Аварийное освещение",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A24Toggle": "A24 Заряд аккумуляторной батареи",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A32Toggle": "A32 Открытие правых дверей",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A31Toggle": "A31 Открытие левых дверей",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A16Toggle": "A16 Закрытие дверей",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A13Toggle": "A13 Сигнализация дверей",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A12Toggle": "A12 Резервное закрытие дверей",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A7Toggle": "A7  Красный фонарь",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A9Toggle": "A9  Красный фонарь",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A46Toggle": "A46 Фары белые",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A47Toggle": "A47 Фары белые",
    "Entities.gmod_subway_81-717_lvz.Buttons.Front.L_4Toggle": "Выключатель фар",
    "Entities.gmod_subway_81-717_lvz.Buttons.Front.VUSToggle": "ВУС: Выключатель усиленого света ходовых фар",
    "Entities.gmod_subway_81-717_lvz.Buttons.Front.VADToggle": "ВАД: Включение аварийного закрытия дверей (неисправность реле контроля дверей)",
    "Entities.gmod_subway_81-717_lvz.Buttons.Front.VAHToggle": "ВАХ: Включение аварийного хода (неисправность реле педали безопасности)",
    "Entities.gmod_subway_81-717_lvz.Buttons.Front.KRPSet": "КРП: Кнопка резервного пуска",
    "Entities.gmod_subway_81-717_lvz.Buttons.Front.RezMKSet": "Резервное включение мотор-компрессора",
    "Entities.gmod_subway_81-717_lvz.Buttons.Front.KDPSet": "КДП: Кнопка правых дверей",
    "Entities.gmod_subway_81-717_lvz.Buttons.Front.KDPKToggle": "Крышка кнопки КДП",
    "Entities.gmod_subway_81-717_lvz.Buttons.Front.PN": "Контроль пневмотормоза",
    "Entities.gmod_subway_81-717_lvz.Buttons.BPSNFront.!Voltage": "Напряжение цепей управления",
    "Entities.gmod_subway_81-717_lvz.Buttons.BPSNFront.VMKToggle": "Включение мотор-компрессора",
    "Entities.gmod_subway_81-717_lvz.Buttons.BPSNFront.BPSNonToggle": "БПСН: Блок питания собственных нужд",
    "Entities.gmod_subway_81-717_lvz.Buttons.BPSNFront.ARS13Set": "АРС 13В: Проверка стабилизированого напряжения АРС",
    "Entities.gmod_subway_81-717_lvz.Buttons.ParkingBrake.ParkingBrakeToggle": "Стояночный тормоз",
    "Entities.gmod_subway_81-717_lvz.Buttons.ParkingBrake.DriverValveTLDisconnectToggle": "Кран двойной тяги напорной магистрали",
    "Entities.gmod_subway_81-717_lvz.Buttons.CabinDoor.CabinDoor": "Дверь в кабину машиниста",
    "Entities.gmod_subway_81-717_lvz.Buttons.PUAVN.!K16": "НЧ: Отсутствие частоты АРС",
    "Entities.gmod_subway_81-717_lvz.Buttons.PUAVN.!OS": "0: Сигнал АРС остановки",
    "Entities.gmod_subway_81-717_lvz.Buttons.PUAVN.!AVT": "40: Ограничение скорости 40 км/ч",
    "Entities.gmod_subway_81-717_lvz.Buttons.PUAVN.!ARS": "60: Ограничение скорости 60 км/ч",
    "Entities.gmod_subway_81-717_lvz.Buttons.PUAVN.!KI1": "70: Ограничение скорости 70 км/ч",
    "Entities.gmod_subway_81-717_lvz.Buttons.PUAVN.!KI2": "80: Ограничение скорости 80 км/ч",
    "Entities.gmod_subway_81-717_lvz.Buttons.PUAVN.!ARSOch": "НЧ: Отсутствие частоты АРС",
    "Entities.gmod_subway_81-717_lvz.Buttons.PUAVN.!ARS0": "0: Сигнал АРС остановки",
    "Entities.gmod_subway_81-717_lvz.Buttons.PUAVN.!ARS40": "40: Ограничение скорости 40 км/ч",
    "Entities.gmod_subway_81-717_lvz.Buttons.PUAVN.!ARS60": "60: Ограничение скорости 60 км/ч",
    "Entities.gmod_subway_81-717_lvz.Buttons.PUAVN.!ARS70": "70: Ограничение скорости 70 км/ч",
    "Entities.gmod_subway_81-717_lvz.Buttons.PUAVN.!ARS80": "80: Ограничение скорости 80 км/ч",
    "Entities.gmod_subway_81-717_lvz.Buttons.PUAVN.KHSet": "",
    "Entities.gmod_subway_81-717_lvz.Buttons.PUAVN.KSZDSet": "",
    "Entities.gmod_subway_81-717_lvz.Buttons.PUAVN.VAVToggle": "",
    "Entities.gmod_subway_81-717_lvz.Buttons.PUAVN.VZPToggle": "",
    "Entities.gmod_subway_81-717_lvz.Buttons.PassengerDoor1.PassengerDoor": "Дверь в кабину машиниста из салона",
    "Entities.gmod_subway_81-717_lvz.Buttons.Reverser.KVReverserDown": "Реверсор назад",
    "Entities.gmod_subway_81-717_lvz.Buttons.Reverser.KVReverserUp": "Реверсор вперёд",
    "Entities.gmod_subway_81-717_lvz.Buttons.EPKDisconnect.EPKToggle": "Кран ЭПВ",
    "Entities.gmod_subway_81-717_lvz.Buttons.Help.ShowHelp": "Помощь в вождении поезда",
    "Entities.gmod_subway_81-717_lvz.Buttons.UAVAPanel.UAVAToggle": "УАВА: Универсальный Автоматический Выключатель Автостопа (отключение автостопа)",
    "Entities.gmod_subway_81-717_lvz.Buttons.UAVAPanel.UAVACToggle   ": "УАВА: Универсальный Автоматический Выключатель Автостопа (восстановление контактов)",
    "Entities.gmod_subway_81-717_lvz.Buttons.DriverValveDisconnect.DriverValveDisconnectToggle": "Клапан разобщения",
    "Entities.gmod_subway_81-717_lvz.Buttons.DriverValveDisconnect.DriverValveBLDisconnectToggle": "Кран двойной тяги тормозной магистрали",
    "Entities.gmod_subway_81-717_lvz.Buttons.AirDistributor.AirDistributorDisconnectToggle": "Выключение воздухораспределителя",




    "Entities.gmod_subway_81-714_lvz.Buttons.GV.GVToggle": "Главный выключатель",
    "Entities.gmod_subway_81-714_lvz.Buttons.RearPneumatic.RearBrakeLineIsolationToggle": "Концевой кран тормозной магистрали",
    "Entities.gmod_subway_81-714_lvz.Buttons.RearPneumatic.RearTrainLineIsolationToggle": "Концевой кран напорной магистрали",
    "Entities.gmod_subway_81-714_lvz.Buttons.RearDoor.RearDoor": "Задняя дверь",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Left.DriverValveBLDisconnectToggle": "Кран двойной тяги тормозной магистрали",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Left.DriverValveTLDisconnectToggle": "Кран двойной тяги напорной магистрали",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Left.A65Toggle": "A65 Interior lighting",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Left.A56Toggle": "A56 Включение аккумуляторной батареи",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Left.A63Toggle": "A63 IGLA/BIS",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Left.A10Toggle": "A10 Motor-compressor control",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Left.A30Toggle": "A30 Rheostat controller motor power",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Left.A80Toggle": "A80 Power circuit mode switch motor power",
    "Entities.gmod_subway_81-714_lvz.Buttons.FrontPneumatic.FrontBrakeLineIsolationToggle": "Концевой кран тормозной магистрали",
    "Entities.gmod_subway_81-714_lvz.Buttons.FrontPneumatic.FrontTrainLineIsolationToggle": "Концевой кран напорной магистрали",
    "Entities.gmod_subway_81-714_lvz.Buttons.FrontPneumatic.ParkingBrakeToggle": "Стояночный тормоз",
    "Entities.gmod_subway_81-714_lvz.Buttons.AirDistributor.AirDistributorDisconnectToggle": "Выключение воздухораспределителя",
    "Entities.gmod_subway_81-714_lvz.Buttons.FrontDoor.FrontDoor": "Передняя дверь",
    "Entities.gmod_subway_81-714_lvz.Buttons.Battery.VBToggle": "ВБ: Выключатель батареи",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Right.A54Toggle": "A54 Управление проводом 10АК",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Right.A27Toggle": "A27 Включение ДИП и освещения",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Right.A24Toggle": "A24 Заряд аккумуляторной батареи",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Right.A53Toggle": "A53 Питание КВЦ",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Right.A13Toggle": "A13 Сигнализация дверей",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Right.A32Toggle": "A32 Открытие правых дверей",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Right.A31Toggle": "A31 Открытие левых дверей",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Right.A16Toggle": "A16 Закрытие дверей",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Right.A12Toggle": "A12 Резервное закрытие дверей",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Right.A50Toggle": "A50 ДИП и освещение включение",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Right.A51Toggle": "A51 ДИП и освещение отключение",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Right.A1Toggle": "A1  Ход 1",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Right.KRPSet": "ПУСК: Кнопка пуска",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Right.VozvratRPSet": "Возврат реле перегрузки",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Right.RezMKSet": "Резервное включение мотор-компрессора",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Right.VMKToggle": "Включение мотор-компрессора",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Right.BPSNonToggle": "БПСН: Блок питания собственных нужд",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Right.A2Toggle": "A2  Ход 2",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Right.A3Toggle": "A3  Ход 3",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Right.A17Toggle": "A17 Возврат РП",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Right.A5Toggle": "A5  ",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Right.A6Toggle": "A6  Tормоз 1",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Right.A8Toggle": "A8  Вентиль #1, #2",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Right.A20Toggle": "A20 Ход 1, 20 провод",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Right.A25Toggle": "A25 Торможение ручное",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Right.A22Toggle": "A22 Включение КК",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Right.A23Toggle": "A23 Резервное включение мотор-компрессора",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Right.A39Toggle": "A39 Резервное управление",
"Entities.gmod_subway_81-714_lvz.Buttons.AV_Right.A14Toggle": "A14 18 провод"
}
]]
