return [[
{
    "Lang": "ru",
    "Name": "Russian",


    "Entities.gmod_subway_81-703.Buttons.HelperPanel.R_Program1Set": "Программа 1",
    "Entities.gmod_subway_81-703.Buttons.HelperPanel.R_Program2Set": "Программа 2",
    "Entities.gmod_subway_81-703.Buttons.HelperPanel.VDLSet": "ВДЛ: Выключатель левых дверей",
    "Entities.gmod_subway_81-703.Buttons.HelperPanel.VUD2Toggle": "ВУД2: Выключатель управления дверьми",
    "Entities.gmod_subway_81-703.Buttons.Meters.!TotalVoltmeter": "Вольтметр высокого напряжения (кВ)",
    "Entities.gmod_subway_81-703.Buttons.Meters.!TotalAmpermeter": "Амперметр (А)",
    "Entities.gmod_subway_81-703.Buttons.AV2.RSTToggle": "РСТ: Радиостанция",
    "Entities.gmod_subway_81-703.Buttons.RearPneumatic.RearTrainLineIsolationToggle": "Концевой кран напорной магистрали",
    "Entities.gmod_subway_81-703.Buttons.RearPneumatic.RearBrakeLineIsolationToggle": "Концевой кран тормозной магистрали",
    "Entities.gmod_subway_81-703.Buttons.Back2.!HVFuses": "Блок высоковольтных предохранителей",
    "Entities.gmod_subway_81-703.Buttons.Back2.!DVR": "Дверной воздухораспределитель",
    "Entities.gmod_subway_81-703.Buttons.Main.RK": "Лампа: Вращение реостатного контроллера)",
    "Entities.gmod_subway_81-703.Buttons.Main.GreenRP": "Лампа: Зелёная РП (сигнализация перегрузки на поезде)",
    "Entities.gmod_subway_81-703.Buttons.Main.RedRP": "Лампа: Красная РП",
    "Entities.gmod_subway_81-703.Buttons.Main.Blue": "Лампа: Сигнализация дверей",
    "Entities.gmod_subway_81-703.Buttons.Main.DIPonSet": "Вкл. Осв.: Включение освещения",
    "Entities.gmod_subway_81-703.Buttons.Main.DIPoffSet": "Выкл. Осв.: Отключение освещения (звонок)",
    "Entities.gmod_subway_81-703.Buttons.Main.VozvratRPSet": "ВРП: Возврат РП",
    "Entities.gmod_subway_81-703.Buttons.Main.KSNSet": "КСН: Принудительное срабатывание РП на неисправном вагоне (Сигнализация неисправности)",
    "Entities.gmod_subway_81-703.Buttons.Main.KRZDSet": "КРЗД: Кнопка резервного закрытия дверей",
    "Entities.gmod_subway_81-703.Buttons.Main.KSDSet": "КСД: Контроль сигнализации дверей(проверка СД)",
    "Entities.gmod_subway_81-703.Buttons.Main.KDPSet": "КДП: Правые двери",
    "Entities.gmod_subway_81-703.Buttons.Main.KDLSet": "КДЛ: Кнопка левых дверей",
    "Entities.gmod_subway_81-703.Buttons.Main.KU1Toggle": "МК: Включение мотор-компрессора",
    "Entities.gmod_subway_81-703.Buttons.Main.VUD1Toggle": "ВУД: Закрытие дверей",
    "Entities.gmod_subway_81-703.Buttons.Main.KRPSet": "КРП: Резервный пуск (ручное управление)",
    "Entities.gmod_subway_81-703.Buttons.AV1.VU3Toggle": "ВУ3: Освещение кабины\n",
    "Entities.gmod_subway_81-703.Buttons.AV1.VU2Toggle": "ВУ2: Аварийное освещение (45В)\n",
    "Entities.gmod_subway_81-703.Buttons.AV1.VU1Toggle": "ВУ1: Печь отопления кабины (3кВт)\n",
    "Entities.gmod_subway_81-703.Buttons.AVMain.AV8BToggle": "АВ-8Б: Автоматическй выключатель (Вспомогательные цепи высокого напряжения)\n",
    "Entities.gmod_subway_81-703.Buttons.Lamp.L_3Toggle": "Лампа: Подсветка приборов",
    "Entities.gmod_subway_81-703.Buttons.DriverValveTLDisconnect.DriverValveTLDisconnectToggle": "Кран двойной тяги напорной магистрали",
    "Entities.gmod_subway_81-703.Buttons.VU.VUToggle": "ВУ: Выключатель управления",
    "Entities.gmod_subway_81-703.Buttons.FrontDoor.FrontDoor": "Передняя дверь",
    "Entities.gmod_subway_81-703.Buttons.PneumaticManometer.!LinesPressure": "Давление в магистралях (красная: тормозной, чёрная: напорной)",
    "Entities.gmod_subway_81-703.Buttons.Stopkran.EmergencyBrakeValveToggle": "Стопкран",
    "Entities.gmod_subway_81-703.Buttons.UAVAPanel.UAVAToggle": "УАВА: Универсальный Автоматический Выключатель Автостопа (отключение автостопа)",
    "Entities.gmod_subway_81-703.Buttons.UAVAPanel.UAVACToggle   ": "УАВА: Универсальный Автоматический Выключатель Автостопа (восстановление контактов)",
    "Entities.gmod_subway_81-703.Buttons.PneumaticPanels.!CylinderPressure": "Тормозной манометр: Давление в тормозных цилиндрах (ТЦ)",
    "Entities.gmod_subway_81-703.Buttons.Battery.VBToggle": "ВБ: Выключатель аккумуляторной батареи (Вспомогательные цепи низкого напряжения)",
    "Entities.gmod_subway_81-703.Buttons.Battery.R_RadioToggle": "Питание радиоинформатора +50В",
    "Entities.gmod_subway_81-703.Buttons.FrontPneumatic.FrontBrakeLineIsolationToggle": "Концевой кран тормозной магистрали",
    "Entities.gmod_subway_81-703.Buttons.FrontPneumatic.FrontTrainLineIsolationToggle": "Концевой кран напорной магистрали",
    "Entities.gmod_subway_81-703.Buttons.ASNP.R_ASNPMenuSet": "Информатор: Меню",
    "Entities.gmod_subway_81-703.Buttons.ASNP.R_ASNPUpSet": "Информатор: Вверх",
    "Entities.gmod_subway_81-703.Buttons.ASNP.R_ASNPDownSet": "Информатор: Вниз",
    "Entities.gmod_subway_81-703.Buttons.ASNP.R_ASNPOnToggle": "Информатор: Включение",
    "Entities.gmod_subway_81-703.Buttons.GV.GVToggle": "Главный выключатель",
    "Entities.gmod_subway_81-703.Buttons.PassengerDoor.PassengerDoor": "Дверь из салона",
    "Entities.gmod_subway_81-703.Buttons.KRR.KRRToggle": "KРР: Кнопка разворота реверсоров",
    "Entities.gmod_subway_81-703.Buttons.VU4.VUSToggle": "Переключатель: Ближний свет/Дальний свет",
    "Entities.gmod_subway_81-703.Buttons.CabinDoor.CabinDoor1": "Дверь в кабину машиниста",
    "Entities.gmod_subway_81-703.Buttons.Tsepi.!BatteryVoltage": "Напряжение цепей управления",
    "Entities.gmod_subway_81-703.Buttons.IGLAButtons.IGLA1USet": "ИГЛА: Первая кнопка вверх",
    "Entities.gmod_subway_81-703.Buttons.IGLAButtons.IGLA1Set": "ИГЛА: Первая кнопка",
    "Entities.gmod_subway_81-703.Buttons.IGLAButtons.IGLA1DSet": "ИГЛА: Первая кнопка вниз",
    "Entities.gmod_subway_81-703.Buttons.IGLAButtons.IGLA2USet": "ИГЛА: Вторая кнопка вверх",
    "Entities.gmod_subway_81-703.Buttons.IGLAButtons.IGLA2Set": "ИГЛА: Вторая кнопка",
    "Entities.gmod_subway_81-703.Buttons.IGLAButtons.IGLA2DSet": "ИГЛА: Вторая кнопка вниз",
    "Entities.gmod_subway_81-703.Buttons.IGLAButtons.!IGLASR": "ИГЛА: SR",
    "Entities.gmod_subway_81-703.Buttons.IGLAButtons.!IGLARX": "ИГЛА: RX",
    "Entities.gmod_subway_81-703.Buttons.IGLAButtons.!IGLAErr": "ИГЛА: Отказ",
    "Entities.gmod_subway_81-703.Buttons.IGLAButtons.!IGLAOSP": "ИГЛА: ОСП",
    "Entities.gmod_subway_81-703.Buttons.IGLAButtons.!IGLAPI": "ИГЛА: ПИ",
    "Entities.gmod_subway_81-703.Buttons.IGLAButtons.!IGLAOff": "ИГЛА: Откл",
    "Entities.gmod_subway_81-703.Buttons.Back1.R_UNchToggle": "УНЧ: Усилитель низких частот(звук салона)",
    "Entities.gmod_subway_81-703.Buttons.Back1.IGLAToggle": "АСОТП: ИГЛА",
    "Entities.gmod_subway_81-703.Buttons.Back1.RezMKSet": "Резервное включение мотор-компрессора",
    "Entities.gmod_subway_81-703.Buttons.ParkingBrake.ParkingBrakeLeft": "Поворот колеса ручного тормоза",
    "Entities.gmod_subway_81-703.Buttons.ParkingBrake.ParkingBrakeRight": "Поворот колеса ручного тормоза",
    "Entities.gmod_subway_81-703.Buttons.DriverValveBLDisconnect.DriverValveBLDisconnectToggle": "Кран двойной тяги тормозной магистрали",
    "Entities.gmod_subway_81-703.Buttons.Speedometer.!Speedometer": "Скоростемер",
    "Entities.gmod_subway_81-703.Buttons.AirDistributor.AirDistributorDisconnectToggle": "Выключение воздухораспределителя",



    "Entities.gmod_subway_81-703_2.Buttons.Stopkran.EmergencyBrakeValveToggle": "Стопкран",
    "Entities.gmod_subway_81-703_2.Buttons.HelperPanel.R_Program1Set": "Программа 1",
    "Entities.gmod_subway_81-703_2.Buttons.HelperPanel.R_Program2Set": "Программа 2",
    "Entities.gmod_subway_81-703_2.Buttons.HelperPanel.VDLSet": "ВДЛ: Выключатель левых дверей",
    "Entities.gmod_subway_81-703_2.Buttons.HelperPanel.VUD2LToggle": "Блокировка ВУД2",
    "Entities.gmod_subway_81-703_2.Buttons.HelperPanel.VUD2Toggle": "ВУД2: Выключатель управления дверьми",
    "Entities.gmod_subway_81-703_2.Buttons.PneumaticPanels.!CylinderPressure": "Тормозной манометр: Давление в тормозных цилиндрах (ТЦ)",
    "Entities.gmod_subway_81-703_2.Buttons.Battery.VBToggle": "ВБ: Выключатель аккумуляторной батареи (Вспомогательные цепи низкого напряжения)",
    "Entities.gmod_subway_81-703_2.Buttons.Battery.R_RadioToggle": "Питание радиоинформатора +50В",
    "Entities.gmod_subway_81-703_2.Buttons.Meters.!TotalVoltmeter": "Вольтметр высокого напряжения (кВ)",
    "Entities.gmod_subway_81-703_2.Buttons.Meters.!TotalAmpermeter": "Амперметр (А)",
    "Entities.gmod_subway_81-703_2.Buttons.AV2.RSTToggle": "РСТ: Радиостанция",
    "Entities.gmod_subway_81-703_2.Buttons.PassengerDoor.PassengerDoor": "Дверь из салона",
    "Entities.gmod_subway_81-703_2.Buttons.VU4.VUSToggle": "Переключатель: Ближний свет/Дальний свет",
    "Entities.gmod_subway_81-703_2.Buttons.AV1.VU3Toggle": "ВУ3: Освещение кабины\n",
    "Entities.gmod_subway_81-703_2.Buttons.AV1.VU2Toggle": "ВУ2: Аварийное освещение (45В)\n",
    "Entities.gmod_subway_81-703_2.Buttons.AV1.VU1Toggle": "ВУ1: Печь отопления кабины (3кВт)\n",
    "Entities.gmod_subway_81-703_2.Buttons.UAVAPanel.UAVAToggle": "УАВА: Универсальный Автоматический Выключатель Автостопа (отключение автостопа)",
    "Entities.gmod_subway_81-703_2.Buttons.UAVAPanel.UAVACToggle   ": "УАВА: Универсальный Автоматический Выключатель Автостопа (восстановление контактов)",
    "Entities.gmod_subway_81-703_2.Buttons.AirDistributor.AirDistributorDisconnectToggle": "Выключение воздухораспределителя",
    "Entities.gmod_subway_81-703_2.Buttons.GV.GVToggle": "Главный выключатель",
    "Entities.gmod_subway_81-703_2.Buttons.FrontPneumatic.FrontBrakeLineIsolationToggle": "Концевой кран тормозной магистрали",
    "Entities.gmod_subway_81-703_2.Buttons.FrontPneumatic.FrontTrainLineIsolationToggle": "Концевой кран напорной магистрали",
    "Entities.gmod_subway_81-703_2.Buttons.Tsepi.!BatteryVoltage": "Напряжение цепей управления",
    "Entities.gmod_subway_81-703_2.Buttons.RearPneumatic.RearTrainLineIsolationToggle": "Концевой кран напорной магистрали",
    "Entities.gmod_subway_81-703_2.Buttons.RearPneumatic.RearBrakeLineIsolationToggle": "Концевой кран тормозной магистрали",
    "Entities.gmod_subway_81-703_2.Buttons.ParkingBrake.ParkingBrakeLeft": "Поворот колеса ручного тормоза",
    "Entities.gmod_subway_81-703_2.Buttons.ParkingBrake.ParkingBrakeRight": "Поворот колеса ручного тормоза",
    "Entities.gmod_subway_81-703_2.Buttons.Back2.!HVFuses": "Блок высоковольтных предохранителей",
    "Entities.gmod_subway_81-703_2.Buttons.Back2.!DVR": "Дверной воздухораспределитель",
    "Entities.gmod_subway_81-703_2.Buttons.Main.RK": "Лампа: Вращение реостатного контроллера)",
    "Entities.gmod_subway_81-703_2.Buttons.Main.GreenRP": "Лампа: Зелёная РП (сигнализация перегрузки на поезде)",
    "Entities.gmod_subway_81-703_2.Buttons.Main.RedRP": "Лампа: Красная РП",
    "Entities.gmod_subway_81-703_2.Buttons.Main.Blue": "Лампа: Сигнализация дверей",
    "Entities.gmod_subway_81-703_2.Buttons.Main.DIPonSet": "Вкл. Осв.: Включение освещения",
    "Entities.gmod_subway_81-703_2.Buttons.Main.DIPoffSet": "Выкл. Осв.: Отключение освещения",
    "Entities.gmod_subway_81-703_2.Buttons.Main.VozvratRPSet": "ВРП: Возврат РП",
    "Entities.gmod_subway_81-703_2.Buttons.Main.KSNSet": "КСН: Принудительное срабатывание РП на неисправном вагоне (Сигнализация неисправности)",
    "Entities.gmod_subway_81-703_2.Buttons.Main.KRZDSet": "КРЗД: Кнопка резервного закрытия дверей",
    "Entities.gmod_subway_81-703_2.Buttons.Main.KSDSet": "КСД: Контроль сигнализации дверей(проверка СД)",
    "Entities.gmod_subway_81-703_2.Buttons.Main.KDPSet": "КДП: Правые двери",
    "Entities.gmod_subway_81-703_2.Buttons.Main.KDLSet": "КДЛ: Кнопка левых дверей",
    "Entities.gmod_subway_81-703_2.Buttons.Main.KU1Toggle": "МК: Включение мотор-компрессора",
    "Entities.gmod_subway_81-703_2.Buttons.Main.VUD1Toggle": "ВУД: Закрытие дверей",
    "Entities.gmod_subway_81-703_2.Buttons.Main.KRPSet": "КРП: Резервный пуск (ручное управление)",
    "Entities.gmod_subway_81-703_2.Buttons.KRR.KRRToggle": "KРР: Кнопка разворота реверсоров",
    "Entities.gmod_subway_81-703_2.Buttons.Back1.R_ZSToggle": "ЗС: Выключатель усиления громкоговорителя, звук в салоне",
    "Entities.gmod_subway_81-703_2.Buttons.Back1.IGLAToggle": "АСОТП: ИГЛА Вкл. (вверх)/Выкл. (вниз)",
    "Entities.gmod_subway_81-703_2.Buttons.Back1.RezMKSet": "Резервное включение мотор-компрессора",
    "Entities.gmod_subway_81-703_2.Buttons.CabinDoor.CabinDoor1": "Дверь в кабину машиниста",
    "Entities.gmod_subway_81-703_2.Buttons.Lamp.L_3Toggle": "Лампа: Подсветка приборов",
    "Entities.gmod_subway_81-703_2.Buttons.DriverValveBLDisconnect.DriverValveBLDisconnectToggle": "Кран двойной тяги тормозной магистрали",
    "Entities.gmod_subway_81-703_2.Buttons.DriverValveTLDisconnect.DriverValveTLDisconnectToggle": "Кран двойной тяги напорной магистрали",
    "Entities.gmod_subway_81-703_2.Buttons.AVMain.AV8BToggle": "АВ-8Б: Автоматическй выключатель (Вспомогательные цепи высокого напряжения)\n",
    "Entities.gmod_subway_81-703_2.Buttons.VU.VUToggle": "ВУ: Выключатель управления",
    "Entities.gmod_subway_81-703_2.Buttons.FrontDoor.FrontDoor": "Передняя дверь",
    "Entities.gmod_subway_81-703_2.Buttons.Speedometer.!Speedometer": "Скоростемер",
"Entities.gmod_subway_81-703_2.Buttons.PneumaticManometer.!LinesPressure": "Давление в магистралях (красная: тормозной, чёрная: напорной)"
}
]]
