return [[
{
	"Lang": "ru",
	"Name": "Russian",

	"Spawner.Title": "Спавнер поездов",
	"Spawner.Trains1": "Поездов",
	"Spawner.Trains2": "Максимально",
	"Spawner.WagNum": "Вагонов",
	"Spawner.AutoCouple": "Автоматически сцепить вагоны",

	"Entities.gmod_subway_81-717_mvm.Spawner.Texture.Name": "Окраска кузова",
	"Entities.gmod_subway_81-717_mvm.Spawner.PassTexture.Name": "Окраска салона",
	"Entities.gmod_subway_81-717_mvm.Spawner.CabTexture.Name": "Окраска кабины",
	"Entities.gmod_subway_81-717_mvm.Spawner.Announcer.Name": "Звук информатора",
	"Entities.gmod_subway_81-717_mvm.Spawner.Lighter.Name": "Присутствие зажигалки",
	"Entities.gmod_subway_81-717_mvm.Spawner.ARSType.Name": "Тип панели АРС",
	"Entities.gmod_subway_81-717_mvm.Spawner.ARSType.1": "Стандартная(квадратные лампы)",
	"Entities.gmod_subway_81-717_mvm.Spawner.ARSType.2": "Стандартная(круглые лампы)",
	"Entities.gmod_subway_81-717_mvm.Spawner.ARSType.3": "Киевские/СПБ",
	"Entities.gmod_subway_81-717_mvm.Spawner.ARSType.4": "Старая панель АРС",
	"Entities.gmod_subway_81-717_mvm.Spawner.Cran.Name": "Тип крана",
	"Entities.gmod_subway_81-717_mvm.Spawner.Cran.1": "334",
	"Entities.gmod_subway_81-717_mvm.Spawner.Cran.2": "013",
	"Entities.gmod_subway_81-717_mvm.Spawner.MaskType.Name": "Тип маски",
	"Entities.gmod_subway_81-717_mvm.Spawner.MaskType.1": "2-2",
	"Entities.gmod_subway_81-717_mvm.Spawner.MaskType.2": "2-2-2",
	"Entities.gmod_subway_81-717_mvm.Spawner.MaskType.3": "1-4-1 тип бампера 1",
	"Entities.gmod_subway_81-717_mvm.Spawner.MaskType.4": "1-4-1 тип бампера 2",
	"Entities.gmod_subway_81-717_mvm.Spawner.MaskType.5": "1-1",
	"Entities.gmod_subway_81-717_mvm.Spawner.MaskType.6": "Ретро",
	"Entities.gmod_subway_81-717_mvm.Spawner.LED.Name": "Светодиодные фары",
	"Entities.gmod_subway_81-717_mvm.Spawner.BPSNType.Name": "Тип БПСН",
	"Entities.gmod_subway_81-717_mvm.Spawner.BPSNType.1": "Старый звук с высоким тоном",
	"Entities.gmod_subway_81-717_mvm.Spawner.BPSNType.2": "Старый звук с средним тоном",
	"Entities.gmod_subway_81-717_mvm.Spawner.BPSNType.3": "Стандартный(из СПБ)",
	"Entities.gmod_subway_81-717_mvm.Spawner.BPSNType.4": "Стандартный(ТКЛ)",
	"Entities.gmod_subway_81-717_mvm.Spawner.BPSNType.5": "Стандартный",
	"Entities.gmod_subway_81-717_mvm.Spawner.BPSNType.6": "Киевский",
	"Entities.gmod_subway_81-717_mvm.Spawner.BPSNType.7": "Старый",
	"Entities.gmod_subway_81-717_mvm.Spawner.BPSNType.8": "Стандартный 2",
	"Entities.gmod_subway_81-717_mvm.Spawner.BPSNType.9": "Стандартный 3",
	"Entities.gmod_subway_81-717_mvm.Spawner.BPSNType.10": "Беззвучный(БПН-115)",
	"Entities.gmod_subway_81-717_mvm.Spawner.NewKV.Name": "Новая модель ГРКВ",
	"Entities.gmod_subway_81-717_mvm.Spawner.HornType.Name": "Питерский тифон",
	"Entities.gmod_subway_81-717_mvm.Spawner.RingType.Name": "Звук звонка",
	"Entities.gmod_subway_81-717_mvm.Spawner.RingType.1": "Старый",
	"Entities.gmod_subway_81-717_mvm.Spawner.RingType.2": "Стандартный с низким тоном",
	"Entities.gmod_subway_81-717_mvm.Spawner.RingType.3": "Стандартный с высоким тоном",
	"Entities.gmod_subway_81-717_mvm.Spawner.RingType.4": "Стандартный прерывистый с низким тоном",
	"Entities.gmod_subway_81-717_mvm.Spawner.RingType.5": "Стандартный прерывистый с высоким тоном",
	"Entities.gmod_subway_81-717_mvm.Spawner.NM.Name": "Давление напорной магистрали",
	"Entities.gmod_subway_81-717_mvm.Spawner.Battery.Name": "Вкл. батарею",
	"Entities.gmod_subway_81-717_mvm.Spawner.Switches.Name": "Вкл. все автоматики",
	"Entities.gmod_subway_81-717_mvm.Spawner.SwitchesR.Name": "Автоматики будут включены случайно",
	"Entities.gmod_subway_81-717_mvm.Spawner.DoorsL.Name": "Открыть левые двери",
	"Entities.gmod_subway_81-717_mvm.Spawner.DoorsR.Name": "Открыть правые двери",
	"Entities.gmod_subway_81-717_mvm.Spawner.GV.Name": "Вкл. главный выключатель",
	"Entities.gmod_subway_81-717_mvm.Spawner.PB.Name": "Вкл. стояночный тормоз",
	"Entities.gmod_subway_81-717_mvm.Spawner.BortLampType.Name": "Тип бортовых ламп",
	"Entities.gmod_subway_81-717_mvm.Spawner.BortLampType.1": "Горизнонтальные",
	"Entities.gmod_subway_81-717_mvm.Spawner.BortLampType.2": "Вертикальные",
	"Entities.gmod_subway_81-717_mvm.Spawner.MVM.Name": "Значок МВМ",
	"Entities.gmod_subway_81-717_mvm.Spawner.HandRail.Name": "Тип поручней",
	"Entities.gmod_subway_81-717_mvm.Spawner.HandRail.1": "Старый",
	"Entities.gmod_subway_81-717_mvm.Spawner.HandRail.2": "Новый",
	"Entities.gmod_subway_81-717_mvm.Spawner.SeatType.Name": "Тип сидушек",
	"Entities.gmod_subway_81-717_mvm.Spawner.SeatType.1": "Старый",
	"Entities.gmod_subway_81-717_mvm.Spawner.SeatType.2": "Новый",
	"Entities.gmod_subway_81-717_mvm.Spawner.LampType.Name": "Тип ламп",
	"Entities.gmod_subway_81-717_mvm.Spawner.LampType.1": "Тип 1",
	"Entities.gmod_subway_81-717_mvm.Spawner.LampType.2": "Тип 2",
	"Entities.gmod_subway_81-717_mvm.Spawner.LampType.3": "Тип 3",
	"Entities.gmod_subway_81-717_mvm.Spawner.Breakers.Name": "Автоматики справа",
	"Entities.gmod_subway_81-717_mvm.Spawner.Adverts.Name": "Вид рекламы",
	"Entities.gmod_subway_81-717_mvm.Spawner.Adverts.1": "Тип 1",
	"Entities.gmod_subway_81-717_mvm.Spawner.Adverts.2": "Тип 2",
	"Entities.gmod_subway_81-717_mvm.Spawner.Adverts.3": "Тип 3",
	"Entities.gmod_subway_81-717_mvm.Spawner.Adverts.4": "Без реклам",

	"Entities.gmod_subway_81-720.Spawner.Texture.Name": "Окраска кузова",
	"Entities.gmod_subway_81-720.Spawner.PassTexture.Name": "Окраска салона",
	"Entities.gmod_subway_81-720.Spawner.CabTexture.Name": "Окраска кабины",
	"Entities.gmod_subway_81-720.Spawner.Announcer.Name": "Информатор",
	"Entities.gmod_subway_81-720.Spawner.Scheme.Name": "Наддверные схемы",
	"Entities.gmod_subway_81-720.Spawner.PassSchemesInvert.Name": "Инвертировать наддверные схемы",
	"Entities.gmod_subway_81-720.Spawner.NM.Name": "Давление напорной магистрали",
	"Entities.gmod_subway_81-720.Spawner.Battery.Name": "Вкл. батарею",
	"Entities.gmod_subway_81-720.Spawner.BRU.Name": "Вкл. БРУ(ГВ)",
	"Entities.gmod_subway_81-720.Spawner.PVZR.Name": "Автоматики на ПВЗ будут включены случайно",
	"Entities.gmod_subway_81-720.Spawner.PPZ.Name": "Вкл. все поездные автоматики",
	"Entities.gmod_subway_81-720.Spawner.PPZDepot.Name": "Выкл. автоматики как в депо",
	"Entities.gmod_subway_81-720.Spawner.PPZR.Name": "Автоматики на ППЗ будут включены случайно",
	"Entities.gmod_subway_81-720.Spawner.DoorsL.Name": "Открыть левые двери",
	"Entities.gmod_subway_81-720.Spawner.DoorsR.Name": "Открыть правые двери",

	"Entities.gmod_subway_81-722.Spawner.Texture.Name": "Окраска кузова",
	"Entities.gmod_subway_81-722.Spawner.PassTexture.Name": "Окраска салона",
	"Entities.gmod_subway_81-722.Spawner.CabTexture.Name": "Окраска кабины",
	"Entities.gmod_subway_81-722.Spawner.Announcer.Name": "Информатор",
	"Entities.gmod_subway_81-722.Spawner.Scheme.Name": "Наддверные схемы",
	"Entities.gmod_subway_81-722.Spawner.SarmatInvert.Name": "Инвертировать наддверные схемы",
	"Entities.gmod_subway_81-722.Spawner.NM.Name": "Давление напорной магистрали",
	"Entities.gmod_subway_81-722.Spawner.Battery.Name": "Вкл. батарею",
	"Entities.gmod_subway_81-722.Spawner.Switches.Name": "Вкл. все автоматики",
	"Entities.gmod_subway_81-722.Spawner.SwitchesR.Name": "Автоматики будут включены случайно",
	"Entities.gmod_subway_81-722.Spawner.DoorsL.Name": "Открыть левые двери",
	"Entities.gmod_subway_81-722.Spawner.DoorsR.Name": "Открыть правые двери",


	"Entities.gmod_subway_ezh.Spawner.Texture.Name": "Окраска кузова",
	"Entities.gmod_subway_ezh.Spawner.PassTexture.Name": "Окраска салона",
	"Entities.gmod_subway_ezh.Spawner.CabTexture.Name": "Окраска кабины",
	"Entities.gmod_subway_ezh.Spawner.Announcer.Name": "Информатор",
	"Entities.gmod_subway_ezh.Spawner.HornType.Name": "Питерский тифон",
	"Entities.gmod_subway_ezh.Spawner.NM.Name": "Давление напорной магистрали",
	"Entities.gmod_subway_ezh.Spawner.Battery.Name": "Вкл. батарею",
	"Entities.gmod_subway_ezh.Spawner.AV8B.Name": "Вкл. АВ8Б",
	"Entities.gmod_subway_ezh.Spawner.DoorsL.Name": "Открыть левые двери",
	"Entities.gmod_subway_ezh.Spawner.DoorsR.Name": "Открыть правые двери",
	"Entities.gmod_subway_ezh.Spawner.GV.Name": "Вкл. главный выключатель",

	"Entities.gmod_subway_em508.Spawner.Texture.Name": "Окраска кузова",
	"Entities.gmod_subway_em508.Spawner.PassTexture.Name": "Окраска салона",
	"Entities.gmod_subway_em508.Spawner.CabTexture.Name": "Окраска кабины",
	"Entities.gmod_subway_em508.Spawner.Announcer.Name": "Информатор",
	"Entities.gmod_subway_em508.Spawner.HornType.Name": "Питерский тифон",
	"Entities.gmod_subway_em508.Spawner.NM.Name": "Давление напорной магистрали",
	"Entities.gmod_subway_em508.Spawner.Battery.Name": "Вкл. батарею",
	"Entities.gmod_subway_em508.Spawner.AV8B.Name": "Вкл. АВ8Б",
	"Entities.gmod_subway_em508.Spawner.DoorsL.Name": "Открыть левые двери",
	"Entities.gmod_subway_em508.Spawner.DoorsR.Name": "Открыть правые двери",
	"Entities.gmod_subway_em508.Spawner.GV.Name": "Вкл. главный выключатель",

	"Entities.gmod_subway_ezh3.Spawner.Texture.Name": "Окраска кузова",
	"Entities.gmod_subway_ezh3.Spawner.PassTexture.Name": "Окраска салона",
	"Entities.gmod_subway_ezh3.Spawner.CabTexture.Name": "Окраска кабины",
	"Entities.gmod_subway_ezh3.Spawner.Announcer.Name": "Информатор",
	"Entities.gmod_subway_ezh3.Spawner.HornType.Name": "Питерский тифон",
	"Entities.gmod_subway_ezh3.Spawner.NM.Name": "Давление напорной магистрали",
	"Entities.gmod_subway_ezh3.Spawner.Battery.Name": "Вкл. батарею",
	"Entities.gmod_subway_ezh3.Spawner.AV8B.Name": "Вкл. АВ8Б",
	"Entities.gmod_subway_ezh3.Spawner.DoorsL.Name": "Открыть левые двери",
	"Entities.gmod_subway_ezh3.Spawner.DoorsR.Name": "Открыть правые двери",
	"Entities.gmod_subway_ezh3.Spawner.GV.Name": "Вкл. главный выключатель",

	"Entities.gmod_subway_81-717_lvz.Spawner.Texture.Name": "Окраска кузова",
	"Entities.gmod_subway_81-717_lvz.Spawner.PassTexture.Name": "Окраска салона",
	"Entities.gmod_subway_81-717_lvz.Spawner.CabTexture.Name": "Окраска кабины",
	"Entities.gmod_subway_81-717_lvz.Spawner.Announcer.Name": "Информатор",
	"Entities.gmod_subway_81-717_lvz.Spawner.Lighter.Name": "Присутствие зажигалки",
	"Entities.gmod_subway_81-717_lvz.Spawner.Cran.Name": "Тип крана",
	"Entities.gmod_subway_81-717_lvz.Spawner.Cran.1": "334",
	"Entities.gmod_subway_81-717_lvz.Spawner.Cran.2": "013",
	"Entities.gmod_subway_81-717_lvz.Spawner.MaskType.Name": "Тип маски",
	"Entities.gmod_subway_81-717_lvz.Spawner.MaskType.1": "1-4-1",
	"Entities.gmod_subway_81-717_lvz.Spawner.MaskType.2": "2-2(снизу)-2",
	"Entities.gmod_subway_81-717_lvz.Spawner.MaskType.3": "2-2",
	"Entities.gmod_subway_81-717_lvz.Spawner.MaskType.4": "2-2-2",
	"Entities.gmod_subway_81-717_lvz.Spawner.MaskType.5": "1-3-1",
	"Entities.gmod_subway_81-717_lvz.Spawner.LED.Name": "Светодиодные фары",
	"Entities.gmod_subway_81-717_lvz.Spawner.BPSNType.Name": "Тип БПСН",
	"Entities.gmod_subway_81-717_lvz.Spawner.BPSNType.1": "Старый звук с высоким тоном",
	"Entities.gmod_subway_81-717_lvz.Spawner.BPSNType.2": "Старый звук с средним тоном",
	"Entities.gmod_subway_81-717_lvz.Spawner.BPSNType.3": "Стандартный(из СПБ)",
	"Entities.gmod_subway_81-717_lvz.Spawner.BPSNType.4": "Стандартный(ТКЛ)",
	"Entities.gmod_subway_81-717_lvz.Spawner.BPSNType.5": "Стандартный",
	"Entities.gmod_subway_81-717_lvz.Spawner.BPSNType.6": "Киевский",
	"Entities.gmod_subway_81-717_lvz.Spawner.BPSNType.7": "Старый",
	"Entities.gmod_subway_81-717_lvz.Spawner.BPSNType.8": "Стандартный 2",
	"Entities.gmod_subway_81-717_lvz.Spawner.BPSNType.9": "Стандартный 3",
	"Entities.gmod_subway_81-717_lvz.Spawner.BPSNType.10": "Беззвучный(БПН-115)",
    "Entities.gmod_subway_81-717_lvz.Spawner.NewKV.Name": "Новая модель ГРКВ",
    "Entities.gmod_subway_81-717_lvz.Spawner.HornType.Name": "Питерский тифон",
    "Entities.gmod_subway_81-717_lvz.Spawner.RingType.Name": "Звук звонка",
    "Entities.gmod_subway_81-717_lvz.Spawner.RingType.1": "Старый",
    "Entities.gmod_subway_81-717_lvz.Spawner.RingType.2": "Стандартный с низким тоном",
    "Entities.gmod_subway_81-717_lvz.Spawner.RingType.3": "Стандартный с высоким тоном",
    "Entities.gmod_subway_81-717_lvz.Spawner.RingType.4": "Стандартный прерывистый с низким тоном",
    "Entities.gmod_subway_81-717_lvz.Spawner.RingType.5": "Стандартный прерывистый с высоким тоном",
    "Entities.gmod_subway_81-717_lvz.Spawner.NM.Name": "Давление напорной магистрали",
    "Entities.gmod_subway_81-717_lvz.Spawner.Battery.Name": "Вкл. батарею",
    "Entities.gmod_subway_81-717_lvz.Spawner.Switches.Name": "Вкл. все автоматики",
    "Entities.gmod_subway_81-717_lvz.Spawner.SwitchesR.Name": "Автоматики будут включены случайно",
    "Entities.gmod_subway_81-717_lvz.Spawner.DoorsL.Name": "Открыть левые двери",
    "Entities.gmod_subway_81-717_lvz.Spawner.DoorsR.Name": "Открыть правые двери",
    "Entities.gmod_subway_81-717_lvz.Spawner.GV.Name": "Вкл. главный выключатель",
    "Entities.gmod_subway_81-717_lvz.Spawner.PB.Name": "Вкл. стояночный тормоз",
    "Entities.gmod_subway_81-717_lvz.Spawner.BortLampType.Name": "Тип бортовых ламп",
    "Entities.gmod_subway_81-717_lvz.Spawner.BortLampType.1": "Горизнонтальные",
    "Entities.gmod_subway_81-717_lvz.Spawner.BortLampType.2": "Вертикальные",
    "Entities.gmod_subway_81-717_lvz.Spawner.HandRail.Name": "Тип поручней",
    "Entities.gmod_subway_81-717_lvz.Spawner.HandRail.1": "Старый",
    "Entities.gmod_subway_81-717_lvz.Spawner.HandRail.2": "Новый",
    "Entities.gmod_subway_81-717_lvz.Spawner.SeatType.Name": "Тип сидушек",
    "Entities.gmod_subway_81-717_lvz.Spawner.SeatType.1": "Старый",
    "Entities.gmod_subway_81-717_lvz.Spawner.SeatType.2": "Новый",
    "Entities.gmod_subway_81-717_lvz.Spawner.LampType.Name": "Тип ламп",
    "Entities.gmod_subway_81-717_lvz.Spawner.LampType.1": "Тип 1",
    "Entities.gmod_subway_81-717_lvz.Spawner.LampType.2": "Тип 2",
    "Entities.gmod_subway_81-717_lvz.Spawner.LampType.3": "Тип 3",
    "Entities.gmod_subway_81-717_lvz.Spawner.Breakers.Name": "Автоматики справа",
    "Entities.gmod_subway_81-717_lvz.Spawner.Adverts.Name": "Вид рекламы",
    "Entities.gmod_subway_81-717_lvz.Spawner.Adverts.1": "Тип 1",
    "Entities.gmod_subway_81-717_lvz.Spawner.Adverts.2": "Тип 2",
    "Entities.gmod_subway_81-717_lvz.Spawner.Adverts.3": "Тип 3",
    "Entities.gmod_subway_81-717_lvz.Spawner.Adverts.4": "Без реклам",

	"Entities.gmod_subway_81-703.Spawner.Texture.Name": "Окраска кузова",
	"Entities.gmod_subway_81-703.Spawner.PassTexture.Name": "Окраска салона",
	"Entities.gmod_subway_81-703.Spawner.CabTexture.Name": "Окраска кабины",
	"Entities.gmod_subway_81-703.Spawner.Announcer.Name": "Информатор",
	"Entities.gmod_subway_81-703.Spawner.HornType.Name": "Питерский тифон",
	"Entities.gmod_subway_81-703.Spawner.NM.Name": "Давление напорной магистрали",
	"Entities.gmod_subway_81-703.Spawner.Battery.Name": "Вкл. батарею",
	"Entities.gmod_subway_81-703.Spawner.AV8B.Name": "Вкл. АВ8Б",
	"Entities.gmod_subway_81-703.Spawner.DoorsL.Name": "Открыть левые двери",
	"Entities.gmod_subway_81-703.Spawner.DoorsR.Name": "Открыть правые двери",
	"Entities.gmod_subway_81-703.Spawner.GV.Name": "Вкл. главный выключатель",



	"Spawner.Close": "Закрыть",
	"Spawner.Spawn": "Готово"
}
]]
