--------------------------------------------------------------------------------
-- Resistor arrays calculations
--------------------------------------------------------------------------------
-- Copyright (C) 2013-2018 Metrostroi Team & FoxWorks Aerospace s.r.o.
-- Contains proprietary code. See license.txt for additional information.
--------------------------------------------------------------------------------
--[[
Rxx   PS    PP1   PP2   PT    PS1   PS2   PT1   PT2   S1     S2
R01 = 4.176 0.000 0.000 1.329 3.267 0.909 1.329
R02 = 4.176 0.000 0.000 1.329 3.267 0.909 1.329
R03 = 3.048 0.000 0.000 1.189 2.139 0.909 1.189
R04 = 2.310 0.000 0.000 1.057 1.401 0.909 1.057
R05 = 1.818 0.000 0.000 0.941 0.909 0.909 0.941
R06 = 1.669 0.000 0.000 0.899 0.760 0.909 0.899
R07 = 1.520 0.149 0.000 0.854 0.760 0.760 0.854
R08 = 1.331 0.149 0.149 0.791 0.760 0.571 0.791
R09 = 1.142 0.149 0.338 0.720 0.571 0.571 0.720
R10 = 0.896 0.338 0.338 0.614 0.325 0.571 0.614
R11 = 0.650 0.584 0.338 0.488 0.325 0.325 0.488
R12 = 0.451 0.584 0.584 0.366 0.325 0.126 0.366
R13 = 0.252 0.584 0.783 0.223 0.126 0.126 0.223
R14 = 0.126 0.783 0.783 0.118 0.000 0.126 0.118
R15 = 0.000 0.909 0.783 0.000 0.000 0.000 0.000
R16 = 0.000 0.909 0.909 0.000 0.000 0.000 0.000
R17 = 0.000 0.909 0.909 0.000 0.000 0.000 0.000
R18 = 0.000 0.909 0.909 0.000 0.000 0.000 0.000
]]--

--------------------------------------------------------------------------------
-- Resistor arrays calculations - auto-generated by gen.lua
--------------------------------------------------------------------------------
Metrostroi.DefineSystem("Gen_Res_717_5m")

local R = {}

local P13_11
local P11_12
local P12_9
local P9_8
local P8_7
local P1_7
local P4_1
local P3_4
local P17_20
local P20_25
local P25_21
local P21_22
local P22_23
local P10_42

local P29_P28
local P30_P29
local P31_P30
local L76_P31

local P35_L18
local P36_P35
local P37_P36
local L74_P37
--

function TRAIN_SYSTEM.InitializeResistances_81_717(Train)
    P13_11 = Train.KF_47A["P13_11"]
    P11_12 = Train.KF_47A["P11_12"]
    P12_9 = Train.KF_47A["P12_9"]
    P9_8 = Train.KF_47A["P9_8"]
    P8_7 = Train.KF_47A["P8_7"]
    P1_7 = Train.KF_47A["P1_7"]
    P4_1 = Train.KF_47A["P4_1"]
    P3_4 = Train.KF_47A["P3_4"]

    P17_20 = Train.KF_47A["P17_20"]
    P20_25 = Train.KF_47A["P20_25"]
    P25_21 = Train.KF_47A["P25_21"]
    P21_22 = Train.KF_47A["P21_22"]
    P22_23 = Train.KF_47A["P22_23"]

    P10_42 = Train.KF_47A["P10_42"]

    P29_P28 = Train.KF_50A["P29-P28"]
    P30_P29 = Train.KF_50A["P30-P29"]
    P31_P30 = Train.KF_50A["P31-P30"]
    L76_P31 = Train.KF_50A["L76-P31"]

    P35_L18 = Train.KF_50A["P35-L18"]
    P36_P35 = Train.KF_50A["P36-P35"]
    P37_P36 = Train.KF_50A["P37-P36"]
    L74_P37 = Train.KF_50A["L74-P37"]
end

function TRAIN_SYSTEM.R1C1(Train)
	local RK = Train.RheostatController
	local PM = Train.PositionSwitch.RPM
	local PT = Train.PositionSwitch.RPT
	R[1] = ((RK[17])^-1 + (P12_9)^-1)^-1
	R[2] = ((RK[18])^-1 + (P11_12+R[1])^-1)^-1
	R[3] = ((RK[19])^-1 + (P13_11+R[2])^-1)^-1
	R[4] = ((RK[5])^-1 + (RK[3]+P3_4)^-1)^-1
	R[5] = ((RK[7])^-1 + (P4_1+R[4])^-1)^-1
	R[6] = ((RK[9])^-1 + (R[5]+P1_7)^-1)^-1
	R[7] = ((RK[11])^-1 + (R[6]+P8_7)^-1)^-1
	R[8] = ((RK[13])^-1 + (R[7]+P9_8)^-1)^-1
	return R[8]+R[3]
end

function TRAIN_SYSTEM.R1C2(Train)
	local RK = Train.RheostatController
	local PM = Train.PositionSwitch.RPM
	local PT = Train.PositionSwitch.RPT
	R[1] = ((RK[17])^-1 + (P12_9)^-1)^-1
	R[2] = ((RK[18])^-1 + (RK[19]+P13_11)^-1)^-1
	R[3] = ((P11_12+R[1])^-1 + (R[2])^-1)^-1
	R[4] = ((RK[7])*(P1_7)+(RK[7])*(P4_1)+(P1_7)*(P4_1))/(RK[7])
	R[5] = ((RK[7])*(P1_7)+(RK[7])*(P4_1)+(P1_7)*(P4_1))/(P1_7)
	R[6] = ((RK[7])*(P1_7)+(RK[7])*(P4_1)+(P1_7)*(P4_1))/(P4_1)
	R[7] = ((RK[9])^-1 + (R[6])^-1)^-1
	R[8] = ((RK[5])^-1 + (R[5])^-1)^-1
	R[9] = ((R[8])*(R[4])+(R[8])*(P3_4)+(R[4])*(P3_4))/(R[8])
	R[10] = ((R[8])*(R[4])+(R[8])*(P3_4)+(R[4])*(P3_4))/(R[4])
	R[11] = ((R[8])*(R[4])+(R[8])*(P3_4)+(R[4])*(P3_4))/(P3_4)
	R[12] = ((R[11])^-1 + (R[7])^-1)^-1
	R[13] = ((R[10])^-1 + (RK[3])^-1)^-1
	R[14] = ((R[9])*(R[12])+(R[9])*(P8_7)+(R[12])*(P8_7))/(R[9])
	R[15] = ((R[9])*(R[12])+(R[9])*(P8_7)+(R[12])*(P8_7))/(R[12])
	R[16] = ((R[9])*(R[12])+(R[9])*(P8_7)+(R[12])*(P8_7))/(P8_7)
	R[17] = ((RK[11])^-1 + (R[14])^-1)^-1
	R[18] = ((R[16])^-1 + (R[13])^-1)^-1
	R[19] = ((RK[13])*(P9_8)+(RK[13])*(R[3])+(P9_8)*(R[3]))/(RK[13])
	R[20] = ((RK[13])*(P9_8)+(RK[13])*(R[3])+(P9_8)*(R[3]))/(P9_8)
	R[21] = ((RK[13])*(P9_8)+(RK[13])*(R[3])+(P9_8)*(R[3]))/(R[3])
	R[22] = ((R[17])^-1 + (R[21])^-1)^-1
	R[23] = ((R[22])^-1 + (R[20]+R[19])^-1)^-1
	R[24] = ((R[23]+R[15])^-1 + (R[18])^-1)^-1
	return R[24]
end

function TRAIN_SYSTEM.R2C1(Train)
	local RK = Train.RheostatController
	local PM = Train.PositionSwitch.RPM
	local PT = Train.PositionSwitch.RPT
	R[1] = ((RK[6])^-1 + (RK[4]+P17_20)^-1)^-1
	R[2] = ((RK[8])^-1 + (P20_25+R[1])^-1)^-1
	R[3] = ((RK[10])^-1 + (P25_21+R[2])^-1)^-1
	R[4] = ((RK[12])^-1 + (P21_22+R[3])^-1)^-1
	R[5] = ((RK[14])^-1 + (R[4]+P22_23)^-1)^-1
	return R[5]
end

function TRAIN_SYSTEM.R2C2(Train)
	local RK = Train.RheostatController
	local PM = Train.PositionSwitch.RPM
	local PT = Train.PositionSwitch.RPT
	R[1] = ((RK[12])^-1 + (RK[14]+P22_23)^-1)^-1
	R[2] = ((RK[10])^-1 + (P21_22+R[1])^-1)^-1
	R[3] = ((RK[8])^-1 + (R[2]+P25_21)^-1)^-1
	R[4] = ((R[3]+P20_25)^-1 + (RK[6])^-1)^-1
	R[5] = ((R[4]+P17_20)^-1 + (RK[4])^-1)^-1
	return R[5]
end

function TRAIN_SYSTEM.R3(Train)
	local RK = Train.RheostatController
	local PM = Train.PositionSwitch.RPM
	local PT = Train.PositionSwitch.RPT
	R[1] = ((RK[17])^-1 + (P12_9)^-1)^-1
	R[2] = ((RK[18])^-1 + (P11_12+R[1])^-1)^-1
	R[3] = ((RK[19])^-1 + (P13_11+R[2])^-1)^-1
	R[4] = ((RK[5])^-1 + (RK[3]+P3_4)^-1)^-1
	R[5] = ((RK[7])^-1 + (P4_1+R[4])^-1)^-1
	R[6] = ((RK[9])^-1 + (P1_7+R[5])^-1)^-1
	R[7] = ((RK[11])^-1 + (P8_7+R[6])^-1)^-1
	R[8] = ((RK[13])^-1 + (P9_8+R[7])^-1)^-1
	R[9] = ((RK[6])^-1 + (RK[4]+P17_20)^-1)^-1
	R[10] = ((RK[8])^-1 + (P20_25+R[9])^-1)^-1
	R[11] = ((RK[10])^-1 + (P25_21+R[10])^-1)^-1
	R[12] = ((RK[12])^-1 + (P21_22+R[11])^-1)^-1
	R[13] = ((RK[14])^-1 + (P22_23+R[12])^-1)^-1
	R[14] = ((P10_42)^-1 + (P10_42)^-1)^-1
	R[15] = ((PT+PT+R[14])^-1 + (R[13]+R[3]+R[8])^-1)^-1
	return R[15]
end

function TRAIN_SYSTEM.S1(Train)
	local RK = Train.RheostatController
	local PM = Train.PositionSwitch.RPM
	local PT = Train.PositionSwitch.RPT
	R[1] = ((L76_P31)^-1 + (RK[21])^-1)^-1
	R[2] = ((RK[23])^-1 + (P31_P30+R[1])^-1)^-1
	R[3] = ((P30_P29+R[2])^-1 + (RK[25])^-1)^-1
	return P29_P28+R[3]
end

function TRAIN_SYSTEM.S2(Train)
	local RK = Train.RheostatController
	local PM = Train.PositionSwitch.RPM
	local PT = Train.PositionSwitch.RPT
	R[1] = ((L74_P37)^-1 + (RK[22])^-1)^-1
	R[2] = ((RK[24])^-1 + (P37_P36+R[1])^-1)^-1
	R[3] = ((P36_P35+R[2])^-1 + (RK[26])^-1)^-1
	return P35_L18+R[3]
end

