return [[
{
  "Lang": "cz",
  "Name": "Čeština",

  "Entities.gmod_subway_81-720.Buttons.VityazButtons.VityazF1Set": "Vityaz: F1",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.VityazF2Set": "Vityaz: Následující strana",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.VityazF3Set": "Vityaz: Předešlá strana",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.VityazF4Set": "Vityaz: Hlavní strana",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.Vityaz1Set": "Vityaz: 1",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.Vityaz4Set": "Vityaz: 4",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.Vityaz7Set": "Vityaz: 7",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.Vityaz2Set": "Vityaz: 2",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.Vityaz5Set": "Vityaz: 5",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.Vityaz8Set": "Vityaz: 8",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.Vityaz0Set": "Vityaz: 0",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.Vityaz3Set": "Vityaz: 3",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.Vityaz6Set": "Vityaz: 6",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.Vityaz9Set": "Vityaz: 9",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.VityazF5Set": "Vityaz: Smazat",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.VityazF6Set": "Vityaz: Nahoru\\Rychlost",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.VityazF7Set": "Vityaz: Dolů\\Proudy",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.VityazF8Set": "Vityaz: Zadat\\Vybavení vozu",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.VityazF9Set": "Vityaz: Vybrat\\Správa vybavení vozu",
  "Entities.gmod_subway_81-720.Buttons.RV.EmerX1Set": "Nouzová J-1",
  "Entities.gmod_subway_81-720.Buttons.RV.EmerX2Set": "Nouzová J-2",
  "Entities.gmod_subway_81-720.Buttons.RV.EmerCloseDoorsSet": "Dveře nouze",
  "Entities.gmod_subway_81-720.Buttons.RV.EmergencyDoorsToggle": "Rezervní dveře",
  "Entities.gmod_subway_81-720.Buttons.BackVent.VentCondMode-": "Chod ventilace: +",
  "Entities.gmod_subway_81-720.Buttons.BackVent.VentCondMode+": "Chod ventilace: -",
  "Entities.gmod_subway_81-720.Buttons.BackVent.VentHeatMode+": "+",
  "Entities.gmod_subway_81-720.Buttons.BackVent.VentHeatMode-": "-",
  "Entities.gmod_subway_81-720.Buttons.BackVent.VentStrengthMode-": "Intenzita ventilace: +",
  "Entities.gmod_subway_81-720.Buttons.BackVent.VentStrengthMode+": "Intenzita ventilace: -",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV1Toggle": "SF1: Napájení obvodů řízení",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV2Toggle": "SF2: Napájení BUV (ovládání vozu)",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV3Toggle": "SF3: Napájení BUTP (ovládánáí trakčních motorů)",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV4Toggle": "SF4: Řízení BUTP",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV5Toggle": "SF5: Nouzové řízení BUTP",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV6Toggle": "SF6: Napájení BUTP",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV7Toggle": "SF7: BBE",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV8Toggle": "SF8: Řízení BV",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV9Toggle": "SF9: Napájení BV (přetížení relé)",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV10Toggle": "SF10: PPO",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV11Toggle": "SF11: Kompresor",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV12Toggle": "SF12: Zavření dveří",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV13Toggle": "SF13: Otevřít levé dveře",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV14Toggle": "SF14: Otevřít pravé dveře",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV15Toggle": "SF15: Přední dveře",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV16Toggle": "SF16: Vlakový rozhlas",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV17Toggle": "SF17: Nouzové spojení",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV18Toggle": "SF18: Rezerva",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV19Toggle": "SF19: Napájení osvětlení interiéru",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV20Toggle": "SF20: Osvětlení nouze",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV21Toggle": "SF21: Senzor rychlosti",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV22Toggle": "SF22: Parkovací brzda",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV23Toggle": "SF23: Ovládání ventilace 1. skupiny",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV24Toggle": "SF24: Ovládání ventilace 2. skupiny",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV25Toggle": "SF25: Napájení ventilace 1. skupiny",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV26Toggle": "SF26: Napájení ventilace 2. skupiny",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV27Toggle": "SF27: Napájení zdroje",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV28Toggle": "SF28: Napájení ZKK",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV29Toggle": "SF29: Sběrač proudu",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV30Toggle": "SF30: Směrová tabule",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV31Toggle": "SF31: Rezerva",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV32Toggle": "SF32: Rezerva",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV33Toggle": "SF33: Rezerva",
  "Entities.gmod_subway_81-720.Buttons.ASNP.R_ASNPMenuSet": "ASNP: Menu",
  "Entities.gmod_subway_81-720.Buttons.ASNP.R_ASNPUpSet": "ASNP: Nahoru",
  "Entities.gmod_subway_81-720.Buttons.ASNP.R_ASNPDownSet": "ASNP: Dolů",
  "Entities.gmod_subway_81-720.Buttons.ASNP.R_ASNPOnToggle": "ASNP: Zapnout",
  "Entities.gmod_subway_81-720.Buttons.PneumoHelper1.!BrakeCylinder": "Brzdový válec",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF1Toggle": "SF1: Hlavní napájení",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF2Toggle": "SF2: Hlavní řízení",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF3Toggle": "SF3: Nouzové řízení",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF4Toggle": "SF4: BARS",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF5Toggle": "SF5: BUP",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF6Toggle": "SF6: BKCU",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF7Toggle": "SF7: BARS",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF8Toggle": "SF8: Vlakový rozhlas",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF9Toggle": "SF9: Radiostanice",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF10Toggle": "SF10: Pozice vozu",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF11Toggle": "SF11: Směr jízdy",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF12Toggle": "SF12: Světla 1. skupina",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF13Toggle": "SF13: Světla 2. skupina",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF14Toggle": "SF14: Parkovací světla",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF15Toggle": "SF15: Osvětlení kabiny",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF16Toggle": "SF16: Topné těleso",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF17Toggle": "SF17: Klimatizace kabiny",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF18Toggle": "SF18: Mazaní okolků",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF19Toggle": "SF19: Napájení hlavního KRM",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF20Toggle": "SF20: Nouzové napájení KRM",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF21Toggle": "SF21: Otevírání dveří",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF22Toggle": "SF22: Zavírání dveří",
  "Entities.gmod_subway_81-720.Buttons.BTO.K29Toggle": "KRMSH (ventil brzdiče)",
  "Entities.gmod_subway_81-720.Buttons.PassengerDoor2.PassengerDoor": "Dveře z kabiny do interiéru",
  "Entities.gmod_subway_81-720.Buttons.VoltHelper2.!HV": "Voltmeter (kV)",
  "Entities.gmod_subway_81-720.Buttons.VoltHelper2.!I1_3": "Napájení trakčních motorů 1. skupiny (A)",
  "Entities.gmod_subway_81-720.Buttons.VoltHelper2.!I2_4": "Napájení trakčních motorů 2. skupiny (A)",
  "Entities.gmod_subway_81-720.Buttons.GV.GVToggle": "Hlavní vypínač",
  "Entities.gmod_subway_81-720.Buttons.RearPneumatic.RearBrakeLineIsolationToggle": "Izolační ventil brzdového potrubí",
  "Entities.gmod_subway_81-720.Buttons.RearPneumatic.RearTrainLineIsolationToggle": "Izolační ventil hlavního potrubí",
  "Entities.gmod_subway_81-720.Buttons.RearDoor1.RearDoor": "Zadní dveře",
  "Entities.gmod_subway_81-720.Buttons.RearDoor.RearDoor": "Zadní dveře",
  "Entities.gmod_subway_81-720.Buttons.BackDown.Pant1Toggle": "Odpojení sběrače proudů 1. skupiny",
  "Entities.gmod_subway_81-720.Buttons.BackDown.Pant2Toggle": "Odpojení sběrače proudů 2. skupiny",
  "Entities.gmod_subway_81-720.Buttons.BackDown.Vent1Toggle": "Ventilace 1. skupina",
  "Entities.gmod_subway_81-720.Buttons.BackDown.Vent2Toggle": "Ventilace 2. skupina",
  "Entities.gmod_subway_81-720.Buttons.BackDown.VentToggle": "",
  "Entities.gmod_subway_81-720.Buttons.BackDown.PassLightToggle": "Osvětlení interiéru",
  "Entities.gmod_subway_81-720.Buttons.BackDown.CabLightToggle": "Osvětlení kabiny",
  "Entities.gmod_subway_81-720.Buttons.BackDown.Headlights1Toggle": "Světla 1. skupina",
  "Entities.gmod_subway_81-720.Buttons.BackDown.Headlights2Toggle": "Světla 2. skupina",
  "Entities.gmod_subway_81-720.Buttons.BackDown.ParkingBrakeToggle": "Parkovací brzda",
  "Entities.gmod_subway_81-720.Buttons.BackDown.TorecDoorsToggle": "Přední dveře",
  "Entities.gmod_subway_81-720.Buttons.BackDown.BBERToggle": "Nouzové zapnutí BBE",
  "Entities.gmod_subway_81-720.Buttons.BackDown.BBEToggle": "BBE",
  "Entities.gmod_subway_81-720.Buttons.BackDown.CompressorToggle": "Kompresor",
  "Entities.gmod_subway_81-720.Buttons.BackDown.CabLightStrengthToggle": "Napájení osvětlení kabiny",
  "Entities.gmod_subway_81-720.Buttons.BackDown.AppLights1Toggle": "Osvětlení vybavení vozu",
  "Entities.gmod_subway_81-720.Buttons.BackDown.AppLights2Toggle": "",
  "Entities.gmod_subway_81-720.Buttons.BackDown.BARSBlock-": "Blokování nefunkčních jednotek BARS: -",
  "Entities.gmod_subway_81-720.Buttons.BackDown.BARSBlock+": "Blokování nefunkčních jednotek BARS: +",
  "Entities.gmod_subway_81-720.Buttons.BackDown.BatteryToggle": "Baterie zapnuto/vypnuto",
  "Entities.gmod_subway_81-720.Buttons.BackDown.ALSFreqToggle": "Dekodér ALS",
  "Entities.gmod_subway_81-720.Buttons.VoltHelper1.!Battery": "Napájení obvodů řízení",
  "Entities.gmod_subway_81-720.Buttons.PassengerDoor.PassengerDoor": "Dveře z kabiny do interiéru",
  "Entities.gmod_subway_81-720.Buttons.CabinDoorR.CabinDoorRight": "Dveře kabiny",
  "Entities.gmod_subway_81-720.Buttons.CabinDoorL.CabinDoorLeft": "Dveře kabiny",
  "Entities.gmod_subway_81-720.Buttons.FrontPneumatic.FrontBrakeLineIsolationToggle": "Izolační ventil brzdového potrubí",
  "Entities.gmod_subway_81-720.Buttons.FrontPneumatic.FrontTrainLineIsolationToggle": "Izolační ventil hlavního potrubí",
  "Entities.gmod_subway_81-720.Buttons.PUL.DoorSelectLToggle": "Dveře levé (předvolba)",
  "Entities.gmod_subway_81-720.Buttons.PUL.DoorSelectRToggle": "Dveře pravé (předvolba)",
  "Entities.gmod_subway_81-720.Buttons.PUL.DoorBlockToggle": "Blokování dveří",
  "Entities.gmod_subway_81-720.Buttons.PUL.!DoorLeftLamp": "Činnost tlačítka levých dveří",
  "Entities.gmod_subway_81-720.Buttons.PUL.DoorLeftSet": "Levé dveře",
  "Entities.gmod_subway_81-720.Buttons.PUU.!DoorsClosed": "Signalizace zavření dveří",
  "Entities.gmod_subway_81-720.Buttons.PUU.StandToggle": "Zastavení",
  "Entities.gmod_subway_81-720.Buttons.PUU.TickerToggle": "Tachograf",
  "Entities.gmod_subway_81-720.Buttons.PUU.KAHToggle": "KAH: Tlačítko nouzové jízdy",
  "Entities.gmod_subway_81-720.Buttons.PUU.ALSToggle": "ALS: Automatická lokomotivní signalizace",
  "Entities.gmod_subway_81-720.Buttons.PUU.FDepotToggle": "Odjezd z depa",
  "Entities.gmod_subway_81-720.Buttons.PUU.!HVoltage": "Vysoké napětí není dostupné",
  "Entities.gmod_subway_81-720.Buttons.PUU.PassSchemeToggle": "Schéma metra nad dveřmi",
  "Entities.gmod_subway_81-720.Buttons.PUU.EmergencyCompressorSet": "Kompresor nouze",
  "Entities.gmod_subway_81-720.Buttons.PUU.EnableBVSet": "Zapnutí ochrany (přetížení relé)",
  "Entities.gmod_subway_81-720.Buttons.PUU.DisableBVSet": "Odpojení BV (přetížení relé)",
  "Entities.gmod_subway_81-720.Buttons.PUU.RingSet": "Zvonek",
  "Entities.gmod_subway_81-720.Buttons.PUU.R_Program2Set": "Start hlášení (Program 2)",
  "Entities.gmod_subway_81-720.Buttons.PUU.R_AnnouncerToggle": "Vlakový rozhlas",
  "Entities.gmod_subway_81-720.Buttons.PUU.R_LineToggle": "Linka",
  "Entities.gmod_subway_81-720.Buttons.PUU.R_EmerSet": "Nouzové spojení",
  "Entities.gmod_subway_81-720.Buttons.PUU.R_Program1Set": "Start hlášení (Program 1)",
  "Entities.gmod_subway_81-720.Buttons.PUU.EnableBVEmerSet": "Rezervní obnova BV",
  "Entities.gmod_subway_81-720.Buttons.PUU.EmergencyControlsToggle": "Nouzové řízení",
  "Entities.gmod_subway_81-720.Buttons.PUU.WiperToggle": "Stěrač",
  "Entities.gmod_subway_81-720.Buttons.PUU.!VDop": "Povolená rychlost",
  "Entities.gmod_subway_81-720.Buttons.PUU.!VFact": "Aktuální rychlost",
  "Entities.gmod_subway_81-720.Buttons.PUU.!VPred": "Předvěst",
  "Entities.gmod_subway_81-720.Buttons.PUU.!VDop2": "Povolená rychlost",
  "Entities.gmod_subway_81-720.Buttons.PUU.!Acc": "Akcelerace",
  "Entities.gmod_subway_81-720.Buttons.PUU.!Forw": "Jízda vpřed",
  "Entities.gmod_subway_81-720.Buttons.PUU.!Back": "Jízda vzad",
  "Entities.gmod_subway_81-720.Buttons.PUR.AccelRateToggle": "Míra akcelerace",
  "Entities.gmod_subway_81-720.Buttons.PUR.EmerBrakeAddSet": "Náhradní brzda (brzdění)",
  "Entities.gmod_subway_81-720.Buttons.PUR.EmerBrakeReleaseSet": "Náhradní brzda (odbrzdění)",
  "Entities.gmod_subway_81-720.Buttons.PUR.EmerBrakeToggle": "Náhradní brzda",
  "Entities.gmod_subway_81-720.Buttons.PUR.EmergencyBrakeToggle": "Rychlobrzda",
  "Entities.gmod_subway_81-720.Buttons.PUR.DoorCloseToggle": "Zavření dveří",
  "Entities.gmod_subway_81-720.Buttons.PUR.AttentionMessageSet": "Upozornění na zprávu",
  "Entities.gmod_subway_81-720.Buttons.PUR.AttentionSet": "Bdělost",
  "Entities.gmod_subway_81-720.Buttons.PUR.AttentionBrakeSet": "Upozornění na brzdu",
  "Entities.gmod_subway_81-720.Buttons.PUR.HornBSet": "Houkačka",
  "Entities.gmod_subway_81-720.Buttons.PUR.DoorRightSet": "Pravé dveře",
  "Entities.gmod_subway_81-720.Buttons.PUR.!DoorRightLamp": "Činnost tlačítka pravých dveří",
  "Entities.gmod_subway_81-720.Buttons.PneumoHelper2.!BrakeTrainLine": "Červená: brzdové potrubí, Černá: hlavní potrubí",

  "Entities.gmod_subway_81-721.Buttons.GV.GVToggle": "Hlavní vypínač",
  "Entities.gmod_subway_81-721.Buttons.RearPneumatic.RearBrakeLineIsolationToggle": "Izolační ventil brzdového potrubí",
  "Entities.gmod_subway_81-721.Buttons.RearPneumatic.RearTrainLineIsolationToggle": "Izolační ventil hlavního potrubí",
  "Entities.gmod_subway_81-721.Buttons.FrontDoor.FrontDoor": "Přední dveře",
  "Entities.gmod_subway_81-721.Buttons.RearDoor.RearDoor": "Zadní dveře",
  "Entities.gmod_subway_81-721.Buttons.Battery.BatteryToggle": "Baterie zapnuto/vypnuto",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV1Toggle": "SF1: Napájení obvodů řízení",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV2Toggle": "SF2: Napájení BUV (ovládání vozů)",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV3Toggle": "SF3: Napájení BUTP (ovládání tračkních motorů)",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV4Toggle": "SF4: Řízení BUTP",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV5Toggle": "SF5: Nouzové řízení BUTP",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV6Toggle": "SF6: Napájení BUTP",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV7Toggle": "SF7: BBE",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV8Toggle": "SF8: Řízení BV",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV9Toggle": "SF9: Napájení BV (přetížení relé)",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV10Toggle": "SF10: PPO",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV11Toggle": "SF11: Kompresor",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV12Toggle": "SF12: Zavření dveří",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV13Toggle": "SF13: Otevřít levé dveře",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV14Toggle": "SF14: Otevřít pravé dveře",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV15Toggle": "SF15: Přední dveře",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV16Toggle": "SF16: Vlakový rozhlas",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV17Toggle": "SF17: Nouzové spojení",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV18Toggle": "SF18: Rezerva",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV19Toggle": "SF19: Napájení osvětlení interiéru",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV20Toggle": "SF20: Osvětlení nouze",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV21Toggle": "SF21: Senzor rychlosti",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV22Toggle": "SF22: Parkovací brzda",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV23Toggle": "SF23: Ovládání ventilace 1. skupiny",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV24Toggle": "SF24: Ovládání ventilace 2. skupiny",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV25Toggle": "SF25: Napájení ventilace 1. skupiny",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV26Toggle": "SF26: Napájení ventilace 2. skupiny",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV27Toggle": "SF27: Napájení zdroje",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV28Toggle": "SF28: Napájení ZKK",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV29Toggle": "SF29: Sběrač proudů",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV30Toggle": "SF30: Směrová tabule",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV31Toggle": "SF31: Rezerva",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV32Toggle": "SF32: Rezerva",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV33Toggle": "SF33: Rezerva",
  "Entities.gmod_subway_81-721.Buttons.FrontPneumatic.FrontBrakeLineIsolationToggle": "Izolační ventil brzdového potrubí",
  "Entities.gmod_subway_81-721.Buttons.FrontPneumatic.FrontTrainLineIsolationToggle": "Izolační ventil hlavního potrubí"
}
]]
