return [[
{
	"Lang": "cz",
	"Name": "Čeština",
	"Panel.Admin": "Admin",
	"Panel.Client": "Klient",
	"Panel.DrawDebugInfo": "Zobrazit informace pro vývojáře",
	"Panel.DisableCamAccel": "Vypnout akceleraci pohledu",
	"Panel.DisableHoverText": "Vypnout vysvětlivky",

	"Entities.gmod_subway_base.Name": "Vozová základna",
	"Entities.gmod_subway_81-703.Name": "E",
	"Entities.gmod_subway_81-703_2.Name": "E (vložený vůz)",
	"Entities.gmod_subway_81-717_mvm.Name": "81-717 (MVM)",
	"Entities.gmod_subway_81-717_lvz.Name": "81-717 (LVZ)",
	"Entities.gmod_subway_81-714_mvm.Name": "81-714 (MVM)",
	"Entities.gmod_subway_81-714_lvz.Name": "81-714 (LVZ)",
	"Entities.gmod_subway_81-7036.Name": "81-7036 (nefunguje)",
	"Entities.gmod_subway_81-7037.Name": "81-7037 (nefunguje)",
	"Entities.gmod_subway_81-720.Name": "81-720 (čelní vůz)",
	"Entities.gmod_subway_81-721.Name": "81-721 (vložený vůz)",
	"Entities.gmod_subway_81-722.Name": "81-722 (čelní vůz)",
	"Entities.gmod_subway_81-723.Name": "81-723 (vložený vůz s pohonem)",
	"Entities.gmod_subway_81-724.Name": "81-724 (vložený vůz bez pohonu)",
	"Entities.gmod_subway_e.Name": "E",
	"Entities.gmod_subway_em.Name": "Em",
	"Entities.gmod_subway_ema.Name": "Ema",
	"Entities.gmod_subway_ezh.Name": "Ež",
	"Entities.gmod_subway_ezh1.Name": "Ež1",
	"Entities.gmod_subway_em508.Name": "Em-508",
	"Entities.gmod_subway_em508_int.Name": "Em-508 (vložený vůz)",
	"Entities.gmod_subway_ezh3.Name": "Ež3",
	"Entities.gmod_subway_ezh3ru1.Name": "Ež3 RU1",
	"Entities.gmod_subway_ema508t.Name": "Em-508T",
	"Entities.gmod_subway_tatra_t3.Name": "Tatra T3",
	"Entities.gmod_subway_ai.Name": "Vlak řízený počítačem",

	"Entities.gmod_train_bogey.Name": "Podvozek vlaku",
	"Entities.gmod_train_couple.Name": "Spřáhlo",

	"Entities.gmod_track_pui.Name": "PUI (Programovatelné zobrazovací zařízení)",
	"Entities.gmod_track_mus_elektronika7.Name": "Digitální hodiny",
	"Entities.gmod_mus_clock_analog.Name": "Analogové hodiny",
	"Entities.gmod_track_clock_time.Name": "Velké intervalové hodiny(čas)",
	"Entities.gmod_track_clock_small.Name": "Malé intervalové hodiny",
	"Entities.gmod_track_clock_interval.Name": "Velké intervalové hodiny(interval)",
	"Entities.gmod_track_switch.Name": "Výhybka",
	"Entities.gmod_track_powermeter.Name": "Měříč výkonu",
	"Entities.gmod_track_controller.Name": "Track controller",
	"Entities.gmod_track_udochka.Name": "Pohyblivý napájecí kabel",
	"Entities.gmod_train_spawner.Name": "Spawner vozů metra"
}
]]
