return [[
{
  "Lang": "cz",
  "Name": "Čeština",


  "Entities.gmod_subway_ezh3.Buttons.Stopkran.EmergencyBrakeValveToggle": "Záchraná brzda",
  "Entities.gmod_subway_ezh3.Buttons.Back.BackDoor": "Zadní dveře",
  "Entities.gmod_subway_ezh3.Buttons.DriverValveBLTLDisconnect.DriverValveBLDisconnectToggle": "Ventil brzdového potrubí",
  "Entities.gmod_subway_ezh3.Buttons.DriverValveBLTLDisconnect.DriverValveTLDisconnectToggle": "Ventil hlavního potrubí",
  "Entities.gmod_subway_ezh3.Buttons.Battery.VBToggle": "VB: Baterie zapnuto/vypnuto (nízkonapětová)",
  "Entities.gmod_subway_ezh3.Buttons.FrontPneumatic.FrontBrakeLineIsolationToggle": "Izolační ventil brzdového potrubí",
  "Entities.gmod_subway_ezh3.Buttons.FrontPneumatic.FrontTrainLineIsolationToggle": "Izolační ventil hlavního potrubí",
  "Entities.gmod_subway_ezh3.Buttons.ASNP.R_ASNPMenuSet": "Vlakový rozhlas: Menu",
  "Entities.gmod_subway_ezh3.Buttons.ASNP.R_ASNPUpSet": "Vlakový rozhlas: Nahoru",
  "Entities.gmod_subway_ezh3.Buttons.ASNP.R_ASNPDownSet": "Vlakový rozhlas: Dolů",
  "Entities.gmod_subway_ezh3.Buttons.ASNP.R_ASNPOnToggle": "Vlakový rozhlas: Zapnout",
  "Entities.gmod_subway_ezh3.Buttons.PassengerDoor1.PassengerDoor": "Dveře z kabiny do interiéru",
  "Entities.gmod_subway_ezh3.Buttons.PassengerDoor.PassengerDoor": "Dveře z kabiny do interiéru",
  "Entities.gmod_subway_ezh3.Buttons.CabinDoor.CabinDoor": "Dveře kabiny",
  "Entities.gmod_subway_ezh3.Buttons.Front.FrontDoor": "Přední dveře",
  "Entities.gmod_subway_ezh3.Buttons.GV.GVToggle": "Hlavní vypínač",
  "Entities.gmod_subway_ezh3.Buttons.RearPneumatic.RearTrainLineIsolationToggle": "Izolační ventil hlavního potrubí",
  "Entities.gmod_subway_ezh3.Buttons.RearPneumatic.RearBrakeLineIsolationToggle": "Izolační ventil brzdového potrubí",
  "Entities.gmod_subway_ezh3.Buttons.Panel.!OCH": "NČ: Bez kódu",
  "Entities.gmod_subway_ezh3.Buttons.Panel.!0": "0: Kód 0 (Návěst zastavení)",
  "Entities.gmod_subway_ezh3.Buttons.Panel.!40": "Rychlost 40 km/h",
  "Entities.gmod_subway_ezh3.Buttons.Panel.!60": "Rychlost 60 km/h",
  "Entities.gmod_subway_ezh3.Buttons.Panel.!70": "Rychlost 70 km/h",
  "Entities.gmod_subway_ezh3.Buttons.Panel.!80": "Rychlost 80 km/h",
  "Entities.gmod_subway_ezh3.Buttons.Panel.!Speedometer": "Rychloměr (km/h)",
  "Entities.gmod_subway_ezh3.Buttons.Panel.!TotalAmpermeter": "Ampérmetr (A)",
  "Entities.gmod_subway_ezh3.Buttons.Panel.!TotalVoltmeter": "Voltmetr (kV)",
  "Entities.gmod_subway_ezh3.Buttons.Panel.!BatteryVoltage": "Napětí baterie řízení(V)",
  "Entities.gmod_subway_ezh3.Buttons.Panel.!BrakeCylinder": "Brzdový válec",
  "Entities.gmod_subway_ezh3.Buttons.Panel.!LinesPressure": "Napájecí-brzdové potrubí (červená: brzdové potrubí, černá: hlavní potrubí)",
  "Entities.gmod_subway_ezh3.Buttons.Main.KU1Toggle": "Kompresor",
  "Entities.gmod_subway_ezh3.Buttons.Main.SAMM1Set": "SAMM: Vypnutí trakce",
  "Entities.gmod_subway_ezh3.Buttons.Main.SAMM2Set": "SAMM: Rozjezd",
  "Entities.gmod_subway_ezh3.Buttons.Main.SAMM3Set": "SAMM: Korekce",
  "Entities.gmod_subway_ezh3.Buttons.Main.SAMMSignal1": "Lamp: Jízda-Brzda",
  "Entities.gmod_subway_ezh3.Buttons.Main.SAMMSignal2": "Lamp: Operační stav SAMM",
  "Entities.gmod_subway_ezh3.Buttons.Main.SAMMSignal3": "Lamp: Zapnuta činná jednotka SAMM",
  "Entities.gmod_subway_ezh3.Buttons.Main.SAMMOnToggle": "SAMM: Zapnutí systému",
  "Entities.gmod_subway_ezh3.Buttons.Main.SAMMBlokToggle": "SAMM: Činná jednotka",
  "Entities.gmod_subway_ezh3.Buttons.Main.SAMMCommand3Set": "SAMM: J-2",
  "Entities.gmod_subway_ezh3.Buttons.Main.SAMMCommand2Set": "SAMM: Dohnat",
  "Entities.gmod_subway_ezh3.Buttons.Main.SAMMCommand1Set": "SAMM: Souhlas",
  "Entities.gmod_subway_ezh3.Buttons.Main.KSNSet": "KSN: Porucha řízení",
  "Entities.gmod_subway_ezh3.Buttons.Main.R_Program1Set": "Start hlášení (Program 1)",
  "Entities.gmod_subway_ezh3.Buttons.Main.R_Program2Set": "Start hlášení (Program 2)",
  "Entities.gmod_subway_ezh3.Buttons.Main.VUSToggle": "Přepínač: Světla (dolů)/Světla dálková (nahoru)",
  "Entities.gmod_subway_ezh3.Buttons.Main.L_3Toggle": "Přepínač: Osvětlení přístojů",
  "Entities.gmod_subway_ezh3.Buttons.Main.VAHToggle": "Spínač: Nouzová jízda",
  "Entities.gmod_subway_ezh3.Buttons.Main.DIPonSet": "Osv. Vkl.: Zapnout osvětlení",
  "Entities.gmod_subway_ezh3.Buttons.Main.DIPoffSet": "Osv. Vykl.: Vypnout osvětlení",
  "Entities.gmod_subway_ezh3.Buttons.Main.KSDSet": "KSD: Signalizace zavření dveří",
  "Entities.gmod_subway_ezh3.Buttons.Main.KVTSet": "KVT: Tlačítko bdělosti",
  "Entities.gmod_subway_ezh3.Buttons.Main.KBSet": "KB: Tlačítko bdělosti",
  "Entities.gmod_subway_ezh3.Buttons.Main.KBLamp": "Lamp: Funkce reostatu kontroléru",
  "Entities.gmod_subway_ezh3.Buttons.Main.ARSToggle": "ARS: Automatická regulace rychlosti",
  "Entities.gmod_subway_ezh3.Buttons.Main.R_UNchToggle": "UNCh: Zesilovač nízké frekvence",
  "Entities.gmod_subway_ezh3.Buttons.Main.VUD1Toggle": "VUD: Zavření dveří",
  "Entities.gmod_subway_ezh3.Buttons.Main.R_RadioToggle": "Vlakový rozhlas",
  "Entities.gmod_subway_ezh3.Buttons.Main.ALSToggle": "ALS: Automatická lokomotivní signalizace",
  "Entities.gmod_subway_ezh3.Buttons.Main.VozvratRPSet": "KVRP: Korekce zátěže relé",
  "Entities.gmod_subway_ezh3.Buttons.Main.RingSet": "Zvonek",
  "Entities.gmod_subway_ezh3.Buttons.Main.L_2Toggle": "Tlačítko: Osvětlení kabiny",
  "Entities.gmod_subway_ezh3.Buttons.Main.KRZDSet": "KRZD: Dveře nouze",
  "Entities.gmod_subway_ezh3.Buttons.Main.KDPSet": "KDP: Otevřít pravé dveře",
  "Entities.gmod_subway_ezh3.Buttons.Main.KDLSet": "KDL: Otevřít levé dveře",
  "Entities.gmod_subway_ezh3.Buttons.Main.KAHSet": "KAH: Tlačítko nouzové jízdy",
  "Entities.gmod_subway_ezh3.Buttons.Main.RezMKSet": "Kompresor nouze",
  "Entities.gmod_subway_ezh3.Buttons.Main.KRPSet": "KRP: Nouzové řízení",
  "Entities.gmod_subway_ezh3.Buttons.Main.RSTToggle": "VPR: Radiostanice",
  "Entities.gmod_subway_ezh3.Buttons.Main.R_GToggle": "Vlakový rozhlas v kabině",
  "Entities.gmod_subway_ezh3.Buttons.Main.R_ZSToggle": "ZS: Vlakový rozhlas ve vozech",
  "Entities.gmod_subway_ezh3.Buttons.Main.Custom2Set": "Unused Switch",
  "Entities.gmod_subway_ezh3.Buttons.Main.Custom3Set": "Unused Switch",
  "Entities.gmod_subway_ezh3.Buttons.Main.ASNPPlay": "Vlakový rozhlas v pořádku",
  "Entities.gmod_subway_ezh3.Buttons.AV1.VU3Toggle": "VU3: Osvětlení kabiny",
  "Entities.gmod_subway_ezh3.Buttons.AV1.VU2Toggle": "VU2: Osvětlení nouze (45V)",
  "Entities.gmod_subway_ezh3.Buttons.AV1.VU1Toggle": "VU1: Vytápění kabiny (3kWt)",
  "Entities.gmod_subway_ezh3.Buttons.AVMain.AV8BToggle": "AV-8B: Automatický spínač (vysokonapětový)",
  "Entities.gmod_subway_ezh3.Buttons.RC1.RC1Toggle": "RC-ARS: Odpojovač řídicích obvodů ARS",
  "Entities.gmod_subway_ezh3.Buttons.UAVAPanel.UAVAToggle": "UAVA: Univerzální Automatický Vypínač Autostopu (vypnutí autostopu)",
  "Entities.gmod_subway_ezh3.Buttons.UAVAPanel.UAVAContactSet": "UAVA: Univerzální Automatický Vypínač Autostopu (obnovení kontaktů)",
  "Entities.gmod_subway_ezh3.Buttons.VUHelper.VUToggle": "VU: Řízení",
  "Entities.gmod_subway_ezh3.Buttons.HelperPanel.VDLSet": "KDL: Otevřít levé dveře",
  "Entities.gmod_subway_ezh3.Buttons.HelperPanel.VUD2Toggle": "VUD2: Zavření dveří",
  "Entities.gmod_subway_ezh3.Buttons.EPKDisconnect.EPKToggle": "Ventil EPK",
  "Entities.gmod_subway_ezh3.Buttons.VU.VUToggle": "VU: Řízení",
  "Entities.gmod_subway_ezh3.Buttons.ParkingBrake.ParkingBrakeLeft": "Parkovací brzda",
  "Entities.gmod_subway_ezh3.Buttons.ParkingBrake.ParkingBrakeRight": "Parkovací brzda",
  "Entities.gmod_subway_ezh3.Buttons.AirDistributor.AirDistributorDisconnectToggle": "Odpojit vzduchový rozdělovač",

  "Entities.gmod_subway_em508t.Buttons.Stopkran.EmergencyBrakeValveToggle": "Záchraná brzda",
  "Entities.gmod_subway_em508t.Buttons.Battery.VBToggle": "VB: Baterie zapnuto/vypnuto (nízkonapětová)",
  "Entities.gmod_subway_em508t.Buttons.FrontPneumatic.FrontBrakeLineIsolationToggle": "Ventil brzdového potrubí",
  "Entities.gmod_subway_em508t.Buttons.FrontPneumatic.FrontTrainLineIsolationToggle": "Ventil hlavního potrubí",
  "Entities.gmod_subway_em508t.Buttons.GV.GVToggle": "Hlavní vypínač",
  "Entities.gmod_subway_em508t.Buttons.RearPneumatic.RearTrainLineIsolationToggle": "Ventil hlavního potrubí",
  "Entities.gmod_subway_em508t.Buttons.RearPneumatic.RearBrakeLineIsolationToggle": "Ventil brzdového potrubí",
  "Entities.gmod_subway_em508t.Buttons.RearDoor.RearDoor": "Zadní dveře",
  "Entities.gmod_subway_em508t.Buttons.Back2.!HVFuse": "Pojistky hlavního vypínače",
  "Entities.gmod_subway_em508t.Buttons.Back2.!Relays": "Skříňka s zařízeními pro dobíjení baterie a dveřního rozdělovače",
  "Entities.gmod_subway_em508t.Buttons.Back2.!Heater": "Topné těleso",
  "Entities.gmod_subway_em508t.Buttons.Front.FrontDoor": "Přední dveře",
  "Entities.gmod_subway_em508t.Buttons.AV1.VU3Toggle": "VU3: Osvětlení kabiny",
  "Entities.gmod_subway_em508t.Buttons.AV1.VU2Toggle": "VU2: Osvětlení nouze (45V)",
  "Entities.gmod_subway_em508t.Buttons.AV1.VU1Toggle": "VU1: Vytápění kabiny (3kWt)",
  "Entities.gmod_subway_em508t.Buttons.ParkingBrake.ParkingBrakeLeft": "Parkovací brzda",
  "Entities.gmod_subway_em508t.Buttons.ParkingBrake.ParkingBrakeRight": "Parkovací brzda",
  "Entities.gmod_subway_em508t.Buttons.CabinDoor.CabinDoor1": "Dveře kabiny",
  "Entities.gmod_subway_em508t.Buttons.PassengerDoor.PassengerDoor": "Dveře z kabiny do interiéru",
  "Entities.gmod_subway_em508t.Buttons.PassengerDoor1.PassengerDoor": "Dveře z kabiny do interiéru",
  "Entities.gmod_subway_em508t.Buttons.Main.!RedRP": "RP: Červené světlo přetížení relé (Nelze zkompletovat jističe)",
  "Entities.gmod_subway_em508t.Buttons.Main.!GreenRP": "RP: Zelené světlo přehřátí relé (zabraňuje nadproudu trakčních motorů)",
  "Entities.gmod_subway_em508t.Buttons.Main.!SD": "Signalizace zavření dveří",
  "Entities.gmod_subway_em508t.Buttons.Main.KDLSet": "Přepínač: Otevřít levé dveře",
  "Entities.gmod_subway_em508t.Buttons.Main.KSDSet": "Přepínač: Signalizace zavření dveří",
  "Entities.gmod_subway_em508t.Buttons.Main.VozvratRPSet": "Přepínač: Korekce zátěže relé",
  "Entities.gmod_subway_em508t.Buttons.Main.KSNSet": "Spínač: Porucha řízení",
  "Entities.gmod_subway_em508t.Buttons.Main.VUD1Toggle": "Přepínač: Zavření dveří",
  "Entities.gmod_subway_em508t.Buttons.Main.KU1Toggle": "Přepínač: Kompresor",
  "Entities.gmod_subway_em508t.Buttons.Main.DIPonSet": "KU4: Zapnout osvětlení",
  "Entities.gmod_subway_em508t.Buttons.Main.DIPoffSet": "KU5: Vypnout osvětlení",
  "Entities.gmod_subway_em508t.Buttons.Main.RezMKSet": "Přepínač: Kompresor nouze",
  "Entities.gmod_subway_em508t.Buttons.Main.KDPSet": "KDP: Otevřít pravé dveře",
  "Entities.gmod_subway_em508t.Buttons.Main.KRZDSet": "KU10: Dveře nouze",
  "Entities.gmod_subway_em508t.Buttons.AVMain.AV8BToggle": "AV-8B: Automatický spínač (vysokonapětový)",
  "Entities.gmod_subway_em508t.Buttons.VU.VUToggle": "VU: Řízení",
  "Entities.gmod_subway_em508t.Buttons.VU.!Voltage": "Napájení obvodů řízení",
  "Entities.gmod_subway_em508t.Buttons.HelperPanel.VUD2Toggle": "VUD2: Zavření dveří",
  "Entities.gmod_subway_em508t.Buttons.HelperPanel.VDLSet": "VDL: Otevřít levé dveře",
  "Entities.gmod_subway_em508t.Buttons.DriverValveBLTLDisconnect.DriverValveBLDisconnectToggle": "Ventil brzdového potrubí",
  "Entities.gmod_subway_em508t.Buttons.DriverValveBLTLDisconnect.DriverValveTLDisconnectToggle": "Ventil hlavního potrubí",
  "Entities.gmod_subway_em508t.Buttons.AirDistributor.AirDistributorDisconnectToggle": "Odpojit vzduchový rozdělovač"
}
]]
