return [[
{
  "Lang": "cz",
  "Name": "Čeština",

  "Entities.gmod_subway_81-717_mvm.Buttons.HelperPanel.VUD2Toggle": "VUD2: Zavření dveří",
  "Entities.gmod_subway_81-717_mvm.Buttons.HelperPanel.VDLSet": "VDL: Otevřít levé dveře",
  "Entities.gmod_subway_81-717_mvm.Buttons.HelperPanel.R_Program2Helper": "Start hlášení (Program 2)",
  "Entities.gmod_subway_81-717_mvm.Buttons.HelperPanel.R_Program1Helper": "Start hlášení (Program 1)",
  "Entities.gmod_subway_81-717_mvm.Buttons.Battery_2.1:RC1Toggle": "RC-1: Odpojovač řídicích obvodů ARS",
  "Entities.gmod_subway_81-717_mvm.Buttons.Battery_2.1:VBToggle": "VB: Baterie zapnuto/vypnuto",
  "Entities.gmod_subway_81-717_mvm.Buttons.Battery_2.1:UOSToggle": "RC-UOS: Odpojovač obvodů omezovače rychlosti",
  "Entities.gmod_subway_81-717_mvm.Buttons.Wiper.WiperToggle": "Stěrač",
  "Entities.gmod_subway_81-717_mvm.Buttons.DriverValveDisconnect.DriverValveDisconnectToggle": "Ventil brzdiče",
  "Entities.gmod_subway_81-717_mvm.Buttons.DriverValveDisconnect.DriverValveBLDisconnectToggle": "Ventil brzdového potrubí",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.R_UNchToggle": "UNCh: Zesilovač nízké frekvence",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.R_ZSToggle": "ZS: Vlakový rozhlas ve vozech",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.R_GToggle": "Vlakový rozhlas v kabině",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.R_RadioToggle": "Vlakový rozhlas",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.R_Program1Set": "Start hlášení (Program 1)",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.R_Program2Set": "Start hlášení (Program 2)",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.2:KVTSet": "KB: Tlačítka bdělosti",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.VZ1Set": "VZ1: Pneumatický ventil #1",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.VUD1Toggle": "VUD: Zavření dveří",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.KDLSet": "KDL: Otevřít levé dveře",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.KDLKToggle": "Krytka KDL",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.KDLRSet": "VDL: Otevřít levé dveře",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.KDLRKToggle": "Krytka VDL",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.DoorSelectToggle": "Dveře předvolba",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.KRZDSet": "RZD: Dveře nouze",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.R_VPRToggle": "VPR: Radiostanice",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.VozvratRPSet": "Korekce zátěže relé",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.GreenRPLight": "RP: Zelené světlo přehřátí relé (zabraňuje nadproudu trakčních motorů)",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.AVULight": "AVU: Automatický odpojovač řízení",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.LKVPLight": "LKVP: Kontrolka měniče vysokého napětí",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.SPLight": "LSP: Stav nouze-požár (přehřátí reostatu)",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.ConverterProtectionSet": "Ochranný měnič",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.KSNSet": "KSN: Porucha řízení",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.DIPoffSet": "Zvonek",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.ARSToggle": "ARS: Automatická regulace rychlosti",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.ALSToggle": "ALS: Automatická lokomotivní signalizace",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.OtklAVUToggle": "Vypnutí automatického odpojovače relé (porucha AVU)",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.TormATToggle": "Vypnutí pneumatické brzdy",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.L_1Toggle": "Osvětlení vozu",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.L_2Toggle": "Osvětlení kabiny",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.L_3Toggle": "Osvětlení Panel",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.ALSFreqToggle": "Dekodér: Přepínač kódování frekvencí ALS (1/5 nebo 2/6)",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.ParkingBrakeSignToggle": "Cedule \"ODBRZDI PARKOVACÍ BRZDU\"",
  "Entities.gmod_subway_81-717_mvm.Buttons.ParkingBrake.ParkingBrakeToggle": "Parkovací brzda",
  "Entities.gmod_subway_81-717_mvm.Buttons.ParkingBrake.DriverValveTLDisconnectToggle": "Ventil hlavního potrubí",
  "Entities.gmod_subway_81-717_mvm.Buttons.IGLAButtons.IGLA1Set": "IGLA: První tlačítko",
  "Entities.gmod_subway_81-717_mvm.Buttons.IGLAButtons.IGLA2Set": "IGLA: Druhé tlačítko",
  "Entities.gmod_subway_81-717_mvm.Buttons.IGLAButtons.IGLA3Set": "IGLA: Třetí tlačítko",
  "Entities.gmod_subway_81-717_mvm.Buttons.IGLAButtons.IGLA4Set": "IGLA: Čtvrté tlačítko",
  "Entities.gmod_subway_81-717_mvm.Buttons.BPSNFront.!Voltage": "Napájení obvodů řízení",
  "Entities.gmod_subway_81-717_mvm.Buttons.BPSNFront.VMKToggle": "Kompresor",
  "Entities.gmod_subway_81-717_mvm.Buttons.BPSNFront.BPSNonToggle": "Měnič",
  "Entities.gmod_subway_81-717_mvm.Buttons.BPSNFront.RezMKSet": "Kompresor nouze",
  "Entities.gmod_subway_81-717_mvm.Buttons.BPSNFront.ARS13Set": "ARS 13V: Kontrola stabilizace napětí ARS",
  "Entities.gmod_subway_81-717_mvm.Buttons.Schedule.!RouteNum": "GVD №\nČíslo turnusu",
  "Entities.gmod_subway_81-717_mvm.Buttons.Schedule.!PathNum": "TRASA №\nČíslo trasy",
  "Entities.gmod_subway_81-717_mvm.Buttons.Schedule.!SchTime": "DOBA JÍZDY\nCelková doba jízdy",
  "Entities.gmod_subway_81-717_mvm.Buttons.Schedule.!SchInterval": "INT\nInterval",
  "Entities.gmod_subway_81-717_mvm.Buttons.Schedule.!SchHour": "HOD\nHodina",
  "Entities.gmod_subway_81-717_mvm.Buttons.Schedule.!SchMin": "MIN\nMinuta",
  "Entities.gmod_subway_81-717_mvm.Buttons.Schedule.!SchSec": "SEK\nSekunda",
  "Entities.gmod_subway_81-717_mvm.Buttons.Schedule.!SchArrival": "Čas příjezdu",
  "Entities.gmod_subway_81-717_mvm.Buttons.Schedule.!SchStations": "Název stanice",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!Speedometer": "Rychloměr",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!LampLSN": "LSN: Indikátor poruchy (Nelze zkompletovat jističe)",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!LampRP": "RP: Červené světlo přetížení relé (Nelze zkompletovat jističe)",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!LampLHRK": "LhRK: Funkce reostatu kontroléru",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!LampLKT": "LKT: Indikátor brzdění ARS",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!LampLKVD": "LKVD: Odpojení trakce",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!LampLKVC": "LKVC: Vysoké napětí není dostupné",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!ARSOch": "OČ: Bez kódu",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!ARS0": "0: Kód 0 (Návěst zastavení)",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!ARS40": "Rychlost 40 km/h",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!ARS60": "Rychlost 60 km/h",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!ARS70": "Rychlost 70 km/h",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!ARS80": "Rychlost 80 km/h",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!LampLSD1": "LSD: Signalizace zavření dveří (dveře jsou zavřeny)",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!LampLSD2": "LSD: Signalizace zavření dveří (dveře jsou zavřeny)",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!LampLST": "LST: Brzdy v chodu",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!LampLVD": "LVD: Trakční motory v chodu",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!LampLN": "LN: Kontrolka směru jízdy",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!LampLRS": "LRS: Předvěst (rychlost v dalším oddílu je stejná nebo vyšší)",
  "Entities.gmod_subway_81-717_mvm.Buttons.PneumaticPanels.!CylinderPressure": "Brzdový válec",
  "Entities.gmod_subway_81-717_mvm.Buttons.PneumaticPanels.!LinePressure": "Napájecí-brzdové potrubí (červená: brzdové potrubí, černá: hlavní potrubí)",
  "Entities.gmod_subway_81-717_mvm.Buttons.Battery.RC1Toggle": "RC-1: Odpojovač řídicích obvodů ARS",
  "Entities.gmod_subway_81-717_mvm.Buttons.Battery.UOSToggle": "RC-UOS: Odpojovač obvodů omezovače rychlosti",
  "Entities.gmod_subway_81-717_mvm.Buttons.Battery.VBToggle": "VB: Baterie zapnuto/vypnuto",
  "Entities.gmod_subway_81-717_mvm.Buttons.FrontPneumatic.FrontBrakeLineIsolationToggle": "Izolační ventil brzdového potrubí",
  "Entities.gmod_subway_81-717_mvm.Buttons.FrontPneumatic.FrontTrainLineIsolationToggle": "Izolační ventil hlavního potrubí",
  "Entities.gmod_subway_81-717_mvm.Buttons.ASNP.R_ASNPMenuSet": "ASNP: Menu",
  "Entities.gmod_subway_81-717_mvm.Buttons.ASNP.R_ASNPUpSet": "ASNP: Nahoru",
  "Entities.gmod_subway_81-717_mvm.Buttons.ASNP.R_ASNPDownSet": "ASNP: Dolů",
  "Entities.gmod_subway_81-717_mvm.Buttons.ASNP.R_ASNPOnToggle": "ASNP: Zapnout",
  "Entities.gmod_subway_81-717_mvm.Buttons.RearDoor.RearDoor": "Zadní dveře",
  "Entities.gmod_subway_81-717_mvm.Buttons.Meters.!TotalVoltmeter": "Voltmetr vysokého napětí (kV)",
  "Entities.gmod_subway_81-717_mvm.Buttons.Meters.!TotalAmpermeter": "Ampérmetr (A)",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A61Toggle": "A61 Elektrické rozvody",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A55Toggle": "A55 Elektrické rozvody",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A54Toggle": "A54 Vyp. řízení",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A56Toggle": "A56 Baterie",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A27Toggle": "A27 Osv.kabina, kontr. MR, park. brzda",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A21Toggle": "A21 Ovládání dveří",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A10Toggle": "A10 Ovládání kompresoru",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A53Toggle": "A53 Vlak. obvody",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A43Toggle": "A43 Baterie ARS",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A45Toggle": "A45 Elektrické rozvody ARS",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A42Toggle": "A42 Napájení ARS",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A41Toggle": "A41 Brzda ARS",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.VUToggle": "VU  Řízení",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A64Toggle": "A64 Osvětlení kabiny",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A63Toggle": "A63 Napájení VR (IGLA/BIS)",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A50Toggle": "A50 Přídrž PBO",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A51Toggle": "A51 Vypnutí DIP a osvětlení",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A23Toggle": "A23 Nouzové zapnutí kompresoru",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A14Toggle": "A14 Relé nouzového řízení",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A75Toggle": "A75 Vytápění kabiny",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A1Toggle": "A1  J-1",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A2Toggle": "A2  J-2",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A3Toggle": "A3  J-3",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A17Toggle": "A17 Korekce zátěže relé",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A62Toggle": "A62 Rádiová komunikace",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A29Toggle": "A29 Rádiový přenos",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A5Toggle": "A5 ASNP",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A6Toggle": "A6  B-1",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A8Toggle": "A8  Pneumatické ventily #1, #2",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A20Toggle": "A20 LS 2, LS 5",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A25Toggle": "A25 Ruční brzdění",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A22Toggle": "A22 Stykač kompresoru",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A30Toggle": "A30 Motor HK",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A39Toggle": "A39 Nouzové řízení vozidla",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A44Toggle": "A44 Nouzové řízení (kompresory KNŘ)",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A80Toggle": "A80 Napájení trakčních motorů",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A65Toggle": "A65 Osvětlení interiéru",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.L_5Toggle": "А49 Osvětlení nouze",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A24Toggle": "A24 Dobíjení baterie",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A32Toggle": "A32 Otevř. pravé dveře",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A31Toggle": "A31 Otevř. levé dveře",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A16Toggle": "A16 Zavírání dveří",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A13Toggle": "A13 Dveřní signalizace",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A12Toggle": "A12 Zavírání nouze",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A7Toggle": "A7 Červené světlo pravé",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A9Toggle": "A9 Červené světlo levé",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A46Toggle": "A46 Bílá světla (klopená)",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A47Toggle": "A47 Bílá světla (dálková)",
  "Entities.gmod_subway_81-717_mvm.Buttons.PassengerDoor.PassengerDoor": "Dveře z kabiny do interiéru",
  "Entities.gmod_subway_81-717_mvm.Buttons.GV.GVToggle": "Hlavní vypínač",
  "Entities.gmod_subway_81-717_mvm.Buttons.Stopkran.EmergencyBrakeValveToggle": "Rychlobrzda",
  "Entities.gmod_subway_81-717_mvm.Buttons.InfoTableSelect.PrevSign": "Předešlí směr jízdy",
  "Entities.gmod_subway_81-717_mvm.Buttons.InfoTableSelect.NextSign": "Další směr jízdy",
  "Entities.gmod_subway_81-717_mvm.Buttons.InfoTableSelect.Num2P": "Turnus: Zvýšit 2. číslo",
  "Entities.gmod_subway_81-717_mvm.Buttons.InfoTableSelect.Num2M": "Turnus: Snížit 2. číslo",
  "Entities.gmod_subway_81-717_mvm.Buttons.InfoTableSelect.Num1P": "Turnus: Zvýšit 1. číslo",
  "Entities.gmod_subway_81-717_mvm.Buttons.InfoTableSelect.Num1M": "Turnus: Snížit 1. číslo",
  "Entities.gmod_subway_81-717_mvm.Buttons.Front.L_4Toggle": "Světla",
  "Entities.gmod_subway_81-717_mvm.Buttons.Front.VUSToggle": "VUS: Světla dálková",
  "Entities.gmod_subway_81-717_mvm.Buttons.Front.VAHToggle": "VAH: Přepínač nouzové jízdy (porucha relé pedálu bdělosti)",
  "Entities.gmod_subway_81-717_mvm.Buttons.Front.VADToggle": "VAD: Přepínač nouzového zavření dveří (porucha relé tlačítka dveří)",
  "Entities.gmod_subway_81-717_mvm.Buttons.Front.KRPSet": "KRP: Nouzové řízení",
  "Entities.gmod_subway_81-717_mvm.Buttons.Front.KAHSet": "Tlačítko nouzové jízdy",
  "Entities.gmod_subway_81-717_mvm.Buttons.Front.KAHKToggle": "Krytka TNJ",
  "Entities.gmod_subway_81-717_mvm.Buttons.Front.KUP": "Vytápění kabiny",
  "Entities.gmod_subway_81-717_mvm.Buttons.Front.KDPSet": "KDP: Otevřít pravé dveře",
  "Entities.gmod_subway_81-717_mvm.Buttons.Front.KDPKToggle": "Krytka KDP",
  "Entities.gmod_subway_81-717_mvm.Buttons.Front.PN": "Pneumatická brzda",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A61Toggle": "A61 Elektrické rozvody",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A55Toggle": "A55 Elektrické rozvody",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A54Toggle": "A54 Vyp. řízení",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A56Toggle": "A56 Baterie",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A27Toggle": "A27 Osv.kabina, kontr. MR, park. brzda",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A21Toggle": "A21 Ovládání dveří",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A10Toggle": "A10 Ovládání kompresoru",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A53Toggle": "A53 Vlak. obvody",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A43Toggle": "A43 Baterie ARS",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A45Toggle": "A45 Elektrické rozvody ARS",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A42Toggle": "A42 Napájení ARS",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A41Toggle": "A41 Brzda ARS",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:VUToggle": "VU  Řízení",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A64Toggle": "A64 Osvětlení kabiny",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A63Toggle": "A63 Napájení VR (IGLA/BIS)",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A50Toggle": "A50 Přídrž PBO",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A51Toggle": "A51 Vypnutí DIP a osvětlení",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A23Toggle": "A23 Nouzové zapnutí kompresoru",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A14Toggle": "A14 Relé nouzového řízení",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A75Toggle": "A75 Vytápění kabiny",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A1Toggle": "A1  J-1",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A2Toggle": "A2  J-2",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A3Toggle": "A3  J-3",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A17Toggle": "A17 Korekce zátěže relé",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A62Toggle": "A62 Rádiová komunikace",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A29Toggle": "A29 Rádiový přenos",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A5Toggle": "A5 ASNP",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A6Toggle": "A6  B-1",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A8Toggle": "A8  Pneumatické ventily #1, #2",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A20Toggle": "A20 LS 2, LS 5",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A25Toggle": "A25 Ruční brzdění",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A22Toggle": "A22 Stykač kompresoru",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A30Toggle": "A30 Motor HK",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A39Toggle": "A39 Nouzové řízení vozidla",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A44Toggle": "A44 Nouzové řízení (kompresory KNŘ)",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A80Toggle": "A80 Napájení trakčních motorů",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A65Toggle": "A65 Osvětlení interiéru",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:L_5Toggle": "А49 Osvětlení nouze",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A24Toggle": "A24 Dobíjení baterie",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A32Toggle": "A32 Otevř. pravé dveře",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A31Toggle": "A31 Otevř. levé dveře",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A16Toggle": "A16 Zavírání dveří",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A13Toggle": "A13 Dveřní signalizace",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A12Toggle": "A12 Zavírání nouze",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A7Toggle": "A7 Červené světlo pravé",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A9Toggle": "A9 Červené světlo levé",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A46Toggle": "A46 Bílá světla (klopená)",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A47Toggle": "A47 Bílá světla (dálková)",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!Speedometer": "Rychloměr",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!LSD": "LSD: Signalizace zavření dveří (dveře jsou zavřeny)",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!LOCh": "NČ: Bez kódu",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!L0": "0: Kód 0 (Návěst zastavení)",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!LRS": "LRS: Předvěst (rychlost v dalším oddílu je stejná nebo vyšší)",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!L40": "Rychlost 40 km/h",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!L60": "Rychlost 60 km/h",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!L80": "Rychlost 80 km/h",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!L70": "Rychlost 70 km/h",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!LRK": "RK: Kontrolka reostatu kontroléru",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!LEKK": "",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!LPU": "",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!LKVD": "LKVD: Odpojení trakce",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!LKT": "LKT: Indikátor brzdění ARS",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!LRP": "LRP: Červené světlo přetížení relé (Nelze zkompletovat jističe)",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!LKVC": "LKVC: Vysoké napětí není dostupné",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!LVD": "LVD: Trakční motory v chodu",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!LST": "LST: Brzdy v chodu",
  "Entities.gmod_subway_81-717_mvm.Buttons.CabinDoor.CabinDoor": "Dveře kabiny",
  "Entities.gmod_subway_81-717_mvm.Buttons.Reverser.KVReverserDown": "Reverz vzad",
  "Entities.gmod_subway_81-717_mvm.Buttons.Reverser.KVReverserUp": "Reverz vpřed",
  "Entities.gmod_subway_81-717_mvm.Buttons.PassengerDoor1.PassengerDoor": "Dveře z kabiny do interiéru",
  "Entities.gmod_subway_81-717_mvm.Buttons.UAVAPanel.UAVAToggle": "UAVA: Univerzální Automatický Vypínač Autostopu (vypnutí autostopu)",
  "Entities.gmod_subway_81-717_mvm.Buttons.UAVAPanel.UAVAContactSet": "UAVA: Univerzální Automatický Vypínač Autostopu (obnovení kontaktů)",
  "Entities.gmod_subway_81-717_mvm.Buttons.EPKDisconnect.EPKToggle": "Ventil EPV",
  "Entities.gmod_subway_81-717_mvm.Buttons.Help.ShowHelp": "Pomoc při řízení soupravy",
  "Entities.gmod_subway_81-717_mvm.Buttons.ParkingBrake2.1:ParkingBrakeToggle": "Parkovací brzda",
  "Entities.gmod_subway_81-717_mvm.Buttons.RearPneumatic.RearBrakeLineIsolationToggle": "Izolační ventil brzdového potrubí",
  "Entities.gmod_subway_81-717_mvm.Buttons.RearPneumatic.RearTrainLineIsolationToggle": "Izolační ventil hlavního potrubí",
  "Entities.gmod_subway_81-717_mvm.Buttons.AirDistributor.AirDistributorDisconnectToggle": "Odpojit vzduchový rozdělovač",

  "Entities.gmod_subway_81-714_mvm.Buttons.GV.GVToggle": "Hlavní vypínač",
  "Entities.gmod_subway_81-714_mvm.Buttons.RearPneumatic.RearBrakeLineIsolationToggle": "Izolační ventil brzdového potrubí",
  "Entities.gmod_subway_81-714_mvm.Buttons.RearPneumatic.RearTrainLineIsolationToggle": "Izolační ventil hlavního potrubí",
  "Entities.gmod_subway_81-714_mvm.Buttons.RearDoor.RearDoor": "Zadní dveře",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Left.DriverValveBLDisconnectToggle": "Ventil brzdového potrubí",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Left.DriverValveTLDisconnectToggle": "Ventil hlavního potrubí",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Left.A65Toggle": "A65 Osvětlení interiéru",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Left.A56Toggle": "A56 Baterie",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Left.A63Toggle": "A63 Napájení VR (IGLA/BIS)",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Left.A10Toggle": "A10 Ovládání kompresoru",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Left.A30Toggle": "A30 Motor HK",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Left.A80Toggle": "A80 Napájení trakčních motorů",
  "Entities.gmod_subway_81-714_mvm.Buttons.FrontPneumatic.FrontBrakeLineIsolationToggle": "Izolační ventil brzdového potrubí",
  "Entities.gmod_subway_81-714_mvm.Buttons.FrontPneumatic.FrontTrainLineIsolationToggle": "Izolační ventil hlavního potrubí",
  "Entities.gmod_subway_81-714_mvm.Buttons.FrontPneumatic.ParkingBrakeToggle": "Parkovací brzda",
  "Entities.gmod_subway_81-714_mvm.Buttons.AirDistributor.AirDistributorDisconnectToggle": "Odpojit vzduchový rozdělovač",
  "Entities.gmod_subway_81-714_mvm.Buttons.FrontDoor.FrontDoor": "Přední dveře",
  "Entities.gmod_subway_81-714_mvm.Buttons.Battery.VBToggle": "VB: Baterie zapnuto/vypnuto",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A54Toggle": "A54 Vyp. řízení",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A27Toggle": "A27 Osv.kabina, kontr. MR, park. brzda",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A24Toggle": "A24 Dobíjení baterie",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A53Toggle": "A53 Vlak. obvody",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A13Toggle": "A13 Dveřní signalizace",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A32Toggle": "A32 Otevř. pravé dveře",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A31Toggle": "A31 Otevř. levé dveře",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A16Toggle": "A16 Zavírání dveří",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A12Toggle": "A12 Zavírání nouze",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A50Toggle": "A50 Přídrž PBO",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A51Toggle": "A51 Vypnutí DIP a osvětlení",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A1Toggle": "A1  J-1",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.KRPSet": "START: Nouzové řízení",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.VozvratRPSet": "Korekce zátěže reléé",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.RezMKSet": "Kompresor nouze",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.VMKToggle": "Kompresor",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.BPSNonToggle": "Měnič",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A2Toggle": "A2  J-2",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A3Toggle": "A3  J-3",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A17Toggle": "A17 Korekce zátěže relé",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A5Toggle": "A5  ",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A6Toggle": "A6  B-1",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A8Toggle": "A8  Pneumatické ventily #1, #2",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A20Toggle": "A20 LS 2, LS 5",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A25Toggle": "A25 Ruční brzdění",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A22Toggle": "A22 Stykač kompresoru",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A23Toggle": "A23 Nouzové zapnutí kompresoru",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A39Toggle": "A39 Nouzové řízení vozidla",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A14Toggle": "A14 Relé nouzového řízení"
}
]]
