return [[
{
  "Lang": "de",
  "Name": "Deutsch",

  "Entities.gmod_subway_81-717_mvm.Buttons.HelperPanel.VUD2Toggle": "VUD2: Tueren schliessen",
  "Entities.gmod_subway_81-717_mvm.Buttons.HelperPanel.VDLSet": "VDL: Oeffne Tueren links",
  "Entities.gmod_subway_81-717_mvm.Buttons.HelperPanel.R_Program2Helper": "Programm 2",
  "Entities.gmod_subway_81-717_mvm.Buttons.HelperPanel.R_Program1Helper": "Programm 1",
  "Entities.gmod_subway_81-717_mvm.Buttons.Battery_2.1:RC1Toggle": "RC-1: ARS Schalkreise abschalten",
  "Entities.gmod_subway_81-717_mvm.Buttons.Battery_2.1:VBToggle": "VB: Batterie an/aus",
  "Entities.gmod_subway_81-717_mvm.Buttons.Battery_2.1:UOSToggle": "RC-UOS: Geschwindigkeitsbegrenzungs Geraet",
  "Entities.gmod_subway_81-717_mvm.Buttons.Wiper.WiperToggle": "Schweibenwischer",
  "Entities.gmod_subway_81-717_mvm.Buttons.DriverValveDisconnect.DriverValveDisconnectToggle": "Zugdruckventil",
  "Entities.gmod_subway_81-717_mvm.Buttons.DriverValveDisconnect.DriverValveBLDisconnectToggle": "Bremsdruckventil",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.R_UNchToggle": "UNCh: Niederfrequenzverstaerker",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.R_ZSToggle": "Lautsprecher im Wagen einschalten",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.R_GToggle": "Lautsprecher im Fuehrerstand einschalten",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.R_RadioToggle": "Fahrgast Informations System",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.R_Program1Set": "Programm 1",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.R_Program2Set": "Programm 2",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.2:KVTSet": "KB: Sicherheitsschalter",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.VZ1Set": "VZ1: Pneumatisches Ventil Nr.1",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.VUD1Toggle": "VUD: Tueren Schliessen",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.KDLSet": "KDL: Oeffne Tueren links",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.KDLKToggle": "KDL Knopf Abdeckung",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.KDLRSet": "KDL: Oeffne Tueren links",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.KDLRKToggle": "KDL Knopf Abdeckung",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.DoorSelectToggle": "Tuerseite auswaehlen",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.KRZDSet": "RZD: Zwangsschliessen",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.R_VPRToggle": "VPR: Schalte Funkgeraet ein",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.VozvratRPSet": "Setze Wagonrelay zuruek",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.GreenRPLight": "RP: Gruene Ueberladungsrelay-Lampe (schuetzt die Motoren vor zu hoher Spannung)",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.AVULight": "AVU: Automatischer steuerung deaktivierer aktiv",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.LKVPLight": "LKVP: Hochspannungs-Transformator kontrolle",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.SPLight": "LSP: Brandgefahr (Relays ueberhitzen)",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.ConverterProtectionSet": "Transformatorschutz",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.KSNSet": "KSN: Ausfallanzeige",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.DIPoffSet": "Ring",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.ARSToggle": "ARS: Automatische Geschwindigkeitskontrolle",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.ALSToggle": "ALS: Automatische Zug Signalisierung",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.OtklAVUToggle": "Deaktiviere automatisches steuerungs Relay(fehler der AVU)",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.TormATToggle": "(platzhalter) Notbremse",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.L_1Toggle": "Wagenbeleuchtung",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.L_2Toggle": "Fuehrerstandbeleuchtung",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.L_3Toggle": "Steuerungsbeleuchtung",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.ALSFreqToggle": "Decodierer: ALS Frequenz waehler 1/5 oder 2/6",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.ParkingBrakeSignToggle": "Schild \"LoeSE DIE PARKBREMSE\"",
  "Entities.gmod_subway_81-717_mvm.Buttons.ParkingBrake.ParkingBrakeToggle": "Parkbremse",
  "Entities.gmod_subway_81-717_mvm.Buttons.ParkingBrake.DriverValveTLDisconnectToggle": "Zugdruckkreislauf Ventil",
  "Entities.gmod_subway_81-717_mvm.Buttons.IGLAButtons.IGLA1Set": "IGLA: Erster Taster",
  "Entities.gmod_subway_81-717_mvm.Buttons.IGLAButtons.IGLA2Set": "IGLA: Zweiter Taster",
  "Entities.gmod_subway_81-717_mvm.Buttons.IGLAButtons.IGLA3Set": "IGLA: Dritter Taster",
  "Entities.gmod_subway_81-717_mvm.Buttons.IGLAButtons.IGLA4Set": "IGLA: Vierter Taster",
  "Entities.gmod_subway_81-717_mvm.Buttons.BPSNFront.!Voltage": "Kontrollschaltkreis Volt",
  "Entities.gmod_subway_81-717_mvm.Buttons.BPSNFront.VMKToggle": "Schalte Kompressor an",
  "Entities.gmod_subway_81-717_mvm.Buttons.BPSNFront.BPSNonToggle": "BPSN: Zug Spannung",
  "Entities.gmod_subway_81-717_mvm.Buttons.BPSNFront.RezMKSet": "Notfall Kompressor Starten",
  "Entities.gmod_subway_81-717_mvm.Buttons.BPSNFront.ARS13Set": "ARS 13V: ARS stabile voltanzahl check",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!Speedometer": "Tachometer",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!LampLSN": "LSN: Ausfallanzeigenlicht (Fehler beim initialisieren der Schaltkreise)",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!LampRP": "RP: ueberladungsleuchte (Fehler beim initialisieren der Schaltkreise)",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!LampLHRK": "LhRK: Rheostat kontroll Lampe",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!LampLKT": "LKT: ARS Bremsleuchte",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!LampLKVD": "LKVD: ARS Motor deaktivierungsleuchte",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!LampLKVC": "LKVC: Hochspannung nicht vorhanden (Kein kontakt zur Stromschiene)",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!ARSOch": "OCh: Keine ARS Frequenz",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!ARS0": "0: ARS Stop signal",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!ARS40": "Geschwindigkeitslimit 40 kmh",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!ARS60": "Geschwindigkeitslimit 60 kmh",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!ARS70": "Geschwindigkeitslimit 70 kmh",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!ARS80": "Geschwindigkeitslimit 80 kmh",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!LampLSD1": "LSD: Tuerleuchte (Tueren sind geschlossen)",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!LampLSD2": "LSD: Tuerleuchte (Tueren sind geschlossen)",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!LampLST": "LST: Bremse aktiviert",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!LampLVD": "LVD: Motor aktiviert",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!LampLN": "LN: Richtungs signal",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!LampLRS": "LRS: Geschwindigkeitsleuchte(Naechste Geschwindigkeitsbegrenzung ist gleich oder groeЯer als die momentane)",
  "Entities.gmod_subway_81-717_mvm.Buttons.PneumaticPanels.!CylinderPressure": "Bremszylinderdruck",
  "Entities.gmod_subway_81-717_mvm.Buttons.PneumaticPanels.!LinePressure": "Luftdruck in Pneumatischem System (Rot: Bremskreislauf, Schwarz: Zugkreislauf)",
  "Entities.gmod_subway_81-717_mvm.Buttons.Battery.RC1Toggle": "RC-1: ARS Schaltkreise trennen",
  "Entities.gmod_subway_81-717_mvm.Buttons.Battery.UOSToggle": "RC-UOS: Geschwindigkeitslimit Geraet",
  "Entities.gmod_subway_81-717_mvm.Buttons.Battery.VBToggle": "VB: Batterie an/aus",
  "Entities.gmod_subway_81-717_mvm.Buttons.FrontPneumatic.FrontBrakeLineIsolationToggle": "Bremskreislauf Ventil",
  "Entities.gmod_subway_81-717_mvm.Buttons.FrontPneumatic.FrontTrainLineIsolationToggle": "Zugkreislauf Ventil",
  "Entities.gmod_subway_81-717_mvm.Buttons.ASNP.R_ASNPMenuSet": "ASNP: Menue",
  "Entities.gmod_subway_81-717_mvm.Buttons.ASNP.R_ASNPUpSet": "ASNP: Hoch",
  "Entities.gmod_subway_81-717_mvm.Buttons.ASNP.R_ASNPDownSet": "ASNP: Runter",
  "Entities.gmod_subway_81-717_mvm.Buttons.ASNP.R_ASNPOnToggle": "ASNP: Einschalten",
  "Entities.gmod_subway_81-717_mvm.Buttons.RearDoor.RearDoor": "Hecktuer",
  "Entities.gmod_subway_81-717_mvm.Buttons.Meters.!TotalVoltmeter": "Hochspannungs Voltmeter (kV)",
  "Entities.gmod_subway_81-717_mvm.Buttons.Meters.!TotalAmpermeter": "Ampermeter (A)",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A61Toggle": "A61 Zug leitung 6 kontrolle",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A55Toggle": "A55 Zug leitung 10AS kontrolle",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A54Toggle": "A54 Zug leitung 10AK kontrolle",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A56Toggle": "A56 Schalte Batteriespannung zu den Kontrollschaltkreisen ein",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A27Toggle": "A27 Schalte DIP und Beleuchtung ein",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A21Toggle": "A21 Tuerkontrolle",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A10Toggle": "A10 Motor-kompressor kontrolle",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A53Toggle": "A53 KVC Netzteil",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A43Toggle": "A43 ARS 12V Spannungsleitung",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A45Toggle": "A45 ARS Zug Leitung 10AU",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A42Toggle": "A42 ARS 75V Spannungsleitung",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A41Toggle": "A41 ARS bremsen",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.VUToggle": "VU  Zugkontrolle",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A64Toggle": "A64 Fuehrerstandsbeleuchtung",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A63Toggle": "A63 IGLA/BIS",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A50Toggle": "A50 Schalte DIP und Beleuchtung ein",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A51Toggle": "A51 Schalte DIP und Beleuchtung aus",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A23Toggle": "A23 Schalte Notfall Kompressor ein",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A14Toggle": "A14 Zug Leitung 18",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A75Toggle": "A75 Fuehrerstandsheistung",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A1Toggle": "A1  X-1",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A2Toggle": "A2  X-2",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A3Toggle": "A3  X-3",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A17Toggle": "A17 Setze Wagonrelay zuruek",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A62Toggle": "A62 Funkgeraet",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A29Toggle": "A29 Funklauschen",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A5Toggle": "A5 Mittelwagen",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A6Toggle": "A6  T-1",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A8Toggle": "A8  Pneumatische Ventile Nr.1 und Nr.2",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A20Toggle": "A20 Anfahr/Brems schaltkreis kontrolle, Zug Leitung 20",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A25Toggle": "A25 Manuelles Elektrisches bremsen",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A22Toggle": "A22 Schalte KK ein",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A30Toggle": "A30 Rheostat kontrolle",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A39Toggle": "A39 Notfallkontrolle",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A44Toggle": "A44 Notfall Zug Kontrolle",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A80Toggle": "A80 Spannungsschaltkreis modus",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A65Toggle": "A65 Wagonbeleuchtung",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.L_5Toggle": "Рђ49 Notfallbeleuchtung",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A24Toggle": "A24 Batterie Laden",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A32Toggle": "A32 Oeffne Tueren rechts",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A31Toggle": "A31 Oeffne Tueren links",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A16Toggle": "A16 Schliesse Tueren",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A13Toggle": "A13 Tueralarm",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A12Toggle": "A12 Zwangsschliessen",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A7Toggle": "A7  Rote Lampe",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A9Toggle": "A9  Rote Lampe",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A46Toggle": "A46 Weisse Lampe",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A47Toggle": "A47 Weisse Lampe",
  "Entities.gmod_subway_81-717_mvm.Buttons.PassengerDoor.PassengerDoor": "Wagentuer",
  "Entities.gmod_subway_81-717_mvm.Buttons.GV.GVToggle": "HV switch",
  "Entities.gmod_subway_81-717_mvm.Buttons.Stopkran.EmergencyBrakeValveToggle": "Notbremse",
  "Entities.gmod_subway_81-717_mvm.Buttons.InfoTableSelect.PrevSign": "Vorheriges schild",
  "Entities.gmod_subway_81-717_mvm.Buttons.InfoTableSelect.NextSign": "Naechstes schild",
  "Entities.gmod_subway_81-717_mvm.Buttons.InfoTableSelect.Num2P": "Zugnummer: Erhoehe Zweite Nummer",
  "Entities.gmod_subway_81-717_mvm.Buttons.InfoTableSelect.Num2M": "Zugnummer: Senke Zweite Nummer",
  "Entities.gmod_subway_81-717_mvm.Buttons.InfoTableSelect.Num1P": "Zugnummer: Erhoehe Erste Nummer",
  "Entities.gmod_subway_81-717_mvm.Buttons.InfoTableSelect.Num1M": "Zugnummer: Senke Erste Nummer",
  "Entities.gmod_subway_81-717_mvm.Buttons.Front.L_4Toggle": "Scheinwerfer",
  "Entities.gmod_subway_81-717_mvm.Buttons.Front.VUSToggle": "VUS: Fernlicht",
  "Entities.gmod_subway_81-717_mvm.Buttons.Front.VAHToggle": "VAH: Notfallfahrt (Fehler beim initialisieren des RPB Relays)",
  "Entities.gmod_subway_81-717_mvm.Buttons.Front.VADToggle": "VAD: Notfall Tuerschliessungs Mechanismus (Fehler des KD Relays)",
  "Entities.gmod_subway_81-717_mvm.Buttons.Front.KRPSet": "KRP: Notfall Start knopf",
  "Entities.gmod_subway_81-717_mvm.Buttons.Front.KAHSet": "Aktiviere Notfallfahrt",
  "Entities.gmod_subway_81-717_mvm.Buttons.Front.KAHKToggle": "KAH Knopfabdeckung",
  "Entities.gmod_subway_81-717_mvm.Buttons.Front.KUP": "Fuehrerstandsheitzung eingeschaltet",
  "Entities.gmod_subway_81-717_mvm.Buttons.Front.KDPSet": "KDP: Oeffne Tueren rechts",
  "Entities.gmod_subway_81-717_mvm.Buttons.Front.KDPKToggle": "KDP Knopfabdeckung",
  "Entities.gmod_subway_81-717_mvm.Buttons.Front.PN": "Bremskontrolle",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A61Toggle": "A61 Zug Leitung 6 Kontrolle",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A55Toggle": "A55 Zug Leitung 10AS Kontrolle",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A54Toggle": "A54 Zug Leitung 10AK Kontrolle",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A56Toggle": "A56 Aktiviere Batterie fuer Steuerungsschaltkreise",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A27Toggle": "A27 Aktiviere DIP und Belechtung",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A21Toggle": "A21 Tuerkontrolle",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A10Toggle": "A10 Kompressor kontrolle",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A53Toggle": "A53 KVC Stromversorgung",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A43Toggle": "A43 ARS 12V Spannungsleitung",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A45Toggle": "A45 ARS Zug Leitung 10AU",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A42Toggle": "A42 ARS 75V Spannungsleitung",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A41Toggle": "A41 ARS bremsen",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:VUToggle": "VU  Zug Kontrolle",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A64Toggle": "A64 Fuehrerstandsbeleuchtung",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A63Toggle": "A63 IGLA/BIS",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A50Toggle": "A50 Schalte DIP und Beleuchtung ein",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A51Toggle": "A51 Schalte DIP und Beleuchtung aus",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A23Toggle": "A23 Notfallkompressor einschalten",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A14Toggle": "A14 Zug Leitung 18",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A75Toggle": "A75 Fuehrerstandsheizung",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A1Toggle": "A1  X-1",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A2Toggle": "A2  X-2",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A3Toggle": "A3  X-3",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A17Toggle": "A17 Setze Wagonrelay zuruek",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A62Toggle": "A62 Funkgeraet",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A29Toggle": "A29 Funklauschen",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A5Toggle": "A5 Zwischenwagen",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A6Toggle": "A6  T-1",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A8Toggle": "A8  Pneumatische Ventile Nr.1 und Nr.2",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A20Toggle": "A20 Anfahr/Brems-relay kontrolle, Zug Leitung 20",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A25Toggle": "A25 Manuelles Elektrisches bremsen",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A22Toggle": "A22 Schalte KK ein",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A30Toggle": "A30 Rheostat steuerung fuer Motorspannung",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A39Toggle": "A39 Notfallkontrolle",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A44Toggle": "A44 Notfall Zug Kontrolle",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A80Toggle": "A80 Spannungsschaltkreismodus auswaehlen",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A65Toggle": "A65 Wagenbeleuchtung",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:L_5Toggle": "Рђ49 Notfallbeleuchtung",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A24Toggle": "A24 Batterie Laden",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A32Toggle": "A32 Oeffne Tueren rechts",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A31Toggle": "A31 Oeffne Tueren links",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A16Toggle": "A16 Schliesse Tueren",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A13Toggle": "A13 Tuerwarnung",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A12Toggle": "A12 Zwangsschliessen",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A7Toggle": "A7  Rote Lampe",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A9Toggle": "A9  Rote Lampe",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A46Toggle": "A46 Weisse Lampe",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A47Toggle": "A47 Weisse Lampe",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!Speedometer": "Tachometer",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!LSD": "LSD: Tuerleuchte(Tueren sind geschlossen)",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!LOCh": "NCh: Keine ARS Frequenz",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!L0": "0: ARS stop signal",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!LRS": "LRS: Geschwindigkeitsleuchte(Naechste Geschwindigkeitsbegrenzung ist gleich oder groeЯer als die momentane)",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!L40": "Geschwindigkeitsbegrenzung 40 kmh",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!L60": "Geschwindigkeitsbegrenzung 60 kmh",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!L80": "Geschwindigkeitsbegrenzung 80 kmh",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!L70": "Geschwindigkeitsbegrenzung 60 kmh",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!LRK": "RK: Rheostat kontroll Lampe",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!LEKK": "",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!LPU": "",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!LKVD": "LKVD: ARS Motor deaktivierungsleuchte",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!LKT": "LKT: ARS Bremsleuchte",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!LRP": "RP: ueberladungsleuchte (Fehler beim initialisieren der Schaltkreise)",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!LKVC": "LKVC: Hochspannung nicht vorhanden (Kein kontakt zur Stromschiene)",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!LVD": "LVD: Motor aktiviert",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!LST": "LST: Bremsen aktiviert",
  "Entities.gmod_subway_81-717_mvm.Buttons.CabinDoor.CabinDoor": "Fuehrerstandstuer",
  "Entities.gmod_subway_81-717_mvm.Buttons.Reverser.KVReverserDown": "Fahrtrichtungsschalter Rueckwaerts",
  "Entities.gmod_subway_81-717_mvm.Buttons.Reverser.KVReverserUp": "Fahrtrichtungsschalter Forwaerts",
  "Entities.gmod_subway_81-717_mvm.Buttons.PassengerDoor1.PassengerDoor": "Wagentuer",
  "Entities.gmod_subway_81-717_mvm.Buttons.UAVAPanel.UAVAToggle": "UAVA: Automatisches Zugbremssystem ausschalten(Verhindert das abbremsen des Zuges nach dem ueberfahren eines Signals mit der Stellung Stop)",
  "Entities.gmod_subway_81-717_mvm.Buttons.UAVAPanel.UAVAContactSet": "UAVA: Automatisches Zugbremssystem (Setze Kontakte zurueck)",
  "Entities.gmod_subway_81-717_mvm.Buttons.EPKDisconnect.EPKToggle": "EPV Oeffne Ventil",
  "Entities.gmod_subway_81-717_mvm.Buttons.Help.ShowHelp": "Zeige die Hilfe (Englisch)",
  "Entities.gmod_subway_81-717_mvm.Buttons.ParkingBrake2.1:ParkingBrakeToggle": "Parkbremse",
  "Entities.gmod_subway_81-717_mvm.Buttons.RearPneumatic.RearBrakeLineIsolationToggle": "Bremskrislauf schliessventil",
  "Entities.gmod_subway_81-717_mvm.Buttons.RearPneumatic.RearTrainLineIsolationToggle": "Zugdruckkreislauf schliessventil",
  "Entities.gmod_subway_81-717_mvm.Buttons.AirDistributor.AirDistributorDisconnectToggle": "Schalte Druckluftverteiler ab",

  "Entities.gmod_subway_81-714_mvm.Buttons.GV.GVToggle": "Hochspannungsschalter",
  "Entities.gmod_subway_81-714_mvm.Buttons.RearPneumatic.RearBrakeLineIsolationToggle": "Bremskrislauf schliessventil",
  "Entities.gmod_subway_81-714_mvm.Buttons.RearPneumatic.RearTrainLineIsolationToggle": "Zugdruckkreislauf schliessventil",
  "Entities.gmod_subway_81-714_mvm.Buttons.RearDoor.RearDoor": "Hecktuer",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Left.DriverValveBLDisconnectToggle": "Bremskrislauf schliessventil",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Left.DriverValveTLDisconnectToggle": "Zugdruckkreislauf schliessventil",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Left.A65Toggle": "A65 Wagenbeleuchtung",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Left.A56Toggle": "A56 Schalte Batterie fuer kontrollschaltkreise ein",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Left.A63Toggle": "A63 IGLA/BIS",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Left.A10Toggle": "A10 Kompressorkontrolle",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Left.A30Toggle": "A30 Rheostat kontrolle",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Left.A80Toggle": "A80 Spannungsschaltkreis modus",
  "Entities.gmod_subway_81-714_mvm.Buttons.FrontPneumatic.FrontBrakeLineIsolationToggle": "Bremskrislauf schliessventil",
  "Entities.gmod_subway_81-714_mvm.Buttons.FrontPneumatic.FrontTrainLineIsolationToggle": "Zugdruckkreislauf schliessventil",
  "Entities.gmod_subway_81-714_mvm.Buttons.FrontPneumatic.ParkingBrakeToggle": "Parkbremse",
  "Entities.gmod_subway_81-714_mvm.Buttons.AirDistributor.AirDistributorDisconnectToggle": "Schalte Druckluftverteiler ab",
  "Entities.gmod_subway_81-714_mvm.Buttons.FrontDoor.FrontDoor": "Fronttuer",
  "Entities.gmod_subway_81-714_mvm.Buttons.Battery.VBToggle": "VB: Batterie an/aus",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A54Toggle": "A54 Zug Leitung 10AK kontrolle",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A27Toggle": "A27 Schalte DIP und Beleuchtung ein",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A24Toggle": "A24 Batterie Laden",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A53Toggle": "A53 KVC Spannungsversorgung",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A13Toggle": "A13 Tueralarm",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A32Toggle": "A32 Oeffne Tueren rechts",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A31Toggle": "A31 Oeffne Tueren links",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A16Toggle": "A16 Schliesse Tueren",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A12Toggle": "A12 Zwangsschliessen",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A50Toggle": "A50 Schalte DIP und Beleuchtung ein",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A51Toggle": "A51 Schalte DIP und Beleuchtung aus",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A1Toggle": "A1  X-1",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.KRPSet": "START: Notfallstart Knopf",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.VozvratRPSet": "Setze Wagonrelay zurueck",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.RezMKSet": "Notfallkompressor starten",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.VMKToggle": "Schalte Kompressor ein",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.BPSNonToggle": "BPSN: Zugspannung",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A2Toggle": "A2  X-2",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A3Toggle": "A3  X-3",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A17Toggle": "A17 Setze Wagonrelay zurueck",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A5Toggle": "A5  ",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A6Toggle": "A6  T-1",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A8Toggle": "A8  Pneumatisches Ventil Nr.1 und Nr.2",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A20Toggle": "A20 Anfahr/Brems schaltkreis kontrolle, Zug Leitung 20",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A25Toggle": "A25 Manuelles Elektisches bremsen",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A22Toggle": "A22 Schalte KK ein",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A23Toggle": "A23 Notfallkompressor starten",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A39Toggle": "A39 Notfallsteuerung",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A14Toggle": "A14 Zug Leitung 18"
}
]]
