return [[
{
	"Lang": "de",
	"Name": "Deutsch",
	"Panel.Admin": "Admin",
	"Panel.Client": "Client",
	"Panel.DrawDebugInfo": "Draw debugging info",
	"Panel.DisableCamAccel": "Deaktivere Bewegende Camera",
	"Panel.DisableHoverText": "Deaktivere Info Text",

	"Entities.gmod_subway_base.Name": "U-Bahn Basis",
	"Entities.gmod_subway_81-703.Name": "E (Triebkopf)",
	"Entities.gmod_subway_81-703_2.Name": "E (Zwischenwagen)",
	"Entities.gmod_subway_81-717_mvm.Name": "81-717(MVM)",
	"Entities.gmod_subway_81-717_lvz.Name": "81-717(LVZ)",
	"Entities.gmod_subway_81-714_mvm.Name": "81-714(MVM)",
	"Entities.gmod_subway_81-714_lvz.Name": "81-714(LVZ)",
	"Entities.gmod_subway_81-7036.Name": "81-7036 (Dummy)",
	"Entities.gmod_subway_81-7037.Name": "81-7037 (Dummy)",
	"Entities.gmod_subway_81-720.Name": "81-720 (Triebkopf)",
	"Entities.gmod_subway_81-721.Name": "81-721 (Zwischenwagen)",
	"Entities.gmod_subway_81-722.Name": "81-722 (Triebkopf)",
	"Entities.gmod_subway_81-723.Name": "81-723 (Zwischenwagen mit Motor)",
	"Entities.gmod_subway_81-724.Name": "81-724 (Zwischenwagen ohne Motor)",
	"Entities.gmod_subway_e.Name": "E",
	"Entities.gmod_subway_em.Name": "Em",
	"Entities.gmod_subway_ema.Name": "Ema",
	"Entities.gmod_subway_ezh.Name": "Ezh",
	"Entities.gmod_subway_ezh1.Name": "Ezh1",
	"Entities.gmod_subway_em508.Name": "Em-508",
	"Entities.gmod_subway_em508_int.Name": "Em-508 (Zwischenwagen)",
	"Entities.gmod_subway_ezh3.Name": "Ezh3",
	"Entities.gmod_subway_ezh3ru1.Name": "Ezh3 RU1",
	"Entities.gmod_subway_ema508t.Name": "Em-508t",
	"Entities.gmod_subway_tatra_t3.Name": "Tatra T3",
	"Entities.gmod_subway_ai.Name": "KI Zug",

	"Entities.gmod_train_bogey.Name": "Drehgestell",
	"Entities.gmod_train_couple.Name": "Kupplung",

	"Entities.gmod_track_pui.Name": "PUI Uhr",
	"Entities.gmod_track_mus_elektronika7.Name": "Digitale Uhr",
	"Entities.gmod_mus_clock_analog.Name": "Analoge Uhr",
	"Entities.gmod_track_clock_time.Name": "Grosser Uhr",
	"Entities.gmod_track_clock_small.Name": "Kleiner Intervallanzeiger",
	"Entities.gmod_track_clock_interval.Name": "Grosser Intervallanzeiger",
	"Entities.gmod_track_switch.Name": "Weichenbox",
	"Entities.gmod_track_powermeter.Name": "Messgeraet",
	"Entities.gmod_track_controller.Name": "Gleis Kontroller",
	"Entities.gmod_track_udochka.Name": "Elektrischer Kontakt",
	"Entities.gmod_train_spawner.Name": "Zug Spawner"
}
]]
