return [[
{
  "Lang": "de",
  "Name": "Deutsch",


  "Entities.gmod_subway_ezh3.Buttons.Stopkran.EmergencyBrakeValveToggle": "Notbremse",
  "Entities.gmod_subway_ezh3.Buttons.Back.BackDoor": "Wagentuer",
  "Entities.gmod_subway_ezh3.Buttons.DriverValveBLTLDisconnect.DriverValveBLDisconnectToggle": "Bremsdruckventil",
  "Entities.gmod_subway_ezh3.Buttons.DriverValveBLTLDisconnect.DriverValveTLDisconnectToggle": "Zugdruckventil",
  "Entities.gmod_subway_ezh3.Buttons.Battery.VBToggle": "VB: Batterie an/aus (Niedrigspannung)",
  "Entities.gmod_subway_ezh3.Buttons.FrontPneumatic.FrontBrakeLineIsolationToggle": "Bremsdruckventil",
  "Entities.gmod_subway_ezh3.Buttons.FrontPneumatic.FrontTrainLineIsolationToggle": "Zugdruckventil",
  "Entities.gmod_subway_ezh3.Buttons.ASNP.R_ASNPMenuSet": "Ansager: Menue",
  "Entities.gmod_subway_ezh3.Buttons.ASNP.R_ASNPUpSet": "Ansager: Hoch",
  "Entities.gmod_subway_ezh3.Buttons.ASNP.R_ASNPDownSet": "Ansager: Runter",
  "Entities.gmod_subway_ezh3.Buttons.ASNP.R_ASNPOnToggle": "Ansager: An",
  "Entities.gmod_subway_ezh3.Buttons.PassengerDoor1.PassengerDoor": "Wagentuer",
  "Entities.gmod_subway_ezh3.Buttons.PassengerDoor.PassengerDoor": "Wagentuer",
  "Entities.gmod_subway_ezh3.Buttons.CabinDoor.CabinDoor": "Fuehrerstandstuer",
  "Entities.gmod_subway_ezh3.Buttons.Front.FrontDoor": "Fronttuer",
  "Entities.gmod_subway_ezh3.Buttons.GV.GVToggle": "Hochspannungsschalter",
  "Entities.gmod_subway_ezh3.Buttons.RearPneumatic.RearTrainLineIsolationToggle": "Zugdruckventil",
  "Entities.gmod_subway_ezh3.Buttons.RearPneumatic.RearBrakeLineIsolationToggle": "Bremsdruckventil",
  "Entities.gmod_subway_ezh3.Buttons.Panel.!OCH": "NCh: Keine Ars Frequenz",
  "Entities.gmod_subway_ezh3.Buttons.Panel.!0": "0: ARS Stop Signal",
  "Entities.gmod_subway_ezh3.Buttons.Panel.!40": "Geschwindigkeitslimit 40 kmh",
  "Entities.gmod_subway_ezh3.Buttons.Panel.!60": "Geschwindigkeitslimit 60 kmh",
  "Entities.gmod_subway_ezh3.Buttons.Panel.!70": "Geschwindigkeitslimit 70 kmh",
  "Entities.gmod_subway_ezh3.Buttons.Panel.!80": "Geschwindigkeitslimit 80 kmh",
  "Entities.gmod_subway_ezh3.Buttons.Panel.!Speedometer": "Tachometer (km/h)",
  "Entities.gmod_subway_ezh3.Buttons.Panel.!TotalAmpermeter": "Amperemeter (A)",
  "Entities.gmod_subway_ezh3.Buttons.Panel.!TotalVoltmeter": "Voltmeter (kV)",
  "Entities.gmod_subway_ezh3.Buttons.Panel.!BatteryVoltage": "Batterie Voltanzahl(V)",
  "Entities.gmod_subway_ezh3.Buttons.Panel.!BrakeCylinder": "Bremsdruck",
  "Entities.gmod_subway_ezh3.Buttons.Panel.!LinesPressure": "Luftdruck in Pneumatischem System (Rot: Bremskreislauf, Schwarz: Zugkreislauf)",
  "Entities.gmod_subway_ezh3.Buttons.Main.KU1Toggle": "Schalte Kompressor ein",
  "Entities.gmod_subway_ezh3.Buttons.Main.SAMM1Set": "SAMM: Deaktiviere Automatisches Fahren",
  "Entities.gmod_subway_ezh3.Buttons.Main.SAMM2Set": "SAMM: Start",
  "Entities.gmod_subway_ezh3.Buttons.Main.SAMM3Set": "SAMM: Neustart",
  "Entities.gmod_subway_ezh3.Buttons.Main.SAMMSignal1": "Lampe: Fahren-Bremsen",
  "Entities.gmod_subway_ezh3.Buttons.Main.SAMMSignal2": "Lampe: SAMM Aktiviert",
  "Entities.gmod_subway_ezh3.Buttons.Main.SAMMSignal3": "Lamp: Aktiviere SAMM Kontrolleinheit",
  "Entities.gmod_subway_ezh3.Buttons.Main.SAMMOnToggle": "SAMM: Aktiviere automatisches Fahren",
  "Entities.gmod_subway_ezh3.Buttons.Main.SAMMBlokToggle": "SAMM: Kontrolleinheit",
  "Entities.gmod_subway_ezh3.Buttons.Main.SAMMCommand3Set": "SAMM: X-2",
  "Entities.gmod_subway_ezh3.Buttons.Main.SAMMCommand2Set": "SAMM: Aufholen",
  "Entities.gmod_subway_ezh3.Buttons.Main.SAMMCommand1Set": "SAMM: Genehmigung",
  "Entities.gmod_subway_ezh3.Buttons.Main.KSNSet": "KSN: Ausfall",
  "Entities.gmod_subway_ezh3.Buttons.Main.R_Program1Set": "Programm 1",
  "Entities.gmod_subway_ezh3.Buttons.Main.R_Program2Set": "Programm 2",
  "Entities.gmod_subway_ezh3.Buttons.Main.VUSToggle": "Fahrlicht/Fernlicht)",
  "Entities.gmod_subway_ezh3.Buttons.Main.L_3Toggle": "Armaturenbeleuchtung",
  "Entities.gmod_subway_ezh3.Buttons.Main.VAHToggle": "Notfall Fahren",
  "Entities.gmod_subway_ezh3.Buttons.Main.DIPonSet": "Osv. Vkl.: Schalte Licht ein",
  "Entities.gmod_subway_ezh3.Buttons.Main.DIPoffSet": "Osv. Vykl.: Schalte Licht aus",
  "Entities.gmod_subway_ezh3.Buttons.Main.KSDSet": "KSD: Türsignalisierungsprüfung",
  "Entities.gmod_subway_ezh3.Buttons.Main.KVTSet": "KVT: Bremsenwahrnehmungstaste",
  "Entities.gmod_subway_ezh3.Buttons.Main.KBSet": "KB: Warnungs Knopf",
  "Entities.gmod_subway_ezh3.Buttons.Main.KBLamp": "Lampe: Rehostat Kontroller",
  "Entities.gmod_subway_ezh3.Buttons.Main.ARSToggle": "ARS: Automatische Geschwindigkeitskontrolle",
  "Entities.gmod_subway_ezh3.Buttons.Main.R_UNchToggle": "UNCh: Niedrigfrequenzverstaerker",
  "Entities.gmod_subway_ezh3.Buttons.Main.VUD1Toggle": "VUD: Schliesse Tueren",
  "Entities.gmod_subway_ezh3.Buttons.Main.R_RadioToggle": "Fahrgast Informations System",
  "Entities.gmod_subway_ezh3.Buttons.Main.ALSToggle": "ALS: Automatische Zug Signalisierung",
  "Entities.gmod_subway_ezh3.Buttons.Main.VozvratRPSet": "KVRP: Setze Wagonrelay zuruek",
  "Entities.gmod_subway_ezh3.Buttons.Main.RingSet": "Pfeifen",
  "Entities.gmod_subway_ezh3.Buttons.Main.L_2Toggle": "Fuehrerstandbeleuchtung",
  "Entities.gmod_subway_ezh3.Buttons.Main.KRZDSet": "KRZD: Zwangsschliessen",
  "Entities.gmod_subway_ezh3.Buttons.Main.KDPSet": "KDP: Oeffne Tueren rechts",
  "Entities.gmod_subway_ezh3.Buttons.Main.KDLSet": "KDL: Oeffne Tueren links",
  "Entities.gmod_subway_ezh3.Buttons.Main.KAHSet": "KAH: Notfallfahrt",
  "Entities.gmod_subway_ezh3.Buttons.Main.RezMKSet": "Notfall Kompressor Starten",
  "Entities.gmod_subway_ezh3.Buttons.Main.KRPSet": "KRP: Notfallstartknopf",
  "Entities.gmod_subway_ezh3.Buttons.Main.RSTToggle": "VPR: Funk",
  "Entities.gmod_subway_ezh3.Buttons.Main.R_GToggle": "Lautsprecher im Fuehrerstand einschalten",
  "Entities.gmod_subway_ezh3.Buttons.Main.R_ZSToggle": "ZS: Lautsprecher im Wagon einschalten",
  "Entities.gmod_subway_ezh3.Buttons.Main.Custom2Set": "Platzhalter",
  "Entities.gmod_subway_ezh3.Buttons.Main.Custom3Set": "Platzhalter",
  "Entities.gmod_subway_ezh3.Buttons.Main.ASNPPlay": "Fahrgast informations System funktioniert",
  "Entities.gmod_subway_ezh3.Buttons.AV1.VU3Toggle": "VU3: Fuehrerstandsbeleuchtung",
  "Entities.gmod_subway_ezh3.Buttons.AV1.VU2Toggle": "VU2: Notfallbeleuchtung (45V)",
  "Entities.gmod_subway_ezh3.Buttons.AV1.VU1Toggle": "VU1: Fuehrerstandsheizung (3kWt)",
  "Entities.gmod_subway_ezh3.Buttons.AVMain.AV8BToggle": "AV-8B: Automatischer Schalter (Hochspannung)",
  "Entities.gmod_subway_ezh3.Buttons.RC1.RC1Toggle": "RC-ARS: ARS Relay",
  "Entities.gmod_subway_ezh3.Buttons.UAVAPanel.UAVAToggle": "UAVA: Automatisches Zugbremssystem ausschalten(Verhindert das abbremsen des Zuges nach dem ueberfahren eines Signals mit der Stellung Stop)",
  "Entities.gmod_subway_ezh3.Buttons.UAVAPanel.UAVAContactSet": "UAVA: Automatisches Zugbremssystem (Setze Kontakte zurueck)",
  "Entities.gmod_subway_ezh3.Buttons.VUHelper.VUToggle": "VU: Aktiviere Zugkontrolle",
  "Entities.gmod_subway_ezh3.Buttons.HelperPanel.VDLSet": "KDL: Oeffne Tueren links",
  "Entities.gmod_subway_ezh3.Buttons.HelperPanel.VUD2Toggle": "VUD2: Schliesse Tueren",
  "Entities.gmod_subway_ezh3.Buttons.EPKDisconnect.EPKToggle": "EPK Oeffne Ventil",
  "Entities.gmod_subway_ezh3.Buttons.VU.VUToggle": "VU: Aktiviere Zugkontrolle",
  "Entities.gmod_subway_ezh3.Buttons.ParkingBrake.ParkingBrakeLeft": "Parkbremse",
  "Entities.gmod_subway_ezh3.Buttons.ParkingBrake.ParkingBrakeRight": "Parkbremse",
  "Entities.gmod_subway_ezh3.Buttons.AirDistributor.AirDistributorDisconnectToggle": "Schalte Druckluftverteiler ab",

  "Entities.gmod_subway_em508t.Buttons.Stopkran.EmergencyBrakeValveToggle": "Notbremse",
  "Entities.gmod_subway_em508t.Buttons.Battery.VBToggle": "VB: Battery on/off (low voltage)",
  "Entities.gmod_subway_em508t.Buttons.FrontPneumatic.FrontBrakeLineIsolationToggle": "Bremsdruckventil",
  "Entities.gmod_subway_em508t.Buttons.FrontPneumatic.FrontTrainLineIsolationToggle": "Zugdruckventil",
  "Entities.gmod_subway_em508t.Buttons.GV.GVToggle": "Hochspannungschalter",
  "Entities.gmod_subway_em508t.Buttons.RearPneumatic.RearTrainLineIsolationToggle": "Zugdruckventil",
  "Entities.gmod_subway_em508t.Buttons.RearPneumatic.RearBrakeLineIsolationToggle": "Bremsdruckventil",
  "Entities.gmod_subway_em508t.Buttons.RearDoor.RearDoor": "Wagentuer",
  "Entities.gmod_subway_em508t.Buttons.Back2.!HVFuse": "Hochspannungssicherungen",
  "Entities.gmod_subway_em508t.Buttons.Back2.!Relays": "Batterie- und Steuerungs-Schaltkreise",
  "Entities.gmod_subway_em508t.Buttons.Back2.!Heater": "Heizung",
  "Entities.gmod_subway_em508t.Buttons.Front.FrontDoor": "Fronttuer",
  "Entities.gmod_subway_em508t.Buttons.AV1.VU3Toggle": "VU3: Fuehrerstandsbeleuchtung",
  "Entities.gmod_subway_em508t.Buttons.AV1.VU2Toggle": "VU2: Notfallbeleuchtung (45V)",
  "Entities.gmod_subway_em508t.Buttons.AV1.VU1Toggle": "VU1: Fuehrerstandsheizung (3kWt)",
  "Entities.gmod_subway_em508t.Buttons.ParkingBrake.ParkingBrakeLeft": "Parkbremse",
  "Entities.gmod_subway_em508t.Buttons.ParkingBrake.ParkingBrakeRight": "Parkbremse",
  "Entities.gmod_subway_em508t.Buttons.CabinDoor.CabinDoor1": "Fuehrerstandstuer",
  "Entities.gmod_subway_em508t.Buttons.PassengerDoor.PassengerDoor": "Wagentuer",
  "Entities.gmod_subway_em508t.Buttons.PassengerDoor1.PassengerDoor": "Wagentuer",
  "Entities.gmod_subway_em508t.Buttons.Main.!RedRP": "RP: Rote Ueberladungsrelay-Lampe (schuetzt die Motoren vor zu hoher Spannung)",
  "Entities.gmod_subway_em508t.Buttons.Main.!GreenRP": "RP: Gruene Ueberladungsrelay-Lampe (schuetzt die Motoren vor zu hoher Spannung)",
  "Entities.gmod_subway_em508t.Buttons.Main.!SD": "Tueren geschlossen)",
  "Entities.gmod_subway_em508t.Buttons.Main.KDLSet": "Oeffne Tueren links",
  "Entities.gmod_subway_em508t.Buttons.Main.KSDSet": "Tuerkontrolle",
  "Entities.gmod_subway_em508t.Buttons.Main.VozvratRPSet": "Setze Wagonrelay zuruek",
  "Entities.gmod_subway_em508t.Buttons.Main.KSNSet": "Ausfallschalter",
  "Entities.gmod_subway_em508t.Buttons.Main.VUD1Toggle": "Schliesse Tueren",
  "Entities.gmod_subway_em508t.Buttons.Main.KU1Toggle": "Kompressor",
  "Entities.gmod_subway_em508t.Buttons.Main.DIPonSet": "KU4: Schalte Wagonbeleuchtung ein",
  "Entities.gmod_subway_em508t.Buttons.Main.DIPoffSet": "KU5: Schalte Wagonbeleuchtung aus",
  "Entities.gmod_subway_em508t.Buttons.Main.RezMKSet": "Switch: Notfallkompressor starten",
  "Entities.gmod_subway_em508t.Buttons.Main.KDPSet": "KDP: Oeffne Tueren rechts",
  "Entities.gmod_subway_em508t.Buttons.Main.KRZDSet": "KU10: Zwangsschliessen",
  "Entities.gmod_subway_em508t.Buttons.AVMain.AV8BToggle": "AV-8B: Automat (Hochspannungs Schalter)",
  "Entities.gmod_subway_em508t.Buttons.VU.VUToggle": "VU: Aktiviere Zugkontrolle",
  "Entities.gmod_subway_em508t.Buttons.VU.!Voltage": "Kontrolliere die Voltanzahl der Schaltkreise",
  "Entities.gmod_subway_em508t.Buttons.HelperPanel.VUD2Toggle": "VUD2: Schliesse Tueren",
  "Entities.gmod_subway_em508t.Buttons.HelperPanel.VDLSet": "VDL: Oeffne Tueren links",
  "Entities.gmod_subway_em508t.Buttons.DriverValveBLTLDisconnect.DriverValveBLDisconnectToggle": "Bremsdruckventil",
  "Entities.gmod_subway_em508t.Buttons.DriverValveBLTLDisconnect.DriverValveTLDisconnectToggle": "Zugdruckventil",
  "Entities.gmod_subway_em508t.Buttons.AirDistributor.AirDistributorDisconnectToggle": "Schalte Druckluftverteiler ab"
}
]]
