return [[
{
  "Lang": "de",
  "Name": "Deutsch",

  "Entities.gmod_subway_81-720.Buttons.VityazButtons.VityazF1Set": "Vityaz: F1",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.VityazF2Set": "Vityaz: Naechster Bildschirm",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.VityazF3Set": "Vityaz: Vorheriger Bildschirm",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.VityazF4Set": "Vityaz: Haupt",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.Vityaz1Set": "Vityaz: 1",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.Vityaz4Set": "Vityaz: 4",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.Vityaz7Set": "Vityaz: 7",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.Vityaz2Set": "Vityaz: 2",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.Vityaz5Set": "Vityaz: 5",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.Vityaz8Set": "Vityaz: 8",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.Vityaz0Set": "Vityaz: 0",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.Vityaz3Set": "Vityaz: 3",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.Vityaz6Set": "Vityaz: 6",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.Vityaz9Set": "Vityaz: 9",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.VityazF5Set": "Vityaz: Loeschen",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.VityazF6Set": "Vityaz: Hoch\\Geschwindigkeit",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.VityazF7Set": "Vityaz: Runter\\Stromsaerke",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.VityazF8Set": "Vityaz: Eingeben\\Wagen equipment",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.VityazF9Set": "Vityaz: Auswaehlen\\Wagen equipment kontrolle",
  "Entities.gmod_subway_81-720.Buttons.RV.EmerX1Set": "Notfall X-1",
  "Entities.gmod_subway_81-720.Buttons.RV.EmerX2Set": "Notfall X-2",
  "Entities.gmod_subway_81-720.Buttons.RV.EmerCloseDoorsSet": "Zwangschliessen",
  "Entities.gmod_subway_81-720.Buttons.RV.EmergencyDoorsToggle": "Notausgaenge",
  "Entities.gmod_subway_81-720.Buttons.BackVent.VentCondMode-": "Belueftungs Kapazitaet: +",
  "Entities.gmod_subway_81-720.Buttons.BackVent.VentCondMode+": "Belueftungs Kapazitaet: -",
  "Entities.gmod_subway_81-720.Buttons.BackVent.VentHeatMode+": "+",
  "Entities.gmod_subway_81-720.Buttons.BackVent.VentHeatMode-": "-",
  "Entities.gmod_subway_81-720.Buttons.BackVent.VentStrengthMode-": "Belueftungs Staerke +",
  "Entities.gmod_subway_81-720.Buttons.BackVent.VentStrengthMode+": "Belueftungs Staerke -",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV1Toggle": "SF1: Kontrolliere Spannung",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV2Toggle": "SF2: BUV Spannung (Zugmitte)",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV3Toggle": "SF3: BUTP Spannung (Zugfront)",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV4Toggle": "SF4: BUTP Kontrolle",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV5Toggle": "SF5: BUTP Notfall Kontrolle",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV6Toggle": "SF6: BUTP Spannung",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV7Toggle": "SF7: BBE (Zugeigenes Netzeil)",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV8Toggle": "SF8: BV Kontrolle",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV9Toggle": "SF9: BV Spannung (Wagen relay)",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV10Toggle": "SF10: PPO",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV11Toggle": "SF11: Kompressor",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV12Toggle": "SF12: Tueren schliessen",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV13Toggle": "SF13: Oeffne Tueren links",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV14Toggle": "SF14: Oeffne Tueren rechts",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV15Toggle": "SF15: Front Tuer",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV16Toggle": "SF16: Fahrgast Informations System",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV17Toggle": "SF17: Notfall Sprechanlage",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV18Toggle": "SF18: (Platzhalter)",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV19Toggle": "SF19: Wagenbeleuchtung",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV20Toggle": "SF20: Notfall Wagenbeleuchtung",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV21Toggle": "SF21: Geschwindigkeits Sensor",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV22Toggle": "SF22: Parkbremse",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV23Toggle": "SF23: Erste Ventilatorgruppe Kontrolle",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV24Toggle": "SF24: Zweite Ventilatorgruppe Kontrolle",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV25Toggle": "SF25: Schalte erste Ventilatorgruppe ein",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV26Toggle": "SF26: Schalte zweite Ventilatorgruppe ein",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV27Toggle": "SF27: Pre-Bremseinstellung",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV28Toggle": "SF28: ZKK Spannung",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV29Toggle": "SF29: Stromabnehmer",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV30Toggle": "SF30: Linienplan",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV31Toggle": "SF31: (Platzhalter)",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV32Toggle": "SF32: (Platzhalter)",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV33Toggle": "SF33: (Platzhalter)",
  "Entities.gmod_subway_81-720.Buttons.ASNP.R_ASNPMenuSet": "ASNP: Menue",
  "Entities.gmod_subway_81-720.Buttons.ASNP.R_ASNPUpSet": "ASNP: Hoch",
  "Entities.gmod_subway_81-720.Buttons.ASNP.R_ASNPDownSet": "ASNP: Runter",
  "Entities.gmod_subway_81-720.Buttons.ASNP.R_ASNPOnToggle": "ASNP: Einschalten",
  "Entities.gmod_subway_81-720.Buttons.PneumoHelper1.!BrakeCylinder": "Bremszylinder",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF1Toggle": "SF1: Zugspannung",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF2Toggle": "SF2: Hauptschalter",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF3Toggle": "SF3: Notfall Kontrolle",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF4Toggle": "SF4: BARS (ARS)",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF5Toggle": "SF5: BUP (Zugkontrolle)",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF6Toggle": "SF6: BKCU (Steuergeraetkommunikation)",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF7Toggle": "SF7: BARS (ARS unit)",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF8Toggle": "SF8: Fahrgast Informations System",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF9Toggle": "SF9: Radiostation",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF10Toggle": "SF10: Wagen orientation",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF11Toggle": "SF11: Richtung",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF12Toggle": "SF12: Erste Scheinwerfergruppe",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF13Toggle": "SF13: Zweite Scheinwerfergruppe",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF14Toggle": "SF14: Markierungsleuchten",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF15Toggle": "SF15: Fuehrerstandsbeleuchtung",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF16Toggle": "SF16: Heizung",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF17Toggle": "SF17: Fuehrerstandsbelueftung",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF18Toggle": "SF18: Radschmierung",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF19Toggle": "SF19: Hauptspannung",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF20Toggle": "SF20: Notfallspannung",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF21Toggle": "SF21: Tueren Oeffnen",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF22Toggle": "SF22: Tueren Schliessen",
  "Entities.gmod_subway_81-720.Buttons.BTO.K29Toggle": "KRMSH",
  "Entities.gmod_subway_81-720.Buttons.PassengerDoor2.PassengerDoor": "Wagontuer",
  "Entities.gmod_subway_81-720.Buttons.VoltHelper2.!HV": "Voltmeter (kV)",
  "Entities.gmod_subway_81-720.Buttons.VoltHelper2.!I1_3": "Erste Motorgruppe Stromstaerke (A)",
  "Entities.gmod_subway_81-720.Buttons.VoltHelper2.!I2_4": "Zweite Motorgruppe Stromstaerke (A)",
  "Entities.gmod_subway_81-720.Buttons.GV.GVToggle": "Hochspannungsschalter",
  "Entities.gmod_subway_81-720.Buttons.RearPneumatic.RearBrakeLineIsolationToggle": "Bremsdruckventil",
  "Entities.gmod_subway_81-720.Buttons.RearPneumatic.RearTrainLineIsolationToggle": "Zugdruckventil",
  "Entities.gmod_subway_81-720.Buttons.RearDoor1.RearDoor": "Tuer",
  "Entities.gmod_subway_81-720.Buttons.RearDoor.RearDoor": "Tuer",
  "Entities.gmod_subway_81-720.Buttons.BackDown.Pant1Toggle": "Schalte erste Stromabnehmergruppe aus",
  "Entities.gmod_subway_81-720.Buttons.BackDown.Pant2Toggle": "Schalte zweite Stromabnehmergruppe aus",
  "Entities.gmod_subway_81-720.Buttons.BackDown.Vent1Toggle": "Erste Ventilator gruppe",
  "Entities.gmod_subway_81-720.Buttons.BackDown.Vent2Toggle": "Zweite Ventilator gruppe",
  "Entities.gmod_subway_81-720.Buttons.BackDown.VentToggle": "",
  "Entities.gmod_subway_81-720.Buttons.BackDown.PassLightToggle": "Wagonbeleuchtung",
  "Entities.gmod_subway_81-720.Buttons.BackDown.CabLightToggle": "Fuehrerstandsbeleuchtung",
  "Entities.gmod_subway_81-720.Buttons.BackDown.Headlights1Toggle": "Erste Scheinwerfergruppe",
  "Entities.gmod_subway_81-720.Buttons.BackDown.Headlights2Toggle": "Zweite Scheinwerfergruppe",
  "Entities.gmod_subway_81-720.Buttons.BackDown.ParkingBrakeToggle": "Parkbremse",
  "Entities.gmod_subway_81-720.Buttons.BackDown.TorecDoorsToggle": "Front Tuer",
  "Entities.gmod_subway_81-720.Buttons.BackDown.BBERToggle": "Schalte Notfal BBE ein",
  "Entities.gmod_subway_81-720.Buttons.BackDown.BBEToggle": "BBE",
  "Entities.gmod_subway_81-720.Buttons.BackDown.CompressorToggle": "Kompressor",
  "Entities.gmod_subway_81-720.Buttons.BackDown.CabLightStrengthToggle": "Fuehrerstandsbeleuchtungs Spannung",
  "Entities.gmod_subway_81-720.Buttons.BackDown.AppLights1Toggle": "Wagen beleuchtung",
  "Entities.gmod_subway_81-720.Buttons.BackDown.AppLights2Toggle": "",
  "Entities.gmod_subway_81-720.Buttons.BackDown.BARSBlock-": "Defektes BARS (ARS) blocke: -",
  "Entities.gmod_subway_81-720.Buttons.BackDown.BARSBlock+": "Defektes BARS (ARS) blocke: +",
  "Entities.gmod_subway_81-720.Buttons.BackDown.BatteryToggle": "Batterie an/aus",
  "Entities.gmod_subway_81-720.Buttons.BackDown.ALSFreqToggle": "ALS decodierer",
  "Entities.gmod_subway_81-720.Buttons.VoltHelper1.!Battery": "Schalkreis Spannung",
  "Entities.gmod_subway_81-720.Buttons.PassengerDoor.PassengerDoor": "Wagenbeleuchtung",
  "Entities.gmod_subway_81-720.Buttons.CabinDoorR.CabinDoorRight": "Fuehrerstandstuer",
  "Entities.gmod_subway_81-720.Buttons.CabinDoorL.CabinDoorLeft": "Fuehrerstandstuer",
  "Entities.gmod_subway_81-720.Buttons.FrontPneumatic.FrontBrakeLineIsolationToggle": "Bremsdruckventil",
  "Entities.gmod_subway_81-720.Buttons.FrontPneumatic.FrontTrainLineIsolationToggle": "Zugdruckventil",
  "Entities.gmod_subway_81-720.Buttons.PUL.DoorSelectLToggle": "Waehle aus linke Tueren",
  "Entities.gmod_subway_81-720.Buttons.PUL.DoorSelectRToggle": "Waehle aus rechte Tueren",
  "Entities.gmod_subway_81-720.Buttons.PUL.DoorBlockToggle": "Tuerkontrolle",
  "Entities.gmod_subway_81-720.Buttons.PUL.!DoorLeftLamp": "Linker Tueren Check",
  "Entities.gmod_subway_81-720.Buttons.PUL.DoorLeftSet": "Tueren Links",
  "Entities.gmod_subway_81-720.Buttons.PUU.!DoorsClosed": "Tueren geschlossen",
  "Entities.gmod_subway_81-720.Buttons.PUU.StandToggle": "Bleib",
  "Entities.gmod_subway_81-720.Buttons.PUU.TickerToggle": "Ticker",
  "Entities.gmod_subway_81-720.Buttons.PUU.KAHToggle": "KAH",
  "Entities.gmod_subway_81-720.Buttons.PUU.ALSToggle": "ALS",
  "Entities.gmod_subway_81-720.Buttons.PUU.FDepotToggle": "Verlassen des Depots",
  "Entities.gmod_subway_81-720.Buttons.PUU.!HVoltage": "Keine Hochspannung",
  "Entities.gmod_subway_81-720.Buttons.PUU.PassSchemeToggle": "Linienplan",
  "Entities.gmod_subway_81-720.Buttons.PUU.EmergencyCompressorSet": "Notfall Kompressor",
  "Entities.gmod_subway_81-720.Buttons.PUU.EnableBVSet": "Aktiviere Ueberladungs schutz",
  "Entities.gmod_subway_81-720.Buttons.PUU.DisableBVSet": "Deaktiviere BV",
  "Entities.gmod_subway_81-720.Buttons.PUU.RingSet": "Ring",
  "Entities.gmod_subway_81-720.Buttons.PUU.R_Program2Set": "Programm 2",
  "Entities.gmod_subway_81-720.Buttons.PUU.R_AnnouncerToggle": "Fahrgast Informations System",
  "Entities.gmod_subway_81-720.Buttons.PUU.R_LineToggle": "Linie",
  "Entities.gmod_subway_81-720.Buttons.PUU.R_EmerSet": "Notfall Sprechanlage",
  "Entities.gmod_subway_81-720.Buttons.PUU.R_Program1Set": "Programm 1",
  "Entities.gmod_subway_81-720.Buttons.PUU.EnableBVEmerSet": "Notfall BV neustart",
  "Entities.gmod_subway_81-720.Buttons.PUU.EmergencyControlsToggle": "Norfall Kontrolle",
  "Entities.gmod_subway_81-720.Buttons.PUU.WiperToggle": "Scheibenwischer",
  "Entities.gmod_subway_81-720.Buttons.PUU.!VDop": "Hoechsgeschwindigkeit",
  "Entities.gmod_subway_81-720.Buttons.PUU.!VFact": "Momentane Geschwindigkeit",
  "Entities.gmod_subway_81-720.Buttons.PUU.!VPred": "Vorbeugende Geschwindigkeit",
  "Entities.gmod_subway_81-720.Buttons.PUU.!VDop2": "Erlaubte Geschwindigkeit",
  "Entities.gmod_subway_81-720.Buttons.PUU.!Acc": "Beschleunigung",
  "Entities.gmod_subway_81-720.Buttons.PUU.!Forw": "Forwaerts",
  "Entities.gmod_subway_81-720.Buttons.PUU.!Back": "Rueckwaerts",
  "Entities.gmod_subway_81-720.Buttons.PUR.AccelRateToggle": "Beschleunigungsrate",
  "Entities.gmod_subway_81-720.Buttons.PUR.EmerBrakeAddSet": "Hilfs-Bremse",
  "Entities.gmod_subway_81-720.Buttons.PUR.EmerBrakeReleaseSet": "Hilfs-Loesen",
  "Entities.gmod_subway_81-720.Buttons.PUR.EmerBrakeToggle": "Hilfs-Bremse",
  "Entities.gmod_subway_81-720.Buttons.PUR.EmergencyBrakeToggle": "Notbremse",
  "Entities.gmod_subway_81-720.Buttons.PUR.DoorCloseToggle": "Schliesse Tueren",
  "Entities.gmod_subway_81-720.Buttons.PUR.AttentionMessageSet": "Nachrichtenwahrnehmung",
  "Entities.gmod_subway_81-720.Buttons.PUR.AttentionSet": "Achtung",
  "Entities.gmod_subway_81-720.Buttons.PUR.AttentionBrakeSet": "Bremswahrnehmung",
  "Entities.gmod_subway_81-720.Buttons.PUR.HornBSet": "Hupe",
  "Entities.gmod_subway_81-720.Buttons.PUR.DoorRightSet": "Tueren Rechts",
  "Entities.gmod_subway_81-720.Buttons.PUR.!DoorRightLamp": "Rechter Tueren Check",
  "Entities.gmod_subway_81-720.Buttons.PneumoHelper2.!BrakeTrainLine": "Rot: Bremskreislauf, Schwarz: Zugkreislauf",

  "Entities.gmod_subway_81-721.Buttons.GV.GVToggle": "Hauptschalter",
  "Entities.gmod_subway_81-721.Buttons.RearPneumatic.RearBrakeLineIsolationToggle": "Bremsdruckventil",
  "Entities.gmod_subway_81-721.Buttons.RearPneumatic.RearTrainLineIsolationToggle": "Zugdruckventil",
  "Entities.gmod_subway_81-721.Buttons.FrontDoor.FrontDoor": "Front Tuer",
  "Entities.gmod_subway_81-721.Buttons.RearDoor.RearDoor": "Rueck Tuer",
  "Entities.gmod_subway_81-721.Buttons.Battery.BatteryToggle": "Batterie an/aus",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV1Toggle": "SF1: Kontrollspannung",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV2Toggle": "SF2: BUV BUV Spannung (Zugmitte)",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV3Toggle": "SF3: BUTP Spannung (Zugfront)",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV4Toggle": "SF4: BUTP Kontrolle",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV5Toggle": "SF5: BUTP Notfall Kontrolle",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV6Toggle": "SF6: BUTP Spannung",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV7Toggle": "SF7: BBE (Zugeigenes Netzeil)",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV8Toggle": "SF8: BV Kontrolle",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV9Toggle": "SF9: BV Spannung (Wagen relay)",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV10Toggle": "SF10: PPO",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV11Toggle": "SF11: Kompressor",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV12Toggle": "SF12: Tueren Schliessen",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV13Toggle": "SF13: Oeffne Tueren Links",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV14Toggle": "SF14: Oeffne Tueren Rechts",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV15Toggle": "SF15: Front Tuer",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV16Toggle": "SF16: Fahrgast Informations System",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV17Toggle": "SF17: Notfall Sprechanlage",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV18Toggle": "SF18: (Platzhalter)",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV19Toggle": "SF19: Wagonbeleuchtungsspannung",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV20Toggle": "SF20: Notfallwagonbeleuchtung",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV21Toggle": "SF21: Geschwindigkeitssensor",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV22Toggle": "SF22: Parkbremse",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV23Toggle": "SF23: Erste Ventilatorgruppe Kontrolle",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV24Toggle": "SF24: Zweite Ventilatorgruppe Kontrolle",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV25Toggle": "SF25: Schalte erste Ventilatorgruppe ein",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV26Toggle": "SF26: Schalte zweite Ventilatorgruppe ein",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV27Toggle": "SF27: Pre-Bremseinstellung",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV28Toggle": "SF28: ZKK Spannung",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV29Toggle": "SF29: Stromabnehmer",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV30Toggle": "SF30: Linienplan",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV31Toggle": "SF31: (Platzhalter)",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV32Toggle": "SF32: (Platzhalter)",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV33Toggle": "SF33: (Platzhalter)",
  "Entities.gmod_subway_81-721.Buttons.FrontPneumatic.FrontBrakeLineIsolationToggle": "Bremsdruckventil",
  "Entities.gmod_subway_81-721.Buttons.FrontPneumatic.FrontTrainLineIsolationToggle": "Zugdruckventil"
}
]]