return [[
{
  "Lang": "FIN",
  "Name": "FINLAND",

  "Entities.gmod_subway_81-717_mvm.Buttons.HelperPanel.VUD2Toggle": "VUD2: Door ohjaus toggle (close doors)",
  "Entities.gmod_subway_81-717_mvm.Buttons.HelperPanel.VDLSet": "VDL: Vasemmanpuoleiset ovet auki",
  "Entities.gmod_subway_81-717_mvm.Buttons.HelperPanel.R_Program2Helper": "Ohjelma 2",
  "Entities.gmod_subway_81-717_mvm.Buttons.HelperPanel.R_Program1Helper": "Ohjelma 1",
  "Entities.gmod_subway_81-717_mvm.Buttons.Battery_2.1:RC1Toggle": "RC-1: ARS-piirit pois",
  "Entities.gmod_subway_81-717_mvm.Buttons.Battery_2.1:VBToggle": "VB: Akusto päälle/pois",
  "Entities.gmod_subway_81-717_mvm.Buttons.Battery_2.1:UOSToggle": "RC-UOS: Nopeudenrajoituslaite",
  "Entities.gmod_subway_81-717_mvm.Buttons.Wiper.WiperToggle": "Pyyhkijä",
  "Entities.gmod_subway_81-717_mvm.Buttons.DriverValveDisconnect.DriverValveDisconnectToggle": "Ohjausventtiilin irroitus",
  "Entities.gmod_subway_81-717_mvm.Buttons.DriverValveDisconnect.DriverValveBLDisconnectToggle": "Jarrujohdon irroitus",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.R_UNchToggle": "UNCh: Matala taajuusvahvistin",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.R_ZSToggle": "ZS: Äänet vaunussa päälle",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.R_GToggle": "Loudspeaker: Äänet ohjaamossa päälle",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.R_RadioToggle": "Radioinffo: Ilmoitukset(sisäänrakennettu)",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.R_Program1Set": "Ohjelma 1",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.R_Program2Set": "Ohjelma 2",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.2:KVTSet": "KB: Huomio nappi",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.VZ1Set": "VZ1: Paineilman venttiili #1",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.VUD1Toggle": "VUD: Ovilukon asento (sulje ovet)",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.KDLSet": "KDL: Vasemmanpuoleiset ovet auki",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.KDLKToggle": "KDL nappulan kansi",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.KDLRSet": "KDL: Vasemmanpuoleiset ovet auki",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.KDLRKToggle": "KDL nappulan kansi",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.DoorSelectToggle": "Ovien puoli",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.KRZDSet": "RZD: ",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.R_VPRToggle": "VPR: Radioasemat päälle",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.VozvratRPSet": "Ylikuormituksen resetoinnin rele",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.GreenRPLight": "RP: Viherä ylikuormituksen valo (estää moottoreiden \"ylivirtauksen\")",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.AVULight": "AVU: Automaattisen ohjauksen sammutus aktiivinen",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.LKVPLight": "LKVP: Suurjännitemuuntimen ohjaus",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.SPLight": "LSP: Palohälytys (reostaatti ylikuumenee)",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.ConverterProtectionSet": "Muuntimen suojaus",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.KSNSet": "KSN:  Failure indication button",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.DIPoffSet": "Hälytys äänimerkki",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.ARSToggle": "ARS:  Automaattinen nopeudenvalvonta",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.ALSToggle": "ALS: Kulunvalvonta",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.OtklAVUToggle": "Sammuta automaattisen ohjausyksikön rele (vikatila AVU)",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.TormATToggle": "(placeholder) Hätäjarrun kytkin",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.L_1Toggle": "Matkustamon valot",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.L_2Toggle": "Ohjaamo valo",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.L_3Toggle": "Paneeli valot",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.ALSFreqToggle": "Decoder: ALS taajuuskytkin 1/5 tai 2/6",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.ParkingBrakeSignToggle": "Sign \"VAPAUTA KÄSIJARRU\"",
  "Entities.gmod_subway_81-717_mvm.Buttons.ParkingBrake.ParkingBrakeToggle": "Käsijarru",
  "Entities.gmod_subway_81-717_mvm.Buttons.ParkingBrake.DriverValveTLDisconnectToggle": "Junaohausventtiili",
  "Entities.gmod_subway_81-717_mvm.Buttons.IGLAButtons.IGLA1Set": "IGLA: Ensimmäinen nappi",
  "Entities.gmod_subway_81-717_mvm.Buttons.IGLAButtons.IGLA2Set": "IGLA: Toinen nappi",
  "Entities.gmod_subway_81-717_mvm.Buttons.IGLAButtons.IGLA3Set": "IGLA: Kolmas nappi",
  "Entities.gmod_subway_81-717_mvm.Buttons.IGLAButtons.IGLA4Set": "IGLA: Neljäs nappi",
  "Entities.gmod_subway_81-717_mvm.Buttons.BPSNFront.!Voltage": "Hallitse ohjauspiirin jännitteitä",
  "Entities.gmod_subway_81-717_mvm.Buttons.BPSNFront.VMKToggle": "Moottori kompressori päälle",
  "Entities.gmod_subway_81-717_mvm.Buttons.BPSNFront.BPSNonToggle": "BPSN: Train power supply",
  "Entities.gmod_subway_81-717_mvm.Buttons.BPSNFront.RezMKSet": "Moottorikompressorin hätä käynnistys",
  "Entities.gmod_subway_81-717_mvm.Buttons.BPSNFront.ARS13Set": "ARS 13V: ARS stabiloitu jännite tarkastus",
  "Entities.gmod_subway_81-717_mvm.Buttons.Schedule.!RouteNum": "М №\nReitti numero",
  "Entities.gmod_subway_81-717_mvm.Buttons.Schedule.!PathNum": "П №\nn numero",
  "Entities.gmod_subway_81-717_mvm.Buttons.Schedule.!SchTime": "ВРЕМЯ ХОДА\nAikataulun totaalinen aika(?)",
  "Entities.gmod_subway_81-717_mvm.Buttons.Schedule.!SchInterval": "ИНТ\nJunien aikaväli",
  "Entities.gmod_subway_81-717_mvm.Buttons.Schedule.!SchHour": "ЧАС\nTunnit",
  "Entities.gmod_subway_81-717_mvm.Buttons.Schedule.!SchMin": "МИН\nMinuutit",
  "Entities.gmod_subway_81-717_mvm.Buttons.Schedule.!SchSec": "СЕК\nSekunnit",
  "Entities.gmod_subway_81-717_mvm.Buttons.Schedule.!SchArrival": "Saapumis ajat",
  "Entities.gmod_subway_81-717_mvm.Buttons.Schedule.!SchStations": "Aseman nimi",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!Speedometer": "Nopeusmittari",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!LampLSN": "LSN: Vian merkkiovalo (tehopiirit eivät onnistuneet kokoontumaan)",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!LampRP": "RP: Punainen ylikuormituksen valo (tehopiirit eivät onnistuneet kasaantumaan)",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!LampLHRK": "LhRK: Reostaattisäätimen liikevalo",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!LampLKT": "LKT: ARS jarrutuksen merkkivalo",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!LampLKVD": "LKVD: ARS moottorin sammutusilmaisin",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!LampLKVC": "LKVC: Korkeajännite ei ole saatavilla",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!ARSOch": "OCh: Ei ARS taajuutta",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!ARS0": "0: ARS pysähtymis singaali",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!ARS40": "Nopeusrajoitus 40 kph",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!ARS60": "Nopeusrajoitus 60 kph",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!ARS70": "Nopeusrajoitus 70 kph",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!ARS80": "Nopeusrajoitus 80 kph",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!LampLSD1": "LSD: Ovi valot (ovet ovat kiinni)",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!LampLSD2": "LSD: Ovi valot  (ovet ovat kiinni)",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!LampLST": "LST: Jarrut kiinni",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!LampLVD": "LVD: Moottorit päällä",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!LampLN": "LN: Suuntaussingaali",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!LampLRS": "LRS: Nopeuden \"tasa-arvo\" (sueraavan segmentin nopeusrajoitus on yhtä suuri tai suurempi kuin nykyinen)",
  "Entities.gmod_subway_81-717_mvm.Buttons.PneumaticPanels.!CylinderPressure": "Jarrusylintereiden paine",
  "Entities.gmod_subway_81-717_mvm.Buttons.PneumaticPanels.!LinePressure": "Paine penumaattisissa linjoissa (punainen: \"jarruviiva\", musta: junan)",
  "Entities.gmod_subway_81-717_mvm.Buttons.Battery.RC1Toggle": "RC-1: ARS piirien irroitus",
  "Entities.gmod_subway_81-717_mvm.Buttons.Battery.UOSToggle": "RC-UOS: Nopeudenrajouituslaite",
  "Entities.gmod_subway_81-717_mvm.Buttons.Battery.VBToggle": "VB: Akusto päälle/pois",
  "Entities.gmod_subway_81-717_mvm.Buttons.FrontPneumatic.FrontBrakeLineIsolationToggle": "jarrujohdon eristysventtiili",
  "Entities.gmod_subway_81-717_mvm.Buttons.FrontPneumatic.FrontTrainLineIsolationToggle": "Junajohdon eristysventtiili",
  "Entities.gmod_subway_81-717_mvm.Buttons.ASNP.R_ASNPMenuSet": "ASNP: Valikko",
  "Entities.gmod_subway_81-717_mvm.Buttons.ASNP.R_ASNPUpSet": "ASNP: Ylös",
  "Entities.gmod_subway_81-717_mvm.Buttons.ASNP.R_ASNPDownSet": "ASNP: Alas",
  "Entities.gmod_subway_81-717_mvm.Buttons.ASNP.R_ASNPOnToggle": "ASNP: Päälle",
  "Entities.gmod_subway_81-717_mvm.Buttons.RearDoor.RearDoor": "Taka-ovi",
  "Entities.gmod_subway_81-717_mvm.Buttons.Meters.!TotalVoltmeter": "HV volttimittari (kV)",
  "Entities.gmod_subway_81-717_mvm.Buttons.Meters.!TotalAmpermeter": "Totaalinen ampeerimittari(A)",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A61Toggle": "A61 Juna johto 6 ohjaus",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A55Toggle": "A55 Juna johto 10AS Ohjaus",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A54Toggle": "A54 Juna johto 10AK ohjaus",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A56Toggle": "A56 Kytke virta akkuvirtapiiriin",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A27Toggle": "A27 Käynnistä DIP ja valaistus",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A21Toggle": "A21 Ovien hallinta",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A10Toggle": "A10 Moottorikompressorin ohjaus",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A53Toggle": "A53 KVC virtalähde",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A43Toggle": "A43 ARS 12V virtalähde",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A45Toggle": "A45 ARS junajohto 10AU",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A42Toggle": "A42 ARS 75V jännitelähde",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A41Toggle": "A41 ARS jarrutus",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.VUToggle": "VU  Junan ohjaus",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A64Toggle": "A64 Ohjaamo valo",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A63Toggle": "A63 IGLA/BIS",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A50Toggle": "A50 Käynnistä DIP ja valaistus",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A51Toggle": "A51 Sammuta DIP and valaistus",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A23Toggle": "A23 Moottorikompressorin hätäkäynnistys",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A14Toggle": "A14 Juna johto  18",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A75Toggle": "A75 Ohjaamon lämmitys",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A1Toggle": "A1  X-1",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A2Toggle": "A2  X-2",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A3Toggle": "A3  X-3",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A17Toggle": "A17 Ylikuormituksen resetointi",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A62Toggle": "A62 Radioviestintä",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A29Toggle": "A29 Radiolägetykset",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A5Toggle": "A5 Välivaunu",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A6Toggle": "A6  T-1",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A8Toggle": "A8  Paineilma venttiilit #1, #2",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A20Toggle": "A20 Ohjaus 20",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A25Toggle": "A25 Manuaalinen sähkojarru",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A22Toggle": "A22 Käynnistä KK",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A30Toggle": "A30 Reostaattisäätimen moottorin teho",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A39Toggle": "A39 Hätäohjaus",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A44Toggle": "A44 Junan hätäohjaus",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A80Toggle": "A80 Virtakytkin kytketty moottorin tehoon",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A65Toggle": "A65 Matkustamon valot",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.L_5Toggle": "А49 Hätä valaistus",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A24Toggle": "A24 Akun lataus",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A32Toggle": "A32 Open right doors",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A31Toggle": "A31 Open left doors",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A16Toggle": "A16 Ovet kiinni",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A13Toggle": "A13 Ovi hälytys",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A12Toggle": "A12 Ovien hätäsulku",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A7Toggle": "A7  Punainen valo",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A9Toggle": "A9  Punainen valo",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A46Toggle": "A46 Valkoinen valo",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A47Toggle": "A47 Valkoinen valo",
  "Entities.gmod_subway_81-717_mvm.Buttons.PassengerDoor.PassengerDoor": "Matkustamon ovi",
  "Entities.gmod_subway_81-717_mvm.Buttons.GV.GVToggle": "HV kytkin",
  "Entities.gmod_subway_81-717_mvm.Buttons.Stopkran.EmergencyBrakeValveToggle": "Hätäjarru",
  "Entities.gmod_subway_81-717_mvm.Buttons.InfoTableSelect.PrevSign": "Edellinen kilpi",
  "Entities.gmod_subway_81-717_mvm.Buttons.InfoTableSelect.NextSign": "Seuraava kilpi",
  "Entities.gmod_subway_81-717_mvm.Buttons.InfoTableSelect.Num2P":  "linja : Lisää 2. numeroa",
  "Entities.gmod_subway_81-717_mvm.Buttons.InfoTableSelect.Num2M": "Linja: Vähennä 2. numeroa",
  "Entities.gmod_subway_81-717_mvm.Buttons.InfoTableSelect.Num1P": "Linja: Lisää 1. numeroa",
  "Entities.gmod_subway_81-717_mvm.Buttons.InfoTableSelect.Num1M": "Linja: Vähennä 1. numeroa",
  "Entities.gmod_subway_81-717_mvm.Buttons.Front.L_4Toggle": "Ajovalojen kytkin",
  "Entities.gmod_subway_81-717_mvm.Buttons.Front.VUSToggle": "VUS: Ajovalot pitkät/lyhyet",
  "Entities.gmod_subway_81-717_mvm.Buttons.Front.VAHToggle": "VAH: Hätä ajo modi (vika RPB releessä)",
  "Entities.gmod_subway_81-717_mvm.Buttons.Front.VADToggle": "VAD: Hätäoven sulkian ylikuormittuminen (vikaf KD releessä)",
  "Entities.gmod_subway_81-717_mvm.Buttons.Front.KRPSet": "KRP: Hätäkäynnistys nappi",
  "Entities.gmod_subway_81-717_mvm.Buttons.Front.KAHSet": "Hätä ajo nappi",
  "Entities.gmod_subway_81-717_mvm.Buttons.Front.KAHKToggle": "KAH nappulan suoja",
  "Entities.gmod_subway_81-717_mvm.Buttons.Front.KUP": "Ohjaamolämmitys aktiivinen",
  "Entities.gmod_subway_81-717_mvm.Buttons.Front.KDPSet": "KDP: Oikeanopuoleiset ovet auki",
  "Entities.gmod_subway_81-717_mvm.Buttons.Front.KDPKToggle": "KDP nappulan suoja",
  "Entities.gmod_subway_81-717_mvm.Buttons.Front.PN": "Ilmajarrun ohjaus",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A61Toggle": "A61 Juna johdon 6 ohjus",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A55Toggle": "A55 Juna johdon 10AS ohjaus",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A54Toggle": "A54 Juna johdon 10AK ohjaus",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A56Toggle": "A56 Käynnistä akustonvirta ohjauspiireihin",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A27Toggle": "A27 Käynnistä DIP ja valaistus",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A21Toggle": "A21 Ovien ohjaus",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A10Toggle": "A10 Moottorikompressorin  ohjaus",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A53Toggle": "A53 KVC virta",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A43Toggle": "A43 ARS 12V virta",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A45Toggle": "A45 ARS junajohto 10AU",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A42Toggle": "A42 ARS 75V virta",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A41Toggle": "A41 ARS jarrutus",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:VUToggle": "VU  Junan ohjaus",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A64Toggle": "A64 Ohjaamo valaistus",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A63Toggle": "A63 IGLA/BIS",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A50Toggle": "A50 Käynnistä DIP ja valaistus",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A51Toggle": "A51 Sammuta DIP ja valaistus",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A23Toggle": "A23 Hätämoottorikompressori päälle",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A14Toggle": "A14  Junajohto 18",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A75Toggle": "A75 Ohjaamon lämmitys",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A1Toggle": "A1  X-1",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A2Toggle": "A2  X-2",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A3Toggle": "A3  X-3",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A17Toggle": "A17 Ylikuormituksen resetointi",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A62Toggle": "A62 Radioviestintä",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A29Toggle": "A29 Radiolägetykset",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A5Toggle": "A5 Välivaunu",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A6Toggle": "A6  T-1",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A8Toggle": "A8  Paineilma venttiilit #1, #2",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A20Toggle": "A20 Ajo/jarru ohjaus, juna johto 20",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A25Toggle": "A25 Manuaalinen sähköjarru",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A22Toggle": "A22 Käynnistä KK",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A30Toggle": "A30 Reostaattisen moottorin teho",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A39Toggle": "A39 Hätäohjaus",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A44Toggle": "A44 Junan hätäohjaus",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A80Toggle": "A80 Virroitin kytkeytyy moottoriin tehoon",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A65Toggle": "A65 Matkustamon valaistus",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:L_5Toggle": "А49 Hätä valaistus",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A24Toggle": "A24 Akuston lataus",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A32Toggle": "A32 Avaa oikeanpuoleiset ovet",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A31Toggle": "A31 Avaa vasemmanpuoleiset ovet",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A16Toggle": "A16 Sulje ovet",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A13Toggle": "A13 Ovi hälytys",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A12Toggle": "A12 Ovien hätäsulkeutuminen",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A7Toggle": "A7  Punainen valo",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A9Toggle": "A9  Punainen valo",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A46Toggle": "A46 Valkoinen lamppu",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A47Toggle": "A47 Valkoinen lamppu",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!Speedometer": "Nopeusmittari",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!LSD": "LSD: Ovien tila valo (ovet ovat kiinni)",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!LOCh": "NCh: Ei ARS taajuutta",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!L0": "0: ARS pysähtymis singaali",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!LRS": "LRS: Nopeuden tasa-arvo (seuraavan singaalin nopeusrajoitus on yhtä suuri tai suurempi kuin nykyinen)",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!L40": "Rajoitus 40 kph",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!L60": "Rajoitus 60 kph",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!L80": "Rajoitus 80 kph",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!L70": "Rajoitus 60 kph",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!LRK": "RK: Reostaattiohauksen valo",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!LEKK": "",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!LPU": "",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!LKVD": "LKVD: ARS Moottorin sammutusilmaisin",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!LKT": "LKT: ARS Jarrutusilmaisin",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!LRP": "RP: Punainen ylikuormituksen valo (tehopiirit eivät onnistuneet kasaantumaan)",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!LKVC": "LKVC: Korkeajännite ei ole saatavilla",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!LVD": "LVD: Moottorit ovat \"mukana\"",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!LST": "LST: Jarrut kiinni",
  "Entities.gmod_subway_81-717_mvm.Buttons.CabinDoor.CabinDoor": "Ohjaamo ovi",
  "Entities.gmod_subway_81-717_mvm.Buttons.Reverser.KVReverserDown": "Suunta taakse",
  "Entities.gmod_subway_81-717_mvm.Buttons.Reverser.KVReverserUp": "Suunta eteen",
  "Entities.gmod_subway_81-717_mvm.Buttons.PassengerDoor1.PassengerDoor": "Matkustamon ovi",
  "Entities.gmod_subway_81-717_mvm.Buttons.UAVAPanel.UAVAToggle": "UAVA: Automaattinen pysähdys pois päältä",
  "Entities.gmod_subway_81-717_mvm.Buttons.UAVAPanel.UAVAContactSet": "UAVA: Automaattisen pysähdyksen resetointi)",
  "Entities.gmod_subway_81-717_mvm.Buttons.EPKDisconnect.EPKToggle": "EPV Irroita venttiili",
  "Entities.gmod_subway_81-717_mvm.Buttons.Help.ShowHelp": "Junan ohjekirja",
  "Entities.gmod_subway_81-717_mvm.Buttons.ParkingBrake2.1:ParkingBrakeToggle": "Käsijarru",
  "Entities.gmod_subway_81-717_mvm.Buttons.RearPneumatic.RearBrakeLineIsolationToggle": " Jarruventtiilin vipu",
  "Entities.gmod_subway_81-717_mvm.Buttons.RearPneumatic.RearTrainLineIsolationToggle": " Junaventtiilin vipu",
  "Entities.gmod_subway_81-717_mvm.Buttons.AirDistributor.AirDistributorDisconnectToggle": "Poista ilmansyöttö",

  "Entities.gmod_subway_81-714_mvm.Buttons.GV.GVToggle": "HV kytkin",
  "Entities.gmod_subway_81-714_mvm.Buttons.RearPneumatic.RearBrakeLineIsolationToggle": "Jarrun eristysventtiili",
  "Entities.gmod_subway_81-714_mvm.Buttons.RearPneumatic.RearTrainLineIsolationToggle": "Junajarrun eristysventtiili",
  "Entities.gmod_subway_81-714_mvm.Buttons.RearDoor.RearDoor": "Rear door",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Left.DriverValveBLDisconnectToggle": "Jarrun eristysventtiili",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Left.DriverValveTLDisconnectToggle": "Junajarrun ohjausventtiili",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Left.A65Toggle": "A65 Matkustamon valot",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Left.A56Toggle": "A56 Kytke akusto päälle ohjaamaan piirejä",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Left.A63Toggle": "A63 IGLA/BIS",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Left.A10Toggle": "A10 Moottorikompressorin ohjaus",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Left.A30Toggle": "A30 Reostaattisen moottorin teho",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Left.A80Toggle": "A80 Virroittimen tila kytkeytyy moottorin tehoon",
  "Entities.gmod_subway_81-714_mvm.Buttons.FrontPneumatic.FrontBrakeLineIsolationToggle": "Jarrun eristysventtiili",
  "Entities.gmod_subway_81-714_mvm.Buttons.FrontPneumatic.FrontTrainLineIsolationToggle": "Junajarrun eristysventtiili",
  "Entities.gmod_subway_81-714_mvm.Buttons.FrontPneumatic.ParkingBrakeToggle": "Käsijarru",
  "Entities.gmod_subway_81-714_mvm.Buttons.AirDistributor.AirDistributorDisconnectToggle": "Disabloi ilmansyöttö",
  "Entities.gmod_subway_81-714_mvm.Buttons.FrontDoor.FrontDoor": "Etuovi",
  "Entities.gmod_subway_81-714_mvm.Buttons.Battery.VBToggle": "VB: Akusto päälle/pois",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A54Toggle": "A54 junajohdon 10AK ohjaus",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A27Toggle": "A27 Käynnistä DIP ja valaistus",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A24Toggle": "A24 Akuston lataus",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A53Toggle": "A53 KVC power supply",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A13Toggle": "A13 Ovi hälytys",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A32Toggle": "A32 Oikeanopuoleiset ovet",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A31Toggle": "A31 Vasemmanpuoleiset ovet",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A16Toggle": "A16 Ovet kiinni",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A12Toggle": "A12 Ovet kiinni hätäkatkaisia",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A50Toggle": "A50 Käynnistä DIP ja valaistus",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A51Toggle": "A51 Sammuta DIP ja valaistus",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A1Toggle": "A1  X-1",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.KRPSet": "START: Hätä käynnistyksen nappi",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.VozvratRPSet": " Ylikuormituksen resetointi",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.RezMKSet": "Moottorikompressorin hätäkäynnistys",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.VMKToggle": "Moottorikompressori päälle ",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.BPSNonToggle": "BPSN: Junan virtalähde",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A2Toggle": "A2  X-2",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A3Toggle": "A3  X-3",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A17Toggle": "A17 Ylikuormituksen resetointi",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A5Toggle": "A5  ",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A6Toggle": "A6  T-1",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A8Toggle": "A8  Paineilman venttiilit #1, #2",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A20Toggle": "A20 Veto/jarru piiri ohjaus, juna johto 20",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A25Toggle": "A25 Manuaalinen sähkojarru",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A22Toggle": "A22 Käynnistä KK",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A23Toggle": "A23 Käynnistä hätämoottorikompressori",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A39Toggle": "A39 Hätäohjaus",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A14Toggle": "A14 Juna johto 18"
}
]]
