return [[
{
  "Lang": "fin",
  "Name": "Suomi",


  "Entities.gmod_subway_ezh3.Buttons.Stopkran.EmergencyBrakeValveToggle": "Hätäjarru",
  "Entities.gmod_subway_ezh3.Buttons.Back.BackDoor": "Taka-ovi",
  "Entities.gmod_subway_ezh3.Buttons.DriverValveBLTLDisconnect.DriverValveBLDisconnectToggle": "Jarrujohdon irroitusventtiili",
  "Entities.gmod_subway_ezh3.Buttons.DriverValveBLTLDisconnect.DriverValveTLDisconnectToggle": "Junajohdon irroitusventtiili",
  "Entities.gmod_subway_ezh3.Buttons.Battery.VBToggle": "VB: Akusto päälle/pois (matala voltti)",
  "Entities.gmod_subway_ezh3.Buttons.FrontPneumatic.FrontBrakeLineIsolationToggle": "Jarrujohdon irroitusventtiili",
  "Entities.gmod_subway_ezh3.Buttons.FrontPneumatic.FrontTrainLineIsolationToggle": "Junajarrun irroitusventtiili",
  "Entities.gmod_subway_ezh3.Buttons.ASNP.R_ASNPMenuSet": "Kuuluttaja: Menu",
  "Entities.gmod_subway_ezh3.Buttons.ASNP.R_ASNPUpSet": "Kuuluttaja: Ylös",
  "Entities.gmod_subway_ezh3.Buttons.ASNP.R_ASNPDownSet": "Kuuluttaja: Alas",
  "Entities.gmod_subway_ezh3.Buttons.ASNP.R_ASNPOnToggle": "Kuuluttaja: Käynnistä",
  "Entities.gmod_subway_ezh3.Buttons.PassengerDoor1.PassengerDoor": "Matkustamon ovi",
  "Entities.gmod_subway_ezh3.Buttons.PassengerDoor.PassengerDoor": "Matkustamon ovi",
  "Entities.gmod_subway_ezh3.Buttons.CabinDoor.CabinDoor": "Ohjaamon ovi",
  "Entities.gmod_subway_ezh3.Buttons.Front.FrontDoor": "Etu ovi",
  "Entities.gmod_subway_ezh3.Buttons.GV.GVToggle": "HV kytkin",
  "Entities.gmod_subway_ezh3.Buttons.RearPneumatic.RearTrainLineIsolationToggle": "Junajohdon irroitusventtiili",
  "Entities.gmod_subway_ezh3.Buttons.RearPneumatic.RearBrakeLineIsolationToggle": "Jarrujohdon irroitusventtiili",
  "Entities.gmod_subway_ezh3.Buttons.Panel.!OCH": "NCh: No ARS taajuutta",
  "Entities.gmod_subway_ezh3.Buttons.Panel.!0": "0: ARS pysähtymis singaali",
  "Entities.gmod_subway_ezh3.Buttons.Panel.!40": "Nopeusrajoitus 40 kph",
  "Entities.gmod_subway_ezh3.Buttons.Panel.!60": "Nopeusrajoitus 60 kph",
  "Entities.gmod_subway_ezh3.Buttons.Panel.!70": "Nopeusrajoitus 80 kph",
  "Entities.gmod_subway_ezh3.Buttons.Panel.!80": "Nopuesrajoitus 60 kph",
  "Entities.gmod_subway_ezh3.Buttons.Panel.!Speedometer": "Nopeusmittari (km/h)",
  "Entities.gmod_subway_ezh3.Buttons.Panel.!TotalAmpermeter": "Moottoreiden totaalinen amppeerimäärä (A)",
  "Entities.gmod_subway_ezh3.Buttons.Panel.!TotalVoltmeter": "Totaalinen volttimäärä (kV)",
  "Entities.gmod_subway_ezh3.Buttons.Panel.!BatteryVoltage": "Akuston volttimäärä junan ohjauksessa(V)",
  "Entities.gmod_subway_ezh3.Buttons.Panel.!BrakeCylinder": "Jarrusylintereiden paine",
  "Entities.gmod_subway_ezh3.Buttons.Panel.!LinesPressure": "Paine paineilmajohdoissa (punainen: jarrujohto, musta: junajohto)",
  "Entities.gmod_subway_ezh3.Buttons.Main.KU1Toggle": "Käynnistä moottorikompressori",
  "Entities.gmod_subway_ezh3.Buttons.Main.SAMM1Set": "SAMM: Sammuta ajomodi",
  "Entities.gmod_subway_ezh3.Buttons.Main.SAMM2Set": "SAMM: Käynnistys",
  "Entities.gmod_subway_ezh3.Buttons.Main.SAMM3Set": "SAMM: Resetointi",
  "Entities.gmod_subway_ezh3.Buttons.Main.SAMMSignal1": "Lamppu: Veto-Jarrutus",
  "Entities.gmod_subway_ezh3.Buttons.Main.SAMMSignal2": "Lamppu: Työ status SAMM",
  "Entities.gmod_subway_ezh3.Buttons.Main.SAMMSignal3": "Lamppu: SAMMM toteutusyksikkö käytössä",
  "Entities.gmod_subway_ezh3.Buttons.Main.SAMMOnToggle": "SAMM: Automaattiajo päälle",
  "Entities.gmod_subway_ezh3.Buttons.Main.SAMMBlokToggle": "SAMM: Suoritusyksikkö",
  "Entities.gmod_subway_ezh3.Buttons.Main.SAMMCommand3Set": "SAMM: X-2",
  "Entities.gmod_subway_ezh3.Buttons.Main.SAMMCommand2Set": "SAMM: Saavuttaa",
  "Entities.gmod_subway_ezh3.Buttons.Main.SAMMCommand1Set": "SAMM: Lupa",
  "Entities.gmod_subway_ezh3.Buttons.Main.KSNSet": "KSN: Vian osoituspainike",
  "Entities.gmod_subway_ezh3.Buttons.Main.R_Program1Set": "Ohjelma 1",
  "Entities.gmod_subway_ezh3.Buttons.Main.R_Program2Set": "Ohjelma 2",
  "Entities.gmod_subway_ezh3.Buttons.Main.VUSToggle": "Kytkin: Lähivalot(alhaalla)/Pitkätvalot(ylhäällä)",
  "Entities.gmod_subway_ezh3.Buttons.Main.L_3Toggle": "Kytkin: Mittarien valaistus",
  "Entities.gmod_subway_ezh3.Buttons.Main.VAHToggle": "Kytkin: Hätäkytkin",
  "Entities.gmod_subway_ezh3.Buttons.Main.DIPonSet": "Osv. Vkl.: Valaistus päälle",
  "Entities.gmod_subway_ezh3.Buttons.Main.DIPoffSet": "Osv. Vykl.: Valaistus pois päältä",
  "Entities.gmod_subway_ezh3.Buttons.Main.KSDSet": "KSD: Ovien tarkastus",
  "Entities.gmod_subway_ezh3.Buttons.Main.KVTSet": "KVT: jarrun havainnointipainike",
  "Entities.gmod_subway_ezh3.Buttons.Main.KBSet": "KB:Huomio-painike",
  "Entities.gmod_subway_ezh3.Buttons.Main.KBLamp": "Lamppu: RK  kehruu",
  "Entities.gmod_subway_ezh3.Buttons.Main.ARSToggle": "ARS: Nopeuden kulunvalvonta",
  "Entities.gmod_subway_ezh3.Buttons.Main.R_UNchToggle": "UNCh: Alhainen taajuusvahvistin",
  "Entities.gmod_subway_ezh3.Buttons.Main.VUD1Toggle": "VUD:Ovilukko (sulje ovet)",
  "Entities.gmod_subway_ezh3.Buttons.Main.R_RadioToggle": "Radioinformator: Kuuluttaja (sisäänrakennettu)",
  "Entities.gmod_subway_ezh3.Buttons.Main.ALSToggle": "ALS: Kulunvalvonta",
  "Entities.gmod_subway_ezh3.Buttons.Main.VozvratRPSet": "KVRP: Ylikuormittuksen resetointi",
  "Entities.gmod_subway_ezh3.Buttons.Main.RingSet": "Kello",
  "Entities.gmod_subway_ezh3.Buttons.Main.L_2Toggle": "Kytkin: Ohjaamo valo",
  "Entities.gmod_subway_ezh3.Buttons.Main.KRZDSet": "KRZD: Ovien hätäsulku",
  "Entities.gmod_subway_ezh3.Buttons.Main.KDPSet": "KDP: Avaa oikeanpuoleiset ovet",
  "Entities.gmod_subway_ezh3.Buttons.Main.KDLSet": "KDL: Vasemmanpuoleiset ovet auki",
  "Entities.gmod_subway_ezh3.Buttons.Main.KAHSet": "KAH: Ajamisen hätäpainnike",
  "Entities.gmod_subway_ezh3.Buttons.Main.RezMKSet": "Moottorikompressorin hätäkäynnistys",
  "Entities.gmod_subway_ezh3.Buttons.Main.KRPSet": "KRP: Hätkäynnistyksen painike",
  "Entities.gmod_subway_ezh3.Buttons.Main.RSTToggle": "VPR: Radioaseman aktivointi",
  "Entities.gmod_subway_ezh3.Buttons.Main.R_GToggle": "Loudspeaker: Äänet ohjaamossa päälle",
  "Entities.gmod_subway_ezh3.Buttons.Main.R_ZSToggle": "ZS: Äänet vaunuissa päälle",
  "Entities.gmod_subway_ezh3.Buttons.Main.Custom2Set": "Käyttämätön kytkin",
  "Entities.gmod_subway_ezh3.Buttons.Main.Custom3Set": "Käyttämätön kytkin",
  "Entities.gmod_subway_ezh3.Buttons.Main.ASNPPlay": "Ilmoittajan työn ilmaisin",
  "Entities.gmod_subway_ezh3.Buttons.AV1.VU3Toggle": "VU3: Ohjaamon valo",
  "Entities.gmod_subway_ezh3.Buttons.AV1.VU2Toggle": "VU2: Hätävalaistus (45V)",
  "Entities.gmod_subway_ezh3.Buttons.AV1.VU1Toggle": "VU1: Ohjaamon lämmitys (3kWt)",
  "Entities.gmod_subway_ezh3.Buttons.AVMain.AV8BToggle": "AV-8B: Automaattinen kytkin(korkeajännite)",
  "Entities.gmod_subway_ezh3.Buttons.RC1.RC1Toggle": "RC-ARS: ARS-katkaisija",
  "Entities.gmod_subway_ezh3.Buttons.UAVAPanel.UAVAToggle": "UAVA: Automaattisen hätäjarrun disablointi (disablointi)",
  "Entities.gmod_subway_ezh3.Buttons.UAVAPanel.UAVAContactSet": "UAVA: Automaattisen hätäjarrun disablointi(resetointi)",
  "Entities.gmod_subway_ezh3.Buttons.VUHelper.VUToggle": "VU: Junaohjaus päälle",
  "Entities.gmod_subway_ezh3.Buttons.HelperPanel.VDLSet": "KDL: Vasemmanpuoleiset ovet auki",
  "Entities.gmod_subway_ezh3.Buttons.HelperPanel.VUD2Toggle": "VUD2: Ovilukon kytkin (ovet kiinni)",
  "Entities.gmod_subway_ezh3.Buttons.EPKDisconnect.EPKToggle": "EPK irroita venttiili",
  "Entities.gmod_subway_ezh3.Buttons.VU.VUToggle": "VU: Junaohjaus päälle",
  "Entities.gmod_subway_ezh3.Buttons.ParkingBrake.ParkingBrakeLeft": "Käsijarrun pyörä",
  "Entities.gmod_subway_ezh3.Buttons.ParkingBrake.ParkingBrakeRight": "Käsijarrun pyörä",
  "Entities.gmod_subway_ezh3.Buttons.AirDistributor.AirDistributorDisconnectToggle": "Disabloi ilmansyöttö",

  "Entities.gmod_subway_em508t.Buttons.Stopkran.EmergencyBrakeValveToggle": "Hätäjarru",
  "Entities.gmod_subway_em508t.Buttons.Battery.VBToggle": "VB: Akusto päälle/pois (matala jännite)",
  "Entities.gmod_subway_em508t.Buttons.FrontPneumatic.FrontBrakeLineIsolationToggle": "Jarrujohdon irroitusventtiili",
  "Entities.gmod_subway_em508t.Buttons.FrontPneumatic.FrontTrainLineIsolationToggle": "Junajohdon irroitusventtiili",
  "Entities.gmod_subway_em508t.Buttons.GV.GVToggle": "HV kytkin",
  "Entities.gmod_subway_em508t.Buttons.RearPneumatic.RearTrainLineIsolationToggle": "Jarrujohdon irroitusventtiili",
  "Entities.gmod_subway_em508t.Buttons.RearPneumatic.RearBrakeLineIsolationToggle": "Jarrujohdon irroitusventtiili",
  "Entities.gmod_subway_em508t.Buttons.RearDoor.RearDoor": "Matkustamon ovi",
  "Entities.gmod_subway_em508t.Buttons.Back2.!HVFuse": "HV sulakkeet estävät",
  "Entities.gmod_subway_em508t.Buttons.Back2.!Relays": "Laatikko, jossa on akuston lataus ja ovien paineanturit",
  "Entities.gmod_subway_em508t.Buttons.Back2.!Heater": "Lämmitys",
  "Entities.gmod_subway_em508t.Buttons.Front.FrontDoor": "Etu-ovi",
  "Entities.gmod_subway_em508t.Buttons.AV1.VU3Toggle": "VU3: Ohjaamon valo",
  "Entities.gmod_subway_em508t.Buttons.AV1.VU2Toggle": "VU2: Hätävalaistus (45V)",
  "Entities.gmod_subway_em508t.Buttons.AV1.VU1Toggle": "VU1: Ohjaamon lämmitys (3kWt)",
  "Entities.gmod_subway_em508t.Buttons.ParkingBrake.ParkingBrakeLeft": "Käsijarrun pyörä",
  "Entities.gmod_subway_em508t.Buttons.ParkingBrake.ParkingBrakeRight": "Käsijarrun pyörä",
  "Entities.gmod_subway_em508t.Buttons.CabinDoor.CabinDoor1": "Ohjaamon ovi",
  "Entities.gmod_subway_em508t.Buttons.PassengerDoor.PassengerDoor": "Matkustamon ovi",
  "Entities.gmod_subway_em508t.Buttons.PassengerDoor1.PassengerDoor": "Matkustamon ovi",
  "Entities.gmod_subway_em508t.Buttons.Main.!RedRP": "RP: Punainen ylikuormituksen relevalo (virtapiirit eivät onnistuneet kasaantumaan)",
  "Entities.gmod_subway_em508t.Buttons.Main.!GreenRP": "RP: Vihreä ylikuormituksen valo (estää moottoreiden ylivirtauksen)",
  "Entities.gmod_subway_em508t.Buttons.Main.!SD": "Sininen ovien tila valo (ovet ovat kiinni)",
  "Entities.gmod_subway_em508t.Buttons.Main.KDLSet": "Kytkin: Avaa vasemmanpuoleiset ovet",
  "Entities.gmod_subway_em508t.Buttons.Main.KSDSet": "Kytkin: Singaalisaatio (Ovien hallinan testaaminen)",
  "Entities.gmod_subway_em508t.Buttons.Main.VozvratRPSet": "Kytkin: Ylikuormittumisen resetointi",
  "Entities.gmod_subway_em508t.Buttons.Main.KSNSet": "Kytkin: Rikkinäisen vaunun havaitseminen",
  "Entities.gmod_subway_em508t.Buttons.Main.VUD1Toggle": "Kytkin: Ovien hallinta (sulje ovet)",
  "Entities.gmod_subway_em508t.Buttons.Main.KU1Toggle": "Kytkin: Kompressori päälle",
  "Entities.gmod_subway_em508t.Buttons.Main.DIPonSet": "KU4: Matkustamovalot päälle",
  "Entities.gmod_subway_em508t.Buttons.Main.DIPoffSet": "KU5: Matkustamovalot pois",
  "Entities.gmod_subway_em508t.Buttons.Main.RezMKSet": "Kytkin: Moottorikompressorin hätäkäynnistäminen",
  "Entities.gmod_subway_em508t.Buttons.Main.KDPSet": "KDP: Avaa oikeanpuoleiset ovet",
  "Entities.gmod_subway_em508t.Buttons.Main.KRZDSet": "KU10: Ovien hätäsulku",
  "Entities.gmod_subway_em508t.Buttons.AVMain.AV8BToggle": "AV-8B: Automaattikytkin (Korkeajännite)",
  "Entities.gmod_subway_em508t.Buttons.VU.VUToggle": "VU: Aktivoi junaohjaus",
  "Entities.gmod_subway_em508t.Buttons.VU.!Voltage": "Ohjauspiirien jännite",
  "Entities.gmod_subway_em508t.Buttons.HelperPanel.VUD2Toggle": "VUD2: Ovilukko (sulje ovet)",
  "Entities.gmod_subway_em508t.Buttons.HelperPanel.VDLSet": "VDL: Avaa vasemmanpuoleiset ovet",
  "Entities.gmod_subway_em508t.Buttons.DriverValveBLTLDisconnect.DriverValveBLDisconnectToggle": "Jarrujohdon irroitusventtiili",
  "Entities.gmod_subway_em508t.Buttons.DriverValveBLTLDisconnect.DriverValveTLDisconnectToggle": "Junajohdon irroitusventtiili",
  "Entities.gmod_subway_em508t.Buttons.AirDistributor.AirDistributorDisconnectToggle": "Disabloi ilmansyöttö"
}
]]
