return [[
{
  "Lang": "fr",
  "Name": "french",

  "Entities.gmod_subway_81-717_mvm.Buttons.HelperPanel.VUD2Toggle": "VUD2: Contrôle des portes(fermer les portes)",
  "Entities.gmod_subway_81-717_mvm.Buttons.HelperPanel.VDLSet": "VDL: Portes gauches",
  "Entities.gmod_subway_81-717_mvm.Buttons.HelperPanel.R_Program2Helper": "Programme 2",
  "Entities.gmod_subway_81-717_mvm.Buttons.HelperPanel.R_Program1Helper": "Programme 1",
  "Entities.gmod_subway_81-717_mvm.Buttons.Battery_2.1:RC1Toggle": "RC-1: ARS déconnecter les circuits ARS",
  "Entities.gmod_subway_81-717_mvm.Buttons.Battery_2.1:VBToggle": "VB: Batterie on/off",
  "Entities.gmod_subway_81-717_mvm.Buttons.Battery_2.1:UOSToggle": "RC-UOS: Limiteur de vitesse",
  "Entities.gmod_subway_81-717_mvm.Buttons.Wiper.WiperToggle": "Essuie-glace",
  "Entities.gmod_subway_81-717_mvm.Buttons.DriverValveDisconnect.DriverValveDisconnectToggle": "Valve pilote (déconnecter la valve)",
  "Entities.gmod_subway_81-717_mvm.Buttons.DriverValveDisconnect.DriverValveBLDisconnectToggle": "Déconnecter la valve de freinage",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.R_UNchToggle": "UNCh: Amplifieur de basses fréquences",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.R_ZSToggle": "ZS: Activer le son des wagons",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.R_GToggle": "Loudspeaker: Activer le son dans la cabine",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.R_RadioToggle": "Radioinformator: Annonceur (en dev)",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.R_Program1Set": "Programme 1",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.R_Program2Set": "Programme 2",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.2:KVTSet": "KB: Bouton d'attention",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.VZ1Set": "VZ1: Valve pneumatique #1",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.VUD1Toggle": "VUD: Contrôle des portes (fermer les portes)",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.KDLSet": "KDL: Ouvrir les portes gauche",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.KDLKToggle": "KDL Couvre-bouton",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.KDLRSet": "KDL: Ouvrir les portes gauche ",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.KDLRKToggle": "KDL Couvre-Bouton",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.DoorSelectToggle": "Sélectionner le côté d'ouverture des portes",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.KRZDSet": "RZD: Fermetures de portes d'urgence",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.R_VPRToggle": "VPR: Activer la radio",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.VozvratRPSet": "Remettre a zéro le relai de l'overload ",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.GreenRPLight": "RP: Lampe vertr de l'overload (évite de surcharger les moteurs",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.AVULight": "AVU: Automatic control disabler active",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.LKVPLight": "LKVP: Controle du Haut Voltage ",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.SPLight": "LSP:Prévention incendie (rhéostat en surchauffe)",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.ConverterProtectionSet": "Protection du converteur",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.KSNSet": "KSN: Bouton affichant l\"erreur",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.DIPoffSet": "Sonette",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.ARSToggle": "ARS: Régulation automatique de la vitesse",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.ALSToggle": "ALS: Signalement de la locomotive automatique",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.OtklAVUToggle": "Désactiver le contrôle automatique, désactiver les relais (erreur de l'AVU)",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.TormATToggle": "(pour rester en place) Frein d'urgence",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.L_1Toggle": "Lumière des wagons",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.L_2Toggle": "Lumières de la cabine",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.L_3Toggle": "Lumières du panneau",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.ALSFreqToggle": "Decoder: Fréquence de l'ALS 1/5 ou 2/6",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.ParkingBrakeSignToggle": "Panneau \"ENLEVER LE FREIN DE PARKING\"",
  "Entities.gmod_subway_81-717_mvm.Buttons.ParkingBrake.ParkingBrakeToggle": "Frein de parking",
  "Entities.gmod_subway_81-717_mvm.Buttons.ParkingBrake.DriverValveTLDisconnectToggle": "Déconnecter la valve(train line)",
  "Entities.gmod_subway_81-717_mvm.Buttons.IGLAButtons.IGLA1Set": "IGLA: Premier Bouton",
  "Entities.gmod_subway_81-717_mvm.Buttons.IGLAButtons.IGLA2Set": "IGLA: Deuxième Bouton",
  "Entities.gmod_subway_81-717_mvm.Buttons.IGLAButtons.IGLA3Set": "IGLA: Troisième bouton",
  "Entities.gmod_subway_81-717_mvm.Buttons.IGLAButtons.IGLA4Set": "IGLA: Quatrième bouton",
  "Entities.gmod_subway_81-717_mvm.Buttons.BPSNFront.!Voltage": "Contrôle du voltage des circuits",
  "Entities.gmod_subway_81-717_mvm.Buttons.BPSNFront.VMKToggle": "Démarrer le compresseur du moteur",
  "Entities.gmod_subway_81-717_mvm.Buttons.BPSNFront.BPSNonToggle": "BPSN: Envoyer de l'énergie vers les wagons",
  "Entities.gmod_subway_81-717_mvm.Buttons.BPSNFront.RezMKSet": "Démarrage d'urgence du compresseur du moteur",
  "Entities.gmod_subway_81-717_mvm.Buttons.BPSNFront.ARS13Set": "ARS 13V: (ARS) Vérifier la tension stable de l'ars",
  "Entities.gmod_subway_81-717_mvm.Buttons.Schedule.!RouteNum": "М №\nNuméro de route",
  "Entities.gmod_subway_81-717_mvm.Buttons.Schedule.!PathNum": "П №\n° de chemin",
  "Entities.gmod_subway_81-717_mvm.Buttons.Schedule.!SchTime": "ВРЕМЯ ХОДА\nTemps total du parcours",
  "Entities.gmod_subway_81-717_mvm.Buttons.Schedule.!SchInterval": "ИНТ\nInterale entre les trains",
  "Entities.gmod_subway_81-717_mvm.Buttons.Schedule.!SchHour": "ЧАС\nHeure",
  "Entities.gmod_subway_81-717_mvm.Buttons.Schedule.!SchMin": "МИН\nMinute",
  "Entities.gmod_subway_81-717_mvm.Buttons.Schedule.!SchSec": "СЕК\nSeconde",
  "Entities.gmod_subway_81-717_mvm.Buttons.Schedule.!SchArrival": "Temps d'arrivée",
  "Entities.gmod_subway_81-717_mvm.Buttons.Schedule.!SchStations": "Nom de la station",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!Speedometer": "Compteur de vitesse",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!LampLSN": "LSN: Lumière indiquant une erreur ( les circuits d'alimentation n'ont pas réussis a s'assembler)",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!LampRP": "RP: Lumière rouge indiquant un overload des relais ( les circuits d'alimentation n'ont pas réussis a s'assembler )",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!LampLHRK": "LhRK: Lumière de contrôle des rhéostats",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!LampLKT": "LKT: ARS Indicateur de freinage ARS",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!LampLKVD": "LKVD: Indicateur de l'état des moteurs ARS (off) ",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!LampLKVC": "LKVC: Haut voltage non disponible",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!ARSOch": "OCh: Aucune fréquence ARS",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!ARS0": "0: ARS Signe stop",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!ARS40": "Limite de vitesse 40 km/h",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!ARS60": "Limite de vitesse 60 km/h",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!ARS70": "Limite de vitesse de 70 km/h",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!ARS80": "Limite de vitesse 80 km/h",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!LampLSD1": "LSD: Lumière d'état des portes (les portes sont fermées)",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!LampLSD2": "LSD: Lumière d'état des portes (les portes sont fermées ",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!LampLST": "LST: Freins engagés",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!LampLVD": "LVD: Moteurs engagés",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!LampLN": "LN: Signal de direction",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!LampLRS": "LRS: Lumière d'égalité des vitesses (la vitesse du prochain segment est égale ou supérieure que celle de maintenant)",
  "Entities.gmod_subway_81-717_mvm.Buttons.PneumaticPanels.!CylinderPressure": "Pression du cylindre des freins",
  "Entities.gmod_subway_81-717_mvm.Buttons.PneumaticPanels.!LinePressure": "Pression des valves pneumatiques (rouge: freinage, noir: ligne du train)",
  "Entities.gmod_subway_81-717_mvm.Buttons.Battery.RC1Toggle": "RC-1: Déconnecter les circuits ARS",
  "Entities.gmod_subway_81-717_mvm.Buttons.Battery.UOSToggle": "RC-UOS: Limitations de vitesses",
  "Entities.gmod_subway_81-717_mvm.Buttons.Battery.VBToggle": "VB: Batterie on/off",
  "Entities.gmod_subway_81-717_mvm.Buttons.FrontPneumatic.FrontBrakeLineIsolationToggle": "Valve d'isolation (Brake line) ",
  "Entities.gmod_subway_81-717_mvm.Buttons.FrontPneumatic.FrontTrainLineIsolationToggle": "Valve d'isolation (Train line)",
  "Entities.gmod_subway_81-717_mvm.Buttons.ASNP.R_ASNPMenuSet": "ASNP: Menu",
  "Entities.gmod_subway_81-717_mvm.Buttons.ASNP.R_ASNPUpSet": "ASNP: haut",
  "Entities.gmod_subway_81-717_mvm.Buttons.ASNP.R_ASNPDownSet": "ASNP: bas",
  "Entities.gmod_subway_81-717_mvm.Buttons.ASNP.R_ASNPOnToggle": "ASNP: Allumer",
  "Entities.gmod_subway_81-717_mvm.Buttons.RearDoor.RearDoor": "Porte arrière",
  "Entities.gmod_subway_81-717_mvm.Buttons.Meters.!TotalVoltmeter": "Voltmètre de haut voltage (kV)",
  "Entities.gmod_subway_81-717_mvm.Buttons.Meters.!TotalAmpermeter": "Ampèremètre (A)",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A61Toggle": "A61 Train wire control 6 ",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A55Toggle": "A55 Train wire 10AS control",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A54Toggle": "A54 Train wire 10AK control",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A56Toggle": "A56 Allumer la batterie pour les circuits",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A27Toggle": "A27 Turn on DIP and lighting",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A21Toggle": "A21 Door control",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A10Toggle": "A10 Motor-compressor control",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A53Toggle": "A53 KVC power supply",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A43Toggle": "A43 ARS 12V power supply",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A45Toggle": "A45 ARS train wire 10AU",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A42Toggle": "A42 ARS 75V power supply",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A41Toggle": "A41 ARS braking",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.VUToggle": "VU  Train control",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A64Toggle": "A64 Cabin lighting",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A63Toggle": "A63 IGLA/BIS",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A50Toggle": "A50 Turn on DIP and lighting",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A51Toggle": "A51 Turn off DIP and lighting",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A23Toggle": "A23 Emergency motor-compressor turn on",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A14Toggle": "A14 Train wire 18",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A75Toggle": "A75 Cabin heating",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A1Toggle": "A1  X-1",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A2Toggle": "A2  X-2",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A3Toggle": "A3  X-3",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A17Toggle": "A17 Reset overload relay",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A62Toggle": "A62 Radio communications",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A29Toggle": "A29 Radio broadcasting",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A5Toggle": "A5 Interim wagon",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A6Toggle": "A6  T-1",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A8Toggle": "A8  Pneumatic valves #1, #2",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A20Toggle": "A20 Drive/brake circuit control, train wire 20",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A25Toggle": "A25 Manual electric braking",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A22Toggle": "A22 Turn on KK",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A30Toggle": "A30 Rheostat controller motor power",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A39Toggle": "A39 Emergency control",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A44Toggle": "A44 Emergency train control",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A80Toggle": "A80 Power circuit mode switch motor power",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A65Toggle": "A65 Interior lighting",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.L_5Toggle": "А49 Emergency lighting",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A24Toggle": "A24 Battery charging",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A32Toggle": "A32 Open right doors",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A31Toggle": "A31 Open left doors",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A16Toggle": "A16 Close doors",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A13Toggle": "A13 Door alarm",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A12Toggle": "A12 Emergency door close",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A7Toggle": "A7  Red lamp",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A9Toggle": "A9  Red lamp",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A46Toggle": "A46 White lamp",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A47Toggle": "A47 White lamp",
  "Entities.gmod_subway_81-717_mvm.Buttons.PassengerDoor.PassengerDoor": "Passenger door",
  "Entities.gmod_subway_81-717_mvm.Buttons.GV.GVToggle": " switcheur HV",
  "Entities.gmod_subway_81-717_mvm.Buttons.Stopkran.EmergencyBrakeValveToggle": "Frein d'urgence",
  "Entities.gmod_subway_81-717_mvm.Buttons.InfoTableSelect.PrevSign": "Panneau précédent",
  "Entities.gmod_subway_81-717_mvm.Buttons.InfoTableSelect.NextSign": "Panneau Suivant",
  "Entities.gmod_subway_81-717_mvm.Buttons.InfoTableSelect.Num2P": "Route: Augmenter le second nombre",
  "Entities.gmod_subway_81-717_mvm.Buttons.InfoTableSelect.Num2M": "Route: Descendre le second nombre",
  "Entities.gmod_subway_81-717_mvm.Buttons.InfoTableSelect.Num1P": "Route: Augmenter le premier nombre",
  "Entities.gmod_subway_81-717_mvm.Buttons.InfoTableSelect.Num1M": "Route: Descendre le premier nombre",
  "Entities.gmod_subway_81-717_mvm.Buttons.Front.L_4Toggle": "Phares",
  "Entities.gmod_subway_81-717_mvm.Buttons.Front.VUSToggle": "VUS: Phares puissants",
  "Entities.gmod_subway_81-717_mvm.Buttons.Front.VAHToggle": "VAH: Mode de conduite d'urgence ",
  "Entities.gmod_subway_81-717_mvm.Buttons.Front.VADToggle": "VAD: Fermeture d'urgence des portes (erreur du relai KD)",
  "Entities.gmod_subway_81-717_mvm.Buttons.Front.KRPSet": "KRP: Bouton de démarrage d'urgence",
  "Entities.gmod_subway_81-717_mvm.Buttons.Front.KAHSet": "Bouton de conduite d'urgence",
  "Entities.gmod_subway_81-717_mvm.Buttons.Front.KAHKToggle": "KAH Couvre bouton",
  "Entities.gmod_subway_81-717_mvm.Buttons.Front.KUP": "Activer le chauffage",
  "Entities.gmod_subway_81-717_mvm.Buttons.Front.KDPSet": "KDP: Ouvrir les portes droites",
  "Entities.gmod_subway_81-717_mvm.Buttons.Front.KDPKToggle": "KDP Couvre bouton",
  "Entities.gmod_subway_81-717_mvm.Buttons.Front.PN": "Contrôle des freins pneumatiques",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A61Toggle": "A61 Train wire 6 control",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A55Toggle": "A55 Train wire 10AS control",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A54Toggle": "A54 Train wire 10AK control",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A56Toggle": "A56 Turn on battery power to control circuits",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A27Toggle": "A27 Turn on DIP and lighting",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A21Toggle": "A21 Door control",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A10Toggle": "A10 Motor-compressor control",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A53Toggle": "A53 KVC power supply",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A43Toggle": "A43 ARS 12V power supply",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A45Toggle": "A45 ARS train wire 10AU",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A42Toggle": "A42 ARS 75V power supply",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A41Toggle": "A41 ARS braking",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:VUToggle": "Contrôle du train (VU)",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A64Toggle": "A64 Cabin lighting",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A63Toggle": "A63 IGLA/BIS",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A50Toggle": "A50 Turn on DIP and lighting",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A51Toggle": "A51 Turn off DIP and lighting",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A23Toggle": "A23 Emergency motor-compressor turn on",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A14Toggle": "A14 Train wire 18",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A75Toggle": "A75 Cabin heating",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A1Toggle": "A1  X-1",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A2Toggle": "A2  X-2",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A3Toggle": "A3  X-3",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A17Toggle": "A17 Reset overload relay",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A62Toggle": "A62 Radio communications",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A29Toggle": "A29 Radio broadcasting",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A5Toggle": "A5 Interim wagon",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A6Toggle": "A6  T-1",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A8Toggle": "A8  Pneumatic valves #1, #2",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A20Toggle": "A20 Drive/brake circuit control, train wire 20",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A25Toggle": "A25 Manual electric braking",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A22Toggle": "A22 Turn on KK",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A30Toggle": "A30 Rheostat controller motor power",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A39Toggle": "A39 Emergency control",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A44Toggle": "A44 Emergency train control",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A80Toggle": "A80 Power circuit mode switch motor power",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A65Toggle": "A65 Interior lighting",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:L_5Toggle": "А49 Emergency lighting",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A24Toggle": "A24 Battery charging",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A32Toggle": "A32 Open right doors",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A31Toggle": "A31 Open left doors",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A16Toggle": "A16 Close doors",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A13Toggle": "A13 Door alarm",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A12Toggle": "A12 Emergency door close",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A7Toggle": "A7  Red lamp",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A9Toggle": "A9  Red lamp",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A46Toggle": "A46 White lamp",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A47Toggle": "A47 White lamp",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!Speedometer": "Speed indicator",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!LSD": "LSD: Door state light (doors are closed)",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!LOCh": "NCh: Compteur",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!L0": "0: ARS signal stop",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!LRS": "LRS: Lumière d'égalité des vitesses (la vitesse du prochain segment est égale ou supérieure que celle de maintenant)",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!L40": "Limite de vitesse 40km/h",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!L60": "Limite de vitesse 60 km/h",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!L80": "Limite de vitesse 80 km/h",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!L70": "Limite de vitesse 60 km/h",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!LRK": "RK: Lampe de contrôle du rhéostat",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!LEKK": "",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!LPU": "",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!LKVD": "LKVD: Indicateur de l'arret des moteurs ARS",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!LKT": "LKT: Indicateur de freinage ARS",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!LRP": "RP: Lumière rouge d'overload des relais, les circuits n'ont pas réussis a s'assembler",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!LKVC": "LKVC: Haut voltage non disponible",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!LVD": "LVD: Moteurs engagés",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!LST": "LST: Freins engagés",
  "Entities.gmod_subway_81-717_mvm.Buttons.CabinDoor.CabinDoor": "Porte de cabine",
  "Entities.gmod_subway_81-717_mvm.Buttons.Reverser.KVReverserDown": "Marche arrière",
  "Entities.gmod_subway_81-717_mvm.Buttons.Reverser.KVReverserUp": "Marche avant",
  "Entities.gmod_subway_81-717_mvm.Buttons.PassengerDoor1.PassengerDoor": " Porte passager",
  "Entities.gmod_subway_81-717_mvm.Buttons.UAVAPanel.UAVAToggle": "UAVA:Désactivateur de l'arrêt automatique lors du dépassement des feux rouges",
  "Entities.gmod_subway_81-717_mvm.Buttons.UAVAPanel.UAVAContactSet": "UAVA: Réinitialiser les contacts de l'UAVA",
  "Entities.gmod_subway_81-717_mvm.Buttons.EPKDisconnect.EPKToggle": " Valve de déconnection de l'EPV",
  "Entities.gmod_subway_81-717_mvm.Buttons.Help.ShowHelp": "Afficher de l'aide concernant la conduite du train",
  "Entities.gmod_subway_81-717_mvm.Buttons.ParkingBrake2.1:ParkingBrakeToggle": "Parking brake Frein de parking",
  "Entities.gmod_subway_81-717_mvm.Buttons.RearPneumatic.RearBrakeLineIsolationToggle": " Valve d'isolation des freins",
  "Entities.gmod_subway_81-717_mvm.Buttons.RearPneumatic.RearTrainLineIsolationToggle": "Valve d'isolation du train",
  "Entities.gmod_subway_81-717_mvm.Buttons.AirDistributor.AirDistributorDisconnectToggle": "Désactiver le distributeur d'air",

  "Entities.gmod_subway_81-714_mvm.Buttons.GV.GVToggle": "Switcheur HV",
  "Entities.gmod_subway_81-714_mvm.Buttons.RearPneumatic.RearBrakeLineIsolationToggle": "Valve d'isolation des freins",
  "Entities.gmod_subway_81-714_mvm.Buttons.RearPneumatic.RearTrainLineIsolationToggle": "Valve d'isolation du train",
  "Entities.gmod_subway_81-714_mvm.Buttons.RearDoor.RearDoor": "Porte arrière",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Left.DriverValveBLDisconnectToggle": " Valve de déconnection des freins",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Left.DriverValveTLDisconnectToggle": " Valve de déconnection du (train line)",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Left.A65Toggle": "A65 Interior lighting",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Left.A56Toggle": "A56 Turn on battery power to control circuits",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Left.A63Toggle": "A63 IGLA/BIS",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Left.A10Toggle": "A10 Motor-compressor control",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Left.A30Toggle": "A30 Rheostat controller motor power",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Left.A80Toggle": "A80 Power circuit mode switch motor power",
  "Entities.gmod_subway_81-714_mvm.Buttons.FrontPneumatic.FrontBrakeLineIsolationToggle": " Valve d'isolation de la ligne de frein",
  "Entities.gmod_subway_81-714_mvm.Buttons.FrontPneumatic.FrontTrainLineIsolationToggle": " Valve d'isolation de la ligne de train",
  "Entities.gmod_subway_81-714_mvm.Buttons.FrontPneumatic.ParkingBrakeToggle": "Frein de parking",
  "Entities.gmod_subway_81-714_mvm.Buttons.AirDistributor.AirDistributorDisconnectToggle": "Désactiver le distributeur d'air",
  "Entities.gmod_subway_81-714_mvm.Buttons.FrontDoor.FrontDoor": "Porte de devant",
  "Entities.gmod_subway_81-714_mvm.Buttons.Battery.VBToggle": "VB: Batterie on/off",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A54Toggle": "A54 Train wire 10AK control",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A27Toggle": "A27 Turn on DIP and lighting",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A24Toggle": "A24 Battery charging",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A53Toggle": "A53 KVC power supply",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A13Toggle": "A13 Door alarm",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A32Toggle": "A32 Open right doors",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A31Toggle": "A31 Open left doors",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A16Toggle": "A16 Close doors",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A12Toggle": "A12 Emergency door close",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A50Toggle": "A50 Turn on DIP and lighting",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A51Toggle": "A51 Turn off DIP and lighting",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A1Toggle": "A1  X-1",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.KRPSet": "START:  Bouton de démarrage d'urgence",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.VozvratRPSet": "Remettre a zéro le relai overload",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.RezMKSet": " Démarrage d'urgence des compresseurs du moteur",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.VMKToggle": "Allumer le compresseur du moteur",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.BPSNonToggle": "BPSN: Envoyer de l'électricité dans le train",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A2Toggle": "A2  X-2",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A3Toggle": "A3  X-3",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A17Toggle": "A17 Reset overload relay",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A5Toggle": "A5  ",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A6Toggle": "A6  T-1",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A8Toggle": "A8  Pneumatic valves #1, #2",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A20Toggle": "A20 Drive/brake circuit control, train wire 20",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A25Toggle": "A25 Manual electric braking",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A22Toggle": "A22 Turn on KK",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A23Toggle": "A23 Emergency motor-compressor turn on",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A39Toggle": "A39 Emergency control",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A14Toggle": "A14 Train wire 18"
}
]]
