return [[
{
	"Lang": "fr",
	"Name": "French",
	"Panel.Admin": "Admin",
	"Panel.Client": "Client",
	"Panel.DrawDebugInfo": "Draw debugging info",
	"Panel.DisableCamAccel": "Disable cam acceleration",
	"Panel.DisableHoverText": "Disable hover text",

	"Entities.gmod_subway_base.Name": "Subway base",
	"Entities.gmod_subway_81-703.Name": "E",
	"Entities.gmod_subway_81-703_2.Name": "E (intermédiaire)",
	"Entities.gmod_subway_81-717_mvm.Name": "81-717(MVM)",
	"Entities.gmod_subway_81-717_lvz.Name": "81-717(LVZ)",
	"Entities.gmod_subway_81-714_mvm.Name": "81-714(MVM)",
	"Entities.gmod_subway_81-714_lvz.Name": "81-714(LVZ)",
	"Entities.gmod_subway_81-7036.Name": "81-7036 (ne fonctionne pas)",
	"Entities.gmod_subway_81-7037.Name": "81-7037 (ne fonctionne pas)",
	"Entities.gmod_subway_81-720.Name": "81-720 (locomotive)",
	"Entities.gmod_subway_81-721.Name": "81-721 (intermédiaire)",
	"Entities.gmod_subway_81-722.Name": "81-722 (locomotive)",
	"Entities.gmod_subway_81-723.Name": "81-723 (intermédiaire motorisé)",
	"Entities.gmod_subway_81-724.Name": "81-724 (wagon intermédiaire)",
	"Entities.gmod_subway_e.Name": "E",
	"Entities.gmod_subway_em.Name": "Em",
	"Entities.gmod_subway_ema.Name": "Ema",
	"Entities.gmod_subway_ezh.Name": "Ezh",
	"Entities.gmod_subway_ezh1.Name": "Ezh1",
	"Entities.gmod_subway_em508.Name": "Em-508",
	"Entities.gmod_subway_em508_int.Name": "Em-508 intermédiaire",
	"Entities.gmod_subway_ezh3.Name": "Ezh3",
	"Entities.gmod_subway_ezh3ru1.Name": "Ezh3 RU1",
	"Entities.gmod_subway_ema508t.Name": "Em-508t",
	"Entities.gmod_subway_tatra_t3.Name": "Tatra T3",
	"Entities.gmod_subway_ai.Name": "train IA",

	"Entities.gmod_train_bogey.Name": "Bogie de train",
	"Entities.gmod_train_couple.Name": "Couple",

	"Entities.gmod_track_pui.Name": "Horloge PUI",
	"Entities.gmod_track_mus_elektronika7.Name": "Horloge Électrique",
	"Entities.gmod_mus_clock_analog.Name": "Horloge Analogique ",
	"Entities.gmod_track_clock_time.Name": "Horloge des Grandes Intervales (temps)",
	"Entities.gmod_track_clock_small.Name": "Horloge de petites intervales",
	"Entities.gmod_track_clock_interval.Name": " Horloge des Grandes Intervales (intervales)",
 	"Entities.gmod_track_switch.Name": "Aiguillage",
	"Entities.gmod_track_powermeter.Name": "Voltmètre",
	"Entities.gmod_track_controller.Name": "Controleur de rails",
	"Entities.gmod_track_udochka.Name": "Connecteur électrique",
	"Entities.gmod_train_spawner.Name": "Outil d'apparition de trains"
}
]]
