return [[
{
	"Lang": "fr",
	"Name": "French",

	"Spawner.Title": "Outil d'apparition de trains",
	"Spawner.Trains1": "Trains",
	"Spawner.Trains2": "Maximum pour toi",
	"Spawner.WagNum": "Wagons",
	"Spawner.AutoCouple": "Coupler automatiquement les wagons",

	"Entities.gmod_subway_81-717_mvm.Spawner.Texture.Name": "Apparence",
	"Entities.gmod_subway_81-717_mvm.Spawner.PassTexture.Name": "Apparence intérieure",
	"Entities.gmod_subway_81-717_mvm.Spawner.CabTexture.Name": "Apparence de la cabine",
	"Entities.gmod_subway_81-717_mvm.Spawner.Announcer.Name": "Annonceur",
	"Entities.gmod_subway_81-717_mvm.Spawner.Lighter.Name": "Lighter",
	"Entities.gmod_subway_81-717_mvm.Spawner.ARSType.Name": "Type d'interface ARS",
	"Entities.gmod_subway_81-717_mvm.Spawner.ARSType.1": "Standard(lampes carrées)",
	"Entities.gmod_subway_81-717_mvm.Spawner.ARSType.2": "Standard(lampes rondes)",
	"Entities.gmod_subway_81-717_mvm.Spawner.ARSType.3": "Kiev/SPB",
	"Entities.gmod_subway_81-717_mvm.Spawner.ARSType.4": "Ancien ARS(compteur à aiguilles)",
	"Entities.gmod_subway_81-717_mvm.Spawner.Cran.Name": "Type de levier de frein",
	"Entities.gmod_subway_81-717_mvm.Spawner.Cran.1": "334",
	"Entities.gmod_subway_81-717_mvm.Spawner.Cran.2": "013",
	"Entities.gmod_subway_81-717_mvm.Spawner.MaskType.Name": "Type de pare-chocs",
	"Entities.gmod_subway_81-717_mvm.Spawner.MaskType.1": "2-2",
	"Entities.gmod_subway_81-717_mvm.Spawner.MaskType.2": "2-2-2",
	"Entities.gmod_subway_81-717_mvm.Spawner.MaskType.3": "1-4-1 avant 1",
	"Entities.gmod_subway_81-717_mvm.Spawner.MaskType.4": "1-4-1 avant 2",
	"Entities.gmod_subway_81-717_mvm.Spawner.MaskType.5": "1-1",
	"Entities.gmod_subway_81-717_mvm.Spawner.MaskType.6": "Rétro",
	"Entities.gmod_subway_81-717_mvm.Spawner.LED.Name": "LED",
	"Entities.gmod_subway_81-717_mvm.Spawner.BPSNType.Name": "Type de BPSN",
	"Entities.gmod_subway_81-717_mvm.Spawner.BPSNType.1": "Ancien son ton haut ",
	"Entities.gmod_subway_81-717_mvm.Spawner.BPSNType.2": " Ancien son ton moyen ",
	"Entities.gmod_subway_81-717_mvm.Spawner.BPSNType.3": "Standard(de SPB)",
	"Entities.gmod_subway_81-717_mvm.Spawner.BPSNType.4": "Standard(TKL)",
	"Entities.gmod_subway_81-717_mvm.Spawner.BPSNType.5": "Standard",
	"Entities.gmod_subway_81-717_mvm.Spawner.BPSNType.6": "Kiev",
	"Entities.gmod_subway_81-717_mvm.Spawner.BPSNType.7": "Ancien",
	"Entities.gmod_subway_81-717_mvm.Spawner.BPSNType.8": "Standard 2",
	"Entities.gmod_subway_81-717_mvm.Spawner.BPSNType.9": "Standard 3",
	"Entities.gmod_subway_81-717_mvm.Spawner.BPSNType.10": "Aucun son(BPN-115)",
	"Entities.gmod_subway_81-717_mvm.Spawner.KVSnd.Name": "Son du controlleur ",
	"Entities.gmod_subway_81-717_mvm.Spawner.KVSnd.1": "Type 1",
	"Entities.gmod_subway_81-717_mvm.Spawner.KVSnd.2": "Type 2",
	"Entities.gmod_subway_81-717_mvm.Spawner.KVSnd.3": "Type 3",
	"Entities.gmod_subway_81-717_mvm.Spawner.NewKV.Name": "Nouveau modèle de controlleur",
	"Entities.gmod_subway_81-717_mvm.Spawner.HornType.Name": "klaxon SPB ",
	"Entities.gmod_subway_81-717_mvm.Spawner.RingType.Name": "Sonette",
	"Entities.gmod_subway_81-717_mvm.Spawner.RingType.1": "Ancien",
	"Entities.gmod_subway_81-717_mvm.Spawner.RingType.2": "Standard, ton bas",
	"Entities.gmod_subway_81-717_mvm.Spawner.RingType.3": "Standard, ton haut",
	"Entities.gmod_subway_81-717_mvm.Spawner.RingType.4": "Standard intermittent et ton bas",
	"Entities.gmod_subway_81-717_mvm.Spawner.RingType.5": "Standard intermittent et ton haut",
	"Entities.gmod_subway_81-717_mvm.Spawner.NM.Name": "Valve(train line)",
	"Entities.gmod_subway_81-717_mvm.Spawner.Battery.Name": "Batterie",
	"Entities.gmod_subway_81-717_mvm.Spawner.Switches.Name": "Activateur de circuit(ON)",
	"Entities.gmod_subway_81-717_mvm.Spawner.SwitchesR.Name": "Activateur de circuit(au hasard)",
	"Entities.gmod_subway_81-717_mvm.Spawner.DoorsL.Name": "Portes Gauches Ouvertes",
	"Entities.gmod_subway_81-717_mvm.Spawner.DoorsR.Name": " Portes Droite Ouvertes ",
	"Entities.gmod_subway_81-717_mvm.Spawner.GV.Name": "Switcheur HV",
	"Entities.gmod_subway_81-717_mvm.Spawner.PB.Name": "Frein de Parking",
	"Entities.gmod_subway_81-717_mvm.Spawner.BortLampType.Name": "Types de lampes(Compteurs)",
	"Entities.gmod_subway_81-717_mvm.Spawner.BortLampType.1": "Horizontal",
	"Entities.gmod_subway_81-717_mvm.Spawner.BortLampType.2": "Vertical",
	"Entities.gmod_subway_81-717_mvm.Spawner.MVM.Name": "Signe MVM",
	"Entities.gmod_subway_81-717_mvm.Spawner.HandRail.Name": "Handrails type",
	"Entities.gmod_subway_81-717_mvm.Spawner.HandRail.1": "Vieux",
	"Entities.gmod_subway_81-717_mvm.Spawner.HandRail.2": "Neuf",
	"Entities.gmod_subway_81-717_mvm.Spawner.SeatType.Name": "Type de sièges",
	"Entities.gmod_subway_81-717_mvm.Spawner.SeatType.1": "Vieux",
	"Entities.gmod_subway_81-717_mvm.Spawner.SeatType.2": "Neuf",
	"Entities.gmod_subway_81-717_mvm.Spawner.LampType.Name": "Type de Lampes(Intérieure)",
	"Entities.gmod_subway_81-717_mvm.Spawner.LampType.1": "Type 1",
	"Entities.gmod_subway_81-717_mvm.Spawner.LampType.2": "Type 2",
	"Entities.gmod_subway_81-717_mvm.Spawner.LampType.3": "Type 3",
	"Entities.gmod_subway_81-717_mvm.Spawner.Breakers.Name": "Activateur de circuits droite",
	"Entities.gmod_subway_81-717_mvm.Spawner.Adverts.Name": "Type de klaxon",
	"Entities.gmod_subway_81-717_mvm.Spawner.Adverts.1": "Type 1",
	"Entities.gmod_subway_81-717_mvm.Spawner.Adverts.2": "Type 2",
	"Entities.gmod_subway_81-717_mvm.Spawner.Adverts.3": "Type 3",
	"Entities.gmod_subway_81-717_mvm.Spawner.Adverts.4": "Aucun",

	"Entities.gmod_subway_81-720.Spawner.Texture.Name": "Apparence",
	"Entities.gmod_subway_81-720.Spawner.PassTexture.Name": "Apparence intérieure",
	"Entities.gmod_subway_81-720.Spawner.CabTexture.Name": "Apparence de la cabine",
	"Entities.gmod_subway_81-720.Spawner.Announcer.Name": "Annonceur",
	"Entities.gmod_subway_81-720.Spawner.Scheme.Name": "Schéma de la ligne",
	"Entities.gmod_subway_81-720.Spawner.PassSchemesInvert.Name": "Inverser le schéma",
	"Entities.gmod_subway_81-720.Spawner.NM.Name": "Valve(Train line)",
	"Entities.gmod_subway_81-720.Spawner.Battery.Name": "Batterie",
	"Entities.gmod_subway_81-720.Spawner.BRU.Name": "Switcheur HV",
	"Entities.gmod_subway_81-720.Spawner.PVZR.Name": "Activateurs de circuit du train(random)",
	"Entities.gmod_subway_81-720.Spawner.PPZ.Name": "Activer tous les activateurs de circuit ",
	"Entities.gmod_subway_81-720.Spawner.PPZDepot.Name": "Désactiver tous les activateurs",
	"Entities.gmod_subway_81-720.Spawner.PPZR.Name": "Activateurs de circuits aléatoires(wagon)",
	"Entities.gmod_subway_81-720.Spawner.DoorsL.Name": "Ouvrir les portes gauche",
	"Entities.gmod_subway_81-720.Spawner.DoorsR.Name": "Ouvrir les portes droite",

	"Entities.gmod_subway_81-722.Spawner.Texture.Name": "Apparence",
	"Entities.gmod_subway_81-722.Spawner.PassTexture.Name": "Apparence intérieure",
	"Entities.gmod_subway_81-722.Spawner.CabTexture.Name": "Apparence de la cabine",
	"Entities.gmod_subway_81-722.Spawner.Announcer.Name": "Annonceur",
	"Entities.gmod_subway_81-722.Spawner.Scheme.Name": "Schéma de la ligne",
	"Entities.gmod_subway_81-722.Spawner.SarmatInvert.Name": "Inverser le schéma",
	"Entities.gmod_subway_81-722.Spawner.NM.Name": "Valve(Train line)",
	"Entities.gmod_subway_81-722.Spawner.Battery.Name": "Batterie",
	"Entities.gmod_subway_81-722.Spawner.Switches.Name": "Activer tous les activateurs de circuits",
	"Entities.gmod_subway_81-722.Spawner.SwitchesR.Name": "Activateur de circuit (random)",
	"Entities.gmod_subway_81-722.Spawner.DoorsL.Name": "Ouvrir les portes gauches",
	"Entities.gmod_subway_81-722.Spawner.DoorsR.Name": "Ouvrir les portes droites",

	"Spawner.Close": "Fermer",
	"Spawner.Spawn": "Fini !"
}
]]
