return [[
{
	"Lang": "kr",
	"Name": "Korean",
	"Panel.Admin": "관리자",
	"Panel.Client": "사용자",
	"Panel.DrawDebugInfo": "디버깅 정보 표시",
	"Panel.DisableCamAccel": "시점 흔들림 끄기",
	"Panel.DisableHoverText": "주석 텍스트 끄기",

	"Entities.gmod_subway_base.Name": "Subway base",
	"Entities.gmod_subway_81-703.Name": "E",
	"Entities.gmod_subway_81-703_2.Name": "E (중간 객차)",
	"Entities.gmod_subway_81-717_mvm.Name": "81-717(MVM)",
	"Entities.gmod_subway_81-717_lvz.Name": "81-717(LVZ)",
	"Entities.gmod_subway_81-714_mvm.Name": "81-714(MVM)",
	"Entities.gmod_subway_81-714_lvz.Name": "81-714(LVZ)",
	"Entities.gmod_subway_81-7036.Name": "81-7036 (작동 안함)",
	"Entities.gmod_subway_81-7037.Name": "81-7037 (작동 안함)",
	"Entities.gmod_subway_81-720.Name": "81-720 (선두차)",
	"Entities.gmod_subway_81-721.Name": "81-721 (중간 객차)",
	"Entities.gmod_subway_81-722.Name": "81-722 (선두차)",
	"Entities.gmod_subway_81-723.Name": "81-723 (중간 동력 객차)",
	"Entities.gmod_subway_81-724.Name": "81-724 (중간 무동력 객차)",
	"Entities.gmod_subway_e.Name": "E",
	"Entities.gmod_subway_em.Name": "Em",
	"Entities.gmod_subway_ema.Name": "Ema",
	"Entities.gmod_subway_ezh.Name": "Ezh",
	"Entities.gmod_subway_ezh1.Name": "Ezh1",
	"Entities.gmod_subway_em508.Name": "Em-508",
	"Entities.gmod_subway_em508_int.Name": "Em-508 (중간차)",
	"Entities.gmod_subway_ezh3.Name": "Ezh3",
	"Entities.gmod_subway_ezh3ru1.Name": "Ezh3 RU1",
	"Entities.gmod_subway_ema508t.Name": "Em-508t",
	"Entities.gmod_subway_tatra_t3.Name": "Tatra T3",
	"Entities.gmod_subway_ai.Name": "AI 차량",

	"Entities.gmod_train_bogey.Name": "대차",
	"Entities.gmod_train_couple.Name": "연결기",

	"Entities.gmod_track_pui.Name": "PUI 시계",
	"Entities.gmod_track_mus_elektronika7.Name": "전자 시계",
	"Entities.gmod_mus_clock_analog.Name": "아날로그 시계",
	"Entities.gmod_track_clock_time.Name": "대형 배차간격 시계(시간)",
	"Entities.gmod_track_clock_small.Name": "소형 배차간격 시계",
	"Entities.gmod_track_clock_interval.Name": "대형 배차간격 시계(배차간격)",
	"Entities.gmod_track_switch.Name": "선로 분기기",
	"Entities.gmod_track_powermeter.Name": "전력계",
	"Entities.gmod_track_udochka.Name": "급전 커넥터",
	"Entities.gmod_train_spawner.Name": "열차 스포너"
}
]]
