return [[
{
  "Lang": "kr",
  "Name": "Korean",


  "Entities.gmod_subway_ezh3.Buttons.Stopkran.EmergencyBrakeValveToggle": "비상 제동",
  "Entities.gmod_subway_ezh3.Buttons.Back.BackDoor": "관통문(뒤)",
  "Entities.gmod_subway_ezh3.Buttons.DriverValveBLTLDisconnect.DriverValveBLDisconnectToggle": "제동관 차단 밸브",
  "Entities.gmod_subway_ezh3.Buttons.DriverValveBLTLDisconnect.DriverValveTLDisconnectToggle": "주 공기관 차단 밸브",
  "Entities.gmod_subway_ezh3.Buttons.Battery.VBToggle": "VB: 배터리 투입/차단 (저전압)",
  "Entities.gmod_subway_ezh3.Buttons.FrontPneumatic.FrontBrakeLineIsolationToggle": "제동관 해방 밸브",
  "Entities.gmod_subway_ezh3.Buttons.FrontPneumatic.FrontTrainLineIsolationToggle": "주 공기관 해방 밸브",
  "Entities.gmod_subway_ezh3.Buttons.ASNP.R_ASNPMenuSet": "안내방송기: 메뉴",
  "Entities.gmod_subway_ezh3.Buttons.ASNP.R_ASNPUpSet": "안내방송기: 위",
  "Entities.gmod_subway_ezh3.Buttons.ASNP.R_ASNPDownSet": "안내방송기: 아래",
  "Entities.gmod_subway_ezh3.Buttons.ASNP.R_ASNPOnToggle": "안내방송기: 전원",
  "Entities.gmod_subway_ezh3.Buttons.PassengerDoor1.PassengerDoor": "객실문",
  "Entities.gmod_subway_ezh3.Buttons.PassengerDoor.PassengerDoor": "객실문",
  "Entities.gmod_subway_ezh3.Buttons.CabinDoor.CabinDoor": "운전실문",
  "Entities.gmod_subway_ezh3.Buttons.Front.FrontDoor": "관통문(앞)",
  "Entities.gmod_subway_ezh3.Buttons.GV.GVToggle": "고전압 스위치",
  "Entities.gmod_subway_ezh3.Buttons.RearPneumatic.RearTrainLineIsolationToggle": "주 공기관 차단 밸브",
  "Entities.gmod_subway_ezh3.Buttons.RearPneumatic.RearBrakeLineIsolationToggle": "제동관 차단 밸브",
  "Entities.gmod_subway_ezh3.Buttons.Panel.!OCH": "NCh: ARS 신호 없음",
  "Entities.gmod_subway_ezh3.Buttons.Panel.!0": "0: ARS 정지 신호",
  "Entities.gmod_subway_ezh3.Buttons.Panel.!40": "속도 제한 40 kph",
  "Entities.gmod_subway_ezh3.Buttons.Panel.!60": "속도 제한 60 kph",
  "Entities.gmod_subway_ezh3.Buttons.Panel.!70": "속도 제한 80 kph",
  "Entities.gmod_subway_ezh3.Buttons.Panel.!80": "속도 제한 60 kph",
  "Entities.gmod_subway_ezh3.Buttons.Panel.!Speedometer": "속도계 (km/h)",
  "Entities.gmod_subway_ezh3.Buttons.Panel.!TotalAmpermeter": "총 전류계 (A)",
  "Entities.gmod_subway_ezh3.Buttons.Panel.!TotalVoltmeter": "총 전압계 (kV)",
  "Entities.gmod_subway_ezh3.Buttons.Panel.!BatteryVoltage": "차량 제어 용 배터리 전압(V)",
  "Entities.gmod_subway_ezh3.Buttons.Panel.!BrakeCylinder": "제동통 압력",
  "Entities.gmod_subway_ezh3.Buttons.Panel.!LinesPressure": "공기관 압력 (red: 제동관 압력, black: 주 공기관 압력)",
  "Entities.gmod_subway_ezh3.Buttons.Main.KU1Toggle": "공기 압축기 기동",
  "Entities.gmod_subway_ezh3.Buttons.Main.SAMM1Set": "SAMM: 운전 종료",
  "Entities.gmod_subway_ezh3.Buttons.Main.SAMM2Set": "SAMM: 시작",
  "Entities.gmod_subway_ezh3.Buttons.Main.SAMM3Set": "SAMM: 리셋",
  "Entities.gmod_subway_ezh3.Buttons.Main.SAMMSignal1": "Lamp: 상용 제동",
  "Entities.gmod_subway_ezh3.Buttons.Main.SAMMSignal2": "Lamp: SAMM 작동 상태",
  "Entities.gmod_subway_ezh3.Buttons.Main.SAMMSignal3": "Lamp: SAMM 실행 유닛 작동",
  "Entities.gmod_subway_ezh3.Buttons.Main.SAMMOnToggle": "SAMM: 자동 운전 시작",
  "Entities.gmod_subway_ezh3.Buttons.Main.SAMMBlokToggle": "SAMM: 실행 유닛",
  "Entities.gmod_subway_ezh3.Buttons.Main.SAMMCommand3Set": "SAMM: X-2",
  "Entities.gmod_subway_ezh3.Buttons.Main.SAMMCommand2Set": "SAMM: 따라 잡기",
  "Entities.gmod_subway_ezh3.Buttons.Main.SAMMCommand1Set": "SAMM: 권한",
  "Entities.gmod_subway_ezh3.Buttons.Main.KSNSet": "KSN: 고장 확인 버튼",
  "Entities.gmod_subway_ezh3.Buttons.Main.R_Program1Set": "안내방송 1",
  "Entities.gmod_subway_ezh3.Buttons.Main.R_Program2Set": "안내방송 2",
  "Entities.gmod_subway_ezh3.Buttons.Main.VUSToggle": "Switch: 하향등 (아래)/상향등 (위)",
  "Entities.gmod_subway_ezh3.Buttons.Main.L_3Toggle": "Switch: 조명 측정기",
  "Entities.gmod_subway_ezh3.Buttons.Main.VAHToggle": "Switch: 비상 운전",
  "Entities.gmod_subway_ezh3.Buttons.Main.DIPonSet": "Osv. Vkl.: 조명 켜기",
  "Entities.gmod_subway_ezh3.Buttons.Main.DIPoffSet": "Osv. Vykl.: 조명 끄기",
  "Entities.gmod_subway_ezh3.Buttons.Main.KSDSet": "KSD: 출입문 신호 전달 확인",
  "Entities.gmod_subway_ezh3.Buttons.Main.KVTSet": "KVT: 제동 확인 버튼",
  "Entities.gmod_subway_ezh3.Buttons.Main.KBSet": "KB: 확인 버튼",
  "Entities.gmod_subway_ezh3.Buttons.Main.KBLamp": "Lamp: RK 회전 중",
  "Entities.gmod_subway_ezh3.Buttons.Main.ARSToggle": "ARS: 자동 속도 제한",
  "Entities.gmod_subway_ezh3.Buttons.Main.R_UNchToggle": "UNCh: 저주파 증폭기",
  "Entities.gmod_subway_ezh3.Buttons.Main.VUD1Toggle": "VUD: 출입문 제어 스위치 (출입문 닫힘)",
  "Entities.gmod_subway_ezh3.Buttons.Main.R_RadioToggle": "안내방송기 전원 (내장형)",
  "Entities.gmod_subway_ezh3.Buttons.Main.ALSToggle": "ALS: 자동 차량 신호 제어",
  "Entities.gmod_subway_ezh3.Buttons.Main.VozvratRPSet": "KVRP: 과전류 계전기 리셋",
  "Entities.gmod_subway_ezh3.Buttons.Main.RingSet": "부저",
  "Entities.gmod_subway_ezh3.Buttons.Main.L_2Toggle": "Switch: 운전실 조명",
  "Entities.gmod_subway_ezh3.Buttons.Main.KRZDSet": "KRZD: 출입문 강제 닫힘",
  "Entities.gmod_subway_ezh3.Buttons.Main.KDPSet": "KDP: 우측 출입문 열림",
  "Entities.gmod_subway_ezh3.Buttons.Main.KDLSet": "KDL: 좌측 출입문 열림",
  "Entities.gmod_subway_ezh3.Buttons.Main.KAHSet": "KAH: 비상 운전 버튼",
  "Entities.gmod_subway_ezh3.Buttons.Main.RezMKSet": "공기 압축기 강제 기동",
  "Entities.gmod_subway_ezh3.Buttons.Main.KRPSet": "KRP: 비상 기동 버튼",
  "Entities.gmod_subway_ezh3.Buttons.Main.RSTToggle": "VPR: 무선국 활성화",
  "Entities.gmod_subway_ezh3.Buttons.Main.R_GToggle": "스피커: 운전실 내부 방송 재생",
  "Entities.gmod_subway_ezh3.Buttons.Main.R_ZSToggle": "ZS: 객실 내부 방송 재생",
  "Entities.gmod_subway_ezh3.Buttons.Main.Custom2Set": "(기능 없음)",
  "Entities.gmod_subway_ezh3.Buttons.Main.Custom3Set": "(기능 없음)",
  "Entities.gmod_subway_ezh3.Buttons.Main.ASNPPlay": "안내방송기 작동 확인등",
  "Entities.gmod_subway_ezh3.Buttons.AV1.VU3Toggle": "VU3: 운전실 조명",
  "Entities.gmod_subway_ezh3.Buttons.AV1.VU2Toggle": "VU2: 비상등 (45V)",
  "Entities.gmod_subway_ezh3.Buttons.AV1.VU1Toggle": "VU1: 운전실 난방 (3kWt)",
  "Entities.gmod_subway_ezh3.Buttons.AVMain.AV8BToggle": "AV-8B: 자동 스위치 (고전압)",
  "Entities.gmod_subway_ezh3.Buttons.RC1.RC1Toggle": "RC-ARS: ARS 차단기",
  "Entities.gmod_subway_ezh3.Buttons.UAVAPanel.UAVAToggle": "UAVA: 범용 자동 정지 장치 비활성 (자동 정지 비활성)",
  "Entities.gmod_subway_ezh3.Buttons.UAVAPanel.UAVAContactSet": "UAVA: 범용 자동 정지 장치 비활성 (복귀)",
  "Entities.gmod_subway_ezh3.Buttons.VUHelper.VUToggle": "VU: 차량 제어 활성화",
  "Entities.gmod_subway_ezh3.Buttons.HelperPanel.VDLSet": "KDL: 좌측 출입문 열림",
  "Entities.gmod_subway_ezh3.Buttons.HelperPanel.VUD2Toggle": "VUD2: 출입문 제어 스위치 (출입문 닫힘)",
  "Entities.gmod_subway_ezh3.Buttons.EPKDisconnect.EPKToggle": "EPK 차단 밸브",
  "Entities.gmod_subway_ezh3.Buttons.VU.VUToggle": "VU: 차량 제어 활성화",
  "Entities.gmod_subway_ezh3.Buttons.ParkingBrake.ParkingBrakeLeft": "주차 제동 핸들",
  "Entities.gmod_subway_ezh3.Buttons.ParkingBrake.ParkingBrakeRight": "주차 제동 핸들",
  "Entities.gmod_subway_ezh3.Buttons.AirDistributor.AirDistributorDisconnectToggle": "공압 제어기 비활성",

  "Entities.gmod_subway_em508t.Buttons.Stopkran.EmergencyBrakeValveToggle": "비상 제동",
  "Entities.gmod_subway_em508t.Buttons.Battery.VBToggle": "VB: 배터리 투입/차단 (저전압)",
  "Entities.gmod_subway_em508t.Buttons.FrontPneumatic.FrontBrakeLineIsolationToggle": "제동관 차단 밸브",
  "Entities.gmod_subway_em508t.Buttons.FrontPneumatic.FrontTrainLineIsolationToggle": "주 공기관 차단 밸브",
  "Entities.gmod_subway_em508t.Buttons.GV.GVToggle": "고전압 스위치",
  "Entities.gmod_subway_em508t.Buttons.RearPneumatic.RearTrainLineIsolationToggle": "주 공기관 차단 밸브",
  "Entities.gmod_subway_em508t.Buttons.RearPneumatic.RearBrakeLineIsolationToggle": "제동관 차단 밸브",
  "Entities.gmod_subway_em508t.Buttons.RearDoor.RearDoor": "객실문",
  "Entities.gmod_subway_em508t.Buttons.Back2.!HVFuse": "고전압 퓨즈 함",
  "Entities.gmod_subway_em508t.Buttons.Back2.!Relays": "배터리 충전/출입문 압력 제어기 함",
  "Entities.gmod_subway_em508t.Buttons.Back2.!Heater": "난방기",
  "Entities.gmod_subway_em508t.Buttons.Front.FrontDoor": "관통문(앞)",
  "Entities.gmod_subway_em508t.Buttons.AV1.VU3Toggle": "VU3: 운전실 조명",
  "Entities.gmod_subway_em508t.Buttons.AV1.VU2Toggle": "VU2: 비상등 (45V)",
  "Entities.gmod_subway_em508t.Buttons.AV1.VU1Toggle": "VU1: 운전실 난방 (3kWt)",
  "Entities.gmod_subway_em508t.Buttons.ParkingBrake.ParkingBrakeLeft": "주차 제동 핸들",
  "Entities.gmod_subway_em508t.Buttons.ParkingBrake.ParkingBrakeRight": "주차 제동 핸들",
  "Entities.gmod_subway_em508t.Buttons.CabinDoor.CabinDoor1": "운전실문",
  "Entities.gmod_subway_em508t.Buttons.PassengerDoor.PassengerDoor": "객실문",
  "Entities.gmod_subway_em508t.Buttons.PassengerDoor1.PassengerDoor": "객실문",
  "Entities.gmod_subway_em508t.Buttons.Main.!RedRP": "RP: 과전류 계전기 확인등 (적색) (전원 회로 연결 실패)",
  "Entities.gmod_subway_em508t.Buttons.Main.!GreenRP": "RP: 과전류 계전기 확인등 (녹색) (추진장치 과전류 방지)",
  "Entities.gmod_subway_em508t.Buttons.Main.!SD": "출입문 닫힘 확인등",
  "Entities.gmod_subway_em508t.Buttons.Main.KDLSet": "Switch: 좌측 출입문 열림",
  "Entities.gmod_subway_em508t.Buttons.Main.KSDSet": "Switch: 신호 전달 (출입문 제어 확인)",
  "Entities.gmod_subway_em508t.Buttons.Main.VozvratRPSet": "Switch: 과전류 계전기 리셋",
  "Entities.gmod_subway_em508t.Buttons.Main.KSNSet": "Switch: 고장 확인 스위치",
  "Entities.gmod_subway_em508t.Buttons.Main.VUD1Toggle": "Switch: 출입문 제어 스위치 (출입문 닫힘)",
  "Entities.gmod_subway_em508t.Buttons.Main.KU1Toggle": "Switch: 공기 압축기 기동",
  "Entities.gmod_subway_em508t.Buttons.Main.DIPonSet": "KU4: 실내 조명 켜기",
  "Entities.gmod_subway_em508t.Buttons.Main.DIPoffSet": "KU5: 실내 조명 끄기",
  "Entities.gmod_subway_em508t.Buttons.Main.RezMKSet": "Switch: 공기 압축기 강제 기동",
  "Entities.gmod_subway_em508t.Buttons.Main.KDPSet": "KDP: 우측 출입문 열림",
  "Entities.gmod_subway_em508t.Buttons.Main.KRZDSet": "KU10: 출입문 강제 닫힘",
  "Entities.gmod_subway_em508t.Buttons.AVMain.AV8BToggle": "AV-8B: 자동 스위치 (고전압)",
  "Entities.gmod_subway_em508t.Buttons.VU.VUToggle": "VU: 차량 제어 활성화",
  "Entities.gmod_subway_em508t.Buttons.VU.!Voltage": "제어 회로 전압",
  "Entities.gmod_subway_em508t.Buttons.HelperPanel.VUD2Toggle": "VUD2: 출입문 제어 스위치 (출입문 닫힘)",
  "Entities.gmod_subway_em508t.Buttons.HelperPanel.VDLSet": "VDL: 좌측 출입문 열림",
  "Entities.gmod_subway_em508t.Buttons.DriverValveBLTLDisconnect.DriverValveBLDisconnectToggle": "제동관 차단 밸브",
  "Entities.gmod_subway_em508t.Buttons.DriverValveBLTLDisconnect.DriverValveTLDisconnectToggle": "주 공기관 차단 밸브",
  "Entities.gmod_subway_em508t.Buttons.AirDistributor.AirDistributorDisconnectToggle": "공압 제어기 비활성"
}
]]
