return [[
{
  "Lang": "kr",
  "Name": "Korean",

  "Entities.gmod_subway_81-717_mvm.Buttons.HelperPanel.VUD2Toggle": "VUD2: 출입문 제어 스위치 (출입문 닫힘)",
  "Entities.gmod_subway_81-717_mvm.Buttons.HelperPanel.VDLSet": "VDL: 좌측 출입문 열림",
  "Entities.gmod_subway_81-717_mvm.Buttons.HelperPanel.R_Program2Helper": "안내방송 2",
  "Entities.gmod_subway_81-717_mvm.Buttons.HelperPanel.R_Program1Helper": "안내방송 1",
  "Entities.gmod_subway_81-717_mvm.Buttons.Battery_2.1:RC1Toggle": "RC-1: ARS 회로 차단",
  "Entities.gmod_subway_81-717_mvm.Buttons.Battery_2.1:VBToggle": "VB: 배터리 투입/차단",
  "Entities.gmod_subway_81-717_mvm.Buttons.Battery_2.1:UOSToggle": "RC-UOS: 속도 제한 장치",
  "Entities.gmod_subway_81-717_mvm.Buttons.Wiper.WiperToggle": "와이퍼",
  "Entities.gmod_subway_81-717_mvm.Buttons.DriverValveDisconnect.DriverValveDisconnectToggle": "직통관 차단 밸브",
  "Entities.gmod_subway_81-717_mvm.Buttons.DriverValveDisconnect.DriverValveBLDisconnectToggle": "제동관 차단 밸브",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.R_UNchToggle": "UNCh: 저주파 증폭기",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.R_ZSToggle": "ZS: 객실 내부 방송 재생",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.R_GToggle": "스피커: 운전실 내부 방송 재생",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.R_RadioToggle": "안내방송기 전원 (내장)",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.R_Program1Set": "안내방송 1",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.R_Program2Set": "안내방송 2",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.2:KVTSet": "KB: 확인 버튼",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.VZ1Set": "VZ1: 공압 밸브 #1",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.VUD1Toggle": "VUD: 출입문 제어 스위치 (출입문 닫힘)",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.KDLSet": "KDL: 좌측 출입문 열림",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.KDLKToggle": "KDL 버튼 커버",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.KDLRSet": "KDL: 좌측 출입문 열림",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.KDLRKToggle": "KDL 버튼 커버",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.DoorSelectToggle": "출입문 방향 선택",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.KRZDSet": "RZD: 출입문 강제 닫힘",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.R_VPRToggle": "VPR: 무선국 활성화",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.VozvratRPSet": "과전류 계전기 리셋",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.GreenRPLight": "RP: 과전류 계전기 확인등(녹색) (추진장치 과전류 방지)",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.AVULight": "AVU: 자동 제어 해제기 활성화",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.LKVPLight": "LKVP: 고전압 변류기 제어",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.SPLight": "LSP: 화재 경고 (가변 저항 과열)",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.ConverterProtectionSet": "변류기 보호",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.KSNSet": "KSN: 고장 확인 버튼",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.DIPoffSet": "부저",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.ARSToggle": "ARS: 자동 속도 제한",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.ALSToggle": "ALS: 자동 차량 신호 제어",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.OtklAVUToggle": "자동 제어 해제기 비활성화 (AVU 고장)",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.TormATToggle": "(기능 없음) 비상 제동 투입",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.L_1Toggle": "객실 조명",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.L_2Toggle": "운전석 조명",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.L_3Toggle": "운전대 조명",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.ALSFreqToggle": "디코더: ALS 주파수 절환 1/5 또는 2/6",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.ParkingBrakeSignToggle": "표지 \"주차 제동 완해\"",
  "Entities.gmod_subway_81-717_mvm.Buttons.ParkingBrake.ParkingBrakeToggle": "주차 제동",
  "Entities.gmod_subway_81-717_mvm.Buttons.ParkingBrake.DriverValveTLDisconnectToggle": "주 공기관 차단 밸브",
  "Entities.gmod_subway_81-717_mvm.Buttons.IGLAButtons.IGLA1Set": "IGLA: 버튼 1",
  "Entities.gmod_subway_81-717_mvm.Buttons.IGLAButtons.IGLA2Set": "IGLA: 버튼 2",
  "Entities.gmod_subway_81-717_mvm.Buttons.IGLAButtons.IGLA3Set": "IGLA: 버튼 3",
  "Entities.gmod_subway_81-717_mvm.Buttons.IGLAButtons.IGLA4Set": "IGLA: 버튼 4",
  "Entities.gmod_subway_81-717_mvm.Buttons.BPSNFront.!Voltage": "제어 회로 전압",
  "Entities.gmod_subway_81-717_mvm.Buttons.BPSNFront.VMKToggle": "공기 압축기 기동",
  "Entities.gmod_subway_81-717_mvm.Buttons.BPSNFront.BPSNonToggle": "BPSN: 차량 전원 공급 장치",
  "Entities.gmod_subway_81-717_mvm.Buttons.BPSNFront.RezMKSet": "공기 압축기 강제 기동",
  "Entities.gmod_subway_81-717_mvm.Buttons.BPSNFront.ARS13Set": "ARS 13V: ARS 전압 안정 검사",
  "Entities.gmod_subway_81-717_mvm.Buttons.Schedule.!RouteNum": "М №\n열번",
  "Entities.gmod_subway_81-717_mvm.Buttons.Schedule.!PathNum": "П №\n경로 번호",
  "Entities.gmod_subway_81-717_mvm.Buttons.Schedule.!SchTime": "ВРЕМЯ ХОДА\n총 운행 시간",
  "Entities.gmod_subway_81-717_mvm.Buttons.Schedule.!SchInterval": "ИНТ\n배차 간격",
  "Entities.gmod_subway_81-717_mvm.Buttons.Schedule.!SchHour": "ЧАС\n시",
  "Entities.gmod_subway_81-717_mvm.Buttons.Schedule.!SchMin": "МИН\n분",
  "Entities.gmod_subway_81-717_mvm.Buttons.Schedule.!SchSec": "СЕК\n초",
  "Entities.gmod_subway_81-717_mvm.Buttons.Schedule.!SchArrival": "도착 시각",
  "Entities.gmod_subway_81-717_mvm.Buttons.Schedule.!SchStations": "역명",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!Speedometer": "속도계",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!LampLSN": "LSN: 고장 표시등 (전원 회로 연결 실패)",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!LampRP": "RP: 과전류 계전기 확인등 (적색) (전원 회로 연결 실패)",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!LampLHRK": "LhRK: 가변저항 제어기 동작 확인등",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!LampLKT": "LKT: ARS 제동 표시등",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!LampLKVD": "LKVD: ARS 추진장치 정지 표시등",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!LampLKVC": "LKVC: 고전압 집전 불가",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!ARSOch": "OCh: ARS 신호 없음",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!ARS0": "0: ARS 정지 신호",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!ARS40": "속도 제한 40 kph",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!ARS60": "속도 제한 60 kph",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!ARS70": "속도 제한 70 kph",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!ARS80": "속도 제한 80 kph",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!LampLSD1": "LSD: 출입문 닫힘 확인등",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!LampLSD2": "LSD: 출입문 닫힘 확인등",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!LampLST": "LST: 제동 작동",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!LampLVD": "LVD: 추진장치 작동",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!LampLN": "LN: 방향 신호",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!LampLRS": "LRS: 속도 유지등",
  "Entities.gmod_subway_81-717_mvm.Buttons.PneumaticPanels.!CylinderPressure": "제동통 압력",
  "Entities.gmod_subway_81-717_mvm.Buttons.PneumaticPanels.!LinePressure": "공기관 압력 (적색: 제동관 압력, 흑색: 주 공기관 압력)",
  "Entities.gmod_subway_81-717_mvm.Buttons.Battery.RC1Toggle": "RC-1: ARS 회로 차단",
  "Entities.gmod_subway_81-717_mvm.Buttons.Battery.UOSToggle": "RC-UOS: 속도 제한 장치",
  "Entities.gmod_subway_81-717_mvm.Buttons.Battery.VBToggle": "VB: 배터리 투입/차단",
  "Entities.gmod_subway_81-717_mvm.Buttons.FrontPneumatic.FrontBrakeLineIsolationToggle": "제동관 해방 밸브",
  "Entities.gmod_subway_81-717_mvm.Buttons.FrontPneumatic.FrontTrainLineIsolationToggle": "주 공기관 해방 밸브",
  "Entities.gmod_subway_81-717_mvm.Buttons.ASNP.R_ASNPMenuSet": "ASNP: 메뉴",
  "Entities.gmod_subway_81-717_mvm.Buttons.ASNP.R_ASNPUpSet": "ASNP: 위",
  "Entities.gmod_subway_81-717_mvm.Buttons.ASNP.R_ASNPDownSet": "ASNP: 아래",
  "Entities.gmod_subway_81-717_mvm.Buttons.ASNP.R_ASNPOnToggle": "ASNP: 켜기",
  "Entities.gmod_subway_81-717_mvm.Buttons.RearDoor.RearDoor": "관통문(뒤)",
  "Entities.gmod_subway_81-717_mvm.Buttons.Meters.!TotalVoltmeter": "HV 전압계 (kV)",
  "Entities.gmod_subway_81-717_mvm.Buttons.Meters.!TotalAmpermeter": "총 전류계 (A)",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A61Toggle": "A61 차량 회로 6 제어",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A55Toggle": "A55 차량 회로 10AS 제어",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A54Toggle": "A54 차량 회로 10AK 제어",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A56Toggle": "A56 제어 회로용 배터리 전원 투입",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A27Toggle": "A27 DIP 기동/점등",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A21Toggle": "A21 출입문 제어",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A10Toggle": "A10 공기 압축기 제어",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A53Toggle": "A53 KVC 전원 공급",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A43Toggle": "A43 ARS 12V 전원 공급",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A45Toggle": "A45 ARS 차량 회로 10AU",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A42Toggle": "A42 ARS 75V 전원 공급",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A41Toggle": "A41 ARS 제동",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.VUToggle": "VU 차량 제어",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A64Toggle": "A64 운전실 조명",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A63Toggle": "A63 IGLA/BIS",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A50Toggle": "A50 부수 객차 DIP 기동/점등",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A51Toggle": "A51 DIP 차단/소등",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A23Toggle": "A23 공기 압축기 강제 기동",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A14Toggle": "A14 차량 회로 18",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A75Toggle": "A75 운전실 난방",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A1Toggle": "A1  X-1",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A2Toggle": "A2  X-2",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A3Toggle": "A3  X-3",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A17Toggle": "A17 과전류 계전기 리셋",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A62Toggle": "A62 무선 통신",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A29Toggle": "A29 무선 방송",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A5Toggle": "A5 부수 객차",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A6Toggle": "A6  T-1",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A8Toggle": "A8  공압 밸브 #1, #2",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A20Toggle": "A20 운전/제동 회로 제어, 차량 회로 20",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A25Toggle": "A25 수동 전기 제동",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A22Toggle": "A22 부수 객차 공기 압축기 접촉기 제어",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A30Toggle": "A30 가변 저항 제어기 모터 전원",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A39Toggle": "A39 비상 제어",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A44Toggle": "A44 차량 비상 제어",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A80Toggle": "A80 전원 회로 스위치 모터 전원",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A65Toggle": "A65 실내 조명",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.L_5Toggle": "А49 비상등",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A24Toggle": "A24 배터리 충전",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A32Toggle": "A32 우측 출입문 열림",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A31Toggle": "A31 좌측 출입문 열림",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A16Toggle": "A16 출입문 닫힘",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A13Toggle": "A13 출입문 알람",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A12Toggle": "A12 출입문 강제 닫힘",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A7Toggle": "A7  적색등",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A9Toggle": "A9  적색등",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A46Toggle": "A46 백색등",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A47Toggle": "A47 백색등",
  "Entities.gmod_subway_81-717_mvm.Buttons.PassengerDoor.PassengerDoor": "객실문",
  "Entities.gmod_subway_81-717_mvm.Buttons.GV.GVToggle": "고전압 스위치",
  "Entities.gmod_subway_81-717_mvm.Buttons.Stopkran.EmergencyBrakeValveToggle": "비상 제동",
  "Entities.gmod_subway_81-717_mvm.Buttons.InfoTableSelect.PrevSign": "이전 방향막",
  "Entities.gmod_subway_81-717_mvm.Buttons.InfoTableSelect.NextSign": "다음 방향막",
  "Entities.gmod_subway_81-717_mvm.Buttons.InfoTableSelect.Num2P": "열번: 십의 자리 증가",
  "Entities.gmod_subway_81-717_mvm.Buttons.InfoTableSelect.Num2M": "열번: 십의 자리 감소",
  "Entities.gmod_subway_81-717_mvm.Buttons.InfoTableSelect.Num1P": "열번: 일의 자리 증가",
  "Entities.gmod_subway_81-717_mvm.Buttons.InfoTableSelect.Num1M": "열번: 일의 자리 감소",
  "Entities.gmod_subway_81-717_mvm.Buttons.Front.L_4Toggle": "헤드라이드 점등",
  "Entities.gmod_subway_81-717_mvm.Buttons.Front.VUSToggle": "VUS: 헤드라이트 상향",
  "Entities.gmod_subway_81-717_mvm.Buttons.Front.VAHToggle": "VAH: 비상 운전 모드 (RPB 계전기 고장)",
  "Entities.gmod_subway_81-717_mvm.Buttons.Front.VADToggle": "VAD: 출입문 강제 닫힘 무시 (KD 계전기 고장)",
  "Entities.gmod_subway_81-717_mvm.Buttons.Front.KRPSet": "KRP: 비상 기동 버튼",
  "Entities.gmod_subway_81-717_mvm.Buttons.Front.KAHSet": "비상 운전 버튼",
  "Entities.gmod_subway_81-717_mvm.Buttons.Front.KAHKToggle": "KAH 버튼 커버",
  "Entities.gmod_subway_81-717_mvm.Buttons.Front.KUP": "운전실 난방 작동",
  "Entities.gmod_subway_81-717_mvm.Buttons.Front.KDPSet": "KDP: 우측 출입문 열림",
  "Entities.gmod_subway_81-717_mvm.Buttons.Front.KDPKToggle": "KDP 버튼 커버",
  "Entities.gmod_subway_81-717_mvm.Buttons.Front.PN": "공압 제동 제어",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A61Toggle": "A61 차량 회로 6 제어",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A55Toggle": "A55 차량 회로 10AS 제어",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A54Toggle": "A54 차량 회로 10AK 제어",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A56Toggle": "A56 제어 회로용 배터리 전원 투입",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A27Toggle": "A27 DIP 기동/점등",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A21Toggle": "A21 출입문 제어",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A10Toggle": "A10 공기 압축기 제어",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A53Toggle": "A53 KVC 전원 공급",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A43Toggle": "A43 ARS 12V 전원 공급",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A45Toggle": "A45 ARS 차량 회로 10AU",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A42Toggle": "A42 ARS 75V 전원 공급",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A41Toggle": "A41 ARS 제동",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:VUToggle": "VU 차량 제어",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A64Toggle": "A64 운전실 조명",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A63Toggle": "A63 IGLA/BIS",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A50Toggle": "A50 부수 객차 DIP 기동/점등",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A51Toggle": "A51 DIP 차단/소등",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A23Toggle": "A23 공기 압축기 강제 기동",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A14Toggle": "A14 차량 회로 18",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A75Toggle": "A75 운전실 난방",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A1Toggle": "A1  X-1",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A2Toggle": "A2  X-2",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A3Toggle": "A3  X-3",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A17Toggle": "A17 과전류 계전기 리셋",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A62Toggle": "A62 무선 통신",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A29Toggle": "A29 무선 방송",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A5Toggle": "A5 부수 객차",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A6Toggle": "A6  T-1",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A8Toggle": "A8  공압 밸브 #1, #2",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A20Toggle": "A20 운전/제동 회로 제어, 차량 회로 20",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A25Toggle": "A25 수동 전기 제동",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A22Toggle": "A22 부수 객차 공기 압축기 접촉기 제어",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A30Toggle": "A30 가변 저항 제어기 모터 전원",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A39Toggle": "A39 비상 제어",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A44Toggle": "A44 차량 비상 제어",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A80Toggle": "A80 전원 회로 스위치 모터 전원",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A65Toggle": "A65 실내 조명",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:L_5Toggle": "А49 비상등",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A24Toggle": "A24 배터리 충전",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A32Toggle": "A32 우측 출입문 열림",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A31Toggle": "A31 좌측 출입문 열림",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A16Toggle": "A16 출입문 닫힘",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A13Toggle": "A13 출입문 알람",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A12Toggle": "A12 출입문 강제 닫힘",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A7Toggle": "A7  적색등",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A9Toggle": "A9  적색등",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A46Toggle": "A46 백색등",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A47Toggle": "A47 백색등",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!Speedometer": "속도계",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!LSD": "LSD: 출입문 닫힘 확인등",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!LOCh": "NCh: ARS 신호 없음",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!L0": "0: ARS 정지 신호",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!LRS": "LRS: 속도 유지등",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!L40": "속도 제한 40 kph",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!L60": "속도 제한 60 kph",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!L80": "속도 제한 80 kph",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!L70": "속도 제한 60 kph",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!LRK": "RK: 가변저항 제어기 동작 확인등",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!LEKK": "",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!LPU": "",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!LKVD": "LKVD: ARS 추진장치 정지 표시등",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!LKT": "LKT: ARS 제동 표시등",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!LRP": "RP: 과전류 계전기 확인등 (적색) (전원 회로 연결 실패)",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!LKVC": "LKVC: 고전압 집전 불가",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!LVD": "LVD: 추진장치 작동",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!LST": "LST: 제동 작동",
  "Entities.gmod_subway_81-717_mvm.Buttons.CabinDoor.CabinDoor": "운전실문",
  "Entities.gmod_subway_81-717_mvm.Buttons.Reverser.KVReverserDown": "역전간 후퇴",
  "Entities.gmod_subway_81-717_mvm.Buttons.Reverser.KVReverserUp": "역전간 전진",
  "Entities.gmod_subway_81-717_mvm.Buttons.PassengerDoor1.PassengerDoor": "객실문",
  "Entities.gmod_subway_81-717_mvm.Buttons.UAVAPanel.UAVAToggle": "UAVA: 범용 자동 정지 장치 비활성 (자동 정지 비활성)",
  "Entities.gmod_subway_81-717_mvm.Buttons.UAVAPanel.UAVAContactSet": "UAVA: 범용 자동 정지 장치 비활성 (복귀)",
  "Entities.gmod_subway_81-717_mvm.Buttons.EPKDisconnect.EPKToggle": "EPV 차단 밸브",
  "Entities.gmod_subway_81-717_mvm.Buttons.Help.ShowHelp": "열차 운전 도움말 보기",
  "Entities.gmod_subway_81-717_mvm.Buttons.ParkingBrake2.1:ParkingBrakeToggle": "주차 제동",
  "Entities.gmod_subway_81-717_mvm.Buttons.RearPneumatic.RearBrakeLineIsolationToggle": "제동관 해방 밸브",
  "Entities.gmod_subway_81-717_mvm.Buttons.RearPneumatic.RearTrainLineIsolationToggle": "주 공기관 해방 밸브",
  "Entities.gmod_subway_81-717_mvm.Buttons.AirDistributor.AirDistributorDisconnectToggle": "공압 제어기 비활성",

  "Entities.gmod_subway_81-714_mvm.Buttons.GV.GVToggle": "고전압 스위치",
  "Entities.gmod_subway_81-714_mvm.Buttons.RearPneumatic.RearBrakeLineIsolationToggle": "제동관 해방 밸브",
  "Entities.gmod_subway_81-714_mvm.Buttons.RearPneumatic.RearTrainLineIsolationToggle": "주 공기관 해방 밸브",
  "Entities.gmod_subway_81-714_mvm.Buttons.RearDoor.RearDoor": "관통문(뒤)",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Left.DriverValveBLDisconnectToggle": "제동관 차단 밸브",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Left.DriverValveTLDisconnectToggle": "주 공기관 차단 밸브",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Left.A65Toggle": "A65 실내 조명",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Left.A56Toggle": "A56 제어 회로용 배터리 전원 투입",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Left.A63Toggle": "A63 IGLA/BIS",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Left.A10Toggle": "A10 공기 압축기 제어",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Left.A30Toggle": "A30 가변 저항 제어기 모터 전원",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Left.A80Toggle": "A80 전원 회로 스위치 모터 전원",
  "Entities.gmod_subway_81-714_mvm.Buttons.FrontPneumatic.FrontBrakeLineIsolationToggle": "제동관 해방 밸브",
  "Entities.gmod_subway_81-714_mvm.Buttons.FrontPneumatic.FrontTrainLineIsolationToggle": "주 공기관 해방 밸브",
  "Entities.gmod_subway_81-714_mvm.Buttons.FrontPneumatic.ParkingBrakeToggle": "주차 제동",
  "Entities.gmod_subway_81-714_mvm.Buttons.AirDistributor.AirDistributorDisconnectToggle": "공압 제어기 비활성",
  "Entities.gmod_subway_81-714_mvm.Buttons.FrontDoor.FrontDoor": "관통문(앞)",
  "Entities.gmod_subway_81-714_mvm.Buttons.Battery.VBToggle": "VB: 배터리 투입/차단",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A54Toggle": "A54 차량 회로 10AK 제어",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A27Toggle": "A27 DIP 기동/점등",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A24Toggle": "A24 배터리 충전",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A53Toggle": "A53 KVC 전원 공급",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A13Toggle": "A13 출입문 알람",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A32Toggle": "A32 우측 출입문 열림",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A31Toggle": "A31 좌측 출입문 열림",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A16Toggle": "A16 출입문 닫힘",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A12Toggle": "A12 출입문 강제 닫힘",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A50Toggle": "A50 부수 객차 DIP 기동/점등",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A51Toggle": "A51 DIP 차단/소등",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A1Toggle": "A1  X-1",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.KRPSet": "START: 비상 기동 버튼",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.VozvratRPSet": "과전류 계전기 리셋",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.RezMKSet": "공기 압축기 강제 기동",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.VMKToggle": "공기 압축기 기동",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.BPSNonToggle": "BPSN: 차량 전원 공급 장치",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A2Toggle": "A2  X-2",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A3Toggle": "A3  X-3",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A17Toggle": "A17 과전류 계전기 리셋",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A5Toggle": "A5  ",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A6Toggle": "A6  T-1",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A8Toggle": "A8  공압 밸브 #1, #2",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A20Toggle": "A20 운전/제동 회로 제어, 차량 회로 20",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A25Toggle": "A25 수동 전기 제동",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A22Toggle": "A22 부수 객차 공기 압축기 접촉기 제어",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A23Toggle": "A23 공기 압축기 강제 기동",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A39Toggle": "A39 비상 제어",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A14Toggle": "A14 차량 회로 18"
}
]]
