return [[
{
  "Lang": "kr",
  "Name": "Korean",

  "Entities.gmod_subway_81-720.Buttons.VityazButtons.VityazF1Set": "Vityaz: F1",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.VityazF2Set": "Vityaz: 다음 화면",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.VityazF3Set": "Vityaz: 이전 화면",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.VityazF4Set": "Vityaz: 메인",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.Vityaz1Set": "Vityaz: 1",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.Vityaz4Set": "Vityaz: 4",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.Vityaz7Set": "Vityaz: 7",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.Vityaz2Set": "Vityaz: 2",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.Vityaz5Set": "Vityaz: 5",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.Vityaz8Set": "Vityaz: 8",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.Vityaz0Set": "Vityaz: 0",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.Vityaz3Set": "Vityaz: 3",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.Vityaz6Set": "Vityaz: 6",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.Vityaz9Set": "Vityaz: 9",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.VityazF5Set": "Vityaz: 삭제",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.VityazF6Set": "Vityaz: 위\\속도",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.VityazF7Set": "Vityaz: 아래\\전류",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.VityazF8Set": "Vityaz: 입력\\객차별 상태",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.VityazF9Set": "Vityaz: 선택\\객차별 상태 제어",
  "Entities.gmod_subway_81-720.Buttons.RV.EmerX1Set": "비상 X-1",
  "Entities.gmod_subway_81-720.Buttons.RV.EmerX2Set": "비상 X-2",
  "Entities.gmod_subway_81-720.Buttons.RV.EmerCloseDoorsSet": "출입문 강제 닫힘",
  "Entities.gmod_subway_81-720.Buttons.RV.EmergencyDoorsToggle": "비상문",
  "Entities.gmod_subway_81-720.Buttons.BackVent.VentCondMode-": "냉난방기 운전 모드: +",
  "Entities.gmod_subway_81-720.Buttons.BackVent.VentCondMode+": "냉난방기 운전 모드: -",
  "Entities.gmod_subway_81-720.Buttons.BackVent.VentHeatMode+": "+",
  "Entities.gmod_subway_81-720.Buttons.BackVent.VentHeatMode-": "-",
  "Entities.gmod_subway_81-720.Buttons.BackVent.VentStrengthMode-": "냉난방 세기: +",
  "Entities.gmod_subway_81-720.Buttons.BackVent.VentStrengthMode+": "냉난방 세기: -",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV1Toggle": "SF1: 제어 회로 전원",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV2Toggle": "SF2: BUV 전원 (객차 제어 유닛)",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV3Toggle": "SF3: BUTP 전원 (추진장치 제어 유닛)",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV4Toggle": "SF4: BUTP 제어",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV5Toggle": "SF5: BUTP 비상 제어",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV6Toggle": "SF6: BUTP 전원",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV7Toggle": "SF7: BBE (내부 전원 공급 유닛)",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV8Toggle": "SF8: BV 제어",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV9Toggle": "SF9: BV 전원 (계전기 과부하)",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV10Toggle": "SF10: PPO",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV11Toggle": "SF11: 공기 압축기",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV12Toggle": "SF12: 출입문 닫힘",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV13Toggle": "SF13: 좌측 출입문 열림",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV14Toggle": "SF14: 우측 출입문 열림",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV15Toggle": "SF15: 관통문 잠금",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV16Toggle": "SF16: 안내방송기",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV17Toggle": "SF17: 비상 통화 장치",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV18Toggle": "SF18: (기능 없음)",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV19Toggle": "SF19: 객실 조명 전원",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV20Toggle": "SF20: 객실 비상 조명 전원",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV21Toggle": "SF21: 속도 센서",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV22Toggle": "SF22: 비상 제동",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV23Toggle": "SF23: 냉난방기 1번 그룹 제어",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV24Toggle": "SF24: 냉난방기 2번 그룹 제어",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV25Toggle": "SF25: 냉난방기 1번 그룹 전원",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV26Toggle": "SF26: 냉난방기 2번 그룹 전원",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV27Toggle": "SF27: 제동 유도기 전원",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV28Toggle": "SF28: ZKK 전원",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV29Toggle": "SF29: 집전기",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV30Toggle": "SF30: 노선도 & 안내기",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV31Toggle": "SF31: (기능 없음)",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV32Toggle": "SF32: (기능 없음)",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV33Toggle": "SF33: (기능 없음)",
  "Entities.gmod_subway_81-720.Buttons.ASNP.R_ASNPMenuSet": "ASNP: 메뉴",
  "Entities.gmod_subway_81-720.Buttons.ASNP.R_ASNPUpSet": "ASNP: 위",
  "Entities.gmod_subway_81-720.Buttons.ASNP.R_ASNPDownSet": "ASNP: 아래",
  "Entities.gmod_subway_81-720.Buttons.ASNP.R_ASNPOnToggle": "ASNP: 전원",
  "Entities.gmod_subway_81-720.Buttons.PneumoHelper1.!BrakeCylinder": "제동관",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF1Toggle": "SF1: 주 전원",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF2Toggle": "SF2: 주 제어",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF3Toggle": "SF3: 비상 제어",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF4Toggle": "SF4: BARS (ARS 유닛)",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF5Toggle": "SF5: BUP (차량 제어 유닛)",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF6Toggle": "SF6: BKCU (제어 회로 정류 유닛)",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF7Toggle": "SF7: BARS (ARS 유닛)",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF8Toggle": "SF8: 안내방송기",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF9Toggle": "SF9: 무선국",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF10Toggle": "SF10: 객차 방향",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF11Toggle": "SF11: 진행 방향",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF12Toggle": "SF12: 전조등 1번 그룹",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF13Toggle": "SF13: 전조등 2번 그룹",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF14Toggle": "SF14: 마커등",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF15Toggle": "SF15: 운전실 조명",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF16Toggle": "SF16: 난방기",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF17Toggle": "SF17: 운전실 에어컨",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF18Toggle": "SF18: 살사 장치",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF19Toggle": "SF19: 주 KRM 전원 (직통관)",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF20Toggle": "SF20: 비상 KRM 전원 (직통관)",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF21Toggle": "SF21: 출입문 열림",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF22Toggle": "SF22: 출입문 닫힘",
  "Entities.gmod_subway_81-720.Buttons.BTO.K29Toggle": "KRMSH (직통관 차단 밸브)",
  "Entities.gmod_subway_81-720.Buttons.PassengerDoor2.PassengerDoor": "객실문",
  "Entities.gmod_subway_81-720.Buttons.VoltHelper2.!HV": "총 전압계 (kV)",
  "Entities.gmod_subway_81-720.Buttons.VoltHelper2.!I1_3": "추진장치 1번 그룹 전류 (A)",
  "Entities.gmod_subway_81-720.Buttons.VoltHelper2.!I2_4": "추진장치 2번 그룹 전류 (A)",
  "Entities.gmod_subway_81-720.Buttons.GV.GVToggle": "고전압 스위치",
  "Entities.gmod_subway_81-720.Buttons.RearPneumatic.RearBrakeLineIsolationToggle": "제동관 차단 밸브",
  "Entities.gmod_subway_81-720.Buttons.RearPneumatic.RearTrainLineIsolationToggle": "주 공기관 차단 밸브",
  "Entities.gmod_subway_81-720.Buttons.RearDoor1.RearDoor": "관통문(뒤)",
  "Entities.gmod_subway_81-720.Buttons.RearDoor.RearDoor": "관통문(뒤)",
  "Entities.gmod_subway_81-720.Buttons.BackDown.Pant1Toggle": "집전기 1번 그룹 비활성",
  "Entities.gmod_subway_81-720.Buttons.BackDown.Pant2Toggle": "집전기 2번 그룹 비활성",
  "Entities.gmod_subway_81-720.Buttons.BackDown.Vent1Toggle": "환풍기 1번 그룹",
  "Entities.gmod_subway_81-720.Buttons.BackDown.Vent2Toggle": "환풍기 2번 그룹",
  "Entities.gmod_subway_81-720.Buttons.BackDown.VentToggle": "",
  "Entities.gmod_subway_81-720.Buttons.BackDown.PassLightToggle": "객실 조명",
  "Entities.gmod_subway_81-720.Buttons.BackDown.CabLightToggle": "운전실 조명",
  "Entities.gmod_subway_81-720.Buttons.BackDown.Headlights1Toggle": "전조등 1번 그룹",
  "Entities.gmod_subway_81-720.Buttons.BackDown.Headlights2Toggle": "전조등 2번 그룹",
  "Entities.gmod_subway_81-720.Buttons.BackDown.ParkingBrakeToggle": "주차 제동",
  "Entities.gmod_subway_81-720.Buttons.BackDown.TorecDoorsToggle": "관통문 잠금",
  "Entities.gmod_subway_81-720.Buttons.BackDown.BBERToggle": "비상 BBE 기동",
  "Entities.gmod_subway_81-720.Buttons.BackDown.BBEToggle": "BBE (내부 전원 공급 유닛)",
  "Entities.gmod_subway_81-720.Buttons.BackDown.CompressorToggle": "공기 압축기",
  "Entities.gmod_subway_81-720.Buttons.BackDown.CabLightStrengthToggle": "운전실 조명 전원",
  "Entities.gmod_subway_81-720.Buttons.BackDown.AppLights1Toggle": "객실 조명 장치",
  "Entities.gmod_subway_81-720.Buttons.BackDown.AppLights2Toggle": "",
  "Entities.gmod_subway_81-720.Buttons.BackDown.BARSBlock-": "BARS 고장 (ARS 유닛) 차단: -",
  "Entities.gmod_subway_81-720.Buttons.BackDown.BARSBlock+": "BARS 고장 (ARS 유닛) 차단: +",
  "Entities.gmod_subway_81-720.Buttons.BackDown.BatteryToggle": "배터리 투입/차단",
  "Entities.gmod_subway_81-720.Buttons.BackDown.ALSFreqToggle": "ALS 디코더",
  "Entities.gmod_subway_81-720.Buttons.VoltHelper1.!Battery": "제어 회로 전압",
  "Entities.gmod_subway_81-720.Buttons.PassengerDoor.PassengerDoor": "객실문",
  "Entities.gmod_subway_81-720.Buttons.CabinDoorR.CabinDoorRight": "운전실문",
  "Entities.gmod_subway_81-720.Buttons.CabinDoorL.CabinDoorLeft": "운전실문",
  "Entities.gmod_subway_81-720.Buttons.FrontPneumatic.FrontBrakeLineIsolationToggle": "제동관 해방 밸브",
  "Entities.gmod_subway_81-720.Buttons.FrontPneumatic.FrontTrainLineIsolationToggle": "주 공기관 해방 밸브",
  "Entities.gmod_subway_81-720.Buttons.PUL.DoorSelectLToggle": "좌측 출입문 선택",
  "Entities.gmod_subway_81-720.Buttons.PUL.DoorSelectRToggle": "우측 출입문 선택",
  "Entities.gmod_subway_81-720.Buttons.PUL.DoorBlockToggle": "출입문 제어 스위치",
  "Entities.gmod_subway_81-720.Buttons.PUL.!DoorLeftLamp": "좌측 출입문 버튼 작동",
  "Entities.gmod_subway_81-720.Buttons.PUL.DoorLeftSet": "좌측 출입문",
  "Entities.gmod_subway_81-720.Buttons.PUU.!DoorsClosed": "출입문 닫힘",
  "Entities.gmod_subway_81-720.Buttons.PUU.StandToggle": "유지",
  "Entities.gmod_subway_81-720.Buttons.PUU.TickerToggle": "안내기",
  "Entities.gmod_subway_81-720.Buttons.PUU.KAHToggle": "KAH",
  "Entities.gmod_subway_81-720.Buttons.PUU.ALSToggle": "ALS",
  "Entities.gmod_subway_81-720.Buttons.PUU.FDepotToggle": "기지 출고",
  "Entities.gmod_subway_81-720.Buttons.PUU.!HVoltage": "고전압 집전 불가",
  "Entities.gmod_subway_81-720.Buttons.PUU.PassSchemeToggle": "노선도",
  "Entities.gmod_subway_81-720.Buttons.PUU.EmergencyCompressorSet": "비상 공기 압축기",
  "Entities.gmod_subway_81-720.Buttons.PUU.EnableBVSet": "보호기 작동 (계전기 과부하)",
  "Entities.gmod_subway_81-720.Buttons.PUU.DisableBVSet": "BV 차단 (계전기 과부하)",
  "Entities.gmod_subway_81-720.Buttons.PUU.RingSet": "부저",
  "Entities.gmod_subway_81-720.Buttons.PUU.R_Program2Set": "안내방송 2",
  "Entities.gmod_subway_81-720.Buttons.PUU.R_AnnouncerToggle": "안내방송기",
  "Entities.gmod_subway_81-720.Buttons.PUU.R_LineToggle": "노선",
  "Entities.gmod_subway_81-720.Buttons.PUU.R_EmerSet": "비상 통화 장치",
  "Entities.gmod_subway_81-720.Buttons.PUU.R_Program1Set": "안내방송 1",
  "Entities.gmod_subway_81-720.Buttons.PUU.EnableBVEmerSet": "비상 BV 복구",
  "Entities.gmod_subway_81-720.Buttons.PUU.EmergencyControlsToggle": "비상 제어",
  "Entities.gmod_subway_81-720.Buttons.PUU.WiperToggle": "와이퍼",
  "Entities.gmod_subway_81-720.Buttons.PUU.!VDop": "제한 속도",
  "Entities.gmod_subway_81-720.Buttons.PUU.!VFact": "현재 속도",
  "Entities.gmod_subway_81-720.Buttons.PUU.!VPred": "제한 속도 예고",
  "Entities.gmod_subway_81-720.Buttons.PUU.!VDop2": "제한 속도",
  "Entities.gmod_subway_81-720.Buttons.PUU.!Acc": "가속",
  "Entities.gmod_subway_81-720.Buttons.PUU.!Forw": "전진",
  "Entities.gmod_subway_81-720.Buttons.PUU.!Back": "후진",
  "Entities.gmod_subway_81-720.Buttons.PUR.AccelRateToggle": "가속도",
  "Entities.gmod_subway_81-720.Buttons.PUR.EmerBrakeAddSet": "(보조) 제동",
  "Entities.gmod_subway_81-720.Buttons.PUR.EmerBrakeReleaseSet": "(보조) 완해",
  "Entities.gmod_subway_81-720.Buttons.PUR.EmerBrakeToggle": "보조 제동",
  "Entities.gmod_subway_81-720.Buttons.PUR.EmergencyBrakeToggle": "비상 제동",
  "Entities.gmod_subway_81-720.Buttons.PUR.DoorCloseToggle": "출입문 닫힘",
  "Entities.gmod_subway_81-720.Buttons.PUR.AttentionMessageSet": "메세지 확인",
  "Entities.gmod_subway_81-720.Buttons.PUR.AttentionSet": "확인",
  "Entities.gmod_subway_81-720.Buttons.PUR.AttentionBrakeSet": "제동 확인",
  "Entities.gmod_subway_81-720.Buttons.PUR.HornBSet": "경적",
  "Entities.gmod_subway_81-720.Buttons.PUR.DoorRightSet": "우측 출입문",
  "Entities.gmod_subway_81-720.Buttons.PUR.!DoorRightLamp": "우측 출입문 버튼 동작",
  "Entities.gmod_subway_81-720.Buttons.PneumoHelper2.!BrakeTrainLine": "적색: 제동관 압력, 흑색: 주 공기관 압력",

  "Entities.gmod_subway_81-721.Buttons.GV.GVToggle": "고전압 스위치",
  "Entities.gmod_subway_81-721.Buttons.RearPneumatic.RearBrakeLineIsolationToggle": "제동관 해방 밸브",
  "Entities.gmod_subway_81-721.Buttons.RearPneumatic.RearTrainLineIsolationToggle": "주 공기관 해방 밸브",
  "Entities.gmod_subway_81-721.Buttons.FrontDoor.FrontDoor": "관통문(앞)",
  "Entities.gmod_subway_81-721.Buttons.RearDoor.RearDoor": "관통문(뒤)",
  "Entities.gmod_subway_81-721.Buttons.Battery.BatteryToggle": "배터리 투입/차단",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV1Toggle": "SF1: 제어 회로 전원",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV2Toggle": "SF2: BUV 전원 (객차 제어 유닛)",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV3Toggle": "SF3: BUTP 전원 (추진장치 제어 유닛)",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV4Toggle": "SF4: BUTP 제어",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV5Toggle": "SF5: BUTP 비상 제어",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV6Toggle": "SF6: BUTP 전원",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV7Toggle": "SF7: BBE (내부 전원 공급 유닛)",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV8Toggle": "SF8: BV 제어",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV9Toggle": "SF9: BV 전원 (계전기 과부하)",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV10Toggle": "SF10: PPO",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV11Toggle": "SF11: 공기 압축기",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV12Toggle": "SF12: 출입문 닫힘",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV13Toggle": "SF13: 좌측 출입문 열림",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV14Toggle": "SF14: 우측 출입문 열림",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV15Toggle": "SF15: 관통문 잠금",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV16Toggle": "SF16: 안내방송기",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV17Toggle": "SF17: 비상 통화 장치",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV18Toggle": "SF18: (기능 없음)",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV19Toggle": "SF19: 객실 조명 전원",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV20Toggle": "SF20: 객실 비상 조명 전원",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV21Toggle": "SF21: 속도 센서",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV22Toggle": "SF22: 주차 제동",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV23Toggle": "SF23: 냉난방기 1번 그룹 제어",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV24Toggle": "SF24: 냉난방기 2번 그룹 제어",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV25Toggle": "SF25: 냉난방기 1번 그룹 전원",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV26Toggle": "SF26: 냉난방기 2번 그룹 전원",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV27Toggle": "SF27: 제동 유도기 전원",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV28Toggle": "SF28: ZKK 전원",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV29Toggle": "SF29: 집전기",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV30Toggle": "SF30: 노선도 & 안내기",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV31Toggle": "SF31: (기능 없음)",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV32Toggle": "SF32: (기능 없음)",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV33Toggle": "SF33: (기능 없음)",
  "Entities.gmod_subway_81-721.Buttons.FrontPneumatic.FrontBrakeLineIsolationToggle": "제동관 해방 밸브",
  "Entities.gmod_subway_81-721.Buttons.FrontPneumatic.FrontTrainLineIsolationToggle": "주 공기관 해방 밸브"
}
]]
