return [[
{
	"Lang": "kr",
	"Name": "Korean",

	"Spawner.Title": "열차 스포너",
	"Spawner.Trains1": "현재 열차 수",
	"Spawner.Trains2": "최대 량수",
	"Spawner.WagNum": "차량 량수",
	"Spawner.AutoCouple": "객차 간 자동 연결",

	"Entities.gmod_subway_81-717_mvm.Spawner.Texture.Name": "도색",
	"Entities.gmod_subway_81-717_mvm.Spawner.PassTexture.Name": "객실 내장재",
	"Entities.gmod_subway_81-717_mvm.Spawner.CabTexture.Name": "운전대 재질",
	"Entities.gmod_subway_81-717_mvm.Spawner.Announcer.Name": "안내방송",
	"Entities.gmod_subway_81-717_mvm.Spawner.Lighter.Name": "라이터",
	"Entities.gmod_subway_81-717_mvm.Spawner.ARSType.Name": "ARS 패널 종류",
	"Entities.gmod_subway_81-717_mvm.Spawner.ARSType.1": "기본(사각형 램프)",
	"Entities.gmod_subway_81-717_mvm.Spawner.ARSType.2": "기본(원형 램프)",
	"Entities.gmod_subway_81-717_mvm.Spawner.ARSType.3": "키예프(Kiev)/SPB",
	"Entities.gmod_subway_81-717_mvm.Spawner.ARSType.4": "구형 ARS",
	"Entities.gmod_subway_81-717_mvm.Spawner.Cran.Name": "제동변 종류",
	"Entities.gmod_subway_81-717_mvm.Spawner.Cran.1": "334",
	"Entities.gmod_subway_81-717_mvm.Spawner.Cran.2": "013",
	"Entities.gmod_subway_81-717_mvm.Spawner.MaskType.Name": "전면부 종류",
	"Entities.gmod_subway_81-717_mvm.Spawner.MaskType.1": "2-2",
	"Entities.gmod_subway_81-717_mvm.Spawner.MaskType.2": "2-2-2",
	"Entities.gmod_subway_81-717_mvm.Spawner.MaskType.3": "1-4-1 범퍼 1",
	"Entities.gmod_subway_81-717_mvm.Spawner.MaskType.4": "1-4-1 범퍼 2",
	"Entities.gmod_subway_81-717_mvm.Spawner.MaskType.5": "1-1",
	"Entities.gmod_subway_81-717_mvm.Spawner.MaskType.6": "복고풍(Retro)",
	"Entities.gmod_subway_81-717_mvm.Spawner.LED.Name": "LED 전조등",
	"Entities.gmod_subway_81-717_mvm.Spawner.BPSNType.Name": "BPSN 종류",
	"Entities.gmod_subway_81-717_mvm.Spawner.BPSNType.1": "높은 톤의 구형 사운드",
	"Entities.gmod_subway_81-717_mvm.Spawner.BPSNType.2": "중간 톤의 구형 사운드",
	"Entities.gmod_subway_81-717_mvm.Spawner.BPSNType.3": "기본(SPB)",
	"Entities.gmod_subway_81-717_mvm.Spawner.BPSNType.4": "기본(TKL)",
	"Entities.gmod_subway_81-717_mvm.Spawner.BPSNType.5": "기본",
	"Entities.gmod_subway_81-717_mvm.Spawner.BPSNType.6": "키예프(Kiev)",
	"Entities.gmod_subway_81-717_mvm.Spawner.BPSNType.7": "구형",
	"Entities.gmod_subway_81-717_mvm.Spawner.BPSNType.8": "기본 2",
	"Entities.gmod_subway_81-717_mvm.Spawner.BPSNType.9": "기본 3",
	"Entities.gmod_subway_81-717_mvm.Spawner.BPSNType.10": "소리 없음(BPN-115)",
	"Entities.gmod_subway_81-717_mvm.Spawner.KVSnd.Name": "주간 제어기 소리",
	"Entities.gmod_subway_81-717_mvm.Spawner.KVSnd.1": "종류 1",
	"Entities.gmod_subway_81-717_mvm.Spawner.KVSnd.2": "종류 2",
	"Entities.gmod_subway_81-717_mvm.Spawner.KVSnd.3": "종류 3",
	"Entities.gmod_subway_81-717_mvm.Spawner.NewKV.Name": "새로운 주간 제어기 모델",
	"Entities.gmod_subway_81-717_mvm.Spawner.HornType.Name": "SPB 경적",
	"Entities.gmod_subway_81-717_mvm.Spawner.RingType.Name": "부저 소리",
	"Entities.gmod_subway_81-717_mvm.Spawner.RingType.1": "구형 소리",
	"Entities.gmod_subway_81-717_mvm.Spawner.RingType.2": "낮은 톤의 기본 부저 소리",
	"Entities.gmod_subway_81-717_mvm.Spawner.RingType.3": "높은 톤의 기본 부저 소리",
	"Entities.gmod_subway_81-717_mvm.Spawner.RingType.4": "간헐적으로 낮은 톤의 기본 부저 소리",
	"Entities.gmod_subway_81-717_mvm.Spawner.RingType.5": "간헐적으로 높은 톤의 기본 부저 소리",
	"Entities.gmod_subway_81-717_mvm.Spawner.NM.Name": "주 공기관 압력",
	"Entities.gmod_subway_81-717_mvm.Spawner.Battery.Name": "배터리",
	"Entities.gmod_subway_81-717_mvm.Spawner.Switches.Name": "모든 차량의 차단기를 활성화 함",
	"Entities.gmod_subway_81-717_mvm.Spawner.SwitchesR.Name": "차단기의 상태를 무작위로 함",
	"Entities.gmod_subway_81-717_mvm.Spawner.DoorsL.Name": "좌측 출입문 열림",
	"Entities.gmod_subway_81-717_mvm.Spawner.DoorsR.Name": "우측 출입문 열림",
	"Entities.gmod_subway_81-717_mvm.Spawner.GV.Name": "고전압 스위치",
	"Entities.gmod_subway_81-717_mvm.Spawner.PB.Name": "주차 제동",
	"Entities.gmod_subway_81-717_mvm.Spawner.BortLampType.Name": "외부 출입문 확인등 배열",
	"Entities.gmod_subway_81-717_mvm.Spawner.BortLampType.1": "수평",
	"Entities.gmod_subway_81-717_mvm.Spawner.BortLampType.2": "수직",
	"Entities.gmod_subway_81-717_mvm.Spawner.MVM.Name": "MVM 마크",
	"Entities.gmod_subway_81-717_mvm.Spawner.HandRail.Name": "객실 손잡이 종류",
	"Entities.gmod_subway_81-717_mvm.Spawner.HandRail.1": "구형",
	"Entities.gmod_subway_81-717_mvm.Spawner.HandRail.2": "신형",
	"Entities.gmod_subway_81-717_mvm.Spawner.SeatType.Name": "좌석 종류",
	"Entities.gmod_subway_81-717_mvm.Spawner.SeatType.1": "구형",
	"Entities.gmod_subway_81-717_mvm.Spawner.SeatType.2": "신형",
	"Entities.gmod_subway_81-717_mvm.Spawner.LampType.Name": "객실 조명 종류",
	"Entities.gmod_subway_81-717_mvm.Spawner.LampType.1": "종류 1",
	"Entities.gmod_subway_81-717_mvm.Spawner.LampType.2": "종류 2",
	"Entities.gmod_subway_81-717_mvm.Spawner.LampType.3": "종류 3",
	"Entities.gmod_subway_81-717_mvm.Spawner.Breakers.Name": "운전석 배전반 우측 배치",
	"Entities.gmod_subway_81-717_mvm.Spawner.Adverts.Name": "차내 광고 종류",
	"Entities.gmod_subway_81-717_mvm.Spawner.Adverts.1": "종류 1",
	"Entities.gmod_subway_81-717_mvm.Spawner.Adverts.2": "종류 2",
	"Entities.gmod_subway_81-717_mvm.Spawner.Adverts.3": "종류 3",
	"Entities.gmod_subway_81-717_mvm.Spawner.Adverts.4": "광고 없음",

	"Entities.gmod_subway_81-720.Spawner.Texture.Name": "도색",
	"Entities.gmod_subway_81-720.Spawner.PassTexture.Name": "객실 내장재",
	"Entities.gmod_subway_81-720.Spawner.CabTexture.Name": "운전대 재질",
	"Entities.gmod_subway_81-720.Spawner.Announcer.Name": "안내 방송",
	"Entities.gmod_subway_81-720.Spawner.Scheme.Name": "노선도 종류",
	"Entities.gmod_subway_81-720.Spawner.PassSchemesInvert.Name": "역방향 노선도",
	"Entities.gmod_subway_81-720.Spawner.NM.Name": "주 공기관 압력",
	"Entities.gmod_subway_81-720.Spawner.Battery.Name": "배터리",
	"Entities.gmod_subway_81-720.Spawner.BRU.Name": "고전압 스위치",
	"Entities.gmod_subway_81-720.Spawner.PVZR.Name": "운전석 배전반의 차단기 상태를 무작위로 함",
	"Entities.gmod_subway_81-720.Spawner.PPZ.Name": "모든 차량의 차단기를 활성화 함",
	"Entities.gmod_subway_81-720.Spawner.PPZDepot.Name": "모든 차량의 차단기를 비활성화 함(기지 입고 상태)",
	"Entities.gmod_subway_81-720.Spawner.PPZR.Name": "모든 차량의 차단기 상태를 무작위로 함",
	"Entities.gmod_subway_81-720.Spawner.DoorsL.Name": "좌측 출입문 열림",
	"Entities.gmod_subway_81-720.Spawner.DoorsR.Name": "우측 출입문 열림",

	"Entities.gmod_subway_81-722.Spawner.Texture.Name": "도색",
	"Entities.gmod_subway_81-722.Spawner.PassTexture.Name": "객실 내장재",
	"Entities.gmod_subway_81-722.Spawner.CabTexture.Name": "운전대 재질",
	"Entities.gmod_subway_81-722.Spawner.Announcer.Name": "안내방송",
	"Entities.gmod_subway_81-722.Spawner.Scheme.Name": "노선도 종류",
	"Entities.gmod_subway_81-722.Spawner.SarmatInvert.Name": "역방향 노선도",
	"Entities.gmod_subway_81-722.Spawner.NM.Name": "주 공기관 압력",
	"Entities.gmod_subway_81-722.Spawner.Battery.Name": "배터리",
	"Entities.gmod_subway_81-722.Spawner.Switches.Name": "모든 차량의 차단기를 활성화 함",
	"Entities.gmod_subway_81-722.Spawner.SwitchesR.Name": "차단기의 상태를 무작위로 함",
	"Entities.gmod_subway_81-722.Spawner.DoorsL.Name": "좌측 출입문 열림",
	"Entities.gmod_subway_81-722.Spawner.DoorsR.Name": "우측 출입문 열림",

	"Spawner.Close": "닫기",
	"Spawner.Spawn": "완료"
}
]]
