return [[
{
  "Lang": "nl",
  "Name": "Nederlands",


  "Entities.gmod_subway_ezh3.Buttons.Stopkran.EmergencyBrakeValveToggle": "Noodrem",
  "Entities.gmod_subway_ezh3.Buttons.Back.BackDoor": "Achterdeur",
  "Entities.gmod_subway_ezh3.Buttons.DriverValveBLTLDisconnect.DriverValveBLDisconnectToggle": "Remleiding verbindingsklep",
  "Entities.gmod_subway_ezh3.Buttons.DriverValveBLTLDisconnect.DriverValveTLDisconnectToggle": "Treinleiding verbindingsklep",
  "Entities.gmod_subway_ezh3.Buttons.Battery.VBToggle": "VB: Batterij inschakelen/uitschakelen (laag voltage)",
  "Entities.gmod_subway_ezh3.Buttons.FrontPneumatic.FrontBrakeLineIsolationToggle": "Remleiding isolatieklep",
  "Entities.gmod_subway_ezh3.Buttons.FrontPneumatic.FrontTrainLineIsolationToggle": "Treinleiding isolatieklep",
  "Entities.gmod_subway_ezh3.Buttons.ASNP.R_ASNPMenuSet": "Omroeper: Menu",
  "Entities.gmod_subway_ezh3.Buttons.ASNP.R_ASNPUpSet": "Omroeper: Omhoog",
  "Entities.gmod_subway_ezh3.Buttons.ASNP.R_ASNPDownSet": "Omroeper: Omlaag",
  "Entities.gmod_subway_ezh3.Buttons.ASNP.R_ASNPOnToggle": "Omroeper: Schakel in",
  "Entities.gmod_subway_ezh3.Buttons.PassengerDoor1.PassengerDoor": "Passagiersdeur",
  "Entities.gmod_subway_ezh3.Buttons.PassengerDoor.PassengerDoor": "Passagiersdeur",
  "Entities.gmod_subway_ezh3.Buttons.CabinDoor.CabinDoor": "Cabinedeur",
  "Entities.gmod_subway_ezh3.Buttons.Front.FrontDoor": "Voordeur",
  "Entities.gmod_subway_ezh3.Buttons.GV.GVToggle": "HV Schakelaar",
  "Entities.gmod_subway_ezh3.Buttons.RearPneumatic.RearTrainLineIsolationToggle": "Treinleiding isolatieklep",
  "Entities.gmod_subway_ezh3.Buttons.RearPneumatic.RearBrakeLineIsolationToggle": "Remleiding isolatieklep",
  "Entities.gmod_subway_ezh3.Buttons.Panel.!OCH": "NCh: Geen ARS frequentie",
  "Entities.gmod_subway_ezh3.Buttons.Panel.!0": "0: ARS stopteken",
  "Entities.gmod_subway_ezh3.Buttons.Panel.!40": "Snelheidslimiet 40 km/u",
  "Entities.gmod_subway_ezh3.Buttons.Panel.!60": "Snelheidslimiet 60 km/u",
  "Entities.gmod_subway_ezh3.Buttons.Panel.!70": "Snelheidslimiet 70 km/u",
  "Entities.gmod_subway_ezh3.Buttons.Panel.!80": "Snelheidslimiet 80 km/u",
  "Entities.gmod_subway_ezh3.Buttons.Panel.!Speedometer": "Snelheidsindicator (km/u)",
  "Entities.gmod_subway_ezh3.Buttons.Panel.!TotalAmpermeter": "Totale motor ampérage (A)",
  "Entities.gmod_subway_ezh3.Buttons.Panel.!TotalVoltmeter": "Totale voltage (kV)",
  "Entities.gmod_subway_ezh3.Buttons.Panel.!BatteryVoltage": "Batterijvoltage treinbesturing (V)",
  "Entities.gmod_subway_ezh3.Buttons.Panel.!BrakeCylinder": "Luchtdruk in remcilinders",
  "Entities.gmod_subway_ezh3.Buttons.Panel.!LinesPressure": "Luchtdruk in pneumatische leidingen (rood: remleiding, zwart: treinleiding)",
  "Entities.gmod_subway_ezh3.Buttons.Main.KU1Toggle": "Schakel compressor in",
  "Entities.gmod_subway_ezh3.Buttons.Main.SAMM1Set": "SAMM: Deactiveer autodrive",
  "Entities.gmod_subway_ezh3.Buttons.Main.SAMM2Set": "SAMM: Start",
  "Entities.gmod_subway_ezh3.Buttons.Main.SAMM3Set": "SAMM: Reset",
  "Entities.gmod_subway_ezh3.Buttons.Main.SAMMSignal1": "Lamp: Rem/Gas",
  "Entities.gmod_subway_ezh3.Buttons.Main.SAMMSignal2": "Lamp: Werkstatus SAMM",
  "Entities.gmod_subway_ezh3.Buttons.Main.SAMMSignal3": "Lamp: SAMM uitvoerings eenheid ingeschakeld",
  "Entities.gmod_subway_ezh3.Buttons.Main.SAMMOnToggle": "SAMM: Activeer autodrive",
  "Entities.gmod_subway_ezh3.Buttons.Main.SAMMBlokToggle": "SAMM: Uitvoerings eenheid",
  "Entities.gmod_subway_ezh3.Buttons.Main.SAMMCommand3Set": "SAMM: X-2",
  "Entities.gmod_subway_ezh3.Buttons.Main.SAMMCommand2Set": "SAMM: Inhalen",
  "Entities.gmod_subway_ezh3.Buttons.Main.SAMMCommand1Set": "SAMM: Toestemming",
  "Entities.gmod_subway_ezh3.Buttons.Main.KSNSet": "KSN: Storingsindicatie knop",
  "Entities.gmod_subway_ezh3.Buttons.Main.R_Program1Set": "Programma 1",
  "Entities.gmod_subway_ezh3.Buttons.Main.R_Program2Set": "Programma 2",
  "Entities.gmod_subway_ezh3.Buttons.Main.VUSToggle": "Switch: Dimlicht/Grootlicht",
  "Entities.gmod_subway_ezh3.Buttons.Main.L_3Toggle": "Switch: Verlichting meters",
  "Entities.gmod_subway_ezh3.Buttons.Main.VAHToggle": "Switch: Noodbesturing",
  "Entities.gmod_subway_ezh3.Buttons.Main.DIPonSet": "Osv. Vkl.: Schakel interieurverlichting in",
  "Entities.gmod_subway_ezh3.Buttons.Main.DIPoffSet": "Osv. Vykl.: Schakel interieurverlichting uit",
  "Entities.gmod_subway_ezh3.Buttons.Main.KSDSet": "KSD: Deuren statuscontrole",
  "Entities.gmod_subway_ezh3.Buttons.Main.KVTSet": "KVT: Reset ARS rem",
  "Entities.gmod_subway_ezh3.Buttons.Main.KBSet": "KB: Attentieknop",
  "Entities.gmod_subway_ezh3.Buttons.Main.KBLamp": "Lamp: Indicatielicht rijweerstandmechanisme in beweging",
  "Entities.gmod_subway_ezh3.Buttons.Main.ARSToggle": "ARS: Automatische snelheidsregulatie",
  "Entities.gmod_subway_ezh3.Buttons.Main.R_UNchToggle": "UNCh: Versterker lage frequentie",
  "Entities.gmod_subway_ezh3.Buttons.Main.VUD1Toggle": "VUD: Deuren open of dicht(doet alle deuren dicht)",
  "Entities.gmod_subway_ezh3.Buttons.Main.R_RadioToggle": "Radioinformator: Omroeper (ingebouwd)",
  "Entities.gmod_subway_ezh3.Buttons.Main.ALSToggle": "ALS: Automatische locomotief signalering",
  "Entities.gmod_subway_ezh3.Buttons.Main.VozvratRPSet": "KVRP: Reset overbelastingsrelais",
  "Entities.gmod_subway_ezh3.Buttons.Main.RingSet": "Bel",
  "Entities.gmod_subway_ezh3.Buttons.Main.L_2Toggle": "Switch: Cabineverlichting",
  "Entities.gmod_subway_ezh3.Buttons.Main.KRZDSet": "KRZD: Nood deuren dicht",
  "Entities.gmod_subway_ezh3.Buttons.Main.KDPSet": "KDP: Open deuren aan rechterkant",
  "Entities.gmod_subway_ezh3.Buttons.Main.KDLSet": "KDL: Open deuren aan linkerkant",
  "Entities.gmod_subway_ezh3.Buttons.Main.KAHSet": "KAH: Noodbesturing knop",
  "Entities.gmod_subway_ezh3.Buttons.Main.RezMKSet": "Compressor noodactivatie",
  "Entities.gmod_subway_ezh3.Buttons.Main.KRPSet": "KRP: Noodstart knop",
  "Entities.gmod_subway_ezh3.Buttons.Main.RSTToggle": "VPR: Radioapparatuur inschakelen/uitschakelen",
  "Entities.gmod_subway_ezh3.Buttons.Main.R_GToggle": "Loudspeaker: Luidspreker in cabine inschakelen/uitschakelen",
  "Entities.gmod_subway_ezh3.Buttons.Main.R_ZSToggle": "ZS: Luidsprekers in de wagon inschakelen/uitschakelen",
  "Entities.gmod_subway_ezh3.Buttons.Main.Custom2Set": "Ongebruikte schakelaar",
  "Entities.gmod_subway_ezh3.Buttons.Main.Custom3Set": "Ongebruikte schakelaar",
  "Entities.gmod_subway_ezh3.Buttons.Main.ASNPPlay": "Omroeper in gebruik",
  "Entities.gmod_subway_ezh3.Buttons.AV1.VU3Toggle": "VU3: Cabineverlichting",
  "Entities.gmod_subway_ezh3.Buttons.AV1.VU2Toggle": "VU2: Noodverlichting (45V)",
  "Entities.gmod_subway_ezh3.Buttons.AV1.VU1Toggle": "VU1: Cabineverwarming (3kW)",
  "Entities.gmod_subway_ezh3.Buttons.AVMain.AV8BToggle": "AV-8B: Automatische schakelaar (Hoog voltage)",
  "Entities.gmod_subway_ezh3.Buttons.RC1.RC1Toggle": "RC-ARS: ARS stroomonderbreker",
  "Entities.gmod_subway_ezh3.Buttons.UAVAPanel.UAVAToggle": "UAVA: Universele Automatische Autostop Deactiveerder (deactiveer autostop)",
  "Entities.gmod_subway_ezh3.Buttons.UAVAPanel.UAVAContactSet": "UAVA: UAVA: Universele Automatische Autostop Deactiveerder (reset contacten)",
  "Entities.gmod_subway_ezh3.Buttons.VUHelper.VUToggle": "VU: Treinbesturing",
  "Entities.gmod_subway_ezh3.Buttons.HelperPanel.VDLSet": "KDL: Open deuren aan linkerkant",
  "Entities.gmod_subway_ezh3.Buttons.HelperPanel.VUD2Toggle": "VUD2: Deuren open of dicht(doet alle deuren dicht)",
  "Entities.gmod_subway_ezh3.Buttons.EPKDisconnect.EPKToggle": "EPK verbindingsklep",
  "Entities.gmod_subway_ezh3.Buttons.VU.VUToggle": "VU: Treinbesturing",
  "Entities.gmod_subway_ezh3.Buttons.ParkingBrake.ParkingBrakeLeft": "Parkeerrem",
  "Entities.gmod_subway_ezh3.Buttons.ParkingBrake.ParkingBrakeRight": "Parkeerrem",
  "Entities.gmod_subway_ezh3.Buttons.AirDistributor.AirDistributorDisconnectToggle": "Deactiveer luchtdrukverdeler",

  "Entities.gmod_subway_em508t.Buttons.Stopkran.EmergencyBrakeValveToggle": "Noodrem",
  "Entities.gmod_subway_em508t.Buttons.Battery.VBToggle": "VB: Batterij inschakelen/uitschakelen (laag voltage)",
  "Entities.gmod_subway_em508t.Buttons.FrontPneumatic.FrontBrakeLineIsolationToggle": "Remleiding isolatieklep",
  "Entities.gmod_subway_em508t.Buttons.FrontPneumatic.FrontTrainLineIsolationToggle": "Treinleiding isolatieklep",
  "Entities.gmod_subway_em508t.Buttons.GV.GVToggle": "HV schakelaar",
  "Entities.gmod_subway_em508t.Buttons.RearPneumatic.RearTrainLineIsolationToggle": "Treinleiding isolatieklep",
  "Entities.gmod_subway_em508t.Buttons.RearPneumatic.RearBrakeLineIsolationToggle": "Remleiding isolatieklep",
  "Entities.gmod_subway_em508t.Buttons.RearDoor.RearDoor": "Passagiersdeur",
  "Entities.gmod_subway_em508t.Buttons.Back2.!HVFuse": "HV zekeringenkast",
  "Entities.gmod_subway_em508t.Buttons.Back2.!Relays": "Kast met apparatuur voor opladen batterij en verspreiding van luchtdruk voor deuren",
  "Entities.gmod_subway_em508t.Buttons.Back2.!Heater": "Verwarming",
  "Entities.gmod_subway_em508t.Buttons.Front.FrontDoor": "Voordeur",
  "Entities.gmod_subway_em508t.Buttons.AV1.VU3Toggle": "VU3: Cabineverlichting",
  "Entities.gmod_subway_em508t.Buttons.AV1.VU2Toggle": "VU2: Noodverlichting (45V)",
  "Entities.gmod_subway_em508t.Buttons.AV1.VU1Toggle": "VU1: Cabineverwarming (3kW)",
  "Entities.gmod_subway_em508t.Buttons.ParkingBrake.ParkingBrakeLeft": "Parkeerrem",
  "Entities.gmod_subway_em508t.Buttons.ParkingBrake.ParkingBrakeRight": "Parkeerrem",
  "Entities.gmod_subway_em508t.Buttons.CabinDoor.CabinDoor1": "Cabinedeur",
  "Entities.gmod_subway_em508t.Buttons.PassengerDoor.PassengerDoor": "Passagiersdeur",
  "Entities.gmod_subway_em508t.Buttons.PassengerDoor1.PassengerDoor": "Passagiersdeur",
  "Entities.gmod_subway_em508t.Buttons.Main.!RedRP": "RP: Rode overbelastingsrelais lamp (krachtcircuits konden niet worden samengevoegd)",
  "Entities.gmod_subway_em508t.Buttons.Main.!GreenRP": "RP: Groene overbelastingsrelais lamp (voorkomt teveel stroom in de motoren)",
  "Entities.gmod_subway_em508t.Buttons.Main.!SD": "Blauwe lamp deurstatus (deuren zijn dicht)",
  "Entities.gmod_subway_em508t.Buttons.Main.KDLSet": "Switch: Open deuren aan linkerkant",
  "Entities.gmod_subway_em508t.Buttons.Main.KSDSet": "Switch: Deuren statuscontrole",
  "Entities.gmod_subway_em508t.Buttons.Main.VozvratRPSet": "Switch: Reset overbelastingsrelais",
  "Entities.gmod_subway_em508t.Buttons.Main.KSNSet": "Switch: Storingsindicatie schakelaar",
  "Entities.gmod_subway_em508t.Buttons.Main.VUD1Toggle": "Switch: Deuren open of dicht(doet alle deuren dicht)",
  "Entities.gmod_subway_em508t.Buttons.Main.KU1Toggle": "Switch: Schakel compressor in",
  "Entities.gmod_subway_em508t.Buttons.Main.DIPonSet": "KU4: Schakel interieurverlichting in",
  "Entities.gmod_subway_em508t.Buttons.Main.DIPoffSet": "KU5: Schakel interieurverlichting uit",
  "Entities.gmod_subway_em508t.Buttons.Main.RezMKSet": "Switch: Compressor noodactivatie",
  "Entities.gmod_subway_em508t.Buttons.Main.KDPSet": "KDP: Open deuren rechterkant",
  "Entities.gmod_subway_em508t.Buttons.Main.KRZDSet": "KU10: Nood deuren dicht",
  "Entities.gmod_subway_em508t.Buttons.AVMain.AV8BToggle": "AV-8B: Automatische schakelaar (Hoog voltage)",
  "Entities.gmod_subway_em508t.Buttons.VU.VUToggle": "VU: Treinbesturing",
  "Entities.gmod_subway_em508t.Buttons.VU.!Voltage": "Voltage besturingscircuits",
  "Entities.gmod_subway_em508t.Buttons.HelperPanel.VUD2Toggle": "VUD2: Deuren open of dicht(doet alle deuren dicht)",
  "Entities.gmod_subway_em508t.Buttons.HelperPanel.VDLSet": "VDL: Open deuren aan linkerkant",
  "Entities.gmod_subway_em508t.Buttons.DriverValveBLTLDisconnect.DriverValveBLDisconnectToggle": "Remleiding verbindingsklep",
  "Entities.gmod_subway_em508t.Buttons.DriverValveBLTLDisconnect.DriverValveTLDisconnectToggle": "Remleiding verbindingsklep",
  "Entities.gmod_subway_em508t.Buttons.AirDistributor.AirDistributorDisconnectToggle": "Deactiveer luchtdrukverdeler"
}
]]
