return [[
{
	"Lang": "nl",
	"Name": "Nederlands",
	"Panel.Admin": "Admin",
	"Panel.Client": "Client",
	"Panel.DrawDebugInfo": "Activeer debug hints",
	"Panel.DisableCamAccel": "Deactiveer camera acceleratie",
	"Panel.DisableHoverText": "Deactiveer zwevende labels",

	"Entities.gmod_subway_base.Name": "Metrotrein basis",
	"Entities.gmod_subway_81-703.Name": "E",
	"Entities.gmod_subway_81-703_2.Name": "E (tussenrijtuig)",
	"Entities.gmod_subway_81-717_mvm.Name": "81-717(MVM)",
	"Entities.gmod_subway_81-717_lvz.Name": "81-717(LVZ)",
	"Entities.gmod_subway_81-714_mvm.Name": "81-714(MVM)",
	"Entities.gmod_subway_81-714_lvz.Name": "81-714(LVZ)",
	"Entities.gmod_subway_81-7036.Name": "81-7036 (werkt niet)",
	"Entities.gmod_subway_81-7037.Name": "81-7037 (werkt niet)",
	"Entities.gmod_subway_81-720.Name": "81-720 (stuurstandrijtuig)",
	"Entities.gmod_subway_81-721.Name": "81-721 (tussenrijtuig)",
	"Entities.gmod_subway_81-722.Name": "81-722 (stuurstandrijtuig)",
	"Entities.gmod_subway_81-723.Name": "81-723 (tussenrijtuig motor)",
	"Entities.gmod_subway_81-724.Name": "81-724 (tussenrijtuig)",
	"Entities.gmod_subway_e.Name": "E (old)",
	"Entities.gmod_subway_em.Name": "Em",
	"Entities.gmod_subway_ema.Name": "Ema",
	"Entities.gmod_subway_ezh.Name": "Ezh",
	"Entities.gmod_subway_ezh1.Name": "Ezh1",
	"Entities.gmod_subway_em508.Name": "Em-508 (stuurstandrijtuig)",
	"Entities.gmod_subway_em508_int.Name": "Em-508 (tussenrijtuig)",
	"Entities.gmod_subway_ezh3.Name": "Ezh3",
	"Entities.gmod_subway_ezh3ru1.Name": "Ezh3 RU1",
	"Entities.gmod_subway_ema508t.Name": "Em-508T",
	"Entities.gmod_subway_tatra_t3.Name": "Tatra T3",
	"Entities.gmod_subway_ai.Name": "AI trein",

	"Entities.gmod_train_bogey.Name": "Trein draaistel",
	"Entities.gmod_train_couple.Name": "Koppeling",

	"Entities.gmod_track_pui.Name": "PUI klok",
	"Entities.gmod_track_mus_elektronika7.Name": "Elektronische klok",
	"Entities.gmod_mus_clock_analog.Name": "Analoge klok",
	"Entities.gmod_track_clock_time.Name": "Grote interval klok(tijd)",
	"Entities.gmod_track_clock_small.Name": "Kleine interval klok",
	"Entities.gmod_track_clock_interval.Name": "Grote interval klok(interval)",
	"Entities.gmod_track_switch.Name": "Wissel bestuurder",
	"Entities.gmod_track_powermeter.Name": "Energie meter",
	"Entities.gmod_track_udochka.Name": "Hoog-voltage verbindingsstuk",
	"Entities.gmod_train_spawner.Name": "Trein spawner"
}
]]
