return [[
{
  "Lang": "nl",
  "Name": "Nederlands",

  "Entities.gmod_subway_81-717_mvm.Buttons.HelperPanel.VUD2Toggle": "VUD2: Deuren open of dicht(doet alle deuren dicht)",
  "Entities.gmod_subway_81-717_mvm.Buttons.HelperPanel.VDLSet": "VDL: Open deuren aan linkerkant",
  "Entities.gmod_subway_81-717_mvm.Buttons.HelperPanel.R_Program2Helper": "Programma 2",
  "Entities.gmod_subway_81-717_mvm.Buttons.HelperPanel.R_Program1Helper": "Programma 1",
  "Entities.gmod_subway_81-717_mvm.Buttons.Battery_2.1:RC1Toggle": "RC-1: Koppel ARS circuits los",
  "Entities.gmod_subway_81-717_mvm.Buttons.Battery_2.1:VBToggle": "VB: Batterij inschakelen/uitschakelen",
  "Entities.gmod_subway_81-717_mvm.Buttons.Battery_2.1:UOSToggle": "RC-UOS: Snelheidsbegrenzing",
  "Entities.gmod_subway_81-717_mvm.Buttons.Wiper.WiperToggle": "Ruitenwisser",
  "Entities.gmod_subway_81-717_mvm.Buttons.DriverValveDisconnect.DriverValveDisconnectToggle": "Bestuurdershendel verbindingsklep",
  "Entities.gmod_subway_81-717_mvm.Buttons.DriverValveDisconnect.DriverValveBLDisconnectToggle": "Remleiding verbindingsklep",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.R_UNchToggle": "UNCh: Versterker lage frequentie",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.R_ZSToggle": "ZS: Luidsprekers in de wagon inschakelen/uitschakelen",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.R_GToggle": "Loudspeaker: Luidspreker in cabine inschakelen/uitschakelen",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.R_RadioToggle": "Radioinformator: Omroeper (ingebouwd)",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.R_Program1Set": "Programma 1",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.R_Program2Set": "Programma 2",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.2:KVTSet": "KB: Attentieknop",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.VZ1Set": "VZ1: Pneumatische klep #1",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.VUD1Toggle": "VUD: Deuren open of dicht(doet alle deuren dicht)",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.KDLSet": "KDL: Open deuren aan linkerkant",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.KDLKToggle": "KDL knop afdekklepje",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.KDLRSet": "KDL: Open deuren aan linkerkant",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.KDLRKToggle": "KDL knop afdekklepje",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.DoorSelectToggle": "Selecteer zijde waar deuren opengaan",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.KRZDSet": "RZD: Noodknop deuren dicht",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.R_VPRToggle": "VPR: Radioapparatuur inschakelen/uitschakelen",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.VozvratRPSet": "Reset overbelastingsrelais",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.GreenRPLight": "RP: Groene overbelastingsrelais lamp (voorkomt teveel stroom in de motoren)",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.AVULight": "AVU: Automatische besturingsdeactivatie actief",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.LKVPLight": "LKVP: Hoog-voltage omvormer besturing",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.SPLight": "LSP: Brandgevaar (rijweerstanden oververhit)",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.ConverterProtectionSet": "Bescherming omvormer",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.KSNSet": "KSN: Storingsindicatie knop ",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.DIPoffSet": "Bel",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.ARSToggle": "ARS: Automatische snelheidsregulatie",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.ALSToggle": "ALS: Automatische locomotief signalering",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.OtklAVUToggle": "Schakel automatische besturingsdeactivatie relais uit (Storing AVU)",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.TormATToggle": "(placeholder) Schakelaar noodrem",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.L_1Toggle": "Wagonverlichting",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.L_2Toggle": "Cabineverlichting",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.L_3Toggle": "Paneelverlichting",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.ALSFreqToggle": "Decoder: ALS frequentie schakelaar 1/5 of 2/6",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.ParkingBrakeSignToggle": "Bord \"DEACTIVEER PARKEERREM\"",
  "Entities.gmod_subway_81-717_mvm.Buttons.ParkingBrake.ParkingBrakeToggle": "Parkeerrem",
  "Entities.gmod_subway_81-717_mvm.Buttons.ParkingBrake.DriverValveTLDisconnectToggle": "Treinleiding verbindingsklep",
  "Entities.gmod_subway_81-717_mvm.Buttons.IGLAButtons.IGLA1Set": "IGLA: Knop één",
  "Entities.gmod_subway_81-717_mvm.Buttons.IGLAButtons.IGLA2Set": "IGLA: Knop twee",
  "Entities.gmod_subway_81-717_mvm.Buttons.IGLAButtons.IGLA3Set": "IGLA: Knop drie",
  "Entities.gmod_subway_81-717_mvm.Buttons.IGLAButtons.IGLA4Set": "IGLA: Knop vier",
  "Entities.gmod_subway_81-717_mvm.Buttons.BPSNFront.!Voltage": "Voltage besturingscircuits",
  "Entities.gmod_subway_81-717_mvm.Buttons.BPSNFront.VMKToggle": "Schakel compressor in",
  "Entities.gmod_subway_81-717_mvm.Buttons.BPSNFront.BPSNonToggle": "BPSN: Trein krachtvoeding",
  "Entities.gmod_subway_81-717_mvm.Buttons.BPSNFront.RezMKSet": "Compressor noodactivatie",
  "Entities.gmod_subway_81-717_mvm.Buttons.BPSNFront.ARS13Set": "ARS 13V: ARS voltage check",
  "Entities.gmod_subway_81-717_mvm.Buttons.Schedule.!RouteNum": "М №\nRoute number",
  "Entities.gmod_subway_81-717_mvm.Buttons.Schedule.!PathNum": "П №\nPath number",
  "Entities.gmod_subway_81-717_mvm.Buttons.Schedule.!SchTime": "ВРЕМЯ ХОДА\nTotal schedule time",
  "Entities.gmod_subway_81-717_mvm.Buttons.Schedule.!SchInterval": "ИНТ\nTrain interval",
  "Entities.gmod_subway_81-717_mvm.Buttons.Schedule.!SchHour": "ЧАС\nHour",
  "Entities.gmod_subway_81-717_mvm.Buttons.Schedule.!SchMin": "МИН\nMinute",
  "Entities.gmod_subway_81-717_mvm.Buttons.Schedule.!SchSec": "СЕК\nSecond",
  "Entities.gmod_subway_81-717_mvm.Buttons.Schedule.!SchArrival": "Arrival times",
  "Entities.gmod_subway_81-717_mvm.Buttons.Schedule.!SchStations": "Station name",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!Speedometer": "Snelheidsindicator",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!LampLSN": "LSN: Storingsindicatie lamp (krachtcircuits konden niet worden samengevoegd)",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!LampRP": "RP: Rode overbelastingsrelais lamp (krachtcircuits konden niet worden samengevoegd)",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!LampLHRK": "LhRK: Indicatielicht rijweerstandmechanisme in beweging ",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!LampLKT": "LKT: ARS rem indicatielicht",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!LampLKVD": "LKVD: ARS motordeactivatie indicatielicht",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!LampLKVC": "LKVC: Hoog-voltage niet beschikbaar",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!ARSOch": "OCh: Geen ARS frequentie",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!ARS0": "0: ARS stopteken",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!ARS40": "Snelheidslimiet 40 km/u",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!ARS60": "Snelheidslimiet 60 km/u",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!ARS70": "Snelheidslimiet 70 km/u",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!ARS80": "Snelheidslimiet 80 km/u",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!LampLSD1": "LSD: Lamp deurstatus (deuren zijn dicht)",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!LampLSD2": "LSD: Lamp deurstatus (deuren zijn dicht)",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!LampLST": "LST: Remmen geactiveerd",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!LampLVD": "LVD: Motoren geactiveerd",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!LampLN": "LN: Richtingssignaal",
  "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!LampLRS": "LRS: Gelijke snelheid lamp (volgende snelheidslimiet gelijk of groter dan huidige)",
  "Entities.gmod_subway_81-717_mvm.Buttons.PneumaticPanels.!CylinderPressure": "Druk in remcilinders",
  "Entities.gmod_subway_81-717_mvm.Buttons.PneumaticPanels.!LinePressure": "Druk in pneumatische leidingen (rood: remleiding, zwart: treinleiding)",
  "Entities.gmod_subway_81-717_mvm.Buttons.Battery.RC1Toggle": "RC-1: Koppel ARS circuits los",
  "Entities.gmod_subway_81-717_mvm.Buttons.Battery.UOSToggle": "RC-UOS: Snelheidsbegrenzing",
  "Entities.gmod_subway_81-717_mvm.Buttons.Battery.VBToggle": "VB: Batterij inschakelen/uitschakelen",
  "Entities.gmod_subway_81-717_mvm.Buttons.FrontPneumatic.FrontBrakeLineIsolationToggle": "Remleiding isolatieklep",
  "Entities.gmod_subway_81-717_mvm.Buttons.FrontPneumatic.FrontTrainLineIsolationToggle": "Treinleiding isolatieklep",
  "Entities.gmod_subway_81-717_mvm.Buttons.ASNP.R_ASNPMenuSet": "ASNP: Menu",
  "Entities.gmod_subway_81-717_mvm.Buttons.ASNP.R_ASNPUpSet": "ASNP: Omhoog",
  "Entities.gmod_subway_81-717_mvm.Buttons.ASNP.R_ASNPDownSet": "ASNP: Omlaag",
  "Entities.gmod_subway_81-717_mvm.Buttons.ASNP.R_ASNPOnToggle": "ASNP: Inschakelen",
  "Entities.gmod_subway_81-717_mvm.Buttons.RearDoor.RearDoor": "Achterdeur",
  "Entities.gmod_subway_81-717_mvm.Buttons.Meters.!TotalVoltmeter": "HV voltmeter (kV)",
  "Entities.gmod_subway_81-717_mvm.Buttons.Meters.!TotalAmpermeter": "Totale ampéragemeter (A)",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A61Toggle": "A61 Besturing signaaldraad 6",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A55Toggle": "A55 Besturing signaaldraad 10AS",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A54Toggle": "A54 Besturing signaaldraad 10AK",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A56Toggle": "A56 Verbind besturingscircuits met batterij",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A27Toggle": "A27 Schakel krachtvoeding en verlichting in (trein)",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A21Toggle": "A21 Deurbesturing",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A10Toggle": "A10 Compressormotor besturing",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A53Toggle": "A53 KVC voeding",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A43Toggle": "A43 ARS 12V voeding",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A45Toggle": "A45 ARS signaaldraad 10AU",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A42Toggle": "A42 ARS 75V voeding",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A41Toggle": "A41 ARS Rem",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.VUToggle": "VU  Treinbesturing",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A64Toggle": "A64 Cabineverlichting",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A63Toggle": "A63 IGLA/BIS",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A50Toggle": "A50 Schakel krachtvoeding en verlichting in (wagon)",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A51Toggle": "A51 Schakel krachtvoeding en verlichting uit",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A23Toggle": "A23 Compressor noodactivatie",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A14Toggle": "A14 Signaaldraad 18",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A75Toggle": "A75 Cabineverwarming",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A1Toggle": "A1  X-1",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A2Toggle": "A2  X-2",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A3Toggle": "A3  X-3",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A17Toggle": "A17 Reset overbelastingsrelais",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A62Toggle": "A62 Radio communicatie",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A29Toggle": "A29 Radio uitzending",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A5Toggle": "A5 Omroeper",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A6Toggle": "A6  T-1",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A8Toggle": "A8  Pneumatische klep #1, #2",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A20Toggle": "A20 Gas/rem besturing, signaaldraad 20",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A25Toggle": "A25 Handmatige elektrische rem",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A22Toggle": "A22 Activeer compressor",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A30Toggle": "A30 Rijweerstand schakelaarmotor voeding",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A39Toggle": "A39 Noodbesturing",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A44Toggle": "A44 Trein noodbesturing",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A80Toggle": "A80 Krachtcircuits schakelmotor voeding",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A65Toggle": "A65 Interieurverlichting",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.L_5Toggle": "А49 Noodverlichting",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A24Toggle": "A24 Opladen batterij",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A32Toggle": "A32 Open deuren aan rechterkant",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A31Toggle": "A31 Open deuren aan linkerkant",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A16Toggle": "A16 Deuren dicht",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A13Toggle": "A13 Deur waarschuwing",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A12Toggle": "A12 Nood deuren dicht",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A7Toggle": "A7  Rode lamp",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A9Toggle": "A9  Rode lamp",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A46Toggle": "A46 Witte lamp",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A47Toggle": "A47 Witte lamp",
  "Entities.gmod_subway_81-717_mvm.Buttons.PassengerDoor.PassengerDoor": "Passagiersdeur",
  "Entities.gmod_subway_81-717_mvm.Buttons.GV.GVToggle": "HV schakelaar",
  "Entities.gmod_subway_81-717_mvm.Buttons.Stopkran.EmergencyBrakeValveToggle": "Noodrem",
  "Entities.gmod_subway_81-717_mvm.Buttons.InfoTableSelect.PrevSign": "Bord: Vorige",
  "Entities.gmod_subway_81-717_mvm.Buttons.InfoTableSelect.NextSign": "Bord: Volgende",
  "Entities.gmod_subway_81-717_mvm.Buttons.InfoTableSelect.Num2P": "Route: Verhoog 2de cijfer",
  "Entities.gmod_subway_81-717_mvm.Buttons.InfoTableSelect.Num2M": "Route: Verlaag 2de cijfer",
  "Entities.gmod_subway_81-717_mvm.Buttons.InfoTableSelect.Num1P": "Route: Verhoog 1ste cijfer",
  "Entities.gmod_subway_81-717_mvm.Buttons.InfoTableSelect.Num1M": "Route: Verlaag 1ste cijfer",
  "Entities.gmod_subway_81-717_mvm.Buttons.Front.L_4Toggle": "Koplampen aan/uit",
  "Entities.gmod_subway_81-717_mvm.Buttons.Front.VUSToggle": "VUS: Koplampen helder/gedimd",
  "Entities.gmod_subway_81-717_mvm.Buttons.Front.VAHToggle": "VAH: Noodbesturing (storing RPB relais)",
  "Entities.gmod_subway_81-717_mvm.Buttons.Front.VADToggle": "VAD: Nood deuren dicht (storing KD relais)",
  "Entities.gmod_subway_81-717_mvm.Buttons.Front.KRPSet": "KRP: Noodstart knop",
  "Entities.gmod_subway_81-717_mvm.Buttons.Front.KAHSet": "Noodbesturing knop",
  "Entities.gmod_subway_81-717_mvm.Buttons.Front.KAHKToggle": "KAH afdekklepje",
  "Entities.gmod_subway_81-717_mvm.Buttons.Front.KUP": "Cabineverwarming actief",
  "Entities.gmod_subway_81-717_mvm.Buttons.Front.KDPSet": "KDP: Deuren aan rechterkant open",
  "Entities.gmod_subway_81-717_mvm.Buttons.Front.KDPKToggle": "KDP afdekklepje",
  "Entities.gmod_subway_81-717_mvm.Buttons.Front.PN": "Luchtrem besturing",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A61Toggle": "A61 Besturing signaaldraad 6",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A55Toggle": "A55 Besturing signaaldraad 10AS",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A54Toggle": "A54 Besturing signaaldraad 10AK",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A56Toggle": "A56 Verbind besturingscircuits met batterij",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A27Toggle": "A27 Schakel krachtvoeding en verlichting in (trein)",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A21Toggle": "A21 Deurbesturing",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A10Toggle": "A10 Besturing compressor",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A53Toggle": "A53 KVC voeding",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A43Toggle": "A43 ARS 12V voeding",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A45Toggle": "A45 ARS signaaldraad 10AU",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A42Toggle": "A42 ARS 75V voeding",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A41Toggle": "A41 ARS rem",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:VUToggle": "VU  Treinbesturing",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A64Toggle": "A64 Cabineverlichting",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A63Toggle": "A63 IGLA/BIS",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A50Toggle": "A50 Schakel krachtvoeding en verlichting in (wagon)",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A51Toggle": "A51 Schakel krachtvoeding en verlichting uit",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A23Toggle": "A23 Compressor noodactivatie",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A14Toggle": "A14 Signaaldraad 18",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A75Toggle": "A75 Cabineverwarming",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A1Toggle": "A1  X-1",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A2Toggle": "A2  X-2",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A3Toggle": "A3  X-3",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A17Toggle": "A17 Reset overbelastingsrelais",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A62Toggle": "A62 Radio communicatie",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A29Toggle": "A29 Radio uitzending",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A5Toggle": "A5 Tussenwagon",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A6Toggle": "A6  T-1",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A8Toggle": "A8  Pneumatische klep #1, #2",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A20Toggle": "A20 Gas/rem besturing, signaaldraad 20",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A25Toggle": "A25 Handmatige elektrische rem",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A22Toggle": "A22 Activeer compressor",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A30Toggle": "A30 Rijweerstand schakelmotor voeding",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A39Toggle": "A39 Noodbesturing",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A44Toggle": "A44 Trein noodbesturing",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A80Toggle": "A80 Krachtcircuits schakelmotor voeding",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A65Toggle": "A65 Interieurverlichting",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:L_5Toggle": "А49 Noodverlichting",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A24Toggle": "A24 Opladen batterij",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A32Toggle": "A32 Open deuren aan rechterkant",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A31Toggle": "A31 Open deuren aan linkerkant",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A16Toggle": "A16 Deuren dicht",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A13Toggle": "A13 Deur waarschuwing",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A12Toggle": "A12 Nood deuren dicht",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A7Toggle": "A7  Rode lamp",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A9Toggle": "A9  Rode lamp",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A46Toggle": "A46 Witte lamp",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A47Toggle": "A47 Witte lamp",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!Speedometer": "Snelheidsindicator",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!LSD": "LSD: Lamp deurstatus (Deuren zijn dicht)",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!LOCh": "NCh: Geen ARS frequentie",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!L0": "0: ARS stopteken",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!LRS": "LRS: Gelijke snelheid indicatielamp (volgende snelheidslimiet gelijk of groter dan huidige)",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!L40": "Snelheidslimiet 40 km/u",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!L60": "Snelheidslimiet 60 km/u",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!L80": "Snelheidslimiet 70 km/u",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!L70": "Snelheidslimiet 80 km/u",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!LRK": "RK: Indicatielicht rijweerstandmechanisme in beweging",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!LEKK": "",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!LPU": "",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!LKVD": "LKVD: ARS motordeactivatie indicatielicht",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!LKT": "LKT: ARS rem indicatielicht",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!LRP": "RP: Rode overbelastingsrelais lamp (krachtcircuits konden niet worden samengevoegd)",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!LKVC": "LKVC: Hoog-voltage niet beschikbaar",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!LVD": "LVD: Motoren geactiveerd",
  "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!LST": "LST: Remmen geactiveerd",
  "Entities.gmod_subway_81-717_mvm.Buttons.CabinDoor.CabinDoor": "Cabinedeur",
  "Entities.gmod_subway_81-717_mvm.Buttons.Reverser.KVReverserDown": "Rijrichting achteruit",
  "Entities.gmod_subway_81-717_mvm.Buttons.Reverser.KVReverserUp": "Rijrichting vooruit",
  "Entities.gmod_subway_81-717_mvm.Buttons.PassengerDoor1.PassengerDoor": "Passagiersdeur",
  "Entities.gmod_subway_81-717_mvm.Buttons.UAVAPanel.UAVAToggle": "UAVA: Universele Automatische Autostop Deactiveerder (deactiveer autostop)",
  "Entities.gmod_subway_81-717_mvm.Buttons.UAVAPanel.UAVAContactSet": "UAVA: Universele Automatische Autostop Deactiveerder (reset contacten)",
  "Entities.gmod_subway_81-717_mvm.Buttons.EPKDisconnect.EPKToggle": "EPV verbindingsklep",
  "Entities.gmod_subway_81-717_mvm.Buttons.Help.ShowHelp": "Toon uitleg voor besturing van de trein (engelstalig)",
  "Entities.gmod_subway_81-717_mvm.Buttons.ParkingBrake2.1:ParkingBrakeToggle": "Parkeerrem",
  "Entities.gmod_subway_81-717_mvm.Buttons.RearPneumatic.RearBrakeLineIsolationToggle": "Remleiding isolatieklep",
  "Entities.gmod_subway_81-717_mvm.Buttons.RearPneumatic.RearTrainLineIsolationToggle": "Treinleiding isolatieklep",
  "Entities.gmod_subway_81-717_mvm.Buttons.AirDistributor.AirDistributorDisconnectToggle": "Deactiveer luchtdrukverdeler",

  "Entities.gmod_subway_81-714_mvm.Buttons.GV.GVToggle": "HV schakelaar",
  "Entities.gmod_subway_81-714_mvm.Buttons.RearPneumatic.RearBrakeLineIsolationToggle": "Remleiding isolatieklep",
  "Entities.gmod_subway_81-714_mvm.Buttons.RearPneumatic.RearTrainLineIsolationToggle": "Treinleiding isolatieklep",
  "Entities.gmod_subway_81-714_mvm.Buttons.RearDoor.RearDoor": "Achterdeur",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Left.DriverValveBLDisconnectToggle": "Remleiding isolatieklep",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Left.DriverValveTLDisconnectToggle": "Treinleiding isolatieklep",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Left.A65Toggle": "A65 Interieurverlichting",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Left.A56Toggle": "A56 Verbind besturingscircuits met batterij",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Left.A63Toggle": "A63 IGLA/BIS",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Left.A10Toggle": "A10 Besturing compressor",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Left.A30Toggle": "A30 Rijweerstand schakelmotor voeding",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Left.A80Toggle": "A80 Krachtcircuits schakelmotor voeding",
  "Entities.gmod_subway_81-714_mvm.Buttons.FrontPneumatic.FrontBrakeLineIsolationToggle": "Remleiding isolatieklep",
  "Entities.gmod_subway_81-714_mvm.Buttons.FrontPneumatic.FrontTrainLineIsolationToggle": "Treinleiding isolatieklep",
  "Entities.gmod_subway_81-714_mvm.Buttons.FrontPneumatic.ParkingBrakeToggle": "Parkeerrem",
  "Entities.gmod_subway_81-714_mvm.Buttons.AirDistributor.AirDistributorDisconnectToggle": "Deactiveer luchtdrukverdeler",
  "Entities.gmod_subway_81-714_mvm.Buttons.FrontDoor.FrontDoor": "Voordeur",
  "Entities.gmod_subway_81-714_mvm.Buttons.Battery.VBToggle": "VB: Batterij inschakelen/uitschakelen",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A54Toggle": "A54 Besturing signaaldraad 10AK",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A27Toggle": "A27 Schakel krachtvoeding en verlichting in (trein)",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A24Toggle": "A24 Opladen batterij",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A53Toggle": "A53 KVC voeding",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A13Toggle": "A13 Deur waarschuwing",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A32Toggle": "A32 Open deuren aan rechterkant",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A31Toggle": "A31 Open deuren aan linkerkant",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A16Toggle": "A16 Deuren dicht",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A12Toggle": "A12 Nood deuren dicht",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A50Toggle": "A50 Schakel krachtvoeding en verlichting in (wagon)",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A51Toggle": "A51 Schakel krachtvoeding en verlichting uit",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A1Toggle": "A1  X-1",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.KRPSet": "START: Noodstart knop",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.VozvratRPSet": "Reset overbelastingsrelais",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.RezMKSet": "Compressor noodactivatie",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.VMKToggle": "Schakel compressor in",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.BPSNonToggle": "BPSN: Trein krachtvoeding",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A2Toggle": "A2  X-2",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A3Toggle": "A3  X-3",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A17Toggle": "A17 Reset overbelastingsrelais",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A5Toggle": "A5  ",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A6Toggle": "A6  T-1",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A8Toggle": "A8  Pneumatische klep #1, #2",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A20Toggle": "A20 Gas/rem besturing, signaaldraad 20",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A25Toggle": "A25 Handmatige elektrische rem",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A22Toggle": "A22 Activeer compressor",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A23Toggle": "A23 Compressor noodactivatie",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A39Toggle": "A39 Noodbesturing",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A14Toggle": "A14 Signaaldraad 18"
}
]]
