return [[
{
	"Lang": "nl",
	"Name": "Nederlands",

	"Spawner.Title": "Trein spawner",
	"Spawner.Trains1": "Trein",
	"Spawner.Trains2": "Maximum voor jou",
	"Spawner.WagNum": "Aantal wagons",
	"Spawner.AutoCouple": "Koppel wagons automatisch",

	"Entities.gmod_subway_81-717_mvm.Spawner.Texture.Name": "Kleurstelling",
	"Entities.gmod_subway_81-717_mvm.Spawner.PassTexture.Name": "Interieur",
	"Entities.gmod_subway_81-717_mvm.Spawner.CabTexture.Name": "Cabine interieur",
	"Entities.gmod_subway_81-717_mvm.Spawner.Announcer.Name": "Omroeper",
	"Entities.gmod_subway_81-717_mvm.Spawner.Lighter.Name": "Aansteker",
	"Entities.gmod_subway_81-717_mvm.Spawner.ARSType.Name": "Model ARS",
	"Entities.gmod_subway_81-717_mvm.Spawner.ARSType.1": "Standaard(vierkante lampen)",
	"Entities.gmod_subway_81-717_mvm.Spawner.ARSType.2": "Standard(ronde lampen)",
	"Entities.gmod_subway_81-717_mvm.Spawner.ARSType.3": "Kiev/SPB",
	"Entities.gmod_subway_81-717_mvm.Spawner.ARSType.4": "Oude ARS",
	"Entities.gmod_subway_81-717_mvm.Spawner.Cran.Name": "Remhendel type",
	"Entities.gmod_subway_81-717_mvm.Spawner.Cran.1": "334",
	"Entities.gmod_subway_81-717_mvm.Spawner.Cran.2": "013",
	"Entities.gmod_subway_81-717_mvm.Spawner.MaskType.Name": "Voorkant",
	"Entities.gmod_subway_81-717_mvm.Spawner.MaskType.1": "2-2",
	"Entities.gmod_subway_81-717_mvm.Spawner.MaskType.2": "2-2-2",
	"Entities.gmod_subway_81-717_mvm.Spawner.MaskType.3": "1-4-1 bumper 1",
	"Entities.gmod_subway_81-717_mvm.Spawner.MaskType.4": "1-4-1 bumper 2",
	"Entities.gmod_subway_81-717_mvm.Spawner.MaskType.5": "1-1",
	"Entities.gmod_subway_81-717_mvm.Spawner.MaskType.6": "Retro",
	"Entities.gmod_subway_81-717_mvm.Spawner.LED.Name": "LED",
	"Entities.gmod_subway_81-717_mvm.Spawner.BPSNType.Name": "BPSN type",
	"Entities.gmod_subway_81-717_mvm.Spawner.BPSNType.1": "Oud hoge toon",
	"Entities.gmod_subway_81-717_mvm.Spawner.BPSNType.2": "Oud medium toon",
	"Entities.gmod_subway_81-717_mvm.Spawner.BPSNType.3": "Standaard(SPB)",
	"Entities.gmod_subway_81-717_mvm.Spawner.BPSNType.4": "Standaard(TKL)",
	"Entities.gmod_subway_81-717_mvm.Spawner.BPSNType.5": "Standaard",
	"Entities.gmod_subway_81-717_mvm.Spawner.BPSNType.6": "Kiev",
	"Entities.gmod_subway_81-717_mvm.Spawner.BPSNType.7": "Oud",
	"Entities.gmod_subway_81-717_mvm.Spawner.BPSNType.8": "Standaard 2",
	"Entities.gmod_subway_81-717_mvm.Spawner.BPSNType.9": "Standaard 3",
	"Entities.gmod_subway_81-717_mvm.Spawner.BPSNType.10": "Geen geluid(BPN-115)",
	"Entities.gmod_subway_81-717_mvm.Spawner.KVSnd.Name": "Controller geluid",
	"Entities.gmod_subway_81-717_mvm.Spawner.KVSnd.1": "Type 1",
	"Entities.gmod_subway_81-717_mvm.Spawner.KVSnd.2": "Type 2",
	"Entities.gmod_subway_81-717_mvm.Spawner.KVSnd.3": "Type 3",
	"Entities.gmod_subway_81-717_mvm.Spawner.NewKV.Name": "Nieuw controller model",
	"Entities.gmod_subway_81-717_mvm.Spawner.HornType.Name": "SPB toeter",
	"Entities.gmod_subway_81-717_mvm.Spawner.RingType.Name": "Bel geluid",
	"Entities.gmod_subway_81-717_mvm.Spawner.RingType.1": "Oud",
	"Entities.gmod_subway_81-717_mvm.Spawner.RingType.2": "Standaard met lage toon",
	"Entities.gmod_subway_81-717_mvm.Spawner.RingType.3": "Standaard met hoge toon",
	"Entities.gmod_subway_81-717_mvm.Spawner.RingType.4": "Standaard onderbroken met lage toon",
	"Entities.gmod_subway_81-717_mvm.Spawner.RingType.5": "Standaard onderbroken met hoge toon",
	"Entities.gmod_subway_81-717_mvm.Spawner.NM.Name": "Treinleiding",
	"Entities.gmod_subway_81-717_mvm.Spawner.Battery.Name": "Batterij",
	"Entities.gmod_subway_81-717_mvm.Spawner.Switches.Name": "Stoppen ingeschakeld",
	"Entities.gmod_subway_81-717_mvm.Spawner.SwitchesR.Name": "Willekeurige stoppen",
	"Entities.gmod_subway_81-717_mvm.Spawner.DoorsL.Name": "Open deuren linkerkant",
	"Entities.gmod_subway_81-717_mvm.Spawner.DoorsR.Name": "Open deuren rechterkant",
	"Entities.gmod_subway_81-717_mvm.Spawner.GV.Name": "Hoog-voltage schakelaar",
	"Entities.gmod_subway_81-717_mvm.Spawner.PB.Name": "Parkeerrem",
	"Entities.gmod_subway_81-717_mvm.Spawner.BortLampType.Name": "Type signaallampen",
	"Entities.gmod_subway_81-717_mvm.Spawner.BortLampType.1": "Horizontaal",
	"Entities.gmod_subway_81-717_mvm.Spawner.BortLampType.2": "Verticaal",
	"Entities.gmod_subway_81-717_mvm.Spawner.MVM.Name": "MVM teken",
	"Entities.gmod_subway_81-717_mvm.Spawner.HandRail.Name": "Handvaten model",
	"Entities.gmod_subway_81-717_mvm.Spawner.HandRail.1": "Oud",
	"Entities.gmod_subway_81-717_mvm.Spawner.HandRail.2": "Nieuw",
	"Entities.gmod_subway_81-717_mvm.Spawner.SeatType.Name": "Stoel model",
	"Entities.gmod_subway_81-717_mvm.Spawner.SeatType.1": "Oud",
	"Entities.gmod_subway_81-717_mvm.Spawner.SeatType.2": "Nieuw",
	"Entities.gmod_subway_81-717_mvm.Spawner.LampType.Name": "Verlichting type",
	"Entities.gmod_subway_81-717_mvm.Spawner.LampType.1": "Type 1",
	"Entities.gmod_subway_81-717_mvm.Spawner.LampType.2": "Type 2",
	"Entities.gmod_subway_81-717_mvm.Spawner.LampType.3": "Type 3",
	"Entities.gmod_subway_81-717_mvm.Spawner.Breakers.Name": "Stoppen rechterkant",
	"Entities.gmod_subway_81-717_mvm.Spawner.Adverts.Name": "Advertenties type",
	"Entities.gmod_subway_81-717_mvm.Spawner.Adverts.1": "Type 1",
	"Entities.gmod_subway_81-717_mvm.Spawner.Adverts.2": "Type 2",
	"Entities.gmod_subway_81-717_mvm.Spawner.Adverts.3": "Type 3",
	"Entities.gmod_subway_81-717_mvm.Spawner.Adverts.4": "Geen advertenties",

	"Entities.gmod_subway_81-720.Spawner.Texture.Name": "Kleurstelling",
	"Entities.gmod_subway_81-720.Spawner.PassTexture.Name": "Interieur",
	"Entities.gmod_subway_81-720.Spawner.CabTexture.Name": "Cabine interieur",
	"Entities.gmod_subway_81-720.Spawner.Announcer.Name": "Omroeper",
	"Entities.gmod_subway_81-720.Spawner.Scheme.Name": "Dienstregeling",
	"Entities.gmod_subway_81-720.Spawner.PassSchemesInvert.Name": "Keer dienstregeling om",
	"Entities.gmod_subway_81-720.Spawner.NM.Name": "Treinleiding",
	"Entities.gmod_subway_81-720.Spawner.Battery.Name": "Batterij",
	"Entities.gmod_subway_81-720.Spawner.BRU.Name": "Hoog-voltage schakelaar",
	"Entities.gmod_subway_81-720.Spawner.PVZR.Name": "Willekeurige stoppen (trein)",
	"Entities.gmod_subway_81-720.Spawner.PPZ.Name": "Activeer alle stoppen",
	"Entities.gmod_subway_81-720.Spawner.PPZDepot.Name": "Deactiveer stoppen als in depot",
	"Entities.gmod_subway_81-720.Spawner.PPZR.Name": "Willekeurige stoppen (wagon)",
	"Entities.gmod_subway_81-720.Spawner.DoorsL.Name": "Open deuren linkerkant",
	"Entities.gmod_subway_81-720.Spawner.DoorsR.Name": "Open deuren rechterkant",

	"Entities.gmod_subway_81-722.Spawner.Texture.Name": "Kleurstelling",
	"Entities.gmod_subway_81-722.Spawner.PassTexture.Name": "Interieur",
	"Entities.gmod_subway_81-722.Spawner.CabTexture.Name": "Cabin interieur",
	"Entities.gmod_subway_81-722.Spawner.Announcer.Name": "Omroeper",
	"Entities.gmod_subway_81-722.Spawner.Scheme.Name": "Dienstregeling",
	"Entities.gmod_subway_81-722.Spawner.SarmatInvert.Name": "Keer dienstregeling om",
	"Entities.gmod_subway_81-722.Spawner.NM.Name": "Treinleiding",
	"Entities.gmod_subway_81-722.Spawner.Battery.Name": "Batterij",
	"Entities.gmod_subway_81-722.Spawner.Switches.Name": "Activeer alle stoppen",
	"Entities.gmod_subway_81-722.Spawner.SwitchesR.Name": "Willekeurige stoppen",
	"Entities.gmod_subway_81-722.Spawner.DoorsL.Name": "Open deuren linkerkant",
	"Entities.gmod_subway_81-722.Spawner.DoorsR.Name": "Open deuren rechterkant",

	"Spawner.Close": "Sluiten",
	"Spawner.Spawn": "Klaar"
}
]]
