return [[
{
  "Lang"											: "pl",
  "Name"											: "polski",


  "Entities.gmod_subway_ezh3.Buttons.Stopkran.EmergencyBrakeValveToggle"			: "Hamulec awaryjny",
  "Entities.gmod_subway_ezh3.Buttons.Back.BackDoor"						: "Drzwi tylne",
  "Entities.gmod_subway_ezh3.Buttons.DriverValveBLTLDisconnect.DriverValveBLDisconnectToggle"	: "Zawór dwudrożny przewodu głównego",
  "Entities.gmod_subway_ezh3.Buttons.DriverValveBLTLDisconnect.DriverValveTLDisconnectToggle"	: "Zawór dwudrożny przewodu zasilającego",
  "Entities.gmod_subway_ezh3.Buttons.Battery.VBToggle"						: "AB: Włącznik akumulatorów baterii",
  "Entities.gmod_subway_ezh3.Buttons.FrontPneumatic.FrontBrakeLineIsolationToggle"		: "Zawór przewodu głównego sprzęgu powietrznego",
  "Entities.gmod_subway_ezh3.Buttons.FrontPneumatic.FrontTrainLineIsolationToggle"		: "Zawór przewodu zasilającegosprzęgu powietrznego",
  "Entities.gmod_subway_ezh3.Buttons.ASNP.R_ASNPMenuSet"					: "Informator: Menu",
  "Entities.gmod_subway_ezh3.Buttons.ASNP.R_ASNPUpSet"						: "Informator: W górę",
  "Entities.gmod_subway_ezh3.Buttons.ASNP.R_ASNPDownSet"					: "Informator: W dół",
  "Entities.gmod_subway_ezh3.Buttons.ASNP.R_ASNPOnToggle"					: "Informator: Włączenie",
  "Entities.gmod_subway_ezh3.Buttons.PassengerDoor1.PassengerDoor"				: "Drzwi do klasy",
  "Entities.gmod_subway_ezh3.Buttons.PassengerDoor.PassengerDoor"				: "Drzwi do klasy",
  "Entities.gmod_subway_ezh3.Buttons.CabinDoor.CabinDoor"					: "Drzwi do kabiny",
  "Entities.gmod_subway_ezh3.Buttons.Front.FrontDoor"						: "Drzwi przednie",
  "Entities.gmod_subway_ezh3.Buttons.GV.GVToggle"						: "Wyłącznik główny",
  "Entities.gmod_subway_ezh3.Buttons.RearPneumatic.RearTrainLineIsolationToggle"		: "Zawór przewodu zasilającego sprzęgu powietrznego",
  "Entities.gmod_subway_ezh3.Buttons.RearPneumatic.RearBrakeLineIsolationToggle"		: "Zawór przewodu głównego sprzęgu powietrznego",
  "Entities.gmod_subway_ezh3.Buttons.Panel.!OCH"						: "ОЧ: Kontrolka braku sygnału ARS",
  "Entities.gmod_subway_ezh3.Buttons.Panel.!0"							: "0: Kontrolka sygnału zatrzymania ARS",
  "Entities.gmod_subway_ezh3.Buttons.Panel.!40"							: "40: Kontrolka ograniczenia prędkości do 40 km/h",
  "Entities.gmod_subway_ezh3.Buttons.Panel.!60"							: "60: Kontrolka ograniczenia prędkości do 60 km/h",
  "Entities.gmod_subway_ezh3.Buttons.Panel.!70"							: "70: Kontrolka ograniczenia prędkości do 70 km/h",
  "Entities.gmod_subway_ezh3.Buttons.Panel.!80"							: "80: Kontrolka ograniczenia prędkości do 80 km/h",
  "Entities.gmod_subway_ezh3.Buttons.Panel.!Speedometer"					: "Wskaźnik prędkości [km/h]",
  "Entities.gmod_subway_ezh3.Buttons.Panel.!TotalAmpermeter"					: "Amperomierz WN [А]",
  "Entities.gmod_subway_ezh3.Buttons.Panel.!TotalVoltmeter"					: "Woltomierz WN [kV]",
  "Entities.gmod_subway_ezh3.Buttons.Panel.!BatteryVoltage"					: "Napięcie akumulatorów baterii [V]",
  "Entities.gmod_subway_ezh3.Buttons.Panel.!BrakeCylinder"					: "Ciśnienie w cylindrach hamulcowych",
  "Entities.gmod_subway_ezh3.Buttons.Panel.!LinesPressure"					: "Ciśnienie w zbiorniku (czarna) i przewodzie głównym (czerwona)",
  "Entities.gmod_subway_ezh3.Buttons.Main.KU1Toggle"						: "VMK: Włączenie sprężarki",
  "Entities.gmod_subway_ezh3.Buttons.Main.SAMM1Set"						: "САММ: Wyłączenie rozruchu",
  "Entities.gmod_subway_ezh3.Buttons.Main.SAMM2Set"						: "САММ: Start",
  "Entities.gmod_subway_ezh3.Buttons.Main.SAMM3Set"						: "САММ: Reset",
  "Entities.gmod_subway_ezh3.Buttons.Main.SAMMSignal1"						: "Kontrolka: Jazda-hamowanie",
  "Entities.gmod_subway_ezh3.Buttons.Main.SAMMSignal2"						: "Kontrolka: Działanie САММ",
  "Entities.gmod_subway_ezh3.Buttons.Main.SAMMSignal3"						: "Kontrolka: Włączona jednostka wykonawcza САММ",
  "Entities.gmod_subway_ezh3.Buttons.Main.SAMMOnToggle"						: "САММ: Włączenie sytemu automatycznego prowadzenia składu",
  "Entities.gmod_subway_ezh3.Buttons.Main.SAMMBlokToggle"					: "САММ: Jednostka wykonawcza",
  "Entities.gmod_subway_ezh3.Buttons.Main.SAMMCommand3Set"					: "САММ: X-2",
  "Entities.gmod_subway_ezh3.Buttons.Main.SAMMCommand2Set"					: "САММ: Doganianie rozkładu",
  "Entities.gmod_subway_ezh3.Buttons.Main.SAMMCommand1Set"					: "САММ: Zezwolenie",
  "Entities.gmod_subway_ezh3.Buttons.Main.KSNSet"						: "КСН: Sygnalizacja usterki",
  "Entities.gmod_subway_ezh3.Buttons.Main.R_Program1Set"					: "Zapowiedź 1",
  "Entities.gmod_subway_ezh3.Buttons.Main.R_Program2Set"					: "Zapowiedź 2",
  "Entities.gmod_subway_ezh3.Buttons.Main.VUSToggle"						: "Przyciemnianie świateł jezdnych",
  "Entities.gmod_subway_ezh3.Buttons.Main.L_3Toggle"						: "Oświetlenie przyrządów",
  "Entities.gmod_subway_ezh3.Buttons.Main.VAHToggle"						: "Jazda awaryjna",
  "Entities.gmod_subway_ezh3.Buttons.Main.DIPonSet"						: "Włączanie oświetlenia",
  "Entities.gmod_subway_ezh3.Buttons.Main.DIPoffSet"						: "Wyłączanie oświetlenia",
  "Entities.gmod_subway_ezh3.Buttons.Main.KSDSet"						: "KSD: Sprawdzanie sygnalizacji drzwi",
  "Entities.gmod_subway_ezh3.Buttons.Main.KVTSet"						: "КВТ: Kasowanie hamowania ARS",
  "Entities.gmod_subway_ezh3.Buttons.Main.KBSet"						: "КB: Czuwak (przycisk)",
  "Entities.gmod_subway_ezh3.Buttons.Main.KBLamp"						: "LHRK: Ruch reostatu",
  "Entities.gmod_subway_ezh3.Buttons.Main.ARSToggle"						: "АRS: Automatyczna regulacja prędkości",
  "Entities.gmod_subway_ezh3.Buttons.Main.R_UNchToggle"						: "UNCh: Wzmacniacz niskich częstotliwości",
  "Entities.gmod_subway_ezh3.Buttons.Main.VUD1Toggle"						: "VUD: Włącznik sterowania drzwiami",
  "Entities.gmod_subway_ezh3.Buttons.Main.R_RadioToggle"					: "Zapowiedzi głosowe (wbudowane)",
  "Entities.gmod_subway_ezh3.Buttons.Main.ALSToggle"						: "АLS: Automatyczna sygnalizacja pociągu",
  "Entities.gmod_subway_ezh3.Buttons.Main.VozvratRPSet"						: "KVRP: Odblokowanie przekaźnika nadmiarowego",
  "Entities.gmod_subway_ezh3.Buttons.Main.RingSet"						: "Dzwonek",
  "Entities.gmod_subway_ezh3.Buttons.Main.L_2Toggle"						: "Oświetlenie kabiny",
  "Entities.gmod_subway_ezh3.Buttons.Main.KRZDSet"						: "KRZD: Awaryjne zamykanie drzwi",
  "Entities.gmod_subway_ezh3.Buttons.Main.KDPSet"						: "KDP: Otwieranie prawych drzwi",
  "Entities.gmod_subway_ezh3.Buttons.Main.KDLSet"						: "KDL: Otwieranie lewych drzwi",
  "Entities.gmod_subway_ezh3.Buttons.Main.KAHSet"						: "KAH: Jazda awaryjna",
  "Entities.gmod_subway_ezh3.Buttons.Main.RezMKSet"						: "Awaryjne załączanie sprężarki",
  "Entities.gmod_subway_ezh3.Buttons.Main.KRPSet"						: "KRP: Rozruch awaryjny",
  "Entities.gmod_subway_ezh3.Buttons.Main.RSTToggle"						: "VPR: Załączenie radiostacji",
  "Entities.gmod_subway_ezh3.Buttons.Main.R_GToggle"						: "Głośnik (dźwięk w kabinie)",
  "Entities.gmod_subway_ezh3.Buttons.Main.R_ZSToggle"						: "ZS: Nagłośnienie klasy",
  "Entities.gmod_subway_ezh3.Buttons.Main.Custom2Set"						: "Nieużywany przełącznik",
  "Entities.gmod_subway_ezh3.Buttons.Main.Custom3Set"						: "Nieużywany przełącznik",
  "Entities.gmod_subway_ezh3.Buttons.Main.ASNPPlay"						: "Odtwarzanie zapowiedzi",
  "Entities.gmod_subway_ezh3.Buttons.AV1.VU3Toggle"						: "VU3: Oświetlenie kabiny",
  "Entities.gmod_subway_ezh3.Buttons.AV1.VU2Toggle"						: "VU2: Awaryjne oświetlenie (45 V)",
  "Entities.gmod_subway_ezh3.Buttons.AV1.VU1Toggle"						: "VU1: Ogrzewanie kabiny (3 kW)\n",
  "Entities.gmod_subway_ezh3.Buttons.AVMain.AV8BToggle"						: "АV-8B: Wyłącznik automatyczny WN",
  "Entities.gmod_subway_ezh3.Buttons.RC1.RC1Toggle"						: "RC_ARS: Odłączenie obwodów ARS",
  "Entities.gmod_subway_ezh3.Buttons.UAVAPanel.UAVAToggle"					: "UAVA: Wyłączenie autostopu",
  "Entities.gmod_subway_ezh3.Buttons.UAVAPanel.UAVAContactSet"					: "UAVA: odblokowanie przekaźników",
  "Entities.gmod_subway_ezh3.Buttons.VUHelper.VUToggle"						: "VU: Wyłącznik sterowania",
  "Entities.gmod_subway_ezh3.Buttons.HelperPanel.VDLSet"					: "VDL: Otwieranie lewych drzwi",
  "Entities.gmod_subway_ezh3.Buttons.HelperPanel.VUD2Toggle"					: "VUD2: Włącznik sterowania drzwiami",
  "Entities.gmod_subway_ezh3.Buttons.EPKDisconnect.EPKToggle"					: "EPV: Zawór elektropneumatyczny",
  "Entities.gmod_subway_ezh3.Buttons.VU.VUToggle"						: "VU: Sterowanie pociągiem",
  "Entities.gmod_subway_ezh3.Buttons.ParkingBrake.ParkingBrakeLeft"				: "Powrót koła hamulca ręcznego",
  "Entities.gmod_subway_ezh3.Buttons.ParkingBrake.ParkingBrakeRight"				: "Powrót koła hamulca ręcznego",
  "Entities.gmod_subway_ezh3.Buttons.AirDistributor.AirDistributorDisconnectToggle"		: "Blokada dystrybutora powietrza",

  "Entities.gmod_subway_em508t.Buttons.Stopkran.EmergencyBrakeValveToggle"			: "Hamulec awaryjny",
  "Entities.gmod_subway_em508t.Buttons.Battery.VBToggle"					: "AB: Włącznik akumulatorów baterii (obwody wspomagające NN)",
  "Entities.gmod_subway_em508t.Buttons.FrontPneumatic.FrontBrakeLineIsolationToggle"		: "Zawór przewodu głównego sprzęgu powietrznego",
  "Entities.gmod_subway_em508t.Buttons.FrontPneumatic.FrontTrainLineIsolationToggle"		: "Zawór przewodu zasilającego sprzęgu powietrznego",
  "Entities.gmod_subway_em508t.Buttons.GV.GVToggle"						: "Wyłącznik główny",
    "Entities.gmod_subway_em508t.Buttons.RearPneumatic.RearTrainLineIsolationToggle"		: "Zawór przewodu zasilającego sprzęgu powietrznego",
  "Entities.gmod_subway_em508t.Buttons.RearPneumatic.RearBrakeLineIsolationToggle"		: "Zawór przewodu głównego sprzęgu powietrznego",
  "Entities.gmod_subway_em508t.Buttons.RearDoor.RearDoor"					: "Drzwi do klasy",
  "Entities.gmod_subway_em508t.Buttons.Back2.!HVFuse"						: "Blok bezpieczników WN",
  "Entities.gmod_subway_em508t.Buttons.Back2.!Relays"						: "Skrzynia aparatów ładowania baterii akumulatorów i dystrybucji powietrza do siłowników drzwi",
  "Entities.gmod_subway_em508t.Buttons.Back2.!Heater"						: "Farelka",
  "Entities.gmod_subway_em508t.Buttons.Front.FrontDoor"						: "Drzwi przednie",
  "Entities.gmod_subway_em508t.Buttons.AV1.VU3Toggle"						: "VU3: Oświetlenie kabiny\n",
  "Entities.gmod_subway_em508t.Buttons.AV1.VU2Toggle"						: "VU2: Awaryjne oświetlenie (45 V)",
  "Entities.gmod_subway_em508t.Buttons.AV1.VU1Toggle"						: "VU1: Ogrzewanie kabiny (3 kW)",
  "Entities.gmod_subway_em508t.Buttons.ParkingBrake.ParkingBrakeLeft"				: "Powrót koła hamulca ręcznego",
  "Entities.gmod_subway_em508t.Buttons.ParkingBrake.ParkingBrakeRight"				: "Powrót koła hamulca ręcznego",
  "Entities.gmod_subway_em508t.Buttons.CabinDoor.CabinDoor1"					: "Drzwi do kabiny",
  "Entities.gmod_subway_em508t.Buttons.PassengerDoor.PassengerDoor"				: "Drzwi do klasy",
  "Entities.gmod_subway_em508t.Buttons.PassengerDoor1.PassengerDoor"				: "Drzwi do klasy",
  "Entities.gmod_subway_em508t.Buttons.Main.!RedRP"						: "RP: Obwody mocy nie załączyły się",
  "Entities.gmod_subway_em508t.Buttons.Main.!GreenRP"						: "RP: Zadziałanie przekaźnika nadmiarowego",
  "Entities.gmod_subway_em508t.Buttons.Main.!SD"						: "SD: Sygnalizacja drzwi",
  "Entities.gmod_subway_em508t.Buttons.Main.KDLSet"						: "Otwieranie lewych drzwi",
  "Entities.gmod_subway_em508t.Buttons.Main.KSDSet"						: "KSD: Sprawdzanie sygnalizacji drzwi",
  "Entities.gmod_subway_em508t.Buttons.Main.VozvratRPSet"					: "VozvratRP: Odblokowanie przekaźnika nadmiarowego",
  "Entities.gmod_subway_em508t.Buttons.Main.KSNSet"						: "Sygnalizacja usterki",
  "Entities.gmod_subway_em508t.Buttons.Main.VUD1Toggle"						: "Włącznik sterowania drzwiami",
  "Entities.gmod_subway_em508t.Buttons.Main.KU1Toggle"						: "Włącznik sprężarki",
  "Entities.gmod_subway_em508t.Buttons.Main.DIPonSet"						: "KU4: Włączanie oświetlenia",
  "Entities.gmod_subway_em508t.Buttons.Main.DIPoffSet"						: "KU5: Wyłączanie oświetlenia",
  "Entities.gmod_subway_em508t.Buttons.Main.RezMKSet"						: "Awaryjne załączanie sprężarki",
  "Entities.gmod_subway_em508t.Buttons.Main.KDPSet"						: "KDP: Otwieranie prawych drzwi",
  "Entities.gmod_subway_em508t.Buttons.Main.KRZDSet"						: "KU10: Awaryjne zamykanie drzwi",
  "Entities.gmod_subway_em508t.Buttons.AVMain.AV8BToggle"					: "АV-8B: Wyłącznik automatyczny WN",
  "Entities.gmod_subway_em508t.Buttons.VU.VUToggle"						: "VU: Wyłącznik sterowania",
  "Entities.gmod_subway_em508t.Buttons.VU.!Voltage"						: "Napięcie obwodów sterowania",
  "Entities.gmod_subway_em508t.Buttons.HelperPanel.VUD2Toggle"					: "VUD2: Włącznik sterowania drzwiami",
  "Entities.gmod_subway_em508t.Buttons.HelperPanel.VDLSet"					: "VDL: Otwieranie lewych drzwi",
  "Entities.gmod_subway_em508t.Buttons.DriverValveBLTLDisconnect.DriverValveBLDisconnectToggle"	: "Zawór dwudrożny przewodu głównego",
  "Entities.gmod_subway_em508t.Buttons.DriverValveBLTLDisconnect.DriverValveTLDisconnectToggle"	: "Zawór dwudrożny przewodu zasilającego",
  "Entities.gmod_subway_em508t.Buttons.AirDistributor.AirDistributorDisconnectToggle"		: "Blokada dystrybutora powietrza"
}
]]
