return [[
{
  "Lang": "pl",
  "Name": "polski",
  "Panel.Admin": "Admin",
  "Panel.Client": "Klient",
  "Panel.DrawDebugInfo": "Rysuj debuginfo",
  "Panel.DisableCamAccel": "Wyłącz ruch kamery przy przyspieszeniu",
  "Panel.DisableHoverText": "Wyłącz tekst pod kursorem",

  "Entities.gmod_subway_base.Name": "Baza pociągu",
  "Entities.gmod_subway_81-703.Name": "81-703 (końcowy)",
  "Entities.gmod_subway_81-703_2.Name": "81-703 (środkowy)",
  "Entities.gmod_subway_81-717_mvm.Name": "81-717 (MVM)",
  "Entities.gmod_subway_81-717_lvz.Name": "81-717 (LVZ)",
  "Entities.gmod_subway_81-714_mvm.Name": "81-714 (MVM)",
  "Entities.gmod_subway_81-714_lvz.Name": "81-714 (LVZ)",
  "Entities.gmod_subway_81-7036.Name": "81-7036 (nie działa)",
  "Entities.gmod_subway_81-7037.Name": "81-7037 (nie działa)",
  "Entities.gmod_subway_81-720.Name": "81-720 (końcowy)",
  "Entities.gmod_subway_81-721.Name": "81-721 (środkowy)",
  "Entities.gmod_subway_81-722.Name": "81-722 (końcowy)",
  "Entities.gmod_subway_81-723.Name": "81-723 (środkowy toczny)",
  "Entities.gmod_subway_81-724.Name": "81-724 (środkowy napędowy)",
  "Entities.gmod_subway_e.Name": "E",
  "Entities.gmod_subway_em.Name": "Em",
  "Entities.gmod_subway_ema.Name": "Ema",
  "Entities.gmod_subway_ezh.Name": "Ezh (ARS-MP)",
  "Entities.gmod_subway_ezh1.Name": "Ezh1",
  "Entities.gmod_subway_em508.Name": "Em-508",
  "Entities.gmod_subway_em508_int.Name": "Em-508 (środkowy)",
  "Entities.gmod_subway_ezh3.Name": "Ezh3",
  "Entities.gmod_subway_ezh3ru1.Name": "Ezh3 RU1",
  "Entities.gmod_subway_ema508t.Name": "Em-508t",
  "Entities.gmod_subway_tatra_t3.Name": "Tatra T3",
  "Entities.gmod_subway_ai.Name": "Pociąg SI",

  "Entities.gmod_train_bogey.Name": "Wózek szynowy",
  "Entities.gmod_train_couple.Name": "Sprzęg",

  "Entities.gmod_track_pui.Name": "Zegar PUI",
  "Entities.gmod_track_mus_elektronika7.Name": "Zegar \"Electronica\"",
  "Entities.gmod_mus_clock_analog.Name": "Zegar analogowy",
  "Entities.gmod_track_clock_time.Name": "Duży zegar interwałowy (czas)",
  "Entities.gmod_track_clock_small.Name": "Mały zegar interwałowy",
  "Entities.gmod_track_clock_interval.Name": "Duży zegar interwałowy (interwał)",
  "Entities.gmod_track_switch.Name": "Rozjazd",
  "Entities.gmod_track_powermeter.Name": "Kilowatomierz",
  "Entities.gmod_track_udochka.Name": "Łącznik WN (udochka)",
  "Entities.gmod_train_spawner.Name": "Spawner pociągów"
}
]]
