return [[
{
 "Lang": "pl",
 "Name": "polski",

 "Entities.gmod_subway_81-717_mvm.Buttons.HelperPanel.VUD2Toggle": "VUD2: Sterowanie drzwiami (zamykanie)",
 "Entities.gmod_subway_81-717_mvm.Buttons.HelperPanel.VDLSet": "VDL: Otwieranie lewych drzwi",
 "Entities.gmod_subway_81-717_mvm.Buttons.HelperPanel.R_Program2Helper": "Zapowiedź 2",
 "Entities.gmod_subway_81-717_mvm.Buttons.HelperPanel.R_Program1Helper": "Zapowiedź 1",
 "Entities.gmod_subway_81-717_mvm.Buttons.Battery_2.1:RC1Toggle": "RC-1: Odłączenie obwodów ARS",
 "Entities.gmod_subway_81-717_mvm.Buttons.Battery_2.1:VBToggle": "VB: Baterie akumulatorów",
 "Entities.gmod_subway_81-717_mvm.Buttons.Battery_2.1:UOSToggle": "RC-UOS: Urządzenie ograniczenia prędkości",
 "Entities.gmod_subway_81-717_mvm.Buttons.Wiper.WiperToggle": "Wycieraczka",
 "Entities.gmod_subway_81-717_mvm.Buttons.DriverValveDisconnect.DriverValveDisconnectToggle": "Zawór odłączający",
 "Entities.gmod_subway_81-717_mvm.Buttons.DriverValveDisconnect.DriverValveBLDisconnectToggle": "Zawór dwudrożny przewodu zasilającego",
 "Entities.gmod_subway_81-717_mvm.Buttons.Main.R_UNchToggle": "UNCh: Wzmacniacz niskich częstotliwości",
 "Entities.gmod_subway_81-717_mvm.Buttons.Main.R_ZSToggle": "ZS: Nagłośnienie klasy",
 "Entities.gmod_subway_81-717_mvm.Buttons.Main.R_GToggle": "Głośnik (dźwięk w kabinie)",
 "Entities.gmod_subway_81-717_mvm.Buttons.Main.R_RadioToggle": "Zapowiedzi głosowe (wbudowane)",
 "Entities.gmod_subway_81-717_mvm.Buttons.Main.R_Program1Set": "Zapowiedź 1",
 "Entities.gmod_subway_81-717_mvm.Buttons.Main.R_Program2Set": "Zapowiedź 2",
 "Entities.gmod_subway_81-717_mvm.Buttons.Main.2:KVTSet": "KB: Czuwak (przycisk)",
 "Entities.gmod_subway_81-717_mvm.Buttons.Main.VZ1Set": "VZ1: Zawór pneumatyczny #1",
 "Entities.gmod_subway_81-717_mvm.Buttons.Main.VUD1Toggle": "VUD: Przełącznik sterowania drzwiami (zamykanie)",
 "Entities.gmod_subway_81-717_mvm.Buttons.Main.KDLSet": "KDL: Otwieranie lewych drzwi",
 "Entities.gmod_subway_81-717_mvm.Buttons.Main.KDLKToggle": "Klapka przycisku KDL",
 "Entities.gmod_subway_81-717_mvm.Buttons.Main.KDLRSet": "KDL: Otwieranie lewych drzwi",
 "Entities.gmod_subway_81-717_mvm.Buttons.Main.KDLRKToggle": "Klapka przycisku KDL",
 "Entities.gmod_subway_81-717_mvm.Buttons.Main.DoorSelectToggle": "Wybór strony otwierania drzwi",
 "Entities.gmod_subway_81-717_mvm.Buttons.Main.KRZDSet": "RZD: Awaryjne zamykanie drzwi",
 "Entities.gmod_subway_81-717_mvm.Buttons.Main.R_VPRToggle": "VPR: Załączanie radiostacji",
 "Entities.gmod_subway_81-717_mvm.Buttons.Main.VozvratRPSet": "Odblokowanie przekaźnika nadmiarowego",
 "Entities.gmod_subway_81-717_mvm.Buttons.Main.GreenRPLight": "RP: Zadziałanie przekaźnika nadmiarowego",
 "Entities.gmod_subway_81-717_mvm.Buttons.Main.AVULight": "AVU: Automatyczny wyłącznik sterowania",
 "Entities.gmod_subway_81-717_mvm.Buttons.Main.LKVPLight": "LKVP: Przetwornica WN",
 "Entities.gmod_subway_81-717_mvm.Buttons.Main.SPLight": "LSP: Kontrolka sygnalizacji pożaru",
 "Entities.gmod_subway_81-717_mvm.Buttons.Main.ConverterProtectionSet": "Ochrona przetwornicy",
 "Entities.gmod_subway_81-717_mvm.Buttons.Main.KSNSet": "KSN: Sygnalizacja usterki",
 "Entities.gmod_subway_81-717_mvm.Buttons.Main.DIPoffSet": "Dzwonek",
 "Entities.gmod_subway_81-717_mvm.Buttons.Main.ARSToggle": "ARS: Automatyczna regulacja prędkości",
 "Entities.gmod_subway_81-717_mvm.Buttons.Main.ALSToggle": "ALS: Automatyczna sygnalizacja pociągu",
 "Entities.gmod_subway_81-717_mvm.Buttons.Main.OtklAVUToggle": "Wyłączanie automatycznego odcinania sterowania (niesprawność AVU)",
 "Entities.gmod_subway_81-717_mvm.Buttons.Main.TormATToggle": "(placeholder) Hamulec awaryjny",
 "Entities.gmod_subway_81-717_mvm.Buttons.Main.L_1Toggle": "Oświetlenie klasy",
 "Entities.gmod_subway_81-717_mvm.Buttons.Main.L_2Toggle": "Oświetlenie kabiny",
 "Entities.gmod_subway_81-717_mvm.Buttons.Main.L_3Toggle": "Oświetlenie pulpitu",
 "Entities.gmod_subway_81-717_mvm.Buttons.Main.ALSFreqToggle": "Dekoder: Przełącznik trybu ALS (1/5 lub 2/6)",
 "Entities.gmod_subway_81-717_mvm.Buttons.Main.ParkingBrakeSignToggle": "Tabliczka \"ZWOLNIJ HAMULEC POSTOJOWY\"",
 "Entities.gmod_subway_81-717_mvm.Buttons.ParkingBrake.ParkingBrakeToggle": "Hamulec postojowy",
 "Entities.gmod_subway_81-717_mvm.Buttons.ParkingBrake.DriverValveTLDisconnectToggle": "Zawór dwudrożny przewodu zasilającego",
 "Entities.gmod_subway_81-717_mvm.Buttons.IGLAButtons.IGLA1Set": "IGLA: Przycisk pierwszy",
 "Entities.gmod_subway_81-717_mvm.Buttons.IGLAButtons.IGLA2Set": "IGLA: Przycisk drugi",
 "Entities.gmod_subway_81-717_mvm.Buttons.IGLAButtons.IGLA3Set": "IGLA: Przycisk trzeci",
 "Entities.gmod_subway_81-717_mvm.Buttons.IGLAButtons.IGLA4Set": "IGLA: Przycisk czwarty",
 "Entities.gmod_subway_81-717_mvm.Buttons.BPSNFront.!Voltage": "Zasilanie obwodu sterowania",
 "Entities.gmod_subway_81-717_mvm.Buttons.BPSNFront.VMKToggle": "Włączanie sprężarki",
 "Entities.gmod_subway_81-717_mvm.Buttons.BPSNFront.BPSNonToggle": "BPSN: Zasilanie systemów pociągu",
 "Entities.gmod_subway_81-717_mvm.Buttons.BPSNFront.RezMKSet": "Awaryjne załączenie sprężarki",
 "Entities.gmod_subway_81-717_mvm.Buttons.BPSNFront.ARS13Set": "ARS 13V: Sprawdzenie stabilizowanego napięcia ARS",
 "Entities.gmod_subway_81-717_mvm.Buttons.Schedule.!RouteNum": "М №\nRoute number",
 "Entities.gmod_subway_81-717_mvm.Buttons.Schedule.!PathNum": "П №\nPath number",
 "Entities.gmod_subway_81-717_mvm.Buttons.Schedule.!SchTime": "ВРЕМЯ ХОДА\nTotal schedule time",
 "Entities.gmod_subway_81-717_mvm.Buttons.Schedule.!SchInterval": "ИНТ\nTrain interval",
 "Entities.gmod_subway_81-717_mvm.Buttons.Schedule.!SchHour": "ЧАС\nHour",
 "Entities.gmod_subway_81-717_mvm.Buttons.Schedule.!SchMin": "МИН\nMinute",
 "Entities.gmod_subway_81-717_mvm.Buttons.Schedule.!SchSec": "СЕК\nSecond",
 "Entities.gmod_subway_81-717_mvm.Buttons.Schedule.!SchArrival": "Arrival times",
 "Entities.gmod_subway_81-717_mvm.Buttons.Schedule.!SchStations": "Station name",
 "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!Speedometer": "Wskaźnik prędkości",
 "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!LampLSN": "LSN: Kontrolka sygnalizacji niesprawności",
 "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!LampRP": "RP: Kontrolka przekaźnika nadmiarowego",
 "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!LampLHRK": "LhRK: Ruch reostatu",
 "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!LampLKT": "LKT: ARS -- hamowanie",
 "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!LampLKVD": "LKVD: ARS -- wyłączenie silników",
 "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!LampLKVC": "LKVC: Kontrolka stycznika WN",
 "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!ARSOch": "OCh: Brak częstotliwości ARS",
 "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!ARS0": "0: Sygnał ARS zatrzymania",
 "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!ARS40": "Ograniczenie prędkości do 40 km/h",
 "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!ARS60": "Ograniczenie prędkości do 60 km/h",
 "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!ARS70": "Ograniczenie prędkości do 70 km/h",
 "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!ARS80": "Ograniczenie prędkości do 80 km/h",
 "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!LampLSD1": "LSD: Sygnalizacja drzwi (drzwi zamknięte)",
 "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!LampLSD2": "LSD: Sygnalizacja drzwi (drzwi zamknięte)",
 "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!LampLST": "LST: Kontrolka sygnalizacji hamowania",
 "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!LampLVD": "LVD: Kontrolka działania silników",
 "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!LampLN": "LN: Kontrolka kierunku",
 "Entities.gmod_subway_81-717_mvm.Buttons.ARS.!LampLRS": "LRS: Kontrolka równości ograniczeń prędkości",
 "Entities.gmod_subway_81-717_mvm.Buttons.PneumaticPanels.!CylinderPressure": "Ciśnienie w cylindach hamulcowych",
 "Entities.gmod_subway_81-717_mvm.Buttons.PneumaticPanels.!LinePressure": "Ciśnienie w zbiorniku (czarna) i przewodzie głównym (czerwona)",
 "Entities.gmod_subway_81-717_mvm.Buttons.Battery.RC1Toggle": "RC-1: Odłączenie obwodów ARS",
 "Entities.gmod_subway_81-717_mvm.Buttons.Battery.UOSToggle": "RC-UOS: Urządzenie ograniczenia prędkości",
 "Entities.gmod_subway_81-717_mvm.Buttons.Battery.VBToggle": "VB: Bateria akumulatorów",
 "Entities.gmod_subway_81-717_mvm.Buttons.FrontPneumatic.FrontBrakeLineIsolationToggle": "Zawór przewodu głównego sprzęgu powietrznego",
 "Entities.gmod_subway_81-717_mvm.Buttons.FrontPneumatic.FrontTrainLineIsolationToggle": "Zawór przewodu zasilającego sprzęgu powietrznego",
 "Entities.gmod_subway_81-717_mvm.Buttons.ASNP.R_ASNPMenuSet": "ASNP: Menu",
 "Entities.gmod_subway_81-717_mvm.Buttons.ASNP.R_ASNPUpSet": "ASNP: W górę",
 "Entities.gmod_subway_81-717_mvm.Buttons.ASNP.R_ASNPDownSet": "ASNP: W dół",
 "Entities.gmod_subway_81-717_mvm.Buttons.ASNP.R_ASNPOnToggle": "ASNP: Włączenie",
 "Entities.gmod_subway_81-717_mvm.Buttons.RearDoor.RearDoor": "Przednie drzwi",
 "Entities.gmod_subway_81-717_mvm.Buttons.Meters.!TotalVoltmeter": "Woltomierz WN [kV]",
 "Entities.gmod_subway_81-717_mvm.Buttons.Meters.!TotalAmpermeter": "Amperomierz [A]",
 "Entities.gmod_subway_81-717_mvm.Buttons.AV.A61Toggle": "A61 Sterowanie przewodem 6",
 "Entities.gmod_subway_81-717_mvm.Buttons.AV.A55Toggle": "A55 Sterowanie przewodem 10AS",
 "Entities.gmod_subway_81-717_mvm.Buttons.AV.A54Toggle": "A54 Sterowanie przewodem 10AK",
 "Entities.gmod_subway_81-717_mvm.Buttons.AV.A56Toggle": "A56 Włączenie akumulatorów baterii",
 "Entities.gmod_subway_81-717_mvm.Buttons.AV.A27Toggle": "A27 Włączenie DIP (komplementarnej jednostki zasilania) i oświetlenia",
 "Entities.gmod_subway_81-717_mvm.Buttons.AV.A21Toggle": "A21 Sterowanie drzwiami",
 "Entities.gmod_subway_81-717_mvm.Buttons.AV.A10Toggle": "A10 Sterowanie sprężarką",
 "Entities.gmod_subway_81-717_mvm.Buttons.AV.A53Toggle": "A53 Zasilanie stycznika obwodów WN",
 "Entities.gmod_subway_81-717_mvm.Buttons.AV.A43Toggle": "A43 Zasilanie 12 V systemu ARS",
 "Entities.gmod_subway_81-717_mvm.Buttons.AV.A45Toggle": "A45 Przewód ARS 10AU",
 "Entities.gmod_subway_81-717_mvm.Buttons.AV.A42Toggle": "A42 Zasilanie 75 V systemu ARS",
 "Entities.gmod_subway_81-717_mvm.Buttons.AV.A41Toggle": "A41 Hamowanie ARS",
 "Entities.gmod_subway_81-717_mvm.Buttons.AV.VUToggle": "VU Sterowanie pociągiem",
 "Entities.gmod_subway_81-717_mvm.Buttons.AV.A64Toggle": "A64 Oświetlenie kabiny",
 "Entities.gmod_subway_81-717_mvm.Buttons.AV.A63Toggle": "A63 IGLA/BIS (jednostka prędkościomierza)",
 "Entities.gmod_subway_81-717_mvm.Buttons.AV.A50Toggle": "A50 Włączenie DIP i oświetlenia",
 "Entities.gmod_subway_81-717_mvm.Buttons.AV.A51Toggle": "A51 Wyłączenie DIP i oświetlenia",
 "Entities.gmod_subway_81-717_mvm.Buttons.AV.A23Toggle": "A23 Awaryjne załączanie sprężarki",
 "Entities.gmod_subway_81-717_mvm.Buttons.AV.A14Toggle": "A14 Przewód 18",
 "Entities.gmod_subway_81-717_mvm.Buttons.AV.A75Toggle": "A75 Ogrzewanie kabiny",
 "Entities.gmod_subway_81-717_mvm.Buttons.AV.A1Toggle": "A1 X-1",
 "Entities.gmod_subway_81-717_mvm.Buttons.AV.A2Toggle": "A2 X-2",
 "Entities.gmod_subway_81-717_mvm.Buttons.AV.A3Toggle": "A3 X-3",
 "Entities.gmod_subway_81-717_mvm.Buttons.AV.A17Toggle": "A17 Odblokowywanie przekaźnika nadmiarowego",
 "Entities.gmod_subway_81-717_mvm.Buttons.AV.A62Toggle": "A62 Łączność radiowa",
 "Entities.gmod_subway_81-717_mvm.Buttons.AV.A29Toggle": "A29 Nadawanie radiowe",
 "Entities.gmod_subway_81-717_mvm.Buttons.AV.A5Toggle": "A5 ASNP: Automatyczny czytnik numeru pociągu",
 "Entities.gmod_subway_81-717_mvm.Buttons.AV.A6Toggle": "A6 T-1",
 "Entities.gmod_subway_81-717_mvm.Buttons.AV.A8Toggle": "A8 Zawory pneumatyczne #1 i #2",
 "Entities.gmod_subway_81-717_mvm.Buttons.AV.A20Toggle": "A20 Sterowanie jazdą i hamowaniem, przewód 20",
 "Entities.gmod_subway_81-717_mvm.Buttons.AV.A25Toggle": "A25 Ręczne hamowanie elektrodynamiczne",
 "Entities.gmod_subway_81-717_mvm.Buttons.AV.A22Toggle": "A22 Zasilanie stycznika sprężarki",
 "Entities.gmod_subway_81-717_mvm.Buttons.AV.A30Toggle": "A30 Zasilanie silnika reostatu",
 "Entities.gmod_subway_81-717_mvm.Buttons.AV.A39Toggle": "A39 Sterowanie awaryjne",
 "Entities.gmod_subway_81-717_mvm.Buttons.AV.A44Toggle": "A44 Awaryjne sterowanie pociągu",
 "Entities.gmod_subway_81-717_mvm.Buttons.AV.A80Toggle": "A80 Zasilanie silnika przełącznika kułakowego",
 "Entities.gmod_subway_81-717_mvm.Buttons.AV.A65Toggle": "A65 Oświetlenie klasy",
 "Entities.gmod_subway_81-717_mvm.Buttons.AV.L_5Toggle": "А49 Oświetlenie awaryjne",
 "Entities.gmod_subway_81-717_mvm.Buttons.AV.A24Toggle": "A24 Ładowanie baterii",
 "Entities.gmod_subway_81-717_mvm.Buttons.AV.A32Toggle": "A32 Otwieranie prawych drzwi",
 "Entities.gmod_subway_81-717_mvm.Buttons.AV.A31Toggle": "A31 Otwieranie lewych drzwi",
 "Entities.gmod_subway_81-717_mvm.Buttons.AV.A16Toggle": "A16 Zamykanie drzwi",
 "Entities.gmod_subway_81-717_mvm.Buttons.AV.A13Toggle": "A13 Dzwonek drzwi",
 "Entities.gmod_subway_81-717_mvm.Buttons.AV.A12Toggle": "A12 Awaryjne zamykanie drzwi",
 "Entities.gmod_subway_81-717_mvm.Buttons.AV.A7Toggle": "A7 Reflektor czerwony",
 "Entities.gmod_subway_81-717_mvm.Buttons.AV.A9Toggle": "A9 Reflektor czerwony",
 "Entities.gmod_subway_81-717_mvm.Buttons.AV.A46Toggle": "A46 Reflektory białe",
 "Entities.gmod_subway_81-717_mvm.Buttons.AV.A47Toggle": "A47 Reflektory białe",
 "Entities.gmod_subway_81-717_mvm.Buttons.PassengerDoor.PassengerDoor": "Drzwi do klasy",
 "Entities.gmod_subway_81-717_mvm.Buttons.GV.GVToggle": "Wyłącznik główny",
 "Entities.gmod_subway_81-717_mvm.Buttons.Stopkran.EmergencyBrakeValveToggle": "Hamulec awaryjny",
 "Entities.gmod_subway_81-717_mvm.Buttons.InfoTableSelect.PrevSign": "Następna tablica",
 "Entities.gmod_subway_81-717_mvm.Buttons.InfoTableSelect.NextSign": "Poprzednia tablica",
 "Entities.gmod_subway_81-717_mvm.Buttons.InfoTableSelect.Num2P": "Linia: Zwiększ drugą cyfrę",
 "Entities.gmod_subway_81-717_mvm.Buttons.InfoTableSelect.Num2M": "Linia: Zmniejsz drugą cyfrę",
 "Entities.gmod_subway_81-717_mvm.Buttons.InfoTableSelect.Num1P": "Linia: Zwiększ pierwszą cyfrę",
 "Entities.gmod_subway_81-717_mvm.Buttons.InfoTableSelect.Num1M": "Linia: Zmniejsz pierwszą cyfrę",
 "Entities.gmod_subway_81-717_mvm.Buttons.Front.L_4Toggle": "Wyłącznik świateł",
 "Entities.gmod_subway_81-717_mvm.Buttons.Front.VUSToggle": "VUS: Przyciemnianie świateł jezdnych",
 "Entities.gmod_subway_81-717_mvm.Buttons.Front.VAHToggle": "VAH: Jazda awaryjna (uszkodzenie przekaźnika czuwaka)",
 "Entities.gmod_subway_81-717_mvm.Buttons.Front.VADToggle": "VAD: Awaryjne zamykanie drzwi (uszkodzony przekaźnik sterowania drzwiami)",
 "Entities.gmod_subway_81-717_mvm.Buttons.Front.KRPSet": "KRP: Rozruch rezerwowy",
 "Entities.gmod_subway_81-717_mvm.Buttons.Front.KAHSet": "KAH: Jazda awaryjna",
 "Entities.gmod_subway_81-717_mvm.Buttons.Front.KAHKToggle": "Klapka przycisku KAH",
 "Entities.gmod_subway_81-717_mvm.Buttons.Front.KUP": "Kontrola ogrzewania",
 "Entities.gmod_subway_81-717_mvm.Buttons.Front.KDPSet": "KDP: Otwieranie prawych drzwi",
 "Entities.gmod_subway_81-717_mvm.Buttons.Front.KDPKToggle": "Klapka przycisku KDP",
 "Entities.gmod_subway_81-717_mvm.Buttons.Front.PN": "Kontrola hamulca pneumatycznego",
 "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A61Toggle": "A61 Sterowanie przewodem 6",
 "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A55Toggle": "A55 Sterowanie przewodem 10AS",
 "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A54Toggle": "A54 Sterowanie przewodem 10AK",
 "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A56Toggle": "A56 Włączenie akumulatorów baterii",
 "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A27Toggle": "A27 Włączenie DIP (komplementarnej jednostki zasilania) i oświetlenia",
 "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A21Toggle": "A21 Sterowanie drzwiami",
 "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A10Toggle": "A10 Sterowanie sprężarką",
 "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A53Toggle": "A53 Zasilanie stycznika obwodów WN",
 "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A43Toggle": "A43 Zasilanie 12 V systemu ARS",
 "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A45Toggle": "A45 Przewód ARS 10AU",
 "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A42Toggle": "A42 Zasilanie 75 V systemu ARS",
 "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A41Toggle": "A41 Hamowanie ARS",
 "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:VUToggle": "VU Sterowanie pociągiem",
 "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A64Toggle": "A64 Oświetlenie kabiny",
 "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A63Toggle": "A63 Włączenie IGLA/BIS (jednotki prędkościomierza)",
 "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A50Toggle": "A50 Włączenie DIP i oświetlenia",
 "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A51Toggle": "A51 Wyłączenie DIP i oświetlenia",
 "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A23Toggle": "A23 Awaryjne załączanie sprężarki",
 "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A14Toggle": "A14 Przewód 18",
 "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A75Toggle": "A75 Ogrzewanie kabiny",
 "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A1Toggle": "A1 X-1",
 "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A2Toggle": "A2 X-2",
 "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A3Toggle": "A3 X-3",
 "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A17Toggle": "A17 Odblokowywanie przekaźnika nadmiarowego",
 "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A62Toggle": "A62 Łączność radiowa",
 "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A29Toggle": "A29 Nadawanie radiowe",
 "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A5Toggle": "A5 ASNP: Automatyczny czytnik numeru pociągu",
 "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A6Toggle": "A6 T-1",
 "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A8Toggle": "A8 Zawory pneumatyczne #1 i #2",
 "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A20Toggle": "A20 Sterowanie jazdą i hamowaniem, przewód 20",
 "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A25Toggle": "A25 Ręczne hamowanie elektrodynamiczne",
 "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A22Toggle": "A22 Zasilanie stycznika sprężarki",
 "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A30Toggle": "A30 Zasilanie silnika reostatu",
 "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A39Toggle": "A39 Sterowanie awaryjne",
 "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A44Toggle": "A44 Awaryjne sterowanie pociągu",
 "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A80Toggle": "A80 Zasilanie silnika przełącznika kułakowego",
 "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A65Toggle": "A65 Oświetlenie klasy",
 "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:L_5Toggle": "А49 Oświetlenie awatyjne",
 "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A24Toggle": "A24 Ładowanie baterii",
 "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A32Toggle": "A32 Otwieranie prawych drzwi",
 "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A31Toggle": "A31 Otwieranie lewych drzwi",
 "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A16Toggle": "A16 Zamykanie drzwi",
 "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A13Toggle": "A13 Dzwonek drzwi",
 "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A12Toggle": "A12 Awaryjne zamykanie drzwi",
 "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A7Toggle": "A7 Reflektor czerwony",
 "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A9Toggle": "A9 Reflektor czerwony",
 "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A46Toggle": "A46 Reflektory białe",
 "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A47Toggle": "A47 Reflektory białe",
 "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!Speedometer": "Wskaźnik prędkości",
 "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!LSD": "LSD: Sygnalizacja drzwi (drzwi zamknięte)",
 "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!LOCh": "NCh: Brak częstotliwości ARS",
 "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!L0": "0: Sygnał ARS zatrzymania",
 "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!LRS": "LRS: Kontrolka równości prędkości",
 "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!L40": "Ograniczenie prędkości do 40 km/h",
 "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!L60": "Ograniczenie prędkości do 60 km/h",
 "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!L80": "Ograniczenie prędkości do 70 km/h",
 "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!L70": "Ograniczenie prędkości do 80 km/h",
 "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!LRK": "RK: Ruch reostatu",
 "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!LEKK": "",
 "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!LPU": "",
 "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!LKVD": "LKVD: ARS -- wyłączenie silników",
 "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!LKT": "LKT: ARS -- hamowanie",
 "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!LRP": "RP: Kontrolka przekaźnika nadmiarowego",
 "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!LKVC": "LKVC: Brak zasilania WN",
 "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!LVD": "LVD: Silniki załączone",
 "Entities.gmod_subway_81-717_mvm.Buttons.OldARS.!LST": "LST: Sygnalizacja hamowania",
 "Entities.gmod_subway_81-717_mvm.Buttons.CabinDoor.CabinDoor": "Drzwi do klasy",
 "Entities.gmod_subway_81-717_mvm.Buttons.Reverser.KVReverserDown": "Nawrotnik -- w tył",
 "Entities.gmod_subway_81-717_mvm.Buttons.Reverser.KVReverserUp": "Nawrotnik -- naprzód",
 "Entities.gmod_subway_81-717_mvm.Buttons.PassengerDoor1.PassengerDoor": "Drzi do klasy",
 "Entities.gmod_subway_81-717_mvm.Buttons.UAVAPanel.UAVAToggle": "UAVA: (wyłączenie autostopu)",
 "Entities.gmod_subway_81-717_mvm.Buttons.UAVAPanel.UAVAContactSet": "UAVA: (odblokowanie przekaźników)",
 "Entities.gmod_subway_81-717_mvm.Buttons.EPKDisconnect.EPKToggle": "EPV: zawór elektropneumatyczny",
 "Entities.gmod_subway_81-717_mvm.Buttons.Help.ShowHelp": "Pomoc w prowadzeniu pociągu",
 "Entities.gmod_subway_81-717_mvm.Buttons.ParkingBrake2.1:ParkingBrakeToggle": "Hamulec postojowy",
 "Entities.gmod_subway_81-717_mvm.Buttons.RearPneumatic.RearBrakeLineIsolationToggle": "Zawór przewodu głównego sprzęgu powietrznego",
 "Entities.gmod_subway_81-717_mvm.Buttons.RearPneumatic.RearTrainLineIsolationToggle": "Zawór przewodu zasilającego sprzęgu powietrznego",
 "Entities.gmod_subway_81-717_mvm.Buttons.AirDistributor.AirDistributorDisconnectToggle": "Blokada dystrybutora powietrza",

 "Entities.gmod_subway_81-714_mvm.Buttons.GV.GVToggle": "Wyłącznik główny",
 "Entities.gmod_subway_81-714_mvm.Buttons.RearPneumatic.RearBrakeLineIsolationToggle": "Zawór przewodu głównego sprzęgu powietrznego",
 "Entities.gmod_subway_81-714_mvm.Buttons.RearPneumatic.RearTrainLineIsolationToggle": "Zawór przewodu zasilającego sprzęgu powietrznego",
 "Entities.gmod_subway_81-714_mvm.Buttons.RearDoor.RearDoor": "Przednie drzwi",
 "Entities.gmod_subway_81-714_mvm.Buttons.AV_Left.DriverValveBLDisconnectToggle": "Zawór dwudrożny przewodu głównego",
 "Entities.gmod_subway_81-714_mvm.Buttons.AV_Left.DriverValveTLDisconnectToggle": "Zawór dwudrożny przewodu zasilającego",
 "Entities.gmod_subway_81-714_mvm.Buttons.AV_Left.A65Toggle": "A65 Oświetlenie klasy",
 "Entities.gmod_subway_81-714_mvm.Buttons.AV_Left.A56Toggle": "A56 Włączenie akumulatorów baterii",
 "Entities.gmod_subway_81-714_mvm.Buttons.AV_Left.A63Toggle": "A63 Włączenie IGLA/BIS (jednostki prędkościomierza)",
 "Entities.gmod_subway_81-714_mvm.Buttons.AV_Left.A10Toggle": "A10 Sterowanie sprężarką",
 "Entities.gmod_subway_81-714_mvm.Buttons.AV_Left.A30Toggle": "A30 Zasilanie silnika reostatu",
 "Entities.gmod_subway_81-714_mvm.Buttons.AV_Left.A80Toggle": "A80 Zasilanie silnika przełącznika kułakowego",
 "Entities.gmod_subway_81-714_mvm.Buttons.FrontPneumatic.FrontBrakeLineIsolationToggle": "Zawór przewodu głównego sprzęgu powietrznego",
 "Entities.gmod_subway_81-714_mvm.Buttons.FrontPneumatic.FrontTrainLineIsolationToggle": "Zawór przewodu zasilającego sprzęgu powietrznego",
 "Entities.gmod_subway_81-714_mvm.Buttons.FrontPneumatic.ParkingBrakeToggle": "Hamulec postojowy",
 "Entities.gmod_subway_81-714_mvm.Buttons.AirDistributor.AirDistributorDisconnectToggle": "Blokada dystrybutora powietrza",
 "Entities.gmod_subway_81-714_mvm.Buttons.FrontDoor.FrontDoor": "Przednie drzwi",
 "Entities.gmod_subway_81-714_mvm.Buttons.Battery.VBToggle": "VB: Baterie akumulatorów",
 "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A54Toggle": "A54 Sterowanie przewodem 10AK",
 "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A27Toggle": "A27 Włączenie DIP (komplementarnej jednostki zasilania) i oświetlenia",
 "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A24Toggle": "A24 Ładowanie baterii",
 "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A53Toggle": "A53 Zasilanie stycznika obwodów WN",
 "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A13Toggle": "A13 Dzwonek drzwi",
 "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A32Toggle": "A32 Otwieranie prawych drzwi",
 "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A31Toggle": "A31 Otwieranie lewych drzwi",
 "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A16Toggle": "A16 Zamykanie drzwi",
 "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A12Toggle": "A12 Awaryjne zamykanie drzwi",
 "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A50Toggle": "A50 Włączenie DIP i oświetlenia",
 "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A51Toggle": "A51 Wyłączenie DIP i oświetlenia",
 "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A1Toggle": "A1 X-1",
 "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.KRPSet": "START: Rozruch awaryjny",
 "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.VozvratRPSet": "Oblokowanie przekaźnika nadmiarowego",
 "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.RezMKSet": "Awaryjne załączanie sprężarki",
 "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.VMKToggle": "Włączanie sprężarki",
 "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.BPSNonToggle": "BPSN: Zasilanie systemów pociągu",
 "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A2Toggle": "A2 X-2",
 "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A3Toggle": "A3 X-3",
 "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A17Toggle": "A17 Odblokowanie przekaźnika nadmiarowego",
 "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A5Toggle": "A5 ASNP: Automatyczny czytnik numeru pociągu",
 "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A6Toggle": "A6 T-1",
 "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A8Toggle": "A8 Zawory pneumatyczne #1 i #2",
 "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A20Toggle": "A20 Sterowanie jazdą i hamowaniem, przewód 20",
 "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A25Toggle": "A25 Ręczne hamowanie elektrodynamiczne",
 "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A22Toggle": "A22 Zasilanie stycznika sprężarki",
 "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A23Toggle": "A23 Awaryjne załączanie sprężarki",
 "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A39Toggle" : "A39 Sterowanie awaryjne",
 "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A14Toggle" : "A14 Przewód 18"
}
]]
