return [[
{
  "Lang"										: "pl",
  "Name"										: "Polish",

  "Entities.gmod_subway_81-720.Buttons.VityazButtons.VityazF1Set"			: "Vityaz: F1",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.VityazF2Set"			: "Vityaz: Następny ekran",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.VityazF3Set"			: "Vityaz: Poprzedni ekran",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.VityazF4Set"			: "Vityaz: Tryb zasadniczy",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.Vityaz1Set"			: "Vityaz: 1",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.Vityaz4Set"			: "Vityaz: 4",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.Vityaz7Set"			: "Vityaz: 7",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.Vityaz2Set"			: "Vityaz: 2",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.Vityaz5Set"			: "Vityaz: 5",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.Vityaz8Set"			: "Vityaz: 8",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.Vityaz0Set"			: "Vityaz: 0",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.Vityaz3Set"			: "Vityaz: 3",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.Vityaz6Set"			: "Vityaz: 6",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.Vityaz9Set"			: "Vityaz: 9",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.VityazF5Set"			: "Vityaz: Usuń",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.VityazF6Set"			: "Vityaz: W górę\\Prędkość",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.VityazF7Set"			: "Vityaz: W dół\\Prądy",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.VityazF8Set"			: "Vityaz: Wprowadzanie\\Wyposażenie wagonów",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.VityazF9Set"			: "Vityaz: Wybór\\Sterowanie wyposażeniem wagonów",
  "Entities.gmod_subway_81-720.Buttons.RV.EmerX1Set"					: "X-1 rezerwowy",
  "Entities.gmod_subway_81-720.Buttons.RV.EmerX2Set"					: "X-2 rezerwowy",
  "Entities.gmod_subway_81-720.Buttons.RV.EmerCloseDoorsSet"				: "Awaryjne zamykanie drzwi",
  "Entities.gmod_subway_81-720.Buttons.RV.EmergencyDoorsToggle"				: "Drzwi awaryjne",
  "Entities.gmod_subway_81-720.Buttons.BackVent.VentCondMode-"				: "Tryb pracy wentylatora: +",
  "Entities.gmod_subway_81-720.Buttons.BackVent.VentCondMode+"				: "Tryb pracy wentylatora: -",
  "Entities.gmod_subway_81-720.Buttons.BackVent.VentHeatMode+"				: "+",
  "Entities.gmod_subway_81-720.Buttons.BackVent.VentHeatMode-"				: "-",
  "Entities.gmod_subway_81-720.Buttons.BackVent.VentStrengthMode-"			: "Moc wentylatora: +",
  "Entities.gmod_subway_81-720.Buttons.BackVent.VentStrengthMode+"			: "Moc wentylatora: -",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV1Toggle"					: "SF1: Zasilanie obwodów sterowania wagonu",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV2Toggle"					: "SF2: Zasilanie BUV (jednostki sterowania wagonu)",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV3Toggle"					: "SF3: Zasilanie BUTP (jednostki sterowania silnikami)",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV4Toggle"					: "SF4: Sterowanie BUTP",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV5Toggle"					: "SF5: Awaryjne sterowanie BUTP",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV6Toggle"					: "SF6: Zasilanie BUTP",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV7Toggle"					: "SF7: BBE (zasilanie pokładowe)",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV8Toggle"					: "SF8: Sterowanie BV (przekaźnik nadmiarowy)",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV9Toggle"					: "SF9: Zasilanie BV (przekaźnik nadmiarowy)",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV10Toggle"					: "SF10: PPO (ochrona przeciwpożarowa)",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV11Toggle"					: "SF11: Sprężarka",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV12Toggle"					: "SF12: Zamknięcie drzwi",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV13Toggle"					: "SF13: Otwarcie drzwi lewych",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV14Toggle"					: "SF14: Otwarcie drzwi prawych",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV15Toggle"					: "SF15: Przednie drzwi",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV16Toggle"					: "SF16: Zapowiedzi głosowe",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV17Toggle"					: "SF17: Radiowa linia awaryjna",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV18Toggle"					: "SF18: (placeholder)",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV19Toggle"					: "SF19: Zasilanie oświetlenia klasy",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV20Toggle"					: "SF20: Awaryjne oświetlenie klasy",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV21Toggle"					: "SF21: Czujnik prędkości",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV22Toggle"					: "SF22: Hamulec postojowy",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV23Toggle"					: "SF23: Sterowanie wentylatorami: pierwsza grupa",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV24Toggle"					: "SF24: Sterowanie wentylatorami: druga grupa",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV25Toggle"					: "SF25: Zasilanie wentylatorów: pierwsza grupa",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV26Toggle"					: "SF26: Zasilanie wentylatorów: druga grupa",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV27Toggle"					: "SF27: Zasilanie wzbudnicy",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV28Toggle"					: "SF28: Zasilanie ZKK",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV29Toggle"					: "SF29: Odbieraki prądu",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV30Toggle"					: "SF30: Tablice świetlne",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV31Toggle"					: "SF31: (placeholder)",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV32Toggle"					: "SF32: (placeholder)",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV33Toggle"					: "SF33: (placeholder)",
  "Entities.gmod_subway_81-720.Buttons.ASNP.R_ASNPMenuSet"				: "ASNP: Menu",
  "Entities.gmod_subway_81-720.Buttons.ASNP.R_ASNPUpSet"				: "ASNP: W górę",
  "Entities.gmod_subway_81-720.Buttons.ASNP.R_ASNPDownSet"				: "ASNP: W dół",
  "Entities.gmod_subway_81-720.Buttons.ASNP.R_ASNPOnToggle"				: "ASNP: Włączenie",
  "Entities.gmod_subway_81-720.Buttons.PneumoHelper1.!BrakeCylinder"			: "Cylinder hamulcowy",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF1Toggle"				: "SF1: Zasilanie ogólne",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF2Toggle"				: "SF2: Sterowanie zasadnicze",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF3Toggle"				: "SF3: Sterowanie rezerwowe",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF4Toggle"				: "SF4: BARS (blok ARS)",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF5Toggle"				: "SF5: BUP (jednostka sterowania pociągiem)",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF6Toggle"				: "SF6: BKCU (jednostka komutacji sieci sterowania)",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF7Toggle"				: "SF7: BARS (blok ARS)",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF8Toggle"				: "SF8: Zapowiedzi głosowe",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF9Toggle"				: "SF9: Radiostacja",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF10Toggle"				: "SF10: Orientacja wagonu",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF11Toggle"				: "SF11: Zwrot jazdy",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF12Toggle"				: "SF12: Reflektory grupy pierwszej",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF13Toggle"				: "SF13: Reflektory grupy drugiej",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF14Toggle"				: "SF14: Światła obrysowe",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF15Toggle"				: "SF15: Oświetlenie kabiny",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF16Toggle"				: "SF16: Ogrzewanie",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF17Toggle"				: "SF17: Klimatyzacja kabiny",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF18Toggle"				: "SF18: Smarowanie obrzeży kół",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF19Toggle"				: "SF19: Zasilanie główne KRM (kranu hamulca)",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF20Toggle"				: "SF20: Zasilanie rezerwowe KRM (kranu hamulca)",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF21Toggle"				: "SF21: Otwieranie drzwi",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF22Toggle"				: "SF22: Zamykanie drzwi",
  "Entities.gmod_subway_81-720.Buttons.BTO.K29Toggle"					: "KRMSh (driver disconnect valve)",
  "Entities.gmod_subway_81-720.Buttons.PassengerDoor2.PassengerDoor"			: "Drzwi do klasy",
  "Entities.gmod_subway_81-720.Buttons.VoltHelper2.!HV"					: "Woltomierz WN [kV]",
  "Entities.gmod_subway_81-720.Buttons.VoltHelper2.!I1_3"				: "Prąd pierwszej grupy silników [A]",
  "Entities.gmod_subway_81-720.Buttons.VoltHelper2.!I2_4"				: "2nd engine group current [A]",
  "Entities.gmod_subway_81-720.Buttons.GV.GVToggle"					: "Wyłącznik główny",
  "Entities.gmod_subway_81-720.Buttons.RearPneumatic.RearBrakeLineIsolationToggle"	: "Zawór przewodu głównego sprzęgu powietrznego",
  "Entities.gmod_subway_81-720.Buttons.RearPneumatic.RearTrainLineIsolationToggle"	: "Zawór przedogu zasilającego sprzęgu powietrznego",
  "Entities.gmod_subway_81-720.Buttons.RearDoor1.RearDoor"				: "Drzwi tylne",
  "Entities.gmod_subway_81-720.Buttons.RearDoor.RearDoor"				: "Drzwi tylne",
  "Entities.gmod_subway_81-720.Buttons.BackDown.Pant1Toggle"				: "Odłączenie pierwszej grupy odbieraków",
  "Entities.gmod_subway_81-720.Buttons.BackDown.Pant2Toggle"				: "Odłączenie drugiej grupy odbieraków",
  "Entities.gmod_subway_81-720.Buttons.BackDown.Vent1Toggle"				: "Pierwsza grupa wentylacji",
  "Entities.gmod_subway_81-720.Buttons.BackDown.Vent2Toggle"				: "Druga grupa wentylacji",
  "Entities.gmod_subway_81-720.Buttons.BackDown.VentToggle"				: "",
  "Entities.gmod_subway_81-720.Buttons.BackDown.PassLightToggle"			: "Oświetlenie klasy",
  "Entities.gmod_subway_81-720.Buttons.BackDown.CabLightToggle"				: "Oświetlenie kabiny",
  "Entities.gmod_subway_81-720.Buttons.BackDown.Headlights1Toggle"			: "Reflektory grupy pierwszej",
  "Entities.gmod_subway_81-720.Buttons.BackDown.Headlights2Toggle"			: "Reflektory grupy drugiej",
  "Entities.gmod_subway_81-720.Buttons.BackDown.ParkingBrakeToggle"			: "Hamulec postojowy",
  "Entities.gmod_subway_81-720.Buttons.BackDown.TorecDoorsToggle"			: "Drzwi przednie",
  "Entities.gmod_subway_81-720.Buttons.BackDown.BBERToggle"				: "Turning on emergency BBE",
  "Entities.gmod_subway_81-720.Buttons.BackDown.BBEToggle"				: "BBE (zasilanie pokładowe)",
  "Entities.gmod_subway_81-720.Buttons.BackDown.CompressorToggle"			: "Sprężarka",
  "Entities.gmod_subway_81-720.Buttons.BackDown.CabLightStrengthToggle"			: "Moc oświetlenia kabiny",
  "Entities.gmod_subway_81-720.Buttons.BackDown.AppLights1Toggle"			: "Oświetlenie urządzeń wagonu",
  "Entities.gmod_subway_81-720.Buttons.BackDown.AppLights2Toggle"			: "",
  "Entities.gmod_subway_81-720.Buttons.BackDown.BARSBlock-"				: "Blokada uszkodzonych bloków ARS: -",
  "Entities.gmod_subway_81-720.Buttons.BackDown.BARSBlock+"				: "Blokada uszkodzonych bloków ARS: +",
  "Entities.gmod_subway_81-720.Buttons.BackDown.BatteryToggle"				: "Wyłącznik baterii",
  "Entities.gmod_subway_81-720.Buttons.BackDown.ALSFreqToggle"				: "Dekoder ALS",
  "Entities.gmod_subway_81-720.Buttons.VoltHelper1.!Battery"				: "Woltomierz baterii akumulatorów",
  "Entities.gmod_subway_81-720.Buttons.PassengerDoor.PassengerDoor"			: "Drzwi do klasy",
  "Entities.gmod_subway_81-720.Buttons.CabinDoorR.CabinDoorRight"			: "Drzwi do kabiny",
  "Entities.gmod_subway_81-720.Buttons.CabinDoorL.CabinDoorLeft"			: "Drzwi do kabiny",
  "Entities.gmod_subway_81-720.Buttons.FrontPneumatic.FrontBrakeLineIsolationToggle"	: "Zawór przewodu głównego sprzęgu powietrznego",
  "Entities.gmod_subway_81-720.Buttons.FrontPneumatic.FrontTrainLineIsolationToggle"	: "Zawór przewodu zasilającego sprzęgu powietrznego",
  "Entities.gmod_subway_81-720.Buttons.PUL.DoorSelectLToggle"				: "Wybór lewych drzwi",
  "Entities.gmod_subway_81-720.Buttons.PUL.DoorSelectRToggle"				: "Wybór prawych drzwi",
  "Entities.gmod_subway_81-720.Buttons.PUL.DoorBlockToggle"				: "Blokada drzwi",
  "Entities.gmod_subway_81-720.Buttons.PUL.!DoorLeftLamp"				: "Praca przycisku lewych drzwi",
  "Entities.gmod_subway_81-720.Buttons.PUL.DoorLeftSet"					: "Drzwi lewe",
  "Entities.gmod_subway_81-720.Buttons.PUU.!DoorsClosed"				: "Drzwi są zamknięte",
  "Entities.gmod_subway_81-720.Buttons.PUU.StandToggle"					: "Postój",
  "Entities.gmod_subway_81-720.Buttons.PUU.TickerToggle"				: "Tablica ledowa",
  "Entities.gmod_subway_81-720.Buttons.PUU.KAHToggle"					: "KAH",
  "Entities.gmod_subway_81-720.Buttons.PUU.ALSToggle"					: "ALS",
  "Entities.gmod_subway_81-720.Buttons.PUU.FDepotToggle"				: "Wyjazd z zajezdni",
  "Entities.gmod_subway_81-720.Buttons.PUU.!HVoltage"					: "Sieć trakcyjna",
  "Entities.gmod_subway_81-720.Buttons.PUU.PassSchemeToggle"				: "Tablica nad drzwiami",
  "Entities.gmod_subway_81-720.Buttons.PUU.EmergencyCompressorSet"			: "Sprężarka rezerwowa",
  "Entities.gmod_subway_81-720.Buttons.PUU.EnableBVSet"					: "Włączenie ochrony",
  "Entities.gmod_subway_81-720.Buttons.PUU.DisableBVSet"				: "Wyłączenie BV (przekaźnika nadmiarowego)",
  "Entities.gmod_subway_81-720.Buttons.PUU.RingSet"					: "Przekazanie sterowania (dzwonek)",
  "Entities.gmod_subway_81-720.Buttons.PUU.R_Program2Set"				: "Zapowiedź 2",
  "Entities.gmod_subway_81-720.Buttons.PUU.R_AnnouncerToggle"				: "Zapowiedzi głosowe",
  "Entities.gmod_subway_81-720.Buttons.PUU.R_LineToggle"				: "Linia",
  "Entities.gmod_subway_81-720.Buttons.PUU.R_EmerSet"					: "Radiowa sieć awaryjna",
  "Entities.gmod_subway_81-720.Buttons.PUU.R_Program1Set"				: "Zapowiedź 1",
  "Entities.gmod_subway_81-720.Buttons.PUU.EnableBVEmerSet"				: "Rezerwowe odblokowanie BV",
  "Entities.gmod_subway_81-720.Buttons.PUU.EmergencyControlsToggle"			: "Sterowanie rezerwowe",
  "Entities.gmod_subway_81-720.Buttons.PUU.WiperToggle"					: "Wycieraczka",
  "Entities.gmod_subway_81-720.Buttons.PUU.!VDop"					: "Prędkość dopuszczalna",
  "Entities.gmod_subway_81-720.Buttons.PUU.!VFact"					: "Prędkość rzeczywista",
  "Entities.gmod_subway_81-720.Buttons.PUU.!VPred"					: "Prędkość zalecana",
  "Entities.gmod_subway_81-720.Buttons.PUU.!VDop2"					: "Prędkość dopuszczalna",
  "Entities.gmod_subway_81-720.Buttons.PUU.!Acc"					: "Przyspieszenie",
  "Entities.gmod_subway_81-720.Buttons.PUU.!Forw"					: "Jazda naprzód",
  "Entities.gmod_subway_81-720.Buttons.PUU.!Back"					: "Jazda w tył",
  "Entities.gmod_subway_81-720.Buttons.PUR.AccelRateToggle"				: "Przyspieszenie",
  "Entities.gmod_subway_81-720.Buttons.PUR.EmerBrakeAddSet"				: "(rezerwowy) Hamulec",
  "Entities.gmod_subway_81-720.Buttons.PUR.EmerBrakeReleaseSet"				: "(rezerwowy) Luzowanie",
  "Entities.gmod_subway_81-720.Buttons.PUR.EmerBrakeToggle"				: "Hamulec rezerwowy",
  "Entities.gmod_subway_81-720.Buttons.PUR.EmergencyBrakeToggle"			: "Hamulec awaryjny",
  "Entities.gmod_subway_81-720.Buttons.PUR.DoorCloseToggle"				: "Zamknięcie drzwi",
  "Entities.gmod_subway_81-720.Buttons.PUR.AttentionMessageSet"				: "Message perception",
  "Entities.gmod_subway_81-720.Buttons.PUR.AttentionSet"				: "Attention",
  "Entities.gmod_subway_81-720.Buttons.PUR.AttentionBrakeSet"				: "Czujnik hamowania",
  "Entities.gmod_subway_81-720.Buttons.PUR.HornBSet"					: "Sygnał",
  "Entities.gmod_subway_81-720.Buttons.PUR.DoorRightSet"				: "Drzwi prawe",
  "Entities.gmod_subway_81-720.Buttons.PUR.!DoorRightLamp"				: "Praca przycisku prawych drzwi",
  "Entities.gmod_subway_81-720.Buttons.PneumoHelper2.!BrakeTrainLine"			: "Czerwona - przewód gł., czarna - przewód zas.",

  "Entities.gmod_subway_81-721.Buttons.GV.GVToggle"					: "Wyłącznik główny",
  "Entities.gmod_subway_81-721.Buttons.RearPneumatic.RearBrakeLineIsolationToggle"	: "Zawór przewodu głównego sprzęgu powietrznego",
  "Entities.gmod_subway_81-721.Buttons.RearPneumatic.RearTrainLineIsolationToggle"	: "Zawór przewodu zasilającego sprzęgu powietrznego",
  "Entities.gmod_subway_81-721.Buttons.FrontDoor.FrontDoor"				: "Drzwi przednie",
  "Entities.gmod_subway_81-721.Buttons.RearDoor.RearDoor"				: "Drzwi tylne",
  "Entities.gmod_subway_81-721.Buttons.Battery.BatteryToggle"				: "Baterie akumulatorów",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV1Toggle"					: "SF1: Zasilanie obwodów sterowania wagonu",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV2Toggle"					: "SF2: Zasilanie BUV (wagon controlling unit)",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV3Toggle"					: "SF3: Zasilanie BUTP (engines controlling unit)",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV4Toggle"					: "SF4: Sterowanie BUTP",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV5Toggle"					: "SF5: Awaryjne sterowanie BUTP",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV6Toggle"					: "SF6: Zasilanie BUTP",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV7Toggle"					: "SF7: BBE (zasilanie pokładowe)",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV8Toggle"					: "SF8: Sterowanie BV",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV9Toggle"					: "SF9: Zasilanie BV (przekaźnik nadmiarowy)",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV10Toggle"					: "SF10: PPO (ochrona przeciwpożarowa)",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV11Toggle"					: "SF11: Sprężarka",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV12Toggle"					: "SF12: Zamykanie drzwi",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV13Toggle"					: "SF13: Otwieranie lewych drzwi",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV14Toggle"					: "SF14: Otwieranie prawych drzwi",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV15Toggle"					: "SF15: Drzwi przednie",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV16Toggle"					: "SF16: Zapowiedzi głosowe",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV17Toggle"					: "SF17: Radiowa sieć awaryjna",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV18Toggle"					: "SF18: (placeholder)",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV19Toggle"					: "SF19: Zasilanie oświetlenia klasy",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV20Toggle"					: "SF20: Awaryjne oświetlenie klasy",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV21Toggle"					: "SF21: Czujnik prędkości",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV22Toggle"					: "SF22: Hamulec postojowy",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV23Toggle"					: "SF23: Sterowanie wentylatorami: pierwsza grupa",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV24Toggle"					: "SF24: Sterowanie wentylatorami: druga grupa",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV25Toggle"					: "SF25: Zasilanie wentylatorów: pierwsza grupa",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV26Toggle"					: "SF26: Zasilanie wentylatorów: druga grupa",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV27Toggle"					: "SF27: Zasilanie wzbudnicy",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV28Toggle"					: "SF28: Zasilanie ZKK",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV29Toggle"					: "SF29: Odbieraki prądu",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV30Toggle"					: "SF30: Tablice świetlne",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV31Toggle"					: "SF31: (placeholder)",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV32Toggle"					: "SF32: (placeholder)",
  "Entities.gmod_subway_81-721.Buttons.PVZ.SFV33Toggle"					: "SF33: (placeholder)",
  "Entities.gmod_subway_81-721.Buttons.FrontPneumatic.FrontBrakeLineIsolationToggle"	: "Zawór przewodu głównego sprzęgu powietrznego",
  "Entities.gmod_subway_81-721.Buttons.FrontPneumatic.FrontTrainLineIsolationToggle"	: "Zawór przewodu zasilającego sprzęgu powietrznego"
}
]]
