return [[
{
  "Lang": "pl",
  "Name": "polski",

  "Spawner.Title": "Spawner ",
  "Spawner.Trains1": "Składów",
  "Spawner.Trains2": "Maks.",
  "Spawner.WagNum": "Wagonów",
  "Spawner.AutoCouple": "Połącz wagony",

  "Entities.gmod_subway_81-717_mvm.Spawner.Texture.Name": "Skin",
  "Entities.gmod_subway_81-717_mvm.Spawner.PassTexture.Name": "Wygląd klasy",
  "Entities.gmod_subway_81-717_mvm.Spawner.CabTexture.Name": "Wygląd kabiny",
  "Entities.gmod_subway_81-717_mvm.Spawner.Announcer.Name": "Dźwięk zapowiedzi",
  "Entities.gmod_subway_81-717_mvm.Spawner.Lighter.Name": "Niezbędnik maszynisty",
  "Entities.gmod_subway_81-717_mvm.Spawner.ARSType.Name": "Typ panelu ARS",
  "Entities.gmod_subway_81-717_mvm.Spawner.ARSType.1": "Standardowy (kwadratowe kontrolki)",
  "Entities.gmod_subway_81-717_mvm.Spawner.ARSType.2": "Standardowy (okrągłe kontrolki)",
  "Entities.gmod_subway_81-717_mvm.Spawner.ARSType.3": "Kijowski/Petersburski",
  "Entities.gmod_subway_81-717_mvm.Spawner.ARSType.4": "Stary panel ARS",
  "Entities.gmod_subway_81-717_mvm.Spawner.Cran.Name": "Rodzaj kranu hamulca",
  "Entities.gmod_subway_81-717_mvm.Spawner.Cran.1": "334",
  "Entities.gmod_subway_81-717_mvm.Spawner.Cran.2": "013",
  "Entities.gmod_subway_81-717_mvm.Spawner.MaskType.Name": "Typ maski",
  "Entities.gmod_subway_81-717_mvm.Spawner.MaskType.1": "2-2",
  "Entities.gmod_subway_81-717_mvm.Spawner.MaskType.2": "2-2-2",
  "Entities.gmod_subway_81-717_mvm.Spawner.MaskType.3": "1-4-1, zderzak 1",
  "Entities.gmod_subway_81-717_mvm.Spawner.MaskType.4": "1-4-1, zderzak 2",
  "Entities.gmod_subway_81-717_mvm.Spawner.MaskType.5": "1-1",
  "Entities.gmod_subway_81-717_mvm.Spawner.MaskType.6": "Retro",
  "Entities.gmod_subway_81-717_mvm.Spawner.LED.Name": "Reflektory ledowe",
  "Entities.gmod_subway_81-717_mvm.Spawner.BPSNType.Name": "Typ BPSN",
  "Entities.gmod_subway_81-717_mvm.Spawner.BPSNType.1": "Stary dźwięk, ton wysoki",
  "Entities.gmod_subway_81-717_mvm.Spawner.BPSNType.2": "Stary dźwięk, ton niski",
  "Entities.gmod_subway_81-717_mvm.Spawner.BPSNType.3": "Standardowy (Petersburg)",
  "Entities.gmod_subway_81-717_mvm.Spawner.BPSNType.4": "Standardowy (TKL)",
  "Entities.gmod_subway_81-717_mvm.Spawner.BPSNType.5": "Standardowy",
  "Entities.gmod_subway_81-717_mvm.Spawner.BPSNType.6": "Kijów",
  "Entities.gmod_subway_81-717_mvm.Spawner.BPSNType.7": "Stary",
  "Entities.gmod_subway_81-717_mvm.Spawner.BPSNType.8": "Standardowy 2",
  "Entities.gmod_subway_81-717_mvm.Spawner.BPSNType.9": "Standardowy 3",
  "Entities.gmod_subway_81-717_mvm.Spawner.BPSNType.10": "Bez dźwięku (BPN-115)",
  "Entities.gmod_subway_81-717_mvm.Spawner.KVSnd.Name": "Dźwięk nastawnika jazdy",
  "Entities.gmod_subway_81-717_mvm.Spawner.KVSnd.1": "Typ 1",
  "Entities.gmod_subway_81-717_mvm.Spawner.KVSnd.2": "Typ 2",
  "Entities.gmod_subway_81-717_mvm.Spawner.KVSnd.3": "Typ 3",
  "Entities.gmod_subway_81-717_mvm.Spawner.NewKV.Name": "Nowy model nastawnika",
  "Entities.gmod_subway_81-717_mvm.Spawner.HornType.Name": "Syrena Petersburska",
  "Entities.gmod_subway_81-717_mvm.Spawner.RingType.Name": "Dźwięk dzwonka",
  "Entities.gmod_subway_81-717_mvm.Spawner.RingType.1": "Stary",
  "Entities.gmod_subway_81-717_mvm.Spawner.RingType.2": "Standardowa, ton niski",
  "Entities.gmod_subway_81-717_mvm.Spawner.RingType.3": "Standardowa, ton wysoki",
  "Entities.gmod_subway_81-717_mvm.Spawner.RingType.4": "Standardowy przerywany, ton niski",
  "Entities.gmod_subway_81-717_mvm.Spawner.RingType.5": "Standardowy przerywany, ton wysoki",
  "Entities.gmod_subway_81-717_mvm.Spawner.NM.Name": "Ciśnienie przewodu zasilającego",
  "Entities.gmod_subway_81-717_mvm.Spawner.Battery.Name": "Wł. baterie",
  "Entities.gmod_subway_81-717_mvm.Spawner.Switches.Name": "Wł. wszystkie bezpieczniki",
  "Entities.gmod_subway_81-717_mvm.Spawner.SwitchesR.Name": "Losowe ust. bezpieczników",
  "Entities.gmod_subway_81-717_mvm.Spawner.DoorsL.Name": "Drzwi lewe otwarte",
  "Entities.gmod_subway_81-717_mvm.Spawner.DoorsR.Name": "Drzwi prawe otwarte",
  "Entities.gmod_subway_81-717_mvm.Spawner.GV.Name": "Wł. wyłącznik główny",
  "Entities.gmod_subway_81-717_mvm.Spawner.PB.Name": "Hamulec postojowy zaciągnięty",
  "Entities.gmod_subway_81-717_mvm.Spawner.BortLampType.Name": "Typ lamp bocznych",
  "Entities.gmod_subway_81-717_mvm.Spawner.BortLampType.1": "Poziome",
  "Entities.gmod_subway_81-717_mvm.Spawner.BortLampType.2": "Pionowe",
  "Entities.gmod_subway_81-717_mvm.Spawner.MVM.Name": "Znak MVM",
  "Entities.gmod_subway_81-717_mvm.Spawner.HandRail.Name": "Poręcze",
  "Entities.gmod_subway_81-717_mvm.Spawner.HandRail.1": "Stare",
  "Entities.gmod_subway_81-717_mvm.Spawner.HandRail.2": "Nowe",
  "Entities.gmod_subway_81-717_mvm.Spawner.SeatType.Name": "Sedzenia",
  "Entities.gmod_subway_81-717_mvm.Spawner.SeatType.1": "Stare",
  "Entities.gmod_subway_81-717_mvm.Spawner.SeatType.2": "Nowe",
  "Entities.gmod_subway_81-717_mvm.Spawner.LampType.Name": "Lampy w klasie",
  "Entities.gmod_subway_81-717_mvm.Spawner.LampType.1": "Typ 1",
  "Entities.gmod_subway_81-717_mvm.Spawner.LampType.2": "Typ 2",
  "Entities.gmod_subway_81-717_mvm.Spawner.LampType.3": "Typ 3",
  "Entities.gmod_subway_81-717_mvm.Spawner.Breakers.Name": "Bezpieczniki z prawej",
  "Entities.gmod_subway_81-717_mvm.Spawner.Adverts.Name": "Reklamy",
  "Entities.gmod_subway_81-717_mvm.Spawner.Adverts.1": "Typ 1",
  "Entities.gmod_subway_81-717_mvm.Spawner.Adverts.2": "Typ 2",
  "Entities.gmod_subway_81-717_mvm.Spawner.Adverts.3": "Typ 3",
  "Entities.gmod_subway_81-717_mvm.Spawner.Adverts.4": "Bez reklam",

  "Entities.gmod_subway_81-720.Spawner.Texture.Name": "Skin",
  "Entities.gmod_subway_81-720.Spawner.PassTexture.Name": "Wygląd klasy",
  "Entities.gmod_subway_81-720.Spawner.CabTexture.Name": "Wygląd kabiny",
  "Entities.gmod_subway_81-720.Spawner.Announcer.Name": "Dźwięk zapowiedzi",
  "Entities.gmod_subway_81-720.Spawner.Scheme.Name": "Schematy nad drzwiami",
  "Entities.gmod_subway_81-720.Spawner.PassSchemesInvert.Name": "Odwrócone schematy",
  "Entities.gmod_subway_81-720.Spawner.NM.Name": "Ciśnienie przewodu zas.",
  "Entities.gmod_subway_81-720.Spawner.Battery.Name": "Wł. baterie",
  "Entities.gmod_subway_81-720.Spawner.BRU.Name": "Wł. wyłącznik główny",
  "Entities.gmod_subway_81-720.Spawner.PVZR.Name": "Losowe ust. bezpieczników",
  "Entities.gmod_subway_81-720.Spawner.PPZ.Name": "Wł. wszystkie bezpieczniki",
  "Entities.gmod_subway_81-720.Spawner.PPZDepot.Name": "Wył. wszystkie bezpieczniki",
  "Entities.gmod_subway_81-720.Spawner.PPZR.Name": "Losowe ust. bezpieczników wagonu",
  "Entities.gmod_subway_81-720.Spawner.DoorsL.Name": "Drzwi lewe otwarte",
  "Entities.gmod_subway_81-720.Spawner.DoorsR.Name": "Drzwi prawe otwarte",

  "Entities.gmod_subway_81-722.Spawner.Texture.Name": "Skin",
  "Entities.gmod_subway_81-722.Spawner.PassTexture.Name": "Wygląd klasy",
  "Entities.gmod_subway_81-722.Spawner.CabTexture.Name": "Wygląd kabiny",
  "Entities.gmod_subway_81-722.Spawner.Announcer.Name": "Dźwięk zapowiedzi",
  "Entities.gmod_subway_81-722.Spawner.Scheme.Name": "Schematy nad drzwiami",
  "Entities.gmod_subway_81-722.Spawner.SarmatInvert.Name": "Odwrócone schematy",
  "Entities.gmod_subway_81-722.Spawner.NM.Name": "Ciśnienie przewodu zas.",
  "Entities.gmod_subway_81-722.Spawner.Battery.Name": "Wł. baterie",
  "Entities.gmod_subway_81-722.Spawner.Switches.Name": "Wł. wszystkie bezpieczniki",
  "Entities.gmod_subway_81-722.Spawner.SwitchesR.Name": "Losowe ust. bezpieczników",
  "Entities.gmod_subway_81-722.Spawner.DoorsL.Name": "Drzwi lewe otwarte",
  "Entities.gmod_subway_81-722.Spawner.DoorsR.Name": "Drzwi prawe otwarte",

  "Spawner.Close": "Zamknij",
  "Spawner.Spawn": "Gotowe"
}
]]
